### ISSUE TITLE
اطلاعات درگاه ها در کجا ذخیره شود؟

### ISSUE THREAD

**Issue by rezaya2938** [Sina-Soltani/Parbad#1]
سلام. اولا تشکر و تبریک، واقعا همچین چیزی نیاز بود.
سوال اینکه اطلاعات درگاه ها رو از کجا میخونه؟؟ مثل مرچنت آیدی یا نام کاربری و رمز و...
درگاه واسط مثل زرین پال هم اضافه کنید.
تشکر

**Comment by Sina-Soltani** [comment]
سلام.
اطلاعات درگاه در هنگام تنظیمات وارد میشه.
نمونه مثال تنظیم درگاه ملت در توضیحات موجود هست.
درگاه‌های واسط پرداخت مانند زرین پال، در صورتیکه توسط دولت فیلتر و مردود نشوند حتما اضافه خواهند شد.
چون درگاه‌های واسط بسیاری بودند که همگی فیلتر و مردود اعلام شدند.
