### ISSUE TITLE
پیاده سازی برای Asp.Net Core 2.x

### ISSUE THREAD

**Issue by Hamidnch** [Sina-Soltani/Parbad#10]
در ابتدا تشکر برای تلاش قابل ستایش شما.
لطفا پیاده سازی پرباد برای نسخه دات نت کور رو هم مدنظر داشته باشید.

موفق باشید.

**Comment by Sina-Soltani** [comment]
خواهش میکنم
بله حتما در برنامه هست

**Comment by aghili371** [comment]
با تشکر از تلاش شما، امکان استفاده تجاری در پرژهای خودم رو دارم؟
مشخصه کی برای دات نت کور ارئه می کنید؟

**Comment by Sina-Soltani** [comment]
خواهش میکنم.
بله امکان استفاده شخصی و تجاری وجود داره.
زمان کاملا دقیق برای دات نت کور نمیتونم بهتون بدم.
اما در حال توسعه و نزدیک به اتمام پروژه هست و احتمالش وجود داره طی هفته های آینده منتشر بشه.

**Comment by aghili371** [comment]
بسیار عالی. منتظر انتشار پرژه شما هستم

**Comment by Sina-Soltani** [comment]
نسخه دات نت کور منتشر شد

`Install-Package Parbad.AspNetCore`

OR

`dotnet add package Parbad.AspNetCore`
