### ISSUE TITLE
دریافت اطلاعات درگاه از دیتابیس

### ISSUE THREAD

**Issue by noawar** [Sina-Soltani/Parbad#100]
من یک کلاس ایجاد کردم برای درگاه payIr
`public class PayOptionsProvider : IGatewayAccountSource<PayIrGatewayAccount>
    {
        public async Task AddAccountsAsync(IGatewayAccountCollection<PayIrGatewayAccount> accounts)
        {
            accounts.Add(new PayIrGatewayAccount
            {
                Name = null,
                Api = null,
                IsTestAccount = true
            });
        }
    }`

توی فایل startup.cs جی باید بنویسم؟
چون این خط را ارور میده:
` gateways
                        .AddPayIr()
                        .WithOptionsProvider<PayOptionsProvider>(ServiceLifetime.Transient);`

WithOptionsProvider را نمیشناسه

**Comment by Sina-Soltani** [comment]
مستندات به صورت کامل موجود هست. لطفا مستندات رو مطالعه کنید

[Adding an account using a custom source](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-an-account-using-a-custom-source-such-as-database)

**Comment by noawar** [comment]
ممنون درست شد. من طبق آموزش سایت dotnettips پیش می رفتم.

**Comment by Sina-Soltani** [comment]
اونجا متاسفانه امکان ویرایش آموزش‌ها و مثال وجود نداره و مثال‌هایی که اونجا نوشته شده قدیمی هستن.
آخرین آموزش‌ها و نمونه کدها رو در همین گیت هاب دنبال کنید
