### ISSUE TITLE
درگاه بانک ملت: فرمت اطلاعات وارد شده صحيح نمي باشد

### ISSUE THREAD

**Issue by noawar** [Sina-Soltani/Parbad#101]
پیغام:
فرمت اطلاعات وارد شده صحيح نمي باشد
لطفا میشه بفرمایید اشکال کار من کجاست؟
`invoice .UseAutoRandomTrackingNumber() .SetAmount(viewModel.Amount) .SetCallbackUrl(verifyUrl) .UseMellat(mellat => mellat.AddMellatCumulativeAccount(1000, viewModel.Amount));`
این subserviceId چی هست؟
در حالت تست terminalId را چی بدم؟

**Comment by Sina-Soltani** [comment]
> 
> 
> پیغام:
> فرمت اطلاعات وارد شده صحيح نمي باشد
> لطفا میشه بفرمایید اشکال کار من کجاست؟

این قابلیت در این درگاه هنوز به صورت واقعی تست نشده و ممکنه مشکلاتی داشته باشه
لطفا یکبار با
SubServiceId
تست کنید و گزارش بدید نتیجه رو

> 
> 
> این subserviceId چی هست؟


SubServiceId
و بقیه موارد در مستندات این بانک ذکر شده و توضیح داده شده

> 
> در حالت تست terminalId را چی بدم؟

درگاه بانک باید به شما داده باشه این اطلاعات رو

**Comment by noawar** [comment]
> > پیغام:
> > فرمت اطلاعات وارد شده صحيح نمي باشد
> > لطفا میشه بفرمایید اشکال کار من کجاست؟
> 
> این قابلیت در این درگاه هنوز به صورت واقعی تست نشده و ممکنه مشکلاتی داشته باشه
> لطفا یکبار با
> SubServiceId
> تست کنید و گزارش بدید نتیجه رو
> 
> > این subserviceId چی هست؟
> 
> SubServiceId
> و بقیه موارد در مستندات این بانک ذکر شده و توضیح داده شده
> 
> > در حالت تست terminalId را چی بدم؟
> 
> درگاه بانک باید به شما داده باشه این اطلاعات رو

خب منم طبق مستندات پیش رفتم ولی موقع انتقال به درگاه این پیغام را میده. به نظرم یه پارامتری درست ارسال نمیشه

**Comment by Sina-Soltani** [comment]
بررسی میکنم بهتون اطلاع میدم

**Comment by Sina-Soltani** [comment]
بررسی شد و اطلاعات دقیقا مطابق با مستندات درگاه بانک ارسال میشه

آیا شما حتما به ارسال درخواست از نوع
Cumulative
نیاز دارید یا اینکه درخواست ساده پرداخت براتون کفایت میکنه؟

اگر بله، در این صورت پیشنهاد میکنم که با پشتیبان درگاه ملت تلفنی چک کنید تا ببینید مشکل از چی هست و چه چیزی در ارسال درخواست باید باشه که نیست
معمولا پشتیبانی درگاه ملت، میتونن پارامتر‌های ورودی و متدها رو به صورت همزمان با شما چک کنن و بگن مشکل کجاست

**Comment by noawar** [comment]
> بررسی شد و اطلاعات دقیقا مطابق با مستندات درگاه بانک ارسال میشه
> 
> آیا شما حتما به ارسال درخواست از نوع
> Cumulative
> نیاز دارید یا اینکه درخواست ساده پرداخت براتون کفایت میکنه؟
> 
> اگر بله، در این صورت پیشنهاد میکنم که با پشتیبان درگاه ملت تلفنی چک کنید تا ببینید مشکل از چی هست و چه چیزی در ارسال درخواست باید باشه که نیست
> معمولا پشتیبانی درگاه ملت، میتونن پارامتر‌های ورودی و متدها رو به صورت همزمان با شما چک کنن و بگن مشکل کجاست

نه همون ساده کفایت می کنه. الان روی لوکام

**Comment by Sina-Soltani** [comment]
اگر درخواست ساده کفایت میکنه پس نیازی به پر کردن مقادیر
Cumulative
به هیچ وجه نیست

```c#
invoice.SetGateway("Mellat");
```
یا
```c#
invoice.UseMellat();
```

**Comment by noawar** [comment]
> اگر درخواست ساده کفایت میکنه پس نیازی به پر کردن مقادیر
> Cumulative
> به هیچ وجه نیست
> 
> ```cs
> invoice.SetGateway("Mellat");
> ```
> 
> یا
> 
> ```cs
> invoice.UseMellat();
> ```

خیر بازم همون پیغام
یه جایی خودم دارم اشتباه می کنم...
آیا به لوکال بودن پروژه ارتباطی نداره؟

`accounts.Add(new MellatGatewayAccount
            {
                Name ="Mellat",
                IsTestTerminal = true,
                TerminalId = 0,
                UserName ="test",
                UserPassword ="test"
            });`

**Comment by Sina-Soltani** [comment]
اطلاعات حساب که دارید ارسال میکنید درسته؟
شماره ترمینال
نام کاربری
رمز عبور

(اطلاعات حساس رو اینجا قرار ندید)

**Comment by noawar** [comment]
> اطلاعات حساب که دارید ارسال میکنید درسته؟
> شماره ترمینال
> نام کاربری
> رمز عبور
> 
> (اطلاعات حساس رو اینجا قرار ندید)

اینها اطلاعات تست لوکاله

**Comment by Sina-Soltani** [comment]
تست لوکال که اصلا فکر نمیکنم وجود داشته باشه برای بانک ملت
ترمینال تست وجود داره که اونم باید آنلاین تست بشه با اطلاعات صحیح که به فروشنده میدن
اگه ندارید پس باید دریافت کنید

**Comment by Sina-Soltani** [comment]
برطرف شده مشکل شما؟

**Comment by noawar** [comment]
> برطرف شده مشکل شما؟

نه شاید چون روی لوکاله اینطوره

**Comment by Sina-Soltani** [comment]
این تیکت رو باید ببندیم؟

**Comment by noawar** [comment]
> این تیکت رو باید ببندیم؟

ظاهرا همینطوره, بعد هز اینکه موفق شدم از بانک ترمینال ای دی بگیرم مجددا مراحم میشم.
در کل ازتون ممنونم این سیستم خیلی کارمو راه انداخت

**Comment by Sina-Soltani** [comment]
خواهش میکنم.
موفق باشید
