### ISSUE TITLE
Invalid data is received from the gateway

### ISSUE THREAD

**Issue by sadeq-qafari** [Sina-Soltani/Parbad#102]
ما با سه درگاه به پرداخت ملت، سامان کیش تجارت و سامان کیش انصار پس از پرداخت موفق، هنگام تایید توسط پرباد با خطای زیر مواجه میشویم
Invalid data is received from the gateway

**Package name and version**
* Package Name: Parbad.AspNetCore 
* Version: 1.0.6

**Web application type:**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
لطفا کدهای پرداخت رو اینجا قرار بدید تا بررسی کنیم

**Comment by sadeq-qafari** [comment]
قبلا کار میکرد با همین تنظیمات فعلی اما از دیروز این مشکل پیش اومد و پکیج رو آپدیت کردیم و بازم درست نشد.

نمونه تنظیمات برای درگاه سامان که خطا میده:

    services.AddParbad()
      .ConfigureGateways(gateways =>
      {
         gateways.AddSaman()
             .WithAccounts(accounts =>
             {
                 accounts.AddInMemory(account =>
		     {
                        account.MerchantId = "MerchantId";
                        account.Password = "Password";
                        account.Name = "AccountName";
                 });
            });
      });

**Comment by sadeq-qafari** [comment]
ممکنه از 
nginx
باشه؟

ما از انجین ایکس برای پروکسی کردن درخواستها به برنامه ها استفاده میکنیم. وقتی از درگاه ملت داره منتقل میشه ممکنه یکسری پارامترها به برنامه پروکسی نشه؟ هرچند ما سعی کردیم همه  پارامترها و داده ها رو فوروارد کنیم

**Comment by Sina-Soltani** [comment]
بله احتمالش هست. چون از لحاظ دریافت و کنترل پارامترهای بانکی همه چیز تست و کنترل شده.
خودتون به صورت دستی در قسمت اکشن متد
Verify
تمام پارامترهای دریافتی رو لیست کنید داخل ویو یا جیسون نمایش بدید ببینید چه پارامترهایی دریافت شده

**Comment by sadeq-qafari** [comment]
ممنون بله تست کردیم. برای درگاه ملت فقط کلید توکن پرداخت در کوئری هست. دیگه چه پارامترهایی در چه بخشی باید وجود داشته باشه؟

مثلا در 
Query
یا
Form
یا
Body
?

**Comment by sadeq-qafari** [comment]
حل شد.
مشکل از این بود که ما توسط دستور زیر آدرس برگشت رو اتوماتیک حساب میکردیم:

    var callbackUrl = Url.Action("Verify", "Payment", null, Request.Schema);

و ما چون پشت پروکسی بودیم، خودش اتوماتیک 
http
بدست میاورد که ناچار شدیم دستی
https
بدیم.

    var callbackUrl = Url.Action("Verify", "Payment", null, "https");
