### ISSUE TITLE
ریفاند انجام نمیشود

### ISSUE THREAD

**Issue by sadeq-qafari** [Sina-Soltani/Parbad#103]
سلام

عملیات پرداخت به درستی انجام میشود. اما ریفاند همیشه خطای زیر را میدهد:

IP Address پذیرنده نامعتبر است

درگاه سامان کیش است.
آیا مشکل از درگاه است؟ چرا موقع پرداخت خطای آی پی نمیدهد!

با تشکر

**Comment by Sina-Soltani** [comment]
درود
کد ها تست شده و بعید میدونم مشکلی وجود داشته باشه
خطایی که دریافت کردید به این معنی هست که درگاه سامان به جای مقدار هزینه ای که باید برگشت بخوره، به شما کد
-۱۸
رو ارسال کرده 
و این کد طبق مستندات درگاه، به معنای آی پی نامعتبر هست
بنابراین شما باید با خود درگاه تماس بگیرید و این مورد رو سوال کنید که چرا چنین پیغامی دریافت میکنید

(یک سری از درگاه ها، عملیات برگشت پول رو در حالت عادی غیر فعال میکنند و فقط زمانیکه فروشنده در قرارداد خواستار این قابلیت باشه اون رو فعال میکنن)

**Comment by sadeq-qafari** [comment]
ممنون از پاسخگویی سریعتون.
داریم مشکل رو از سمت درگاه پیگیر میشیم، احتمال زیاد مشکل همین هستش که شما فرمودین و قابلیت برگشت پول از سمت درگاه باید برای ما فعال بشه.
