### ISSUE TITLE
Verify بانک ملت

### ISSUE THREAD

**Issue by amirreza58** [Sina-Soltani/Parbad#104]
سلام

در نرم افزار از سه درگاه بصورت همزمان استفاده میکنم

 هر سه درگاه به یک آدرس بازگشت میشوند ولی در هنگام برگشت از پرداخت از درگاه بانک ملت با خطای زیر مواجه میشم

`InvalidDataReceivedFromGateway `

روند بازگشت در درگاه های دیگه مثل زرین و آی دی پی  بدون مشکل کار میکنه

لطفا راهنمایی کنید

**Comment by Sina-Soltani** [comment]
درود
این درگاه تست شده و مشکلی وجود نداره

لطفا تنظیمات وب سایت خودتون رو چک کنید

* پروکسی استفاده میکنید؟
* آیا از لود بالانتسر استفاده میکنید؟
* آیا
Callback URL
که در هنگام ارسال درخواست ایجاد میکنید درست هست؟
* آیا پروتکل موجود در این آدرس
که یا
HTTP
و یا
HTTPS
شروع میشه، در هنگام بازگشت از درگاه بانک هم همون آدرس هست و یا تغییر داده شده؟

**Comment by amirreza58** [comment]
سلام
مشکل از cloudflare است
ظاهرا بدلیلی  Formdata به سرور ارسال نمیشود
بانک مقادیر را ارسال میکند ولی به سرور نمیرسد با غیر فعال کردن cloudflare مشکل رفع شد

آیا باید تنظیمی برای cloudflare انجام شود؟

**Comment by Sina-Soltani** [comment]
اگر منظورتون از تنظیم، تنظیم در این پکیج هست، خیر تنظیمی وجود نداره و نیازی هم نیست که باشه
همونطور که خودتون اشاره کردید، اطلاعات ارسال نشده. بنابراین از چیزی که وجود نداره نمیشه انتظار نتیجه ای هم داشت
این مورد رو باید با صاحب هاست و یا فرد متخصص در میان بزارید.

**Comment by amirreza58** [comment]
مرسی

**Comment by najafzadeh1055** [comment]
سلام؛  من پرداخت زرین پال و بانک ملت رو همزمان دارم
برای زرین پال هیچ مشکلی نیست
ولی برای بانک ملت بعد از پرداخت موفق بانک و برگشت به سایت همه session ها پاک می شود!

زیرساخت: ASP.NET Web from است و از  NGINX به عنوان لود بالانتسر و دامنه بر روی HTTPS

**Comment by Sina-Soltani** [comment]
@najafzadeh1055 
درود
لطفا از تیکت‌های دیگه برای طرح پرسش جدید استفاده نکنید.
محتوا و موضوع هر تیکت برای خودش منحصر به فرد هست.
برای پرسش جدید باید تیکت جدید ارسال کنید.

**Comment by najafzadeh1055** [comment]
سلام و درود؛ ضمن تشکر از پاسخگویی؛ [جهت اشتراک راه حل]
مشکل پیدا شد که ظاهرا مربوط به  SameSite cookie است که در نسخه 80 گوگل کروم و نسخه های جدید فایرفاکس اتفاق افتاده است و در برگشت های غیرسایت جاری، منجر به خالی شدن Session خواهد شد؛ و با قطعه کد زیر در webconfig مشکل رفع شد؛ 

`<httpCookies httpOnlyCookies="true" requireSSL="true" sameSite="None"/>
<sessionState cookieSameSite="None" />`
