### ISSUE TITLE
درخواست درگاه یک پی

### ISSUE THREAD

**Issue by Anushiravani** [Sina-Soltani/Parbad#105]
امکانش هست درگاه یک پی هم اضافه کنید ؟
مستنداتش :

[Yekpay-Documentation-fa-1.7.pdf](https://github.com/Sina-Soltani/Parbad/files/5054783/Yekpay-Documentation-fa-1.7.pdf)

**Comment by Sina-Soltani** [comment]
بله ممکن هست.
تاریخ دقیقی برای انتشار ذکر نمیشه

**Comment by Sina-Soltani** [comment]
درود
درگاه افزوده شد
لطفا در صورت تست، نتیجه رو اعلام کنید

```
Install-Package Parbad.Gateway.YekPay -Version 1.0.0
```

موفق باشید
