### ISSUE TITLE
Change YekPay  MerchantId to string

### ISSUE THREAD

**Issue by Anushiravani** [Sina-Soltani/Parbad#109]
please change Yekpay MerchantId to string

**Comment by Anushiravani** [comment]
![Annotation 2020-08-16 132720](https://user-images.githubusercontent.com/6858775/90330717-3e4c6700-dfc4-11ea-8c66-6273651ee92d.jpg)

**Comment by Sina-Soltani** [comment]
در مستنداتشون برای این پارامتر از کلمه
digits
استفاده کردن که یعنی رقم.
متاسفانه نمیدونن چطور باید به انگلیسی داکیومنت بنویسن

اصلاح میشه به زودی

**Comment by Anushiravani** [comment]
بله منم اول همین فکرو میکردم . متاسفانه این موارد زیاد هست . اگر راهی هست  که من تمام موارد رو فیکس کنم به شما ارسال کنم بفرمایید بعد از اتمام پروژه به شما ارسال کنم

**Comment by Sina-Soltani** [comment]
در صورتیکه تمایل دارید خودتون برطرفش کنید، میتونید یک
Pull-Request
بفرستید تا من پس از بررسی،
Merge
کنم با برنچ اصلی

**Comment by Sina-Soltani** [comment]
لطفا اعلام کنید تا بدونم شما انجام میدید یا باید خودم انجام بدم

**Comment by Anushiravani** [comment]
بله میتونم دسترسی بدید 403 میگیرم

**Comment by Sina-Soltani** [comment]
چه دسترسی ای؟

**Comment by Sina-Soltani** [comment]
[How to send a Pull Request](https://github.com/Sina-Soltani/Parbad/blob/master/CONTRIBUTING.md)

**Comment by Anushiravani** [comment]
![Annotation 2020-08-16 145305](https://user-images.githubusercontent.com/6858775/90332182-35fa2900-dfd0-11ea-98f9-af3d352d5c4b.jpg)

**Comment by Sina-Soltani** [comment]
شما باید اول مخزن رو
Fork
کنید تا یک کپی از مخزن رو در گیت هاب خودتون داشته باشید.
بعدش اون مخزن رو روی سیستم لوکال
Clone
کنید
یک برنچ جدید ازش بسازید
تغییرات رو اعمال کنید
تغییرات رو به مخزن خودتون
Push
کنید
در صفحه گیت هاب روی گزینه
Create Pull Request
کلیک کنید

**Comment by Sina-Soltani** [comment]
شما فراموش کردین شماره نسخه نوگت رو هم تغییر بدید
لطفا یک
Pull Request
دیگه ارسال کنید و ورژن رو به
1.0.1
تغییر بدید تا نوگت جدید تولید بشه

**Comment by Anushiravani** [comment]
ببخشید من تاحالا مشارکت نداشتم مشکلاتم برطرف بشه دیگه این مسائل رو ندارم .ممنون

**Comment by Sina-Soltani** [comment]
خواهش میکنم. مشکلی نیست
