### ISSUE TITLE
مبلغ واریزی

### ISSUE THREAD

**Issue by MohammadReza10** [Sina-Soltani/Parbad#11]
سلام با عرض خسته نباشید 
وقتی از صفحه بانک برگشت داده میشه به سایت خودمون مبلغ واریزی از بانک به ما داده میشه ؟
اگه میشه تو کدوم متد و چطوری اون مبلغ واریزی رو بگیرم و بررسی کنم ببینم طرف  هزینه رو موقع ارسال دستکاری نکرده باشه و درست واریز کرده باشه
با تشکر

**Comment by Sina-Soltani** [comment]
تمامی موارد امنیتی از جمله چک کردن مبلغ، به صورت خودکار توسط پَرباد انجام میشه و نیازی به انجام این کار ندارید.
همچنین امکان دستکاری اطلاعات مانند مبلغ توسط کاربر وجود نداره چون قبل از انتقال کاربر به وب سایت بانک، اطلاعات پرداخت در سمت سرور شما به بانک ارسال شده و بانک در ازای آماده سازی برای پرداخت، یک کلید رمزنگاری شده به ما ارسال میکنه. در نتیجه امکان تغییر وجود نداره
هر چند که چک کردن مبلغ پرداختی برای شرایط خاص مانند بانک سامان، توسط خود پَرباد به صورت توکار انجام میشه و در صورتیکه مبلغی که در دیتابیس ثبت شده با مبلغی که از بانک دریافت میشه مطابقت نداشته باشه، تراکنش به شما ناموفق اعلام میشه.
