### ISSUE TITLE
پیاده سازی سایر درخواست های درگاه ها

### ISSUE THREAD

**Issue by Anushiravani** [Sina-Soltani/Parbad#113]
سلام 
رو درگاه یک پی دارم کار میکنم . 2تا  آدرس دیگه داره واسه تبدیل نرخ ارز و دریافت لوکیشن جهت کد نرخ ارز
برای این دو مود اکستنش متد پیاده سازی بشه بهتره یا روی لایه اصلی پرباد یه تابع کاستوم ریکوئست نوشته بشه با ورودی خروجی جیسون ؟
چون تو درخواست هاشون مرچند کد داره یا اصلا نیازی نیست این کار که تو پروژه بیاد هرکسی خواست خودش پیاده سازی کنه ؟
 
مثال :
استعالم نرخ ارز
https://gate.yekpay.com/api/payment/exchange
PARAMETERS :  MerchantID , FromCurrencyCode, ToCurrencyCode
OutPut: INT with code status

**Comment by Sina-Soltani** [comment]
درود
در حال حاضر فقط سه عمل اصلی پرداخت، تایید و بازگشت، برای کلیه درگاه‌های بانکی ساپورت میشه
سایر امکانات در حال حاضر باید برای توسط مصرف کننده ها به صورت شخصی توسعه داده بشه
البته امکانش هست که تغییراتی در لایه های بالا انجام بدم تا مصرف کننده ها بتونن سایر عملیات رو راحت پیاده سازی کنن

**Comment by amirreza58** [comment]
سلام
درگاه سیزپی و زیبال را هم هم بررسی کنید

**Comment by Sina-Soltani** [comment]
> 
> 
> سلام
> درگاه سیزپی و زیبال را هم هم بررسی کنید

درود
تعداد درگاه‌های واسط قطعا یکی دو تا نیست و زیاد هستن. بنابراین توسعه همه اونها توسط یک نفر برابر هست با مدت زمان خیلی طولانی تر. چون بنده فقط آخر هفته به این مسائل نگاه میکنم

توسعه دهنده ها خودشون هم میتونن درگاه رو کدنویسی کنن و
Pull Request
ارسال کنن تا در اینجا افزوده بشه
آموزش توسعه درگاه جدید موجود هست. همچنین سایر درگاه‌های توسعه داده شده میتونن نمونه مثال باشن
[توسعه درگاه جدید](https://github.com/Sina-Soltani/Parbad/wiki/Developing-a-new-Gateway)
[درگاه‌های پیاده سازی شده](https://github.com/Sina-Soltani/Parbad/tree/master/src/Parbad.Gateway)
