### ISSUE TITLE
درگاه پارسیان

### ISSUE THREAD

**Issue by voogle** [Sina-Soltani/Parbad#114]
سلام وقت بخیر 
من میخواستم از درگاه پارسیان استفاده کنم
دسترسی که بهم دادن حاوی PIN Code و Terminal ID هستش ، 
توی تنظیمات ConfigureGateways برای پارسیان این پارامتر ها اصلن وجود ندارند ، چطور باید پارسیان رو کانفیگ کرد ؟
برای پارسیان فقط LoginAccount  و Name وجود داره

`            services.AddParbad()
                .ConfigureGateways(gateways =>
                {
                    gateways
                         .AddParsian()
                         .WithAccounts(source =>
                         {
                             source.AddInMemory(account =>
                             {
                                 account.LoginAccount = "xxxxx";
                                 account.Name = "yyyyy";
                             });
                         });
                });`

**Comment by Sina-Soltani** [comment]
درود

پاسخ:
https://github.com/Sina-Soltani/Parbad/issues/94#issuecomment-654453458
