### ISSUE TITLE
SQL Script

### ISSUE THREAD

**Issue by emdadgar2** [Sina-Soltani/Parbad#115]
سلام
یا تشکر از پروژه مفیدتان
‫لطف می فرمایید script مربوط به دیتابیس sql server را به صورت مجزا قرار دهید تا نیازی به migration نباشد؟
ممنون

**Comment by Sina-Soltani** [comment]
درود

Migrations
فقط برای ایجاد بانک اطلاعاتی نیستن، دلیل اصلی استفاده از اونها، تغییراتی هست که گاهی در این جداول داده میشه بعد از انتشار نسخه های جدید
اگر قرار باشه اسکپریت به صورت مجزا قرار داده بشه، اونوقت باید بر از هر تغییری در جداول، اسکریپت تغییر نیز قرار داده بشه که این کار رو معمولا کسی انجام نمیده حتی کمپوننت های معروفی مانند
IdenetityServer
