### ISSUE TITLE
خطای در مورد Owin

### ISSUE THREAD

**Issue by keyone2693** [Sina-Soltani/Parbad#116]
اپدیت کردیم اخرین ورزن 
این ارورو داره
Asp mvc 5

Could not load file or assembly 'Microsoft.AspNetCore.Owin, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.

**Comment by Sina-Soltani** [comment]
درود

پروژه خطایی نداره
مشکل احتمالا داخلی از سمت خودتون هست
هر چند که خطا داره به شما میگه که باید پکیج زیر رو نصب کنید

`Install-Package Microsoft.AspNetCore.Owin -Version 2.2.0`

**Comment by keyone2693** [comment]
خب تو asp mvc .netframwork که نمیزاره اینو نصب کنیم



[DependencyResolutionException: An exception was thrown while activating λ:Areas.Site.Controllers.TrainsController -> Areas.Site.Controllers.TrainsController -> λ:Parbad.Internal.DefaultOnlinePayment -> Parbad.Internal.DefaultOnlinePayment -> λ:Parbad.Internal.GuidQueryStringPaymentTokenProvider -> Parbad.Internal.GuidQueryStringPaymentTokenProvider -> λ:Parbad.Owin.Http.OwinHttpContextAccessor -> Parbad.Owin.Http.OwinHttpContextAccessor.]

**Comment by Sina-Soltani** [comment]
> 
> 
> خب تو asp mvc .netframwork که نمیزاره اینو نصب کنیم
> 

[پروژه نمونه](https://github.com/Sina-Soltani/Parbad/tree/master/samples/Parbad.Sample.Mvc)
