### ISSUE TITLE
Error: Invalid object name 'parbad.payment'.

### ISSUE THREAD

**Issue by feryt20** [Sina-Soltani/Parbad#118]
**Bug description (wIthout specifiing the sensitive data)**
با سلام و احترام
بنده هنگام استفاده از تنظیمات پیشفرض برای دخیره اطلاعات در دیتابیس با خطای زیرا مواجه میشم
Invalid object name 'parbad.payment'.
از این لینک استفاده کردم:
https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-entityframework-core

```
.ConfigureStorage(builder =>
                {
                    builder.UseEfCore(options =>
                    {
                        // Using SQL Server
                        var assemblyName = typeof(Startup).Assembly.GetName().Name;
                        options.ConfigureDbContext = db => db.UseSqlServer(con.GetSection("Financial").Value, sql => sql.MigrationsAssembly(assemblyName));

                    });
                });
```

نمیدونم مشکل از کجاست
لطفا راهنمایی کنید

**Package name and version**
**نام و نسخه پکیج**
* Package Name: Parbad
* Version: 3.5.1

**Web application type:**
**نوع برنامه وب**
* ASP.NET CORE 3.1

**Comment by Sina-Soltani** [comment]
درود

خطا رو
SQL Server
داره به شما میده و میگه جدولی به نام
parbad.payment
در پایگاه داده شما وجود نداره.

اگر مطابق راهنمای
EFCore
پیش رفته باشید نباید چنین خطایی ببینید

احتمالا شما قسمت اضافه کردن
Migration
و آپدیت کردن دیتابیس رو انجام ندادید

راهنما رو یکبار دیگه نگاه کنید و کامل انجام بدید
