### ISSUE TITLE
تفاوت is_paid و is_completed

### ISSUE THREAD

**Issue by parsintalk** [Sina-Soltani/Parbad#119]
سلام، ضمن تشکر از زحمات شما.
می تونم بپرسم تفاوت فیلد های is_paid و is_completed در جدول payment چیه؟
با سپاس فراوان

**Comment by Sina-Soltani** [comment]
درود

is_paid
آیا انتقال پول انجام گرفت؟

is_completed
بیانگر بسته شدن پرونده یک تراکنش هست. چه موفق، چه ناموفق

**Comment by parsintalk** [comment]
سپاس فراوان
