### ISSUE TITLE
ایدی دیتابیس

### ISSUE THREAD

**Issue by MohammadReza10** [Sina-Soltani/Parbad#12]
با سلام
در کدوم قسمت و کدوم متد میتونم 
ایدی دیتابیس که guid 
هستش رو بگیرم
چون میخوام تو جدول دیگه ای ب غیر جدول مورد نظر شما هم کلید خارجی بدم
این مورد خیلی واجبه
با تشکر

**Comment by Sina-Soltani** [comment]
کلید اصلی جدول سیستم پَرباد، برای مصرف داخلی درون سیستمی هست و شما برای کارهای مورد نیاز خودتون از همون شماره سفارش که تولید کردید استفاده کنید چون شماره سفارش کد کاملا یکتا هست و میتونه برای شما یک رفرنس به حساب بیاد
