### ISSUE TITLE
شیوه صحیح به روز رسانی دیتابیس هنگام وریفای

### ISSUE THREAD

**Issue by mrmashal** [Sina-Soltani/Parbad#120]
با سلام و خداقوت

در نمونه کدهای پرباد، خروجی
VerifyAsync
مستقیما برای نمایش به کاربر ارسال میشود اما فرض کنیم که باید ابتدا اطلاعات مربوط به خرید در دیتابیس به روز رسانی شده و سپس نتایج به کاربر نمایش داده شود. سوال من این هست که اولا آیا روش معمول برای این کار این هست که کد مربوط به به روز رسانی اطلاعات خرید بلافاصله بعد از وریفای قرار داده بشه؟ و در این صورت اگر به هر دلیل وریفای با موفقیت انجام شد اما به روز رسانی اطلاعات 
خرید در دیتابیس ثبت نشد (مثلا به دلیل وجود باگ در برنامه یا به دلیل خاموش شدن ناگهانی سرور) آیا باید
Refund
زده بشه یا امکانش هست که مجددا از پرباد استعلام گرفت؟

**Comment by Sina-Soltani** [comment]
درود

هنگامیکه کاربر پرداخت رو انجام میده و به وب سایت شما برمیگرده، عملیات 
Fetch
انجام میشه تا صورت حسابه درخواست شده، مورد بررسی قرار بگیره.
در نتیجه ی این عمل، دو پراپرتی مهم وجود داره

Status 
که بیانگر این هست که صورت حساب جدیده یا اینکه قبلا مورد بررسی قرار گرفته شده

IsAlreadyVerified 
که بیانگر این هست که با توجه به اینکه صورت حساب قبلا مورد بررسی قرار گرفته، آیا پرداخت هم واقعا انجام شده یا خیر

هر دوی این پارامترها، توسط پَرباد بعد از اجرای دستور
Verify
به روز رسانی و ذخیره میشن در پایگاه داده شما.

بنابراین اگر فرض رو بر این بزاریم که
Verify
انجام گرفت و شما در هنگام به روز رسانیه اطلاعاته خودتون به خطای ناگهانی بر بخورید، همچنان اطلاعات کامل و مراحل طی شده عملیات پرداخت، در داخل پایگاه داده شما ذخیره شده

در نتیجه شما میتونید در هر زمانی با توجه به شماره پیگیری یا به اصطلاح همون
TrackingNumber
جدول پرداخت و تراکنش‌هایی که پَرباد برای شما پر میکنه رو جستجو کنید و ببینید که وضعیت اون دو پارامتری که گفتم به چه صورت هست
اگه پرداخت مورد نظر موفق بوده باشه که خب شما ادامه مراحل تجاری خودتون رو طی میکنید
اگه نبوده باشه شما به راحتی دستور
Verify
رو صدا میزنید که بهش شماره پیگیری
TrackingNumber
رو میدید و عملیات دوباره تکرار میشه

**Comment by mrmashal** [comment]
سلام. در خصوص این سوال الان تست کردم خیلی ساده تونستم یک وهله از استوریج پرباد رو با تزریق وابستگی به این صورت:
`Parbad.Storage.Abstractions.IStorageManager parbadStorageManager`
بدست بیارم و بعد با استفاده از
`parbadStorageManager.GetPaymentByTrackingNumberAsync(myTrackingNumber)`
به رکورد پرداخت پرباد دسترسی پیدا کنم.

خواستم ببینم آیا این روش رو توصیه میکنید؟

**Comment by Sina-Soltani** [comment]
درود

بله این روش هم کاملا درست هست و چیزی نیست که جز عملیات داخلی به حساب بیاد.
چون مخزن داده، کاملا قابلیت برنامه ریزی توسط کاربر رو داره
