### ISSUE TITLE
امکان تسهیم در پرداخت

### ISSUE THREAD

**Issue by rezafaghani** [Sina-Soltani/Parbad#125]
سلام پرباد امکان تسهیم مبالغ پرداختی رو داره ؟
امکان اینکه یه مبلغ مشخص رو دریافت کنیم از کاربر و به حسابهای مختلف واریز کنیم

**Comment by Sina-Soltani** [comment]
درود

پَرباد یک ابزار پرداخت هست و به خودی خود سیستم بانکی نیست که بگیم آیا فلان امکان بانکی رو داره یا خیر.
در واقع سوال رو باید اینطور مطرح کرد: آیا امکان تسهیم پرداخت در بانک الف یا بانک ب، توسط پَرباد قابل انجام هست یا خیر

با توجه به توضیح بالا بفرمایید چه بانکی مدنظرتون هست؟

**Comment by rezafaghani** [comment]
مرسی ، 
 آیا امکان تسهیم پرداخت در بانک ملی یا بانک ملت، توسط پَرباد قابل انجام هست یا خیر
و در تمامی دیگر درگاه هایی که شما در سیستم پرباد ثبت کردید.
البته بهتر است اینطور سوال را تکمیل کنم امکان افزودن امکانات اختصاصی در پرباد وجود دارد ؟

**Comment by Sina-Soltani** [comment]
> 
> 
> آیا امکان تسهیم پرداخت در بانک ملی یا بانک ملت، توسط پَرباد قابل انجام هست یا خیر

امکانات اختصاصی تهیه شده برای تمام درگاه‌ها رو در این صفحه میتونید مشاهده کنید
[Gateways specific functions](https://github.com/Sina-Soltani/Parbad/wiki/Gateways-specific-functions)
تسهیم در پرداخت برای بانک ملی هنوز آماده نشده


> 
> 
> و در تمامی دیگر درگاه هایی که شما در سیستم پرباد ثبت کردید.

در حال حاضر فقط برای بانک ملت پیاده سازی شده


> 
> 
> البته بهتر است اینطور سوال را تکمیل کنم امکان افزودن امکانات اختصاصی در پرباد وجود دارد ؟

افزودن امکانات اختصاصی از طریق کدنویسی امکان پذیر هست، زمانیکه مصرف کننده سورس رو دانلود کنه و خودش امکان مورد نظر رو اونطور که تمایل داره پیاده سازی کنه
البته خب از اونجایی که این پکیج برای همه هست، راه بهترش اینه که کاربران در توسعه پکیج شرکت داشته باشن و
Pull Request
ارسال کنن تا در پکیج اصلی درج بشه تا سایرین هم استفاده کنن.
چون امکاناتی که میتونه اضافه بشه یکی دوتا نیستن و مسلما برای من مقدور نیست تمام وقتم رو صرف اینکار بکنم

**Comment by rezafaghani** [comment]
ممنونم ، تسهیم بانک ملت رو تست کردم جواب نداد ، من روی تسهیم کار میکنم برای بانک ملی و یانک ملت و پول ریکوئست میدم به پروژه

**Comment by Sina-Soltani** [comment]
بسیار خوب
لطفا این صفحه رو مطالعه کنید. چند نکته کوتاه ولی مفید در مورد ارسال پول ریکوئست هست که باید رعایت بشه
[نحوه مشارکت در پروژه](https://github.com/Sina-Soltani/Parbad/blob/master/CONTRIBUTING.md)
اگر سوالی داشتید بپرسید
