### ISSUE TITLE
خطای رمزنگاری دیتا در هنگام SignRequestData

### ISSUE THREAD

**Issue by mohammad68a** [Sina-Soltani/Parbad#13]
با سلام متد 
SignRequestData 
در هنگام استفاده از درگاه بانک ملی سداد خطای زیر را می دهد

The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters

که نمیتواند مقدار terminalKey را بصورت Base64 تبدیل کند

**Comment by Sina-Soltani** [comment]
TerminalKey
شما به احتمال زیاد نامعتبر هست
کلیدی که بانک به شما داده رو بدون دست کاری استفاده کنید
این کلید باید قابلیت تبدیل از فرمت
Base64
باشد

**Comment by mohammad68a** [comment]
همینکارو کردم متاسفانه کار نمیکنه فقط
TerminalId
قابلیت تبدیل از
base64
را داره که از اونم نمیشه استفاده کرد
در داکیومنت بانک چیزی در مورد
SignData
ندیدم کاربردش چیه دقیقا؟

**Comment by Sina-Soltani** [comment]
فایل
PDF
که بانک به شما تحویل داده رو لطفا بزارید اینجا تا ببینم چه ویرایشی رو به شما تحویل دادن
بانک باید به شما سه مقدار تحویل بده
TerminalID
MerchantID
TerminalKey ==> Base64

مقداری تحت عنوان
TransactionKey
وجود نداره
