### ISSUE TITLE
اضافه کردن داینامیکgateway ها

### ISSUE THREAD

**Issue by parsintalk** [Sina-Soltani/Parbad#135]
ضمن عرض سلام و تشکر و خسته نباشید.
آیا راهی هست که من بتونم از رو دیتابیس  gateway ها رو اضافه کنم؟
مثال مربوط به اضافه کردن اکانت ها رو دیدم اما این مورد برای یک گیت وی خاص مثل ملت ایجاد شده.
من می خوام بسته به تنظیمات از پایگاه داده اکانت های مختلف روی گیت وی های مورد نیاز فعال کنم.
اینجا رو نگاه کردم: 
https://github.com/Sina-Soltani/Parbad/issues/66
اما
gateways.Add
ظاهرا وجود نداره و به جاش 
addgateway
اضافه شده که اونم یه تایپ خاص مثل زرین پال رو قبول می کنه.
ممنون میشم راهنماییم کنید.

**Comment by Sina-Soltani** [comment]
درود

ویژگی که شما نیاز دارید در حال توسعه هست و هنوز برای انتشار آماده نشده

در حال حاضر، افزودن داینامیک خود اکانت‌ها امکان پذیر هست که در این راهنما آموزش داده شده
[adding an account using a custom source such as database](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-an-account-using-a-custom-source-such-as-database)

اگر قابلیت افزودن کاملا داینامیک برای خود درگاه‌ها مد نظرتون هست، مانند اون مثالی که در اون تیکت نوشته شده، باید منتظر باشید تا توسعه تمام بشه و آماده انتشار بشه

**Comment by parsintalk** [comment]
سلام، بله دقیقا منظورم همین بود.
بی صبرانه منتظرش می مونم.
سپاس بیکران  بابت زحمات و پروژه خوبتون.

**Comment by Sina-Soltani** [comment]
خواهش میکنم
پس از انتشار اطلاع رسانی خواهد شد
موفق باشید

**Comment by parsintalk** [comment]
سلام و عرض احترام.
امکانش هست در مورد ویژگی بالا سوال کنم؟
تو نسخه های جدید اضافه شده و یا به زودی اضافه خواهد شد؟
با سپاس فراوان

**Comment by Sina-Soltani** [comment]
درود

متاسفانه خیر

البته اگر این مورد رو به صورت دیگه ای نگاه کنید، شاید حتی نیازی بهش نداشته باشید
این پکیج تعداد کاملا مشخصی درگاه داره. برای مثال
* ملت
* ملی
* سامان
* و غیره

اگر تمام این درگاه ها در قسمت تنظیمات اضافه بشن و اکانت های اونا رو به صورت [داینامیک](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-the-accounts-dynamically-using-a-custom-source) از پایگاه داده بخونید و اضافه کنید، دیگه فکر نمیکنم نیاز خاص دیگه ای باشه
درسته؟
