### ISSUE TITLE
Values ​​to be replaced to replace the real gate instead of the simulation

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#137]
Values ​​to be replaced to replace the real gate instead of the simulation

**Comment by Sina-Soltani** [comment]
What's this about?

**Comment by mmo1383** [comment]
How to replace Bank Mellat with testing

**Comment by Sina-Soltani** [comment]
If you mean you want to use the test terminal in Mellat gateway, you must set the `IsTestTerminal` property to true in `ConfigureGateways` method.
