### ISSUE TITLE
نحوه انجام عملیات verify

### ISSUE THREAD

**Issue by amin-pi** [Sina-Soltani/Parbad#138]
سلام.
توی یه پروژه از پرباد دارم استفاده میکنم به همراه درگاه زرین پال
پروژه ی من شامل سرویس های رست و کلاینت انگولار هست
درخواست از سمت کلاینت میاد
فاکتور تولید میشه و کارهای سمت بک اند انجام میشه و لینک ارسال میشه برای کلاینت و کلاینت کاربر رو میفرسته به درگاه
فعلا از حالت SandBox دارم استفاده میکنم
بعد از انتخاب موفق یا ناموفق بودن عملیات، کاربر از درگاه ریدایرکت میشه به کلاینت مجدد
تا اینجا همه چیز خوب پیش میره
توی این مرحله میخوام چک کنم که آیا پرداخت درست صورت گرفته یا نه
واسه همین اطلاعات رو میفرستم با یک سرویس به سمت سرور
اما اونجا نتیجه verify رو فالس برمیگردونه
برای این کار از کد زیر استفاده میکنم
`var verifyResult = await _onlinePayment.VerifyAsync(trackingCode);`

ممنون میشم راهنماییم کنید.

**Comment by Sina-Soltani** [comment]
درود

لطفا آموزش‌ها رو مطالعه کنید همه چیز موجوده
[آموزش](https://github.com/Sina-Soltani/Parbad/wiki/Payment#verifying-a-payment)

[نمونه مثال](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.AspNetCore/Controllers/PaymentController.cs#L57)

**Comment by amin-pi** [comment]
از روی آموزش ها پیاده سازی رو انجام دادم
`var invoice = await _onlinePayment.FetchAsync();`
این خط، خطا میده
"No Token is received."
-------------------------------------------
این آورلود از متد verify به نظر وجود نداره
`var result = await _onlinePayment.VerifyAsync(invoice =>
    {
        // در این مرحله هنوز درخواست واریز وجه از وب سایت شما به بانک ارسال نشده است
        // بنابراین شما می‌توانید اطلاعات صورتحساب را با پایگاه داده خود چک کنید
        // و در صورت لزوم تراکنش را لغو کنید

        if (!Is_There_Still_Enough_SmartPhone_In_Shop(invoice.TrackingNumber))
        {
            // لغو عملیات پرداخت
            invoice.CancelPayment("We have no more smart phones to sell.");
        }
    });`

**Comment by Sina-Soltani** [comment]
از چه ورژنی دارید استفاده میکنید؟

**Comment by amin-pi** [comment]
`
    <PackageReference Include="Parbad" Version="3.5.3" />
    <PackageReference Include="Parbad.Gateway.ZarinPal" Version="1.0.5" />
    <PackageReference Include="Parbad.Storage.EntityFrameworkCore" Version="1.1.0" />
`

**Comment by Sina-Soltani** [comment]
- متدی که در کامنت بالا نوشتید اصلا وجود نداره و برای ورژن های خیلی قدیمی بوده

 علت این که شما در هنگام برگشت به وب سایت اون خطا رو دریافت میکنید، به این خاطر هست که شما به جای اینکه آدرس بازگشتی رو آدرسی بر روی سمت سرور بدید، آدرسی به سمت کلاینت دادید

در نتیجه تمامه اطلاعاتی که بانک آماده کرده و هنگام بازگشت به شما داده تا بررسیشون کنید رو شما از بین بردید و دیگه هیچ اطلاعاتی موجود نیست

در نهایت شما زمانیکه دیگه هیچ اطلاعاتی وجود نداره کاربر رو به سرور هدایت کردید و دستور
Fetch
بررسی میکنه میبینه هیچ اطلاعات بانکی ای از ریکوعست جاری نمیتونه پیدا کنه و به شما خطا میده

**Comment by amin-pi** [comment]
ورژن هایی که نصب کردم مشکل دارن؟
`
<PackageReference Include="Parbad" Version="3.5.3" />

<PackageReference Include="Parbad.Gateway.ZarinPal" Version="1.0.5" />

<PackageReference Include="Parbad.Storage.EntityFrameworkCore" Version="1.1.0" />

`

متوجه نمیشم چطوری باید ریدایرکت کنم به یه سرویس؟
پروژه بک اند فقط شامل یه سری Api
بعد کاربر چطوری برگرده از درگاه اگر ریدایرکت نشه به کلاینت؟

**Comment by Sina-Soltani** [comment]
> 
> ورژن هایی که نصب کردم مشکل دارن؟
>
> 

ورژن ها مشکلی ندارن و به روز هستن.

فقط مثالی که زدید رو همونطور که گفتم قدیمی هست و وجود نداره

>
> متوجه نمیشم چطوری باید ریدایرکت کنم به یه سرویس؟
> پروژه بک اند فقط شامل یه سری Api
> بعد کاربر چطوری برگرده از درگاه اگر ریدایرکت نشه به کلاینت؟

روش کار در برنامه‌های کلاینت متفاوت هست و نباید کاربر به کلاینت هدایت بشه. هر درگاهی اطلاعات مهم و امنیتی ارسال میکنه تا شما سمت سرور اونها رو بررسی کنید.

به روش زیر عمل کنید

آدرس بازگشتی رو آدرسی در سرور میدید نه کلاینت


1. درخواست رو ارسال میکنید و اطلاعات آدرس پرداخت رو دریافت میکنید
2. آدرس پرداخت درگاه رو به کلاینت ارسال میکنید
3. سمت کلاینت یک پنجره جدید باز میکنید برای آدرسی که دریافت کردید تا درگاه پرداخت در اون پنجره نمایش داده بشه
4. کاربر پرداختش رو در اون پنجره انجام میده و بانک اون رو به آدرس سرور شما که در مرحله اول دادید هدایت میکنه
5. در اونجا متدهای مربوط به تایید پرداخت رو استفاده میکنید

پس از انجام کارها و بررسی هاتون، پاسخی که برمیگردونید باید یک صفحه شامل جاوا اسکریپت باشه که دو تا کار رو انجام میده
یک متد در پنجره والد رو صدا میزنه جهت اطلاع از اتمام پرداخت
window.parent.yourmethod();
و پنجره رو میبندید
window.close()

روشهای مختلف دیگه ای هم هست. باید ببینید کدوم برای شما سازگار هست
مشابه این تیکت قبلا هم بوده
[نمونه](https://github.com/Sina-Soltani/Parbad/issues/54#issuecomment-565010043)

**Comment by amin-pi** [comment]
ممنون از راهنماییتون
عذر میخوام سوال هام زیاد شد
فقط اینکه راهکاری برای چک کردن غیر از این روشی که فرمودید، یعنی ریدایرک وجود داره توی پرباد؟
منظورم حالتی هست که فرض کنید بعد از پرداخت به هر دلیلی ریدایرکت رخ نده. مثلا به خاطر بستن مرورگر یا قطع شدن اینترنت یا هر اتفاق دیگه ای
اما پرداخت انجام شده
و در واقع این وریفای باید به روش دیگه ای هم امکان پذیر باشه . مثلا از طریق همون کد پیگیری

**Comment by Sina-Soltani** [comment]
برای بعضی از درگاه ها امکان پذیره و برای بعضی خیر
علتش هم اینه که یک سری از درگاه‌ها، اطلاعات خاصی رو فقط لحظه هدایت کاربر به وب سایت به شما میدن
در نتیجه نمیشه بعدا در جای دیگه ای اون رو دنبال کرد

برای اون دسته از درگاه‌هایی که امکان پذیر هست، کافیه فقط 
Verify
رو صدا بزنید و شماره پیگیری رو بهش بدید

البته برای زرین پال شدنی هست. در آپدیت جدیدی که به زودی منتشر میشه، این امکان افزوده میشه

و در نهایت نصیحتی که به شما در رابطه با سیستم های مالی میتونم بکنم اینه که هر عملیات پرداخت رو به صورت یک پرونده‌ای ببینید که برای لحظه ای باز میشه و بعد برای همیشه بسته میشه
یعنی اینکه زمانیکه یک عملیات پرداخت به هر دلیلی ناموفق بوده، دیگه بسته شده و نباید ادامش داد.

باید رکورد پرداخت جدیدی برای فاکتور مورد نظر ایجاد کنید و پرداخت جدیدی رو راه اندازی کنید،‌نه اینکه پرداخت قدیمی رو ادامه بدید.
