### ISSUE TITLE
مستندات بانک سامان

### ISSUE THREAD

**Issue by amirreza58** [Sina-Soltani/Parbad#139]
سلام
در مستندات جدید بانک سامان استفاده از توکن اجباری شده است 
در وب سرویس متد زیر اضافه شده است

`RequestToken `

در صورت امکان بررسی بفرمایید

**Comment by Sina-Soltani** [comment]
درود

یعنی سرویس دیگه کار نمیکنه؟ یا اینکه صرفا امکان جدیده؟
امکانش هست مستندات رو اینجا آپلود کنید؟

**Comment by amirreza58** [comment]
بله هنگام پرداخت وقتی در فرم توکن ارسال نشود درگاه پیام توکن میدهد
ظاهرا در مستندات از قبل  موجود بوده ولی استفاده ازش اجباری شده

در آدرس وب سرویس هم متد دریافت توکن موجود است
[https://sep.shaparak.ir/payments/referencepayment.asmx](url)

**Comment by amirreza58** [comment]
[saman-doc.zip](https://github.com/Sina-Soltani/Parbad/files/5559693/saman-doc.zip)

**Comment by Sina-Soltani** [comment]
بله مثل اینکه عوض شده
تغییرات لازم به زودی اعمال میشه

ممنون برای اطلاع رسانی

**Comment by amirreza58** [comment]
سپاس
