### ISSUE TITLE
به روز بودن آموزش

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#140]
آیا همه آموزش هاتون با نخسخه آخر مطابقت دارد

**Comment by Sina-Soltani** [comment]
درود

بله

**Comment by mmo1383** [comment]
بعضی متد ها که در آموزش ویدئویی هست کار نمی کند در حالی که من مو به مو اجرا کردم
و  بسته ها و یوزینگ ها رو انجام دادم
به غیر خود پرباد ها بسته دبگری می خواهد

**Comment by Sina-Soltani** [comment]
آموزش‌ها و نمونه‌ها رو فقط از طریق گیت‌هاب دنبال کنید چون کاملا به روز هستن
[آموزش](https://github.com/Sina-Soltani/Parbad/wiki)

ویدئو‌ها قدیمی هستن و مسلما نمیشه به ازای هر ویژگی یا تغییری، یک ویدئو تولید کرد

**Comment by mmo1383** [comment]
دو تا سوال دیگه 
سورس سمپل بروز هست ؟
اگر بروز هست من عینا سورس پروژه شما رو تو یک پروژه  خالی پیاده کنم
لطف کنید بفرمایید همه چیز هایی که باید تغییر دهم تا به درگاه بانک ملت وصل شود

متشکر

**Comment by Sina-Soltani** [comment]
بله سمپل‌ها هم کاملا به روز هستن

**Comment by mmo1383** [comment]
می شود لطف کنید بفرمایید 
چه چیز هایی رو باید تغییر دهم تا به درگاه اصلی بانک ملت وصل شود

**Comment by Sina-Soltani** [comment]
منظورتون از تغییر چی هست؟ نیازی به تغییر جایی نیست
نوگت ها رو نصب کنید و طبق آموزش‌ها پیش برید و در قسمت تنظیم درگاه‌ها، بانک ملت رو تنظیم کنید

**Comment by mmo1383** [comment]
یعنی فقط ترمینال آی دی و یوزر پس رو تغییر بدهم درست است

**Comment by Sina-Soltani** [comment]
بله

1. [نوگت پرباد رو نصب کنید](https://github.com/Sina-Soltani/Parbad/wiki/Installation)
2. [با توجه به نوع پروژه، نوگت مخصوص پروژه رو نصب کنید](https://github.com/Sina-Soltani/Parbad/wiki/Installation#web-integration)
3. [پایگاه داده مورد نظر برای ذخیره و بازیابی اطلاعات پرداخت رو راه اندازی کنید](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#storage)
4. [اطلاعات بانک ملت رو وارد کنید](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-an-account)
5. [هنگام ارسال درخواست پرداخت، بانک ملت رو انتخاب کنید](https://github.com/Sina-Soltani/Parbad/wiki/Payment#requesting-a-payment)
6. [تایید پرداخت، هنگام بازگشت خریدار به وب سایت](https://github.com/Sina-Soltani/Parbad/wiki/Payment#verifying-a-payment)

**Comment by mmo1383** [comment]
یعنی مدل هایی که در سمپل زدید ویو مدل نیست باید در کانتکست ادد شوند؟

**Comment by Sina-Soltani** [comment]
اگر منظورتون از مدل‌ها
[اینها](https://github.com/Sina-Soltani/Parbad/tree/master/samples/Parbad.Sample.AspNetCore/Models)
هست، که خب دیگه مطابق میل و سلیقه خودتون هست میتونید هر چی دلتون میخواد درست کنید
اینها فقط ساده ترین حالت مدل برای معرفی نمونه مثال ها هست

**Comment by mmo1383** [comment]
در core    
net cli
 ها که نباید ادد بشود فقط ناگت کافی است؟

**Comment by Sina-Soltani** [comment]
مایکروسافت در دات نت، دو روش برای نصب نوگت ها معرفی کرده

Install-Package
برای تقریبا همه پروژه‌ها

و

dotnet add package........
برای پروژه‌های دات نت کر

شما همون روش اول رو استفاده کنید

**Comment by mmo1383** [comment]
راهی هست سنپل را کامل دانلود کنید

**Comment by Sina-Soltani** [comment]
از این وب سایت استفاده کنید و آدرس پوشه مورد نظر رو داخلش وارد کنید. روی دانلود کلیک کنید
[Website](https://minhaskamal.github.io/DownGit/#/home)
