### ISSUE TITLE
ارور

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#141]
اطلاعات كاربري پذيرنده نامعتبر است

این ارور چیست؟

**Comment by Sina-Soltani** [comment]
دیگه گویا‌تر از این پیام چی میتونه باشه؟
اطلاعات درگاه بانکی که در بخش تنظیمات وارد کردید، نزد بانک معتبر نیست

**Comment by mmo1383** [comment]
ممکن است مربوط به 
ip 
سرور باشد

**Comment by mmo1383** [comment]
ببخشید با سوال هایم اذیتتون کردم
ممنون از پاسخ هاتون

**Comment by Sina-Soltani** [comment]
> 
> 
> ممکن است مربوط به
> ip
> سرور باشد

بله احتمالش هست


> 
> 
> ببخشید با سوال هایم اذیتتون کردم
> ممنون از پاسخ هاتون

خواهش میکنم

**Comment by mmo1383** [comment]
به بانک وصل شد مشتکر
