### ISSUE TITLE
Dapper Storage

### ISSUE THREAD

**Issue by alipour-pwd** [Sina-Soltani/Parbad#142]
سلام ، برای استفاده از Dapper در storage اقدامی انجام ندادید ؟
اگر نیست لطفا بفرمایید بهترین پیاده سازی چیست؟

**Comment by Sina-Soltani** [comment]
درود

خیر پیاده‌سازی نشده

> 
> 
> اگر نیست لطفا بفرمایید بهترین پیاده سازی چیست؟

پیاده‌سازی  یک استوریج
[Custom Storage](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-a-custom-storage)
