### ISSUE TITLE
عدد TrackingNumber تکراری است

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#143]
TrackingNumber 
روی حالت خودکار گزاشتم ولی بانک می گوید تکراری است 
منظور از غیر تکراری بودن غیر تکراری در دیتا بیس من است یا بانک
چه کار کنم که ارور رفع شود
البته دستی که یک عدد طولانی وارد می کنم جواب میدهد

**Comment by mmo1383** [comment]
```
 var verifyUrl = Url.Action("Verify", "Payment", null, Request.Scheme);

            var result = await _onlinePayment.RequestAsync(invoice =>
            {
                invoice
                    .SetAmount(SumOrdersANDDelivery)
                    .SetCallbackUrl(verifyUrl)
                    .SetGateway("Mellat");
                invoice.UseAutoIncrementTrackingNumber();
            });
```

**Comment by Sina-Soltani** [comment]
اون پیام از سمت بانک هست
تنظیمات پرباد رو کپی کنید اینجا لطفا تا بررسی کنیم
(بدون ذکر اطلاعات حساس)

**Comment by mmo1383** [comment]
var verifyUrl = Url.Action("Verify", "Payment", null, Request.Scheme);

            var result = await _onlinePayment.RequestAsync(invoice =>
            {
                invoice
                    .SetAmount(SumOrdersANDDelivery)
                    .SetCallbackUrl(verifyUrl)
                    .SetGateway("Mellat");
                invoice.UseAutoIncrementTrackingNumber();
            });

**Comment by mmo1383** [comment]
همین رو دستی وارد میکنم جواب می دهد
ولی یک عدد طولانی و شانسی است شاید یک بار جواب ندهد

**Comment by Sina-Soltani** [comment]
اینهایی که گذاشتین کد عملیات پرداخت هست

لطفا تنظیمات رو کپی کنید
یعنی
AddParbad()
.Configure....()
.Configure...()
.Configue...()

**Comment by mmo1383** [comment]
**` services.AddParbad()
           .ConfigureGateways(gateways =>
           {
               gateways
                   .AddMellat()
                   .WithAccounts(accounts =>
                   {
                       accounts.AddInMemory(account =>
                       {
                           account.TerminalId = my;
                           account.UserName = "Rise my";
                           account.UserPassword = "my";
                       });
                   });

               gateways
                   .AddParbadVirtual()
                   .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
           })
           .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
           .ConfigureStorage(builder => builder.UseMemoryCache());
        }`**

**Comment by mmo1383** [comment]
```
 services.AddParbad()
           .ConfigureGateways(gateways =>
           {
               gateways
                   .AddMellat()
                   .WithAccounts(accounts =>
                   {
                       accounts.AddInMemory(account =>
                       {
                           account.TerminalId = my;
                           account.UserName = "Rise my";
                           account.UserPassword = "my";
                       });
                   });

               gateways
                   .AddParbadVirtual()
                   .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
           })
           .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
           .ConfigureStorage(builder => builder.UseMemoryCache());
        }``
```

**Comment by mmo1383** [comment]
درست شد
سوال اگر کد های سایت را پاک کنم و دوباره با تصحیح آپلود کنم 
مگر تولید کد را از ادامه قبل نمی رود 
در قبل دو بار تست کردم و بعد کد ها را پاک کردم
الان چند بار زدم و همین خطا را دریافت کردم 
بعد به عدد1004 که رسید دیگر خطا نداشت
متشکر

**Comment by Sina-Soltani** [comment]
شما تنظیم منبع ذخیره و بازیابی رو از نوع مموری انتخاب کردید
در توضیحاتش نوشته شده که این منبع برای تست استفاده میشه نه برای محصول نهایی.
علتش هم اینه که هر بار که سرور یا وب سایت از نو راه اندازی بشه، اطلاعات این منبع پاک میشه
در نتیجه شماره پیگیری دوباره از اول شروع به تولید میشه و به همین علت بانک به شما میگه کد تکراری هست
شما باید از یک منبع داده پایدار مانند
SQL Server
یا
Sqlite
استفاده کنید
[Entity Framework Core](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-entityframework-core)
[منبع سفارشی - ذخیره و بازیابی توسط روش شما](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-a-custom-storage)
