### ISSUE TITLE
The AddAdditionalData method does not work.

### ISSUE THREAD

**Issue by DiniMad** [Sina-Soltani/Parbad#144]
**Bug description (wIthout specifying the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**
I am trying to set some additional data alongside the invoice request, and it seems that the `AddAdditionalData` method does not work (neither overloads).
And by "does not work" I mean the `AdditionalData` property of the invoice request and verified invoice is empty.
 This is how I create an invoice requiest:
`
          var requestResult = await _onlinePayment.RequestAsync(invoice =>
            {
                invoice
                    .SetAmount((long) 123)
                    .SetCallbackUrl(verifyUrl)
                    .SetGateway("ParbadVirtual")
                    .UseAutoIncrementTrackingNumber()
                    .AddAdditionalData("purchaseType", "1");
            });
`
And this is the DI configuration:
`
            services.AddParbad()
                    .ConfigureGateways(builder =>
                    {
                        builder.AddParbadVirtual()
                               .WithOptions(options => options.GatewayPath =
                                                           "/MyVirtualGateway");
                    })
                    .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
                    .ConfigureStorage(builder =>
                    {
                        builder.UseEfCore(options =>
                        {
                            var assemblyName = typeof(Startup).Assembly.GetName().Name;
                            options.ConfigureDbContext =
                                db => db.UseSqlServer(connectionString,
                                                      sql => sql.MigrationsAssembly(assemblyName));
                        });
                    });
`

**Package name and version**
**نام و نسخه پکیج**
Parbad.AspNetCore 1.0.6
Parbad.Storage.EntityFrameworkCore 1.1.0

**Web application type:**
**نوع برنامه وب**
ASP.NET 5

**Comment by Sina-Soltani** [comment]
Hi,

the AdditionalData is not like some data that you want to send to the gateways. It's for building and customizing the invoices.

**Comment by SARM256** [comment]
how could we get the value of additional value in Verify action?

**Comment by Sina-Soltani** [comment]
As I already explained in this ticket, The AdditionalData is not about Banks additional data.

**Comment by SARM256** [comment]
can you please tell some it's usage?

**Comment by Sina-Soltani** [comment]
https://github.com/Sina-Soltani/Parbad/issues/144#issuecomment-734289490
