### ISSUE TITLE
امکان برگشت وجه پرداخت شده

### ISSUE THREAD

**Issue by keyone2693** [Sina-Soltani/Parbad#146]
فرض کنیم که کاربر وجه رو پرداخت کرده و حالا در هنگام وریفای متوجه میشیم محصول موجود نیست
باید برگشت بزنیم به حسابش
لطف میکنید بگید کدوم بانک های این حالت برگشت وجه رو پشتیبانی میکنن؟

**Comment by Sina-Soltani** [comment]
درگاه‌های زیر امکان بازگشت وجه رو دارن

- ملت
- پارسیان
- پاسارگاد
- سامان
- سپهر الکترونیک

سوالی که برای شما باید پیش بیاد اینه که چرا باید یک پرداخت رو وریفای کنین،‌ وقتی که خودتون میدونین که محصول موجود نیست؟؟

**Comment by keyone2693** [comment]
این اتمام موجودی یه مثال بود

تو پروژه مورد نظر کاربر یک بسته ای رو میخره که چندین بلیط قطار و پرواز همزمان خریداری میشن 
و ممکنه هرکدومشون خطایی بدن یا ناموجود بشن 
و اگر ما بیایم همه بلیطارو بخریم بعد تازه بیایم وریفای بکنیم
و متوجه بشیم اصلا پرداخت موفق نبوده 
کلی بلیط رو دستمون مونده که تازه شامل جریمه هم میشن استرادشون
پس در نتیجه باید وریفای بکنه تا متوجه بشه خرید موفق بوده کامل

در مورد بانک ملت من قبلا یادمه پرسیده بودم گفتید بازگشت وجه رو ساپورت نمیکنه جدید اضافه شده ؟

**Comment by Sina-Soltani** [comment]
بانک ملت همیشه برگشت وجه رو داشته.

**Comment by keyone2693** [comment]
ممنون
انتقال وجه چطور یعنی به کارت کاربران؟

**Comment by Sina-Soltani** [comment]
متد
RefundCompletely
شماره پیگیری مورد نظر رو میگیره و درخواست بازگشت وجه رو ارسال میکنه به طور خودکار به بانکی که توش پرداخت صورت گرفته.
بانک، مبلغ پرداخت شده برای اون صورت حساب رو برمی گردونه به کارتی که کاربر باهاش پرداخت کرده بوده.
مدت زمان انجام این کار توسط درگاه های مختلف متفاوت هست.
بین پونزده دقیقه تا یک روز.

**Comment by keyone2693** [comment]
نه منظورم اینه
متدی هست 
 که مبلغی رو از کیف پول طرف واریز کنه به کارت کاربر
