### ISSUE TITLE
بانک ارور Tracking number میدهد

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#147]
گفتید باید در دیتا بیس ذخیره بشود ولی من می خواهم به همان مدل پیش فرض ذخیره 
از istorge 
اگر ارث بری کند کلی متد هست مه باید ایملپلنت کنم
چگونه در دیتا بیس ذخیره کنم ولی به همان مدل پیش فرض
؟

**Comment by Sina-Soltani** [comment]
لطفا از یک نفر که تجربه بیشتری در زمینه برنامه نویسی داره درخواست کنید تا بهتون کمک کنه.
اینها چیزهای پایه و ابتدایی هستن که اینجا محل یادگیریشون نیست

**Comment by mmo1383** [comment]
برای ارث بری باید مثل 
identity 
TStorge 
را داشته باشد 
حالا این 
هیچی 
من نمی خواهم تیبل ها را شخصی سازی کنم 
فقط می خواهم اطلاعات در دیتا بیس ذخیره شود تا اگر کد نویسی را عوض کردم 
ترکینگ نامبر از اول شروع نشود 
و بانک ارور ندهد

روشی که در آموزش دیدم با زدن مایگریشن
خودش یک مایگریشن جدید درست می کنند
و کد های fluent api 
می نویسد 
من می خواهم در همان مایگریشن خودم این کار را انجام دهد
