### ISSUE TITLE
بانک داده

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#149]
برای ارث بری باید مثل
identity
TStorge
را داشته باشد
حالا این
هیچی
من نمی خواهم تیبل ها را شخصی سازی کنم
فقط می خواهم اطلاعات در دیتا بیس ذخیره شود تا اگر کد نویسی را عوض کردم
ترکینگ نامبر از اول شروع نشود
و بانک ارور ندهد

روشی که در آموزش دیدم با زدن مایگریشن
خودش یک مایگریشن جدید درست می کنند
و کد های fluent api
می نویسد
من می خواهم در همان مایگریشن خودم این کار را انجام دهد

**Comment by Sina-Soltani** [comment]
من متوجه منظور شما نمیتونم بشم.

در آموزش‌های موجود، راه حل صفر تا صد کاملا راحت و ساده توضیح داده شده.
[EntityFramework Core](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-entityframework-core)

**Comment by mmo1383** [comment]
گفتید برای اینکه ترکینگ نامبر تکراری نوشد
باید اطلاعات در دیتا بیس ذخیره شود خوب می خواهم با 
DBContext
خودم 
به دیتا بیس متصل شود
روشی که  لینک دادید برای شخصی سازی دیتابیس پرداخت بود 
من می خواهم همان جداول شما 
در دیتابیس ذخیره شود و من دست نزم
فقط نه در مایگریشن جدا در همان مایگریشن خودم

**Comment by mmo1383** [comment]
چرا جواب نمی دهید

**Comment by Sina-Soltani** [comment]
همانطور که گفتم، تمام چیزی که نیاز دارید در این راهنما به صورت کامل توضیح داده شده
اگر راهنما کمکی نمیتونه بهتون بکنه، پس احتمالا کار مورد نظر شما انجام شدنی نیست.
[راهنما](https://github.com/Sina-Soltani/Parbad/wiki)
لطفا از یک نفر که در زمینه انتیتی فریم ورک تجربه بیشتری داره بپرسید تا راهنماییتون کنه
