### ISSUE TITLE
IParbadOptionsProvider موجود نیست

### ISSUE THREAD

**Issue by MohsenEs** [Sina-Soltani/Parbad#150]
سلام
برای انجام تنظیمات اتوماتیک این اینرفیس موجود نیست

**Comment by MohsenEs** [comment]
مثالی از تنطیمات اتوماتیک دارید ؟

**Comment by Sina-Soltani** [comment]
درود
لطفا راهنما رو مطالعه کنید

**Comment by MohsenEs** [comment]
ممنون 
من داکیمنت .net tips رو خونده بودم
ولی اینی که اینجا هست فرق داره

ولی یه مشکل دارم 
IMySettingsService از کجا باید بگیرم
ممنون میشم راهنمایی کنید

**Comment by Sina-Soltani** [comment]
IMySettingsService 
یک مثاله. چنین چیزی وجود نداره

IMySettingsService 
IYourSettingsService 
ISomeService
