### ISSUE TITLE
Http error 500

### ISSUE THREAD

**Issue by MohsenEs** [Sina-Soltani/Parbad#156]
سلام 
پرداخت با موفقیت انحام میشه 
ولی به متد varify نمیرسه
فکر میکنید مشکل از کجاست

**Comment by Sina-Soltani** [comment]
درود

اطلاعی ندارم
این یک مشکل داخلی هست و به پَرباد ارتباطی نداره

try catch
بزارید و یا لاگ کنید تا ببینید خطا چی هست

**Comment by MohsenEs** [comment]
An unhandled exception was thrown by the application. System.InvalidOperationException: The view 'Verify' was not found. The following locations were searched:
/Views/Payment/Verify.desktop.cshtml
/Views/Payment/Verify.cshtml
/Views/Shared/Verify.desktop.cshtml
/Views/Shared/Verify.cshtml
/Pages/Shared/Verify.desktop.cshtml
/Pages/Shared/Verify.cshtml


ارور این هست view رو پیدا نمیکنه
البته زمانی که خطا میده هم همین ارور میده
ولی توی لوکال زمانی که ارور میداد مشکلی نداشت
فکر میکنید مشکل از کجا باشه

**Comment by Sina-Soltani** [comment]
همونطور که گفتم این خطا مشکل داخلی در برنامه شما هست.
خطا داره میگه که هیچ ویو تحت عنوان
Verify
در برنامه شما پیدا نمیکنه
کدها رو کپی کنید اینجا شاید بتونم کمکتون کنم

**Comment by MohsenEs** [comment]
`   public class PaymentController : Controller
    {
        private readonly IOnlinePayment _onlinePayment;
        private readonly IOrderService _orderService;
        private readonly IMenuService _menuService;
        private readonly ICollectionService _collectionService;
        private readonly ILogger<PaymentController> _logger;

        public PaymentController(IOnlinePayment onlinePayment, IOrderService orderService, IMenuService menuService, ICollectionService collectionService, ILogger<PaymentController> logger)
        {
            _onlinePayment = onlinePayment;
            _orderService = orderService;
            _menuService = menuService;
            _collectionService = collectionService;
            _logger = logger;
            _logger.LogDebug(1, "NLog injected into PaymentController");
        }

        public IActionResult PayOrder(int orderId)
        {
            var order = _orderService.GetOrderById(orderId);
            if (order.PaymentMethod == null)
            {
                return Json(false);
            }

            if (order.PaymentMethod == PayMethodEnum.PayOnTheSpot)
            {
                order.IsSuccessfulPay = true;
                _orderService.UpdateOrder(order);
                return RedirectToAction("Tankyou",new {id=order.Menus.CollectionId});
            }

            if (order.PaymentMethod == PayMethodEnum.ParsianPay)
            {
                PayViewModel payViewModel=new PayViewModel()
                {
                    Amount = 1000,
                    SelectedGateway = GatewaysEnum.Parsian
                  
                };
                return RedirectToAction("Pay", payViewModel);
            }

            return Json("Ok");
        }

      
        public async Task<IActionResult> Pay(PayViewModel viewModel)
        {
            var verifyUrl = Url.Action("Verify", "Payment", null, Request.Scheme);

            var result = await _onlinePayment.RequestAsync(invoice =>
            {
                invoice
                    .SetAmount(viewModel.Amount)
                    .SetCallbackUrl(verifyUrl)
                    .SetGateway(viewModel.SelectedGateway.ToString());
            });

            // Save the result.TrackingNumber in your database.

            if (result.IsSucceed)
            {
                return result.GatewayTransporter.TransportToGateway();
            }

            return RedirectToAction("PayRequestError", result);
        }

        public IActionResult PayRequestError(PaymentRequestResult result)
        {
            return PartialView(result);
        }

        // It's better to set no HttpMethods(HttpGet, HttpPost, etc.) for the Verify action,
        // because the banks send their information with different HTTP methods
        [HttpPost]
        public async Task<IActionResult> Verify()
        {
            _logger.LogInformation("PaymentVerifyIs");

            var invoice = await _onlinePayment.FetchAsync();
            _logger.LogInformation(invoice.Message);

            // Check if the invoice is new or it's already processed before.
            if (invoice.Status == PaymentFetchResultStatus.AlreadyProcessed)
            {
                // You can also see if the invoice is already verified before.
                var isAlreadyVerified = invoice.IsAlreadyVerified;
                return Content("The payment is already processed before.");
            }

            // This is an example of cancelling an invoice when you think that the payment process must be stopped.
            if (!Is_There_Still_Product_In_Shop(invoice.TrackingNumber))
            {
                var cancelResult = await _onlinePayment.CancelAsync(invoice, cancellationReason: "Sorry, We have no more products to sell.");

                return View("CancelResult", cancelResult);
            }

            var verifyResult = await _onlinePayment.VerifyAsync(invoice);

            return View(verifyResult);
        }

        [HttpGet]
        public IActionResult Refund()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Refund(RefundViewModel viewModel)
        {
            var result = await _onlinePayment.RefundCompletelyAsync(viewModel.TrackingNumber);

            // Note: This is just for development and testing.
            // Don't show the actual result object to clients in production environment.
            // Instead, show only the important information such as IsSucceed, Tracking Number and Transaction Code.
            return View("RefundResult", result);
        }

        private static bool Is_There_Still_Product_In_Shop(long trackingNumber)
        {
            // Yes, we still have products :)

            return true;
        }

        public IActionResult Tankyou(int id)
        {
            var collecton = _collectionService.GetCollectionsById(id);
            var menuSetting = _menuService.GetFirstMenuSettingByCollectionId(id);
            SettingMenuViewModel model = Newtonsoft.Json.JsonConvert.DeserializeObject<SettingMenuViewModel>(menuSetting);


            ViewData["CollectionId"] = id;
            ViewData["CollectionName"] = collecton.CollectionName;
            ViewData["CollectionCode"] = collecton.CollectionCode;
            ViewData["css"] = model.MenuCss;
            ViewData["IsRtl"] = model.IsRtl;
            ViewData["IsUiRounded"] = model.IsUiRounded;
            ViewData["css"] = model.MenuCss;
            ViewData["IsHeaderFill"] = model.IsHeaderFill;

            return View();

        }

    }`
