### ISSUE TITLE
شماره موبایل

### ISSUE THREAD

**Issue by pineportal** [Sina-Soltani/Parbad#159]
درگاه های مختلف مثلا بانک ملت، تاپ، سپهر و .... امکان این را دارند که شماره موبایل را با پرامتر ها به سمت درگاه ارسال کنید.. و در خرید های بعدی اطلاعات کارت برای کاربر ذخیره می شود

**Comment by shaahink** [comment]
Hi @Sina-Soltani 
We are also after this feature. I appreciate this is open source and you progress it when you wish, and it is also difficult to expect a delivery date. 
I wonder if there is any chance so you can provide a clue how to implement this at least for Mellat Bank, so I can try and fork it. If it went all well I am happy to help with implementing this in Parbad too. 
Any hint will be greatly appreciated.

**Comment by Sina-Soltani** [comment]
@shaahink 

درود
چون این تیکت به فارسی نوشته شده من هم به فارسی جواب میدم

آیا درگاه ملت شماره موبایل رو جدیدا اضافه کرده؟
چون طبق آخرین مستنداتی که من از این درگاه دارم، چیزی به نام شماره موبایل در مستندات این درگاه وجود نداره
فقط یک فیلد
AdditionalData
از نوع رشته دارن

شاید هم منظور شما اینه قابلیتی باشه که شماره موبایل رو در همین فیلد بنویسید و درخواست رو بفرستید؟

**Comment by pineportal** [comment]
در تصویر زیر مشخص می باشد.
![image](https://user-images.githubusercontent.com/31403448/106520235-b4e90c80-64f1-11eb-85d9-e56b44ec9e59.png)

**Comment by pineportal** [comment]
آخرین نسخه مستندات بانک ملت که من دارم
[mellat_pgw_tech doc_ver 1.15_fa.pdf](https://github.com/Sina-Soltani/Parbad/files/5906889/mellat_pgw_tech.doc_ver.1.15_fa.pdf)

**Comment by pineportal** [comment]
درخواست ثبت شماره موبایل برای درگاه تاپ 
![image](https://user-images.githubusercontent.com/31403448/111294933-10b1c400-8660-11eb-89c3-72cf6a197fd3.png)


آخرین مستندات

[10010101-sw1.pdf](https://github.com/Sina-Soltani/Parbad/files/6148103/10010101-sw1.pdf)
