### ISSUE TITLE
بازگرداندن مبلغ به چندین حساب

### ISSUE THREAD

**Issue by MohammadReza10** [Sina-Soltani/Parbad#16]
گاها نیاز پیدا میشه مبلغ به چند حساب برگشت داده بشه
به عنوان مثال دکتر 20 نفر انلاین ویزیت کرده بعد کنسل شده و میخواد به 20 نفر پولشون رو برگردونه
منشی که نمیتونه بشینه کارت به کارت بزنه دونه به دونه
البته شنیده بودم که فقط بانک ملی شماره کارت ها رو به صورت ارایه میگیره و هزینه رو میگیره و انجامش میده ولی فک کنم بقیه بانک ها هم داشته باشن همچین چیزی
اگه بشه تو پکیج اضافه بشه خیلی عالی میشه

**Comment by Sina-Soltani** [comment]
متوجه مشکل شما نشدم من دقیقا

اگر قرار هست که کارت به کارت کنن پس برای چی اصلا از این ابزار استفاده میخوان بکنن؟؟
هر تراکنشی رو که قصد بازگشتش رو دارن، خب به راحتی برگشت بزنن با کمک این ابزار.
حالا میخواد بیست تا باشه یا هزار تا

زمانیکه مشتری پرداخت آنلاین انجام میده،‌ به معنای اینه که یک تراکنش انجام شده. و اون تراکنش امکان بازگشت رو داره توسط صاحب وب سایت

پس زمانیکه بیست نفر آنلاین پرداخت میکنن و شما تصمیم میگیرید که باید پول ها همه برگشت داده بشه، خب خیلی راحت به ازای هر تراکنش، یکبار دستور برگشت پول رو استفاده کنید

**Comment by MohammadReza10** [comment]
خب تو درگاه اینترنتی همچین امکانی وجود نداره
منظورم این نیست که موقع پرداخت کنسل شه خب این که سادس
فرض کنیم مثلا بعد یه مدتی بخوام از طریق وبسایت همچین کدی بنویسم که شماره کارت رو بدم بعدش مبلغ بعدشم انتقال انجام شه 
منظورم تو سایت خودم اینو انجام بدم
الان من قصد دارم پول 50 نفر رو برگردونم
تو پکیج شما با کدوم کد این امکان وجود داره ؟
دستور برگشت پول کدومه
همه بانک ها طوری که من شنیدم ندارن

**Comment by Sina-Soltani** [comment]
1
برگشت پول به حساب مشتری فقط تا بیست و چهار ساعت پس از پرداخت امکان پذیر هست

2
در سیستم درگاه پرداخت آنلاین امکانی به اسم واریز به شماره کارت وجود نداره. بازگشت یک مبلغ فقط توسط اطلاعات تراکنش مانند کد رهگیری و شماره تراکنش بانکی که انجام شده امکان پذیر هست. این اطلاعات پس از هر پرداخت دریافت میشه که باید در بانک اطلاعاتی وب سایت فروشنده ذخیره شده باشه برای فاکتور مورد نظر

3
من اطلاع ندارم که شما با برنامه نویسی آشنا هستید یا خیر. اما دستوری وجود داره به نام دستور
For
بنابراین اگر که ما برای مثال قصد داشته باشیم پنجاه تراکنش رو بازگشت بزنیم به این صورت میتونیم عمل کنیم

var data;

For(int i = 0; i < data.Count; i++)
{
   var trackingNumber = data[i].TrackingNumber;

    _onlinePayment.RefundInvoiceCompletely(trackingNumber);
}

**Comment by MohammadReza10** [comment]
جواب به 2
چرا وجود داره بانک ملی ی همچین چیزی داشت بالا هم نوشته بودم که 
txt 
دریافت میکرد ک شامل شماره کارت بود
و.لی هر چقدر تو کد های چند سال قبل میگردم ادرس وب سرویسش رو پیدا نمیکنم
تو ویزیت انلاین بیمارستان 24 خیلی کمه ب دردی نمیخوره
بازم تشکر

**Comment by Sina-Soltani** [comment]
خواهش میکنم
