### ISSUE TITLE
درگاه پرداخت فن آوا کارت

### ISSUE THREAD

**Issue by pineportal** [Sina-Soltani/Parbad#160]
**Is your feature request related to a problem? Please describe.**
**آیا ویژگی درخواستی شما مربوط به مشکل خاصی است؟**

**Describe the feature you'd like**
**ویژگی مورد نظر را توضیح دهید**

داکیومنت درگاه فن آوا کارت
[TokenBase-Rest-99-06 (1).pdf](https://github.com/Sina-Soltani/Parbad/files/5696843/TokenBase-Rest-99-06.1.pdf)

**Comment by mmokhtari** [comment]
i'd like to implement this feature

**Comment by Sina-Soltani** [comment]
درود

ممنون برای درخواست توسعه

شما میتونید توسعه رو انجام بدید و
Pull Request
ارسال کنید

لطفا قبل از شروع حتما راهنمای مشارکت رو مطالعه کنید تا اگر سوالی داشتید و یا ابهامی وجود داره، برطرف بشه
[راهنمای مشارکت](https://github.com/Sina-Soltani/Parbad/blob/master/CONTRIBUTING.md)

همچنین میتونید سایر درگاه ها رو نگاهی بندازید تا با روال کارشون آشنا بشید.
تقریبا تمام درگاه ها یک روال رو تکرار میکنن
[نمونه درگاه ها](https://github.com/Sina-Soltani/Parbad/tree/master/src/Parbad.Gateway)

موفق باشید
