### ISSUE TITLE
پرداخت صحیح

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#161]
در 
asp.net core
در کدام اکشن بفهمیم 
که پرداخت صحیح انجام شده 
و با کدام 
if

**Comment by Sina-Soltani** [comment]
[ASP.NET CORE Sample](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.AspNetCore/Controllers/PaymentController.cs#L57)

**Comment by mmo1383** [comment]
if (!Is_There_Still_Product_In_Shop(invoice.TrackingNumber))
برای لغو و بازگشت وجه 
است
if (invoice.Status == PaymentFetchResultStatus.AlreadyProcessed) 
برای تکراری بودن پرداخت است



اگر 
verifyResult 
این درست بود یعنی پرداخت شده ؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟؟

**Comment by Sina-Soltani** [comment]
کدهای لازم قبل از تایید و اتمام عملیات پرداخت

```c#
var invoice = await _onlinePayment.FetchAsync();

            // Check if the invoice is new or it's already processed before.
            if (invoice.Status == PaymentFetchResultStatus.AlreadyProcessed)
            {
                // You can also see if the invoice is already verified before.
                var isAlreadyVerified = invoice.IsAlreadyVerified;
                return Content("The payment is already processed before.");
            }

            // This is an example of cancelling an invoice when you think that the payment process must be stopped.
            if (!Is_There_Still_Product_In_Shop(invoice.TrackingNumber))
            {
                var cancelResult = await _onlinePayment.CancelAsync(invoice, cancellationReason: "Sorry, We have no more products to sell.");

                return View("CancelResult", cancelResult);
            }
```

` PaymentFetchResultStatus.AlreadyProcessed`
یعنی پرداخت قبلا مورد بررسی قرار گرفته بوده

`Is_There_Still_Product_In_Shop()`
صرفا فقط یک مثال هست

`_onlinePayment.Cancel`
عملیات رو لغو میکنه

```c#
var verifyResult = await _onlinePayment.VerifyAsync(invoice);
```
کد تایید پرداخت و اعلام به بانک جهت واریز نهایی پول

**Comment by mmo1383** [comment]
با کدوم متد همون واریز نهایی هم انجام شده

**Comment by Sina-Soltani** [comment]
> 
> 
> با کدوم متد همون واریز نهایی هم انجام شده

فکر کنم به وضوح نوشتم این رو نه؟
