### ISSUE TITLE
تست

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#166]
برای تست درگاه پرداخت که نیاز نباشد روی هاست اصلی تست کنیم 
آیتمی دارید 
که به صورت لوکال هاست روی کامپیوتر خود درگاه رو تست کنیم و جواب تایید یا انصراف پرداخت دهد 
برای بانک ملت 

بانک ملت یک وب سرویس برای کالای ایرانی دارد آن را هم دارید

**Comment by Sina-Soltani** [comment]
> 
> 
> برای تست درگاه پرداخت که نیاز نباشد روی هاست اصلی تست کنیم
> آیتمی دارید
> که به صورت لوکال هاست روی کامپیوتر خود درگاه رو تست کنیم و جواب تایید یا انصراف پرداخت دهد
> برای بانک ملت
> 

۱. بانک ملت در هنگام عقد قرارداد به مشتریان یک درگاه تست هم میده. درگاه تست رو در قسمت [تنظیمات این بانک](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.AspNetCore/Startup.cs#L36) فعال کنید تا درخواست ها به این درگاه هدایت بشه
۲. از [درگاه مجازی](https://github.com/Sina-Soltani/Parbad/wiki/Virtual-Gateway) استفاده کنید

> 
> بانک ملت یک وب سرویس برای کالای ایرانی دارد آن را هم دارید

خیر
