### ISSUE TITLE
متد توکن بانک سامان

### ISSUE THREAD

**Issue by emdadgar2** [Sina-Soltani/Parbad#167]
سلام
بانک  سامان جدیدا متد توکن را اجباری کرده و این پیام را فرستاده است:

-------
پذیرنده گرامی

به اطلاع می رساند مطابق با الزامات شرکت شاپرک، تمامی تراکنش های اینترنتی می بایست با استفاده از متد توکن انجام گردد ، لذا خواهشمند است حداکثر تا 1399/11/01 اقدامات مقتضی در خصوص پیاده سازی درگاه پرداخت اینترنتی به روش توکنی مطابق با مستند ذیل را اعمال نمایید .

برای مشاهده و دریافت راهنمای درگاه پرداخت اینترنتی (از طریق توکن) از این لینک استفاده نمایید.

https://www.sep.ir/Data/Sites/1/media/epay/1.SEP-PPG-Purchase%20With%20Mobile%20Number-TechnicalSpecification%20-%20Token%20Payment.pdf

------

الان از چه متدی استفاده می شود؟
ممنون از پروژه خوبتان

**Comment by Sina-Soltani** [comment]
درود
از چه ورژنی استفاده میکنید؟

**Comment by emdadgar2** [comment]
از آخرین نسخه nuget استفاده می کنم
موضوع را مطرح کردم که ببینم مشکلی برخورد نکنیم و متوجه بشم بانک برای همه این ایمیل را فرستاده یا کمی هوشمند عمل کرده!

در هر صورت ممنونم

**Comment by Sina-Soltani** [comment]
روش جدید توکن در آخرین نسخه موجود هست.

احتمال داره اون پیام رو برای همه ارسال کرده باشن
موفق باشید.
