### ISSUE TITLE
UseSqlServer پیدا نمیشود

### ISSUE THREAD

**Issue by SARM256** [Sina-Soltani/Parbad#168]
سلام 
برای استفاده از sql server بعنوان دیتابیس پرباد از متد UseEfCore استفاده میکنم ولی رفرنس مربوط به تابع UseSqlServer رو پیدا نمیکنه

**Comment by Sina-Soltani** [comment]
درود
به خاطر اینکه نصبش نکردید
[https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/](https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/)

[آموزش کار با EFCORE](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)

**Comment by arm-00** [comment]
نصب شده و رفرنس هم داده شده

> درود
> به خاطر اینکه نصبش نکردید
> https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.SqlServer/
> 
> [آموزش کار با EFCORE](https://docs.microsoft.com/en-us/ef/core/get-started/overview/first-app?tabs=netcore-cli)

**Comment by arm-00** [comment]
نمونه این بلاک کد رو میشه تو mvc بگید؟
.ConfigureStorage(builder => {
                builder.UseEfCore(options =>
                {
                    // Using SQL Server
                    var assemblyName = typeof(Startup).Assembly.GetName().Name;
                    options.ConfigureDbContext = db => db.UseSqlServer("Your Connection String", sql => sql.MigrationsAssembly(assemblyName));

                    // If you prefer to have a separate MigrationHistory table for Parbad, you can change the above line to this:
                    options.ConfigureDbContext = db => db.UseSqlServer("Your Connection String", sql =>
                    {
                        sql.MigrationsAssembly(assemblyName);
                        sql.MigrationsHistoryTable("TABLE NAME");
                    });

                    options.DefaultSchema = "SCHEMA NAME"; // optional

                    options.PaymentTableOptions.Name = "TABLE NAME"; // optional
                    options.PaymentTableOptions.Schema = "SCHEMA NAME"; // optional

                    options.TransactionTableOptions.Name = "TABLE NAME"; // optional
                    options.TransactionTableOptions.Schema = "SCHEMA NAME"; // optional
                });
            })

**Comment by Sina-Soltani** [comment]
متوجه نمیشم
چه ارتباطی با 
mvc 
داره؟

**Comment by arm-00** [comment]
چون پروژه .net core نیست بهمین خاطر useSqlServer رو نمیشناسه و حتی اگر نوگت هم نصب کنم با مشکل رفع نمیشه

**Comment by Sina-Soltani** [comment]
مواردی که گفتین هیچگونه ارتباطی با هم ندارن

EFCORE
یک پروژه کاملا مجزا از
.NETCORE
هست

لطفا از کسی که تجربه بیشتری در زمینه کار بار
EFCORE
داره کمک بگیرید یا توی گوگل آموزش ها رو پیدا کنید

**Comment by SARM256** [comment]
ممنون
