### ISSUE TITLE
پیاده سازی DI با ninject 

### ISSUE THREAD

**Issue by SARM256** [Sina-Soltani/Parbad#169]
نمونه کد برای پیاده سازی DI داخل ninject بجای Autofac موجود هست؟

**Comment by Sina-Soltani** [comment]
Ninject
یک کتابخانه قدیمی هست که توسعه اون ادامه داده نشد و من دیگه اطلاعی ازش ندارم

باید به دنبال آموزشی بگردین که
ninject
رو با تزریق وابستگی مایکروسافت، مرتبط بکنه

مانند 
Autofac
که با نصب نوگت
https://www.nuget.org/packages/Autofac.Extensions.DependencyInjection/
و این [تنظیم](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Startup.cs#L36) به راحتی سازگار میشه

**Comment by SARM256** [comment]
ممنون
