### ISSUE TITLE
تنظیمات پایگاه داده

### ISSUE THREAD

**Issue by MohammadReza10** [Sina-Soltani/Parbad#17]
با سلام
میشه راهنمایی کنید در اپدیت جدید چرا مثل نسخه قدیمی فیلد های جداول رو تو اموزش نذاشتید
چون نیاز دارم یه جدول براش ایجاد کنم تا ordernumber 
رو کلید خارجی کنم
الان مسئله برام گنگ هستش
در ضمن در نسخه جدید فقط برای donet core
گذاشتید
services.AddParbad()
        .ConfigureStorage(builder => builder.UseParbadSqlServer("ConnectionString"));
خبری از dotnet framework 
نیستش

**Comment by Sina-Soltani** [comment]
آیا مقاله آ«وزش رو مطالعه کردید؟

[آموزش](https://www.dotnettips.info/post/3009/%d9%be%d8%b1%d8%a8%d8%a7%d8%af-%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d9%be%db%8c%d8%a7%d8%af%d9%87%e2%80%8c%d8%b3%d8%a7%d8%b2%db%8c-%d9%be%d8%b1%d8%af%d8%a7%d8%ae%d8%aa-%d8%a2%d9%86%d9%84%d8%a7%db%8c%d9%86-%d8%af%d8%b1-%d8%af%d8%a7%d8%aa-%d9%86%d8%aa-%d9%85%d9%82%d8%af%d9%85%d9%87)

**Comment by MohammadReza10** [comment]
بله هزار بار خوندم
منتها نسخه قبلی بهتر بود
این نسخه رو نصب میکنم کدش رو طبق اموزش میزنم ایراد میده به متد سازنده
ای کاش اموزش به صورت فیلم بود
اموزش متنی پراکنده هستش

**Comment by Sina-Soltani** [comment]
کد کلاس مورد نظر که میگید به خطا بر میخوره رو اینجا کپی کنید تا بررسی کنم براتون

نمونه پروژه های مختلف هم وجود دارند که می‌تونید استفاده کنید و ببینید که بدون هیچگونه مشکلی کار میکنن.
[Sample](https://github.com/Sina-Soltani/Parbad/raw/master/samples/Parbad%20Samples.zip)
