### ISSUE TITLE
 migration برای اتصال به دیتابیس

### ISSUE THREAD

**Issue by SARM256** [Sina-Soltani/Parbad#172]
سلام
وقتی از دستور dotnet ef migrations add Migration1 -c ParbadDataContext --project option برای migration استفاده میکنم ارور زیر رو نمایش میده:
error MSB4006: There is a circular dependency in the target dependency graph involving target "GetEFProjectMetadata"
پروژه mvc 5 هستش

**Comment by Sina-Soltani** [comment]
درود

این مشکلات هیچگونه ارتباطی با این ابزار ندارند
همونطور که گفتم لطفا از یک نفر که در این زمینه تجربه داره کمک بگیرید

اینجا صرفا فقط سوال های مربوط به خود ابزار باید پرسیده بشه

خطا هم به وضوح داره به شما میگه که در ساختار پروژه شما یک
circular dependency
وجود داره

یعنی اینکه دو یا چند پروژه در داخل سلوشن شما، به همدیگه پیوند داده شدند و به هم وابسته شدن
وابستگی فقط باید یک طرفه باشه نه دو طرفه
