### ISSUE TITLE
اضافه کردن نمونه کد 

### ISSUE THREAD

**Issue by SARM256** [Sina-Soltani/Parbad#173]
سلام 
اگر امکانش هست لطفا یک نمونه کد برای پیاده سازی sql server به پروژه اضافه کنید.
چون از دستور dotnet ef migrations add Migration1 -c ParbadDataContext که استفاده میکنم ارور زیر رو میده :
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.

**Comment by Sina-Soltani** [comment]
درود

خطایی که شما گذاشتین ارتباطی با نمونه کد نداره
داره به شما میگه دستوری که وارد کردین رو نمیتونه شناسایی کنه
به خاطر اینکه شما اصلا موارد مورد نیاز برای کار با 
efcore
رو روی سیستم خودتون نصب نکردید و این اهمیتی نداره که چه پروژه ای باشه

[EFCORE CLI](https://docs.microsoft.com/en-us/ef/core/cli/dotnet)
رو باید روی سیستم خودتون نصب کنید

لطفا اینگونه مشکلات رو توی فروم های برنامه نویسی مطرح کنید تا بهتون راهنمایی کنن
Stackoverflow.com
dotnettips.info
barnamenevis.org

**Comment by SARM256** [comment]
حتی بعد از نصب هم همچنان خطا وجود داره البته از سیستم پرباد نیست قاعدتا ولی ممنون میشم آموزشی در این خصوص بزارید
با تشکر

**Comment by Sina-Soltani** [comment]
`Windows + R`
رو بزنید و
`cmd`
رو وارد کنید تا
Command Prompt
باز بشه

دستور زیر رو وارد کنید و بگید چه چیزی نمایش میده
`dotnet-ef --version`

**Comment by SARM256** [comment]
خروجی ای که نمایش داد این بود : 
Entity Framework Core .NET Command-line Tools
5.0.1

> `Windows + R`
> رو بزنید و
> `cmd`
> رو وارد کنید تا
> Command Prompt
> باز بشه
> 
> دستور زیر رو وارد کنید و بگید چه چیزی نمایش میده
> `dotnet-ef --version`

**Comment by Sina-Soltani** [comment]
Command Prompt
رو با دستور
`CD`
هدایت کنید به داخل پوشه پروژه و  جایی که قصد دارید مایگریشین ها اضافه بشن.

سپس دستور زیر رو وارد کنید
`dotnet-ef migrations add Migration1 -c ParbadDataContext`

**Comment by SARM256** [comment]
> Command Prompt
> رو با دستور
> `CD`
> هدایت کنید به داخل پوشه پروژه و جایی که قصد دارید مایگریشین ها اضافه بشن.
> 
> سپس دستور زیر رو وارد کنید
> `dotnet-ef migrations add Migration1 -c ParbadDataContext`
> 
> نتیجه رو بنویسید اینجا
بابت کمکتون خیلی ممنونم و خروجی این بود : 
error MSB4019: The imported project "C:\Program Files\dotnet\sdk\5.0.101\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "C:\Program Files\dotnet\sdk\5.0.101\Microsoft\VisualStudio\v16.0\WebApplications\Microsoft.WebApplication.targets" is correct, and that the file exists on disk.
Unable to retrieve project metadata. Ensure it's an SDK-style project. If you're using a custom BaseIntermediateOutputPath or MSBuildProjectExtensionsPath values, Use the --msbuildprojectextensionspath option.

**Comment by Sina-Soltani** [comment]
در داخل ویژوال استودیو در پنجره
Solution Explorer
روی گزینه
Collapse
در بالای پنجره کلیک کنید تا همه جزئیات مرتب بشن.
سپس یک اسکرین شات از پنجره بگیرید و اینجا داخل کامنت آپلودش کنید

**Comment by SARM256** [comment]
![Capture](https://user-images.githubusercontent.com/59338359/103439943-c28f4600-4c56-11eb-8842-36c02c608fa7.PNG)

**Comment by Sina-Soltani** [comment]
در ابتدا مثال مربوط به پروژه های قدیمی
[MVC](https://github.com/Sina-Soltani/Parbad/tree/master/samples/Parbad.Sample.Mvc)
رو نگاه کنید و مقایسه کنید با پروژه خودتون و مانند مثال تنظیمش کنید. به خصوص بخش مربوط به کلاس
[Startup.cs](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Startup.cs)

همچنین در تنظیمات پَرباد، تنظیمات پایگاه داده رو هم مانند زیر باید تنظیم کرده باشید
[EFCORE Storage](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-entityframework-core)

سپس
Package Manager Console 
رو باز کنید
از طریق
Tools -> Nuget Package Manger -> Package Manager Console

نوگت های زیر رو نصب کنید. موقع نصب، ورژنی رو انتخاب کنید که همین الان در پروژه موجود هست.
برای مثال اگر
EFCORE v3.1.0
نصب هست، موقع نصب نوگت های زیر، همون ورژن رو انتخاب کنید که چیز اضافی ای نصب نشه

`Install-Package Microsoft.EntityFrameworkCore.Tools -Version 3.1.0`
`Install-Package Microsoft.EntityFrameworkCore.Design -Version 3.1.0`

کلاس زیر رو در پروژه در هر کجا که مناسب میدونید اضافه کنید
```c#
public class MyDesignTimeFactory : IDesignTimeDbContextFactory<ParbadDataContext>
    {
        public ParbadDataContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ParbadDataContext>();
            optionsBuilder.UseSqlServer("CONNECTION STRING",
                contextOptionsBuilder =>
                {
                    contextOptionsBuilder.MigrationsAssembly(typeof(Startup).Assembly.GetName().Name);
                });

            var options = new EntityFrameworkCoreOptions();
            var optionsWrapper = new OptionsWrapper<EntityFrameworkCoreOptions>(options);
            return new ParbadDataContext(optionsBuilder.Options, optionsWrapper);
        }
    }
```

رشته اتصال به پایگاه داده رو در کد بالا تنظیم کنید

سپس در
Package Manager Console 
دستور زیر رو وارد کنید
`Add-Migration Migration1 -c ParbadDataContext`

الان باید فایل های مایگرشن به پروژه شما اضافه شده باشه

در ادامه دستور زیر رو وارد کنید تا مایگرشن هایی که اضافه شده بودن، بر روی پایگاه داده اعمال بشه
`Update-Database -c ParbadDataContext

اگر همه چیز درست انجام شده باشه، الان باید در پایگاه داده، جداول مربوط به ابزار رو ببینید
Payment
Transaction

**Comment by SARM256** [comment]
بالاخره دیتابیس ساخته شد و بابت کمک ها و توضیحات کاملتون خیلی ممنونم.
کارهایی که باید انجام میشد رو در ادامه مینویسم:

برای اجرا شدن دستورات پکیج های زیر باید نصب میشدند
Microsoft.EntityFrameworkCore
Install-Package Microsoft.EntityFrameworkCore.Tools
Install-Package Microsoft.EntityFrameworkCore.Design

کد زیر باید به برنامه اضافه بشه :

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.Extensions.Options;
using Parbad.Storage.EntityFrameworkCore.Context;
using Parbad.Storage.EntityFrameworkCore.Options;
```csharp
public class MyDesignTimeFactory : IDesignTimeDbContextFactory<ParbadDataContext>
    {
        public ParbadDataContext CreateDbContext(string[] args)
        {
            var optionsBuilder = new DbContextOptionsBuilder<ParbadDataContext>();
            optionsBuilder.UseSqlServer("CONNECTION STRING",
                contextOptionsBuilder =>
                {
                    contextOptionsBuilder.MigrationsAssembly(typeof(Startup).Assembly.GetName().Name);
                });

            var options = new EntityFrameworkCoreOptions();
            var optionsWrapper = new OptionsWrapper<EntityFrameworkCoreOptions>(options);
            return new ParbadDataContext(optionsBuilder.Options, optionsWrapper);
        }
    }
```
⚠ باید رشته اتصال جایگزین شود

برای ساخت فایل مایگرشن دستور زیر باید اجرا بشه :

Add-Migration Migration1 -c ParbadDataContext

و در نهایت برای اعمال در دیتابیس باید کد زیر را اجرا کرد :

Update-Database -c ParbadDataContext

⚠ ممکنه بعد از اجرای دستور بالا با ارور زیر مواجه بشید
Format of the initialization string does not conform to specification starting at index 41.
که برای رفع این ارور شخصا رشته اتصال رو از 
"Data Source=.;Initial Catalog=ParbadDb;Integrated Security:True"
به 
"Server=.;Database=ParbadDb;Trusted_Connection=True;"
تغییر دادم.

**Comment by SARM256** [comment]
یک موردی که هست اینه که داخل لایه های دیگه از برنامه وقتی کد رو بارم ارور No DbContext named 'ParbadDataContext' was found.
رو نمایش میده و اگر داخل پروژه وب بزارم درست میشه اما مشکلی که بعدش بوجود میاد اینه که ارور زیر رو نمایش میده
Value cannot be null. Parameter name: httpContext

**Comment by Sina-Soltani** [comment]
در قسمت تنظیمات پَرباد کد زیر رو پیدا کنید و به این صورت تغییرش بدید
```c#
contextOptionsBuilder.MigrationsAssembly("WebApplication8.Data");
```
همین کار رو در کلاس
`MyDesignFactory`
هم انجام بدید

کلاس
MyDesignFactory
باید در پروژه اصلی باقی بمونه و نباید به پروژه مورد نظر منتقل بشه چون در این صورت پیغام زیر رو دریافت میکنید
`No DbContext named 'ParbadDataContext' was found.`

البته اگه تلاش کنید راهش رو پیدا میکنید که این کلاس هم به پروژه دیتا منتقل بشه


رشته نام اسمبلی که در این متد نوشته شده رو به نام پروژه ای که میخواین مایگرشن ها اونجا باشن تغییر بدید
برای مثال اگر نام پروژه شما
`ASPNETTest.Data`
هست باید به این شکل تغییر پیده کنه
```c#
contextOptionsBuilder.MigrationsAssembly("ASPNETTest.Data");
```

در پنجره
Package Manager Console
ابتدا از منوی
Default Project
نام پروژه مورد نظر رو انتخاب کنید سپس دستور زیر رو وارد کنید
`Add-Migration Migration1 -c ParbadDataContext`

**Comment by SARM256** [comment]
برای این بخش هم راه حلی هست؟
چون وقتی از کد
```csharp
            .ConfigureStorage(builder =>
            {
                builder.UseEfCore(options =>
                {
                    //var assemblyName = typeof(Startup).Assembly.GetName().Name;
                    options.ConfigureDbContext = db => db.UseSqlServer("Data Source=.;Initial Catalog=***;Integrated Security=True; MultipleActiveResultSets=True;MultipleActiveResultSets=True", sql =>
                    {
                        sql.MigrationsAssembly("NamavaTech.Data");
                        sql.MigrationsHistoryTable("ParbadMigrationHistory");
                    });

                    options.DefaultSchema = "dbo"; // optional

                    options.PaymentTableOptions.Name = "ParbadPayment"; // optional

                    options.TransactionTableOptions.Name = "ParbadTransaction"; // optional
                });
            })
```
استفاده کنم ارور httpContext میده
> اما مشکلی که بعدش بوجود میاد اینه که ارور زیر رو نمایش میده
> Value cannot be null. Parameter name: httpContext
> البته متد رکوئست هم await نوشته شده

**Comment by Sina-Soltani** [comment]
کد تنظیمات پَرباد رو کپی کنید اینجا

**Comment by SARM256** [comment]
کد تنظیمات : 
```csharp
            var parbad = ParbadBuilder.CreateDefaultBuilder()
            .ConfigureGateways(getways =>
            {
                getways.AddParbadVirtual()
                    .WithOptions(option => { option.GatewayPath = "/virtualPath"; });
            })
            .ConfigureHttpContext(conf => conf.UseOwinFromCurrentHttpContext())
            //.ConfigureStorage(conf => conf.UseMemoryCache())
            .ConfigureStorage(builder =>
            {
                builder.UseEfCore(options =>
                {
                    //var assemblyName = typeof(Startup).Assembly.GetName().Name;
                    options.ConfigureDbContext = db => db.UseSqlServer("Data Source=.;Initial Catalog=***;Integrated Security=True; MultipleActiveResultSets=True;MultipleActiveResultSets=True", sql =>
                    {
                        sql.MigrationsAssembly("AspNetTest.Data");
                        sql.MigrationsHistoryTable("ParbadMigrationHistory");
                    });

                    options.DefaultSchema = "dbo"; // optional

                    options.PaymentTableOptions.Name = "ParbadPayment"; // optional

                    options.TransactionTableOptions.Name = "ParbadTransaction"; // optional
                });
            })
            .Build();

            app.UseParbadVirtualGateway(parbad.Services);
```

**Comment by Sina-Soltani** [comment]
چه زمانی این خطا دریافت میشه؟
StackTrace
رو اینجا کپی کنید

**Comment by SARM256** [comment]
وقتی متد زیر فراخونی میشه وارد صفحه پرداخت نمیشه و تو حالت لود میمونه : 
```csharp
            var verifyUrl = Url.Action("Verify", "Payment", null, Request.Url.Scheme);

            var result = StaticOnlinePayment.Instance.Request(invoice =>
            {
                invoice.SetAmount(52000);
                invoice.SetCallbackUrl(verifyUrl);
                invoice.UseParbadVirtual();
                invoice.UseAutoRandomTrackingNumber();
            });            
```

**Comment by Sina-Soltani** [comment]
چرا از
StaticOnlinePayment
استفاده میکنید؟
مگه در پروژتون تزریق وابستگی وجود نداره؟

**Comment by SARM256** [comment]
از ninject استفاده شده و رو جایگزین پیدا نکردم ...
ممکنه مشکل از اون بخش باشه؟

**Comment by Sina-Soltani** [comment]
بله

**Comment by SARM256** [comment]
ولی وقتی اکشن کنترلر رو async مینویسم ارور httpContent value is null میده و وقتی اینطور نباشه کلا لود نمیشه

**Comment by SARM256** [comment]
و اینکه میشه بگید اگر بخوام DI انجام بدم چه کلاسی رو برای IOnlinePayment پاس بدم؟
```csharp
kernel.Bind(typeof(IOnlinePayment)).To(typeof(???));
```
جای سه تا علامت سوال چه کلاسی باید گذاشته بشه؟

**Comment by Sina-Soltani** [comment]
```c#
var parbad = ParbadBuilder.CreateDefaultBuilder()
.Confiure()...
...
...
.Build();

var onlinePayment = parbad.OnlinePayment;
```

در کد بالا داخل متغیر
onlinePayment
یک وحله از چیزی که شما نیاز دارید تا به اون اینترفیس نسبت بدید، وجود داره
من نمیدونم و به یاد ندارم که در
ninject
 چه شکلی باید نسبت بدید. ولی یه چیزی شبیه به کد زیر باید باشه
```c#
var parbad = ParbadBuilder.CreateDefaultBuilder()
.Confiure()...
...
...
.Build();

kernel.Bind(typeof(IOnlinePayment)).To(parbad.OnlinePayment);
```

**Comment by SARM256** [comment]
بله کد دقیقا همینه ولی این مورد یا 
kernel.Bind(typeof(IOnlinePayment)).To(typeof(parbad.OnlinePayment));
کار نکردن

**Comment by Sina-Soltani** [comment]
همونطور که گفتم من به یاد ندارم که
ninject
چه جوری کار میکنه

اینترفیس رو دارید. نحوه گرفتن وحله از اینترفیس رو هم دارید
اون دیگه وظیفه شماست که ببینید چجوری باید به هم نسبتشون بدید در
ninject

کافی بود فقط یه سرچ ساده بکنید توی گوگل تا جوابتون رو پیدا کنید
https://stackoverflow.com/questions/16916140/ninject-registering-an-already-created-instance-with-ninject

**Comment by SARM256** [comment]
بله درسته و با این خط کد درست شد :
```csharp
kernel.Bind(typeof(IOnlinePayment)).ToMethod(context => parbad.OnlinePayment);
```
اما همچنان وقتی متد زیر فراخونی میشه صفحه تو حالت لودینگ میمونه و وارد درگاه نمیشه :
```csharp
var result = _payment.RequestAsync(invoice =>
{
    invoice.SetAmount(52000);
    invoice.SetCallbackUrl(verifyUrl);
    invoice.UseParbadVirtual();
    invoice.UseAutoRandomTrackingNumber();
}).Result;            
```

**Comment by Sina-Soltani** [comment]
کدها رو لطفا کامل بزارید اینجا
این فقط قسمت پرداخت هست

[وارد شدن به درگاه پرداخت](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Controllers/PaymentController.cs#L54) مربوط به قسمت بعدی هست که شما نزاشتید

**Comment by SARM256** [comment]
این کد اکشن مربوطه است
```csharp
public ActionResult Test()
{
    var verifyUrl = Url.Action("Verify", "Payment", null, Request.Url.Scheme);

    var result = _payment.Request(invoice =>
    {
        invoice.SetAmount(52000);
        invoice.SetCallbackUrl(verifyUrl);
        invoice.UseParbadVirtual();
        invoice.UseAutoRandomTrackingNumber();
    });            

    if (result.IsSucceed)
        return result.GatewayTransporter.TransportToGateway();
    else
        return View();
}
```
اما متد Reuest  اجرا نمیشه که بخواد result رو پر کنه و ادامه کد ها اجرا بشن و تو حالت لودینگ میمونه

**Comment by Sina-Soltani** [comment]
متاسفم.
من اطلاعی ندارم و کمکی از دستم بر نمیاد
اینها مشکلات داخلی برنامه شما هستن و به ابزار مربوط نیستن
نمونه پروژه
[MVC](https://github.com/Sina-Soltani/Parbad/tree/master/samples/Parbad.Sample.Mvc)
موجود هست و به راحتی کار میکنه

**Comment by SARM256** [comment]
خیلی ممنونم

**Comment by Sina-Soltani** [comment]
خواهش میکنم

**Comment by SARM256** [comment]
سلام مجدد 
اینترفیس IStorage رو پیاده سازی کردم و مجدد با همین مشکل رو به رو شدم و بعد از trace کردن متوجه شدم که متد ها  task برمیگردونن به همین خاطر قبل از اجرا شدن یک متد متد بعدی اجرا میشه و همین باعث خطا میشه چون میگه یا از await استفاده کن یا اجازه بده که

**Comment by SARM256** [comment]
سلام مجدد 
اینترفیس IStorage رو پیاده سازی کردم و مجدد با همین مشکل رو به رو شدم و بعد از trace کردن متوجه شدم که متد ها task برمیگردونن به همین خاطر قبل از اجرا شدن یک متد متد بعدی اجرا میشه و همین باعث خطا میشه چون میگه از await استفاده کن.
ممنون میشم راهنمایی کنید...

```csharp
    public class MyStorage : IStorage
    {
        private MyContext _db;
        public MyStorage()
        {
            _db = new MyContext();
        }

        public IQueryable<Payment> Payments => _db.Payment;

        public IQueryable<Transaction> Transactions => _db.Transaction;

        public Task CreatePaymentAsync(Payment payment, CancellationToken cancellationToken = default)
        {
            return Task.Run(() =>
            {
                _db.Payment.Add(payment);
                _db.SaveChangesAsync();
            });
        }

        public Task CreateTransactionAsync(Transaction transaction, CancellationToken cancellationToken = default)
        {
            return Task.Run(() =>
            {
                _db.Transaction.Add(transaction);
                _db.SaveChangesAsync();
            });
        }

        public Task DeletePaymentAsync(Payment payment, CancellationToken cancellationToken = default)
        {
            return Task.Run(() =>
            {
                _db.Payment.Remove(payment);
                _db.SaveChangesAsync();
            });
        }

        public Task DeleteTransactionAsync(Transaction transaction, CancellationToken cancellationToken = default)
        {
            return Task.Run(() =>
            {
                _db.Transaction.Remove(transaction);
                _db.SaveChangesAsync();
            });
        }

        public Task UpdatePaymentAsync(Payment payment, CancellationToken cancellationToken = default)
        {
            return Task.Run(() =>
            {
                var currentPayment = _db.Payment.Find(payment.Id);
                currentPayment.Amount = payment.Amount;
                currentPayment.GatewayAccountName = payment.GatewayAccountName;
                currentPayment.GatewayName = payment.GatewayName;
                currentPayment.IsCompleted = payment.IsCompleted;
                currentPayment.IsPaid = payment.IsPaid;
                currentPayment.Token = payment.Token;
                currentPayment.TrackingNumber = payment.TrackingNumber;
                currentPayment.TransactionCode = payment.TransactionCode;

                _db.Entry(currentPayment).State = EntityState.Modified;

                _db.SaveChangesAsync();
            });
        }

        public Task UpdateTransactionAsync(Transaction transaction, CancellationToken cancellationToken = default)
        {
            return Task.Run(() =>
            {
                var currentTransaction = _db.Transaction.Find(transaction.Id);
                currentTransaction.Amount = transaction.Amount;
                currentTransaction.AdditionalData = transaction.AdditionalData;
                currentTransaction.IsSucceed = transaction.IsSucceed;
                currentTransaction.Message = transaction.Message;
                currentTransaction.PaymentId = transaction.PaymentId;
                currentTransaction.Type = transaction.Type;

                _db.Entry(currentTransaction).State = EntityState.Modified;

                _db.SaveChangesAsync();
            });
        }
    }
```

**Comment by Sina-Soltani** [comment]
```c#
public class MyStorage : IStorage
    {
        private MyContext _db;

        public MyStorage()
        {
            _db = new MyContext();
        }

        public IQueryable<Payment> Payments => _db.Payment.AsNonTracking();

        public IQueryable<Transaction> Transactions => _db.Transaction.AsNonTracking();

        public Task CreatePaymentAsync(Payment payment, CancellationToken cancellationToken = default)
        {
                _db.Payment.Add(payment);
                return _db.SaveChangesAsync();
        }

        public Task CreateTransactionAsync(Transaction transaction, CancellationToken cancellationToken = default)
        {
                _db.Transaction.Add(transaction);
                return _db.SaveChangesAsync();
        }

        public Task DeletePaymentAsync(Payment payment, CancellationToken cancellationToken = default)
        {
                _db.Payment.Remove(payment);
                return _db.SaveChangesAsync();
        }

        public Task DeleteTransactionAsync(Transaction transaction, CancellationToken cancellationToken = default)
        {
                _db.Transaction.Remove(transaction);
                return _db.SaveChangesAsync();
        }

        public Task UpdatePaymentAsync(Payment payment, CancellationToken cancellationToken = default)
        {
                var currentPayment = _db.Payment.Find(payment.Id);
                currentPayment.Amount = payment.Amount;
                currentPayment.GatewayAccountName = payment.GatewayAccountName;
                currentPayment.GatewayName = payment.GatewayName;
                currentPayment.IsCompleted = payment.IsCompleted;
                currentPayment.IsPaid = payment.IsPaid;
                currentPayment.Token = payment.Token;
                currentPayment.TrackingNumber = payment.TrackingNumber;
                currentPayment.TransactionCode = payment.TransactionCode;

                _db.Entry(currentPayment).State = EntityState.Modified;

                return _db.SaveChangesAsync();
        }

        public Task UpdateTransactionAsync(Transaction transaction, CancellationToken cancellationToken = default)
        {
                var currentTransaction = _db.Transaction.Find(transaction.Id);
                currentTransaction.Amount = transaction.Amount;
                currentTransaction.AdditionalData = transaction.AdditionalData;
                currentTransaction.IsSucceed = transaction.IsSucceed;
                currentTransaction.Message = transaction.Message;
                currentTransaction.PaymentId = transaction.PaymentId;
                currentTransaction.Type = transaction.Type;

                _db.Entry(currentTransaction).State = EntityState.Modified;

                return _db.SaveChangesAsync();
        }
    }
```

موقع کار با کلاس
IOnlinePayment
از
await
استفاده کنید

https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Controllers/PaymentController.cs
RequestAsync
FetchAsync
VerifyAsync
CancelAsync

متد یا اکشن کنترلری که داخلش دارید متدهای بالا رو صدا میزنید باید کلمه
async
رو داشته باشن
[PaymentController](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Controllers/PaymentController.cs#L24)

**Comment by SARM256** [comment]
کاملا درست شد خیلی ممنونم
