### ISSUE TITLE
Auto Setting

### ISSUE THREAD

**Issue by MohsenEs** [Sina-Soltani/Parbad#174]
سلام
میخوام تنطیمات هر درگاه داینامیک باشه 
چطور میتونم این کارو انجام بدم
داکیومنت و خوندم نتونستم انجام بدم 
براتون مقدوره یه  پرژه ایجاد کنید که این مورد باشه داخلش

ممنون

**Comment by Sina-Soltani** [comment]
درود

> 
> براتون مقدوره یه پرژه ایجاد کنید که این مورد باشه داخلش

متاسفانه خیر

[مستندات](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-the-accounts-dynamically-using-a-custom-source) کاملا شفاف و با جزئیات توضیح داده
اگر طبق اون رفته باشید،هیچ مشکلی وجود نداره

**Comment by MohsenEs** [comment]
public class GatewaysSource : 
   IGatewayAccountSource<MellatGatewayAccount>,
   IGatewayAccountSource<ParsianGatewayAccount>,
   IGatewayAccountSource<SamanGatewayAccount>
{
    private readonly IYourSettingsService _settingsService;

    public GatewaysSource(IYourSettingsService settingsService)
    {
        _settingsService = settingsService;
    }

    public async Task AddAccountsAsync(IGatewayAccountCollection<MellatGatewayAccount> accounts)
    {
        var settings = await _settingsService.GetSettingsAsync();

        accounts.Add(new MellatGatewayAccount
        {
           TerminalId = settings.TerminalId,
           UserName = settings.UserName,
           UserPassword = settings.UserPassword
        });
    }

    public async Task AddAccountsAsync(IGatewayAccountCollection<ParsianGatewayAccount> accounts)
    {
        var settings = await _settingsService.GetSettingsAsync();

        accounts.Add(new ParsianGatewayAccount
        {
           LoginAccount = settings.LoginAccount
        });
    }

    public async Task AddAccountsAsync(IGatewayAccountCollection<SamanGatewayAccount> accounts)
    {
        var settings = await _settingsService.GetSettingsAsync();

        accounts.Add(new SamanGatewayAccount
        {
           MerchantId = settings.MerchantId,
           Password = settings.Password
        });
    }
}

**Comment by MohsenEs** [comment]
این در واقع من برای یه سیستم چند شعبه ای استفاده میکنم و بر اساس سفارش باید id درگاه عوض شه 
کلاس بالا بازم استاتیک میشه چطور میتونم یه پارامتر بفرستم که بر اساس اون 
کد رو از دیتابیس بگیره

**Comment by Sina-Soltani** [comment]
متوجه منظور شما نشدم

**Comment by MohsenEs** [comment]
چطور میتونم یه پارامتر بفرستم برای کلاس بالاو با توجه به اون پارامتر اطلاعات از دیتابیس واکشی کنم؟

**Comment by Sina-Soltani** [comment]
پارامتر رو نمیشه به سازنده کلاس داد؟

**Comment by MohsenEs** [comment]
نه من بر اساس اون پارامتر اطلاعات بانک و میخوام 
کلاس بالا فقط میتونم از دیتابیس بگیرم
اطلاعات بانک بر اساس سفارش تغییر میکنه

**Comment by Sina-Soltani** [comment]
خیر این ویژگی وجود نداره
احتمال داره در نسخه های بعدی اضافه بشه

**Comment by MohsenEs** [comment]
این خیلی واجبه برام فکر میکنید چقدر طول بکشه 
اگه بخواید اضافه کنید؟

**Comment by Sina-Soltani** [comment]
اینها چیزی نیست که فکر کنید امشب نوشته میشه و فردا یا هفته بعدش میاد بیرون.
تمام ویژگی ها و درخواست ها یادداشت میشه و همگی با هم در یک نسخه ارائه میشه
[نمونه](https://github.com/Sina-Soltani/Parbad/releases/tag/V3.6.0)

چون نمیشه در ازای هر درخواست یک نسخه بیرون داد
تنها در صورتی یک نسخه سریع منتشر میشه که مربوط به باگ باشه

**Comment by MohsenEs** [comment]
باشه ممنون بابت زحماتتون به امید خدا 
روز به روز بهتر بشه
پس من توی نسخه بعدی هر موقع بود منتظر این امکان هستم

**Comment by Sina-Soltani** [comment]
خواهش میکنم

**Comment by MohsenEs** [comment]
سلام وقت بخیر توی نسخه های جدید درگاه داینامیک هست

**Comment by Sina-Soltani** [comment]
درود
متاسفانه خیر. فرصت نشده هنوز
