### ISSUE TITLE
انصراف از پرداخت 

### ISSUE THREAD

**Issue by SARM256** [Sina-Soltani/Parbad#175]
سلام
چطور میشه متوجه شد که کاربر دکمه انصراف بانک رو زده و پرداخت صورت نگرفته؟

**Comment by Sina-Soltani** [comment]
درود

```c#
var verifyResult = await _onlinePayment.VerifyAsync(invoice);

if(verifyResult.Status == Failed)
{
   // پرداخت نشد
}
```

**Comment by SARM256** [comment]
ممنون از راهنماییتون
فقط اینکه این موضوع رو پرباد از طریق دیتابیس خودش چک میکنه؟

**Comment by Sina-Soltani** [comment]
ابتدا درخواست اعتبار سنجی میشه به صورت زیر
آیا درخواست توسط سیستم ثبت شده؟
آیا قبلا بررسی شده؟

سپس پاسخ  ارسالی از درگاه پرداخت مورد بررسی قرار میگیره

در صورتیکه تمام موارد بالا موفقیت آمیز باشه، پرداخت موفق در نظر گرفته میشه

**Comment by SARM256** [comment]
خیلی ممنون
فقط اینکه اگه بعد از ارسال کاربر به سمت درگاه و با توجه به این نکته که داریم از memorycash استفاده میکنیم سیستم به هر دلیلی ریستارت بشه و کاربر زمانی برگرده سمت سایت که سرور مجدد بالا باشه به مشکل بر میخوریم؟

**Comment by Sina-Soltani** [comment]
مموری کش همونطور که در [توضیحاتش](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-cached-storage) نوشته شده، صرفا برای تست و زمان توسعه باید استفاده بشه و نه در محیط اجرایی یا اصلی
اگر سرور ریستارت بشه، اطلاعات هم از بین میرن

باید از استوریج های پایدار استفاده کرد مانند
SQL Server
و یا اینکه  [پیاده سازی استوریج](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-a-custom-storage) رو خودتون به شیوه مورد نظر انجام بدید
