### ISSUE TITLE
بررسی وضعیت تراکنش قبل از تایید

### ISSUE THREAD

**Issue by masoud86** [Sina-Soltani/Parbad#187]
بعد از برگشت از درگاه بانک و قبل از تایید پرداخت با استفاده از متد
Verify
باید شرایط مجدد چک بشه.
مشکل جایی پیش میاد که کاربر پرداخت رو داخل درگاه کنسل میکنه و تا قبل از استفاده از
Verify
راهی برای متوجه شدن وجود ندارد. یعنی در صورتیکه کاربر پرداخت را کنسل کرده باشد باز هم شرایط باید چک شود و پرداخت کنسل شود در صورتیکه اصلاً پرداختی انجام نشده.
در این شرایط نمایش پیغام مناسب به کاربر امکان پذیر نیست و چک کردن شرایط اجتناب ناپذیر است.

**Comment by Sina-Soltani** [comment]
توسعه داده شده
