### ISSUE TITLE
درگاه بانک ملت: IsTestTerminal عمل نمی کند

### ISSUE THREAD

**Issue by shaahink** [Sina-Soltani/Parbad#188]
سلام، 

می خواستم بدونم برای استفاده از درگاه تست بانک ملت، علاوه بر ست کردن 
IsTestTerminal 
کار دیگه ای هم باید انجام بشه؟

این نحوه ی اضافه کردن پرباد به سیستم هست. 

`      services.AddParbad()
                .ConfigureGateways(gateways =>
                {
                    gateways
                         .AddMellat()
                         .WithAccounts(source =>
                         {
                             source.AddInMemory(account =>
                             {
                                 account.Name = "Mellat";
                                 account.TerminalId = ;
                                 account.UserName = "";
                                 account.UserPassword = "";
                                 account.IsTestTerminal = true;
                             });
                         });

// rest is removed for brevity`

برای درخواست فاکتور برای پرداخت از کدهای نمونه استفاده شده است.

**Comment by Sina-Soltani** [comment]
درود

`عمل نمی کند`
عنوان صحیحی برای شرح مشکل نیست

لطفا توضیح بدید که چه اتفاقی افتاده
آیا خطایی رخ داده؟
آیا پاسخی از بانک دریافت نمیشه؟

**Comment by shaahink** [comment]
منظورم این هست که پرداخت واقعا صورت میگیرد و از حساب صاحب کارت مبلغ کسر
می‌شود.

**Comment by Sina-Soltani** [comment]
ظاهرا این درگاه دیگه سرور تستی نداره و فقط سرور عملیاتی دارن.
اگر براتون مقدور هست از پشتیبانی این بانک، بپرسید که آیا درگاه تستی دارن هنوز یا خیر.

**Comment by shaahink** [comment]
ممنون از پاسخ.
با پشتیبانی تماس گرفتم و گفتند که محیط تستی حدود 4 5 سال هست که غیر فعال
شده.

**Comment by Sina-Soltani** [comment]
جالبه که پنج ساله که اینجا هیچکس درگاه تستی رو امتحان نکرده و یا گزارشی نداده که درگاه تست کار نمیکنه
سپاس برای پیگیری این قضیه
در نسخه بعدی این قابلیت حذف میشه که باعث سردرگمی نشه
