### ISSUE TITLE
تغییرات زرین پال

### ISSUE THREAD

**Issue by Anushiravani** [Sina-Soltani/Parbad#189]
زرین پال یکسری تغییرات داشته که در تلاشم روی نسخه جدید اضافه کنم 
سرویس های wsdl عوض شده
و لیست خطا ها تغییر کرده به نظر تا اینجا که من فهمیدم

**Comment by Sina-Soltani** [comment]
این مورد بسته شد؟ پیگیری نمیشه دیگه؟

**Comment by Anushiravani** [comment]
چرا ولی چون یکم مشغول بودم گفتم تا وقتی روش کار نکردم الکی باز نگه ندارم
