### ISSUE TITLE
استفاده از چندین درگاه بانک

### ISSUE THREAD

**Issue by MR-MAP** [Sina-Soltani/Parbad#19]
سلام دوست عزیز

این پروژه امکان این رو داره که بشه از چندین حساب یک بانک استفاده کنه و در متد مشخص بشه که کدوم حساب هست ؟؟

در داکیومنت دیدم که باید در StartUp اطلاعات بانک رو مشخص کرد .

من میخوام بصورت داینامیک اطلاعات بانک رو در متد  شما وارد کنم نه در کانفیگ برنامه .

**Comment by Sina-Soltani** [comment]
درود.

امکان تنظیم درگاه‌ها به صورت کاملا داینامیک موجود هست.
اما امکان چند حسابی وجود نداره. در نسخه بعدی اضافه میشه

**Comment by MR-MAP** [comment]
ممنون.
میشه یک مثال برای تنظیم اطلاعات درگاه بصورت داینامیک در متد بفرمایید ؟

**Comment by Sina-Soltani** [comment]
[آموزش تنظیم درگاه به صورت داینامیک](https://www.dotnettips.info/post/3012/%d9%be%d8%b1%d8%a8%d8%a7%d8%af-%d8%a2%d9%85%d9%88%d8%b2%d8%b4-%d9%be%db%8c%d8%a7%d8%af%d9%87%e2%80%8c%d8%b3%d8%a7%d8%b2%db%8c-%d9%be%d8%b1%d8%af%d8%a7%d8%ae%d8%aa-%d8%a2%d9%86%d9%84%d8%a7%db%8c%d9%86-%d8%af%d8%b1-%d8%af%d8%a7%d8%aa-%d9%86%d8%aa-%d8%aa%d9%86%d8%b8%db%8c%d9%85%d8%a7%d8%aa)

[نمونه مثال تعریف منبع داینامیک برای بانک ملت](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Services/MellatOptionsProvider.cs)

[استفاده از منبع داینامیک تعریف شده](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/App_Start/ParbadConfig.cs#L18)

**Comment by MR-MAP** [comment]
ممنونم.

**Comment by Sina-Soltani** [comment]
[امکان چند حسابی برای درگاه‌ها افزوده شده.](https://github.com/Sina-Soltani/Parbad/wiki/Configuration/#adding-multiple-accounts)
