### ISSUE TITLE
وابستگی های بسیار زیاد و مستندات کم

### ISSUE THREAD

**Issue by idotnetdev** [Sina-Soltani/Parbad#190]
با سلام و عرض ادب
قبلا از زحمات شما برای کتابخانه ای به این پرکاربرد تشکر میکنم.
فقط دو تا مشکل دارم با این پروژه.
اول اینکه چرا وابستگی های این پروژه خیلی زیاده به خصوص موقعی که توی MVC میخوام ازش استفاده کنم کلی کتابخونه دیگه از .Net Standard نصب میکنه؟
و دوم هم اینکه چرا مستندات و نمونه پروژه ها رو بروز نمی کنید؟
با سپاس

**Comment by Sina-Soltani** [comment]
درود

وابستگی  های این کتابخونه برای
ASP.NET CORE
فقط و فقط کتابخونه
Newtonsoft.Json
هست

و برای
MVC, WebForms
این کتابخونه ها
![image](https://user-images.githubusercontent.com/10329804/110032610-9f594380-7d38-11eb-9111-9ea58e7ff785.png)

دو کتابخونه اول در این تصویر، در هر صورت لازم هست چون این پروژه یک پروژه وب هست نه یک ابزار ساده و کمکی
همچنین این کتابخونه همونطور که میدونید از تمام محصولات وب مایکروسافت پشتیبانی میکنه
ASP.NET CORE
ASP.NET MVC
ASP.NET WebForms

برای به دست آوردن چنین قابلیتی، دو کتابخونه اول در هر صورت لازم هست

سه کتابخونه باقیمونده در تصویر:
* ابزارهای استاندارد و معرفی شده مایکروسافت هستند
* مایکروسافت این ابزارها رو فقط برای مصرف خودش معرفی نکرده بلکه برای مصرف در تمام پروژه هایی که مردم یا شرکت ها دارن. و همونطور که از نام اکستنشن موجود در این کتابخونه ها پیداست، اینها برای توسعه یک محصول استفاده میشن. برای نمونه، یکی از اینها مربوط به تزریق وابستگی هست. به نظر شما کسی در این دوره میاد برای یک محصول وقت بزاره که ترریق وابستگی رو خودش پیاده سازی کنه؟ خیر. علت اینکه مایکروسافت این کتابخونه ها رو به صورت مجزا و عمومی معرفی کرده دقیقا همین هست
* تمام کتابخونه های این پروژه، همه متعلق به مایکروسافت هستن و اینها تقریبا در همه جا به چشم میخورن، به خصوص زمانیکه پروژه دات نت کور باشه که دیگه اینها حتی نصب هم نمیشه چون به صورت پیشفرض جزئی از دات نت کور هست
* کتابخونه هایی مانند اچ تی تی پی، توسط مایکروسافت ارائه شد برای برقراری ارتباط اچ تی تی پی. هر گونه پیاده سازی دستی یا شخصی از این کتابخونه کاملا اشتباه هست و در اینترنت هزاران مطلب موجود هست که زمانیکه میخواین ارتباط اچ تی تی پی داشته باشید، باید این کتابخونه نصب بشه. هیچکس نمیاد خودش یک اچ تی تی پی کلاینت بشینه از صفر بنویسه اونم باز هزاران باگ و پرفورمنس ضعیف و غیر استاندارد. تعداد نصب تک تک این کتابخونه ها، خودش گویای این مطالب هست
* همونطور که در وابستگی های این پروژه مشاهده میکنید، از هیچ کتابخونه غیر استاندارد و غیر محبوبی استفاده نشده چون معمولا مصرف کننده ها دوست ندارن هر چیزی رو توی پروژشون اضافه کنن

**Comment by Sina-Soltani** [comment]
در مورد مستندات کم، لطف میکنید توضیح بدید دقیقا در چه قسمتی مستندات کافی نبوده؟
(در صورتی که کافی نباشه حتما اضافه میشه)

**Comment by idotnetdev** [comment]
ممنونم از توضیحاتتون.
بله درسته شما چند تا وابستگی توی پروژه دارید ولی خب هر کدوم این کتابخونه ها هم وابستگی های خاص خودشون رو دارن.
در هر صورت بنده فکر میکنم جزء اولین کسانی هستم که از این کتابخونه استفاده میکنم یعنی از زمانی که برای اولین بار توی سایت dotnettips.info مقاله هاشو منتشر کردید.

چیزی که به نظرم کم هست توی موارد مربوط به Storage هست یا حداقل نمونه پروژه ای که با EntityFramework پیاده سازی شده باشه.
در هر صورت من روی پروژه م پیاده سازی کردم ولی با توجه به نحوه پیاده سازی بنده از DbContext متفاوته برای همین نتونستم از DataContext شما استفاده کنم و به همون ذخیره روی Memory بسنده کردم ولی در هر صورت چند ساعتی رو وقت گذاشتم براش.

**Comment by Sina-Soltani** [comment]
تشکر از نظر شما

سعی میکنم طی چند روز آینده نمونه پروژه مربوط به
EF Storage
رو اضافه کنم

**Comment by idotnetdev** [comment]
یه مسأله دیگه
اگه بتونید Context خودتون رو طوری پیاده سازی کنید که از Context ما ارث بری کنه و نیاز نباشه که دو تا باشه توی پروژه.

**Comment by Sina-Soltani** [comment]
> 
> 
> یه مسأله دیگه
> اگه بتونید Context خودتون رو طوری پیاده سازی کنید که از Context ما ارث بری کنه و نیاز نباشه که دو تا باشه توی پروژه.

این مورد جز ویژگی هایی هست که قرار هست روش کار بشه و اضافه بشه

در هر صورت،اگر در حال حاضر با یک استوریج مشکلاتی در پروژتون دارید و نمیتونید استفادش کنید، کافیه که خودتون کار ذخیره و بازیابی رو انجام بدید
[Custom Storage](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-a-custom-storage)

**Comment by idotnetdev** [comment]
بله درسته. خواستم زمان اضافی برای پیاده سازی چیزی که هست صرف نکنم که متأسفانه نشد.

**Comment by Sina-Soltani** [comment]
نمونه پروژه ها به صورت مجزا افزوده شدند.

[Samples](https://github.com/Sina-Soltani/Parbad.Samples)

**Comment by idotnetdev** [comment]
عالی. دستتون درد نکنه.
