### ISSUE TITLE
Add PayPing Gateway

### ISSUE THREAD

**Issue by Azaferany** [Sina-Soltani/Parbad#194]
با سلام 

توی موارد دید درگاه های واسط رو هم پیاده کردین
می خواستم بپرسم قصد پیاده سازی درگاه های واسط پی پینگ رو ندارید 
او اگر نه, مشکلی نداره که خودم اضافه کنم و ریکوریکوئست بفرستم ؟

با تشکر

**Comment by Sina-Soltani** [comment]
درود

> 
> توی موارد دید درگاه های واسط رو هم پیاده کردین
> می خواستم بپرسم قصد پیاده سازی درگاه های واسط پی پینگ رو ندارید

متاسفانه در حال حاضر فرصت این کار رو ندارم

> 
> او اگر نه, مشکلی نداره که خودم اضافه کنم و ریکوریکوئست بفرستم ؟

بله در صورت تمایل میتونید خودتون توسعه بدید و درخواست ارسال کنید
قبل از شروع، لطفا حتما شرایط مشارکت رو مطالعه کنید تا از روند انجام کار مطلع باشید
[مشارکت](https://github.com/Sina-Soltani/Parbad/blob/master/CONTRIBUTING.md)

[راهنمای توسعه درگاه جدید](https://github.com/Sina-Soltani/Parbad/wiki/Developing-a-new-Gateway)

همچنین از درگاه‌های موجود که پیاده سازی شدن، میتونید نمونه کدها رو مشاهده کنید
[Gateways](https://github.com/Sina-Soltani/Parbad/tree/master/src/Parbad.Gateway)

در صورتیکه هر گونه سوالی داشتید میتونید همینجا بپرسید

**Comment by Sina-Soltani** [comment]
پس از مرج و تایید نهایی، نوگت به صورت خودکار تولید و آپلود میشه
