### ISSUE TITLE
افزودن بانک های جدید

### ISSUE THREAD

**Issue by mohamad-pahlavan** [Sina-Soltani/Parbad#2]
سلام. خسته نباشید
آیا بانک های جدید هم اضافه میشن؟ مثل مبنا کارت بانک صادرات و یا ایران کیش؟

**Comment by Sina-Soltani** [comment]
سلام.
هر بانکی که عضو شبکه شتاب باشه امکان افزودنش هست.
مبنا کارت و ایران کیش رو بررسی میکنم و احتمالا به زودی اضافه میکنم

**Comment by Sina-Soltani** [comment]
درگاه ایران کیش اضافه شد.
البته با اطلاعات واقعی تست نشده و نیاز هست دوستانی که این درگاه را دارن تست کنن

درگاه مبنا کارت بانک صادرات همونطور که گفتم به دلیل گنگ بودن سیستم و همچنین طراحی افتضاحش، از قرار دادنش صرف نظر کردم.

لطفا در صورتیکه درگاه ایران کیش رو کسی تست واقعی انجام داد، به من اطلاع بده
