### ISSUE TITLE
استفاده از پروژه بدونه دیتابیس

### ISSUE THREAD

**Issue by MR-MAP** [Sina-Soltani/Parbad#20]
سلام.

میشه از این پروژه بدون دیتابیس استفاده کرد و اطلاعاتی که قراره در دیتابیس ذخیره بشه رو بصورت خروجی از متد ها بگیریم و خودمون تو دیتابیس ذخیره کنیم ؟

**Comment by Sina-Soltani** [comment]
درود.

خیر
تمامی عملیاتی که توسط پَرباد به صورت اتوماتیک به کاربر ارائه میشه، با استفاده از دیتابیس داخلی اون هست.

در غیر اینصورت وجود این ابزار، غیر ضروری بود و کاربر از همان سرویس‌هایی که بانک‌ها ارائه میکنن میتونست استفاده کنه

**Comment by Sina-Soltani** [comment]
ضمن اینکه دیتابیس‌های زیادی قابل استفاده هستن. برای مثال
Sqlite
که فقط یک فایل ساده هست درون فولدر وب سایت شما

**Comment by MR-MAP** [comment]
خب بعضی از موارد بصورتی است که یک پروژه احتیاج داره یکسری اطلاعات اضافه همراه این جدول ذخیره کنه . مثلا شماره فاکتور و کد اپلیکیشن مربوطه

**Comment by Sina-Soltani** [comment]
احتمالا شما کاربرد دقیق این ابزار رو شاید متوجه نشده باشید.

تمامی اطلاعات مهم از جمله کد رهگیری، نام بانک، مبلغ، شماره تراکنش بانکی و غیره به شما داده میشه زمانیکه درخواست پرداخت ارسال میکنید و یا اینکه پرداختی رو تایید میکنید.

بنابراین شما این اطلاعات رو هر گونه که در نظر دارید در دیتابیس وب سایتِ خودتون می‌تونید ذخیره کنید.

**Comment by MR-MAP** [comment]
بله حق با شماست.
ممنون
