### ISSUE TITLE
blazor problems

### ISSUE THREAD

**Issue by nshayanfar** [Sina-Soltani/Parbad#203]
در زمان استفاده از fetchasync کتابخانه به درستی پارامترهای جستجو را پارس نمیکند.
حدس من در این هست که در blazor باید از NavigationManager به جای HttpContext استفاده شود. آیا راهی هست که برای رفع سریع مشکل بتوانم استفاده کنم؟

**Comment by nshayanfar** [comment]
خطا No token is received هست

**Comment by Sina-Soltani** [comment]
کدوم فریم ورک رو دارید استفاده میکنید؟
Blazor WebAssembly?
Blazor WebServer?

**Comment by nshayanfar** [comment]
blazor webserver

**Comment by nshayanfar** [comment]
الان برای دور زدن موضوع صفحه برگشت از پرداخت رو دارم به صورت mvc میزنم که اصلا راه حل جذابی نیست.

**Comment by Sina-Soltani** [comment]
با توجه به اینکه پروژه
Blazor WebServer
هست پس بنابراین
HttpContext
هم موجوده و مشکلی نباید وجود داشته باشه

میتونید نمونه پروژه
[Angular](https://github.com/Sina-Soltani/Parbad.Samples/tree/master/Web/Parbad.Sample.Angular)
رو نگاه کنید و ببینید برای پروژه های کلاینت چطور میشه کار کرد
