### ISSUE TITLE
مشکل در درگاه IDPay

### ISSUE THREAD

**Issue by hooh88** [Sina-Soltani/Parbad#204]
سلام
بعد از پرداخت و موقع
Verify
شدن مقدار
Status = failed
هست
ولی در زرین پال مشکلی وجود نداره

**Comment by Sina-Soltani** [comment]
درود
چه پیامی دریافت کردید؟

**Comment by hooh88** [comment]
خطای 
Invalid data is received from the gateway.
با 
Status = failed
توضیحات بیشتری بدم خدمتتون؟
عکس ارسال کنم؟

**Comment by Sina-Soltani** [comment]
این پیام آیا موقع 
Fetch
هم دریافت میشه؟

**Comment by hooh88** [comment]
ببخشید احتمالا من درست توضیح ندادم.
بعد از دریافت
var invoice = await _onlinePayment.FetchAsync();
invoice.Status = failed
میشه.

**Comment by Sina-Soltani** [comment]
لطفا کدهای زیر رو در برنامه وب خودتون در اکشن متدی که برای وریفای دارید قرار بدید و مقادیر اونها رو اینجا در چت قرار بدید تا بررسی کنیم

```c#
var status = await httpRequest.TryGetParamAsync("status");
var id = await httpRequest.TryGetParamAsync("id");
var trackId = await httpRequest.TryGetParamAsync("track_id");
var orderId = await httpRequest.TryGetParamAsync("order_id");
var amount = await httpRequest.TryGetParamAsync("amount");
```

لطفا همچنین مقادیر زیر رو از شئ
invoice
بخونید و اینجا قرار بدید
`var invoice = await _onlinePayment.FetchAsync();`

* TrackingNumber
* Amount

**Comment by hooh88** [comment]
مهندس من از
MVC
استفاده نکردم ، از
razor pages
استفاده میکنم امکان داره از این باشه؟
درمورد 5 موردی که گفتین ارسال کنم متاسفانه 
httpRequest
در
OnGetVerifyAsync
نیست و خطا میده.
 
درگاه بانک ملت هم تست کردم درست نشدودر قسمت
Verify
همین خطا میده
امکان داره از 
razor pages
باشه که استفاده میکنم؟

**Comment by hooh88** [comment]
مشکل رو متوجه شدم
از سمت بانک 
callbackUrl
به صورت 
Post
ارسال میشه، و من هرکاری کردم نشد با 
handler
دریافتش کنم برای همین یک کنترلر و یک اکشن نوشتم و اونجا کنترل میکنم.
فقط یک سوال، چون من نیاز به شماره فاکتور دارم، شماره فاکتور رو توی
SetTrackingNumber
قرار میدم. مشکل اینجاست که اگه یکبار تراکنش به مشکل خورد و نیاز بود همون تراکنش تکرار بشه خطا میده که این تراکنش در حال اجراست.
چطور میتونم این مشکل رو رفع کنم؟

ممنون از پیگیریتون

**Comment by Sina-Soltani** [comment]
> 
> 
> فقط یک سوال، چون من نیاز به شماره فاکتور دارم، شماره فاکتور رو توی
> SetTrackingNumber
> قرار میدم. مشکل اینجاست که اگه یکبار تراکنش به مشکل خورد و نیاز بود همون تراکنش تکرار بشه خطا میده که این تراکنش در حال اجراست.
> چطور میتونم این مشکل رو رفع کنم؟

امکان پذیر نیست
این قابلیتی هست که به استفاده کننده از این پکیج این اطمینان رو میده که هیچوقت از یک شماره پیگیری دو بار استفاده نشه
 تراکنش ها نباید تکرار یا ویرایش بشن بلکه باید تولید بشن
به این ترتیب میتونید تاریخچه پرداخت ها و تراکنش ها رو برای یک سفارش یا محصول نگه دارید

**Comment by hooh88** [comment]
ممنون از پیگیریتون
سیستم عالی و جامعیه امیدوارم موفق باشین.

راستی درگاه بانک صادرات هم اگه اضافه کنین عالی میشه
ممنون

**Comment by Sina-Soltani** [comment]
> ممنون از پیگیریتون
> سیستم عالی و جامعیه امیدوارم موفق باشین.
>
> راستی درگاه بانک صادرات هم اگه اضافه کنین عالی میشه
> ممنون


خواهش میکنم.
درگاه بانک صادرات رو اگر کسی توسعه بده و پول ریکوئست ارسال کنه میتونه اضافه بشه.
بنده چون زمان کمی دارم نمیتونم زیاد وقت بزارم.
