### ISSUE TITLE
خطا در زمان استفاده از Parbad.Storage.EntityFrameworkCore

### ISSUE THREAD

**Issue by hooh88** [Sina-Soltani/Parbad#205]
سلام
من در حالت تست از مموری استفاده میکردم مشکلی نبود.
وقتی از 
EntityFrameworkCore
استفاده کردم خطای زیر را بهم داد:

The provider for the source IQueryable doesn't implement IAsyncQueryProvider. Only providers that implement IAsyncQueryProvider can be used for Entity Framework asynchronous operations.

`
var result = await _onlinePayment.RequestAsync(inv =>
            {
                inv
                    .UseAutoIncrementTrackingNumber()
                    .SetCallbackUrl(callbackUrl);
`
نسخه ی 
sample
هم که اجرا کردم خطا داد.

ممنون میشم راهنمایی بفرمایید.

* Package Name: Parbad.Storage.EntityFrameworkCore
* Version: 1.3.0
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود

بله خطا داره. احتمالا در تغییرات نسخه جدید، دچار مشکل شده
پس از برطرف شدن،‌ اطلاع میدم همینجا

**Comment by Sina-Soltani** [comment]
لطفا نسخه جدید رو نصب کنید
`Install-Package Parbad.Storage.EntityFrameworkCore -Version 1.3.1`

**Comment by hooh88** [comment]
ممنون
عالی بود
موفق باشین
