### ISSUE TITLE
Add Addtional Data To Invoice

### ISSUE THREAD

**Issue by mmokhtari** [Sina-Soltani/Parbad#207]
hello there  

Im trying to add some addtional data to my invoice like this

`  var result = await _onlinePayment.RequestAsync(req =>
            {
                req
                  .SetAmount((decimal)item.Amount)
                  .SetCallbackUrl(item.VerifyCallBackUrl)
                  .SetGateway(item.Gateway == SubscriptionPaymentGatewayType.SandBox ? "ParbadVirtual" : item.Gateway.ToString())
                  .UseAutoRandomTrackingNumber()
                  .AddProperty(nameof(item.ClientCallBackUrl), item.ClientCallBackUrl);
            });
`

and i expect to get this data in Verify Method like this

`
 var invoice = await _onlinePayment.FetchAsync();
invoice.AdditionalData[nameof(PaymentInputDto.ClientCallBackUrl)]
`

but the result is emty

thank you for your great job

**Comment by Sina-Soltani** [comment]
Hi,
`AdditionalData` in `PaymentResult` object is NOT related to `Properties` in `Invoice` object.
`Properties` are used for building an `Invoice` object.
`AdditionalData` are some extra data that each gateway may send, such as Card Number.

Parbad only saves the necessary payment and transaction data. So you need to save/load your BUSINESS DATA yourself in your database.

**Comment by mmokhtari** [comment]
thanks
