### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by mmokhtari** [Sina-Soltani/Parbad#208]
hello there

im using parbad virtual gatway  like the sample you provide for angular 

when i click pay and gateway want to redirect to verify url i got 400 http bad request error

 my api action
`
        [HttpGet, HttpPost]
        public async Task<IActionResult> Verify() => RedirectPermanent(await _shetabPaymentAppService.Verify());`

the error

`
{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"Bad Request","status":400,"traceId":"00-189c4f8901111844b6b41f59ce9a46fb-a4fc0ee20ca1fc45-00"}
`

the url in browser 
`
https://localhost/Verify?paymentToken=c1ae7793f5c84eeca2e19574859dafd2
`

* Package Name:  parbad
* Version: latest

**Web application type:**
* ASP.NET Core Api & Vue

**Comment by Sina-Soltani** [comment]
Hi,
[Angular Sample](https://github.com/Sina-Soltani/Parbad.Samples/tree/master/Web/Parbad.Sample.Angular) is tested and has no problem.

![image](https://user-images.githubusercontent.com/10329804/117575137-cd645680-b0e0-11eb-8e34-aa1d9bc8e93b.png)
![image](https://user-images.githubusercontent.com/10329804/117575167-ea008e80-b0e0-11eb-932f-191a971b9592.png)
![image](https://user-images.githubusercontent.com/10329804/117575179-f7b61400-b0e0-11eb-8bcb-d5eb8b46f6f8.png)
![image](https://user-images.githubusercontent.com/10329804/117575187-08ff2080-b0e1-11eb-84b7-492edf7e85d0.png)

**Comment by mmokhtari** [comment]
the reason i got bad request was AntiForgeryToken  
it would be nice if you add `AntiForgeryToken ` to virtual gateway Form.
