### ISSUE TITLE
استفاده از دیتابیس sqlserver ولی نه EF

### ISSUE THREAD

**Issue by msngithub** [Sina-Soltani/Parbad#209]
<div dir="rtl" align="right">
عرض سلام و ادب و تشکر بابت ابزار کاربردی که تهیه شده

بنده از دیتابیس SQL Server استفاده میکنیم و ORM اختصاصی خودمو برای کار با دیتابیس دارم و از EF استفاده نمیکنم

طبیعتا استفاده از UseMemoryCache هم که توصیه نمیشه

با توجه به محدودیت سرور ها امکان ساخت دو دیتابیس SQL Server  هم برای هر پروژه وجود ندارد و منطقی هم نیست

در این موارد امکان استفاده از پرباد در دیتابیسم وجود داره ؟ ( اگر هست به چه صورت ؟ )

یا باید دیتابیس جداگونه ای مثل SQLLite درست کنم برای هر پروژه و با EF بهش وصل بشم  ؟

یا اینکه میشه یک دیتابیس مشترک برای چند تا پروژه استفاده کرد ؟ که در این صورت من یک دیتابیس SQL Server  جداگونه درست کنم و همه پروژه هارو به اون وصل کنم و با EF بهش وصل بشم

پیشنهاد شما استفاده از چه روشی هست ؟ 
دیتابیس اختصاصی خود پروژه یا SQLLite برای هر پروژه یا یک دیتابیس مشترک برای همه پروژه ها

با تشکر
</div>

**Comment by Sina-Soltani** [comment]
درود

UseMemoryCache
باید فقط برای تست و توسعه استفاده بشه

مخزن
[EntityFrameworkCore](https://www.nuget.org/packages/Parbad.Storage.EntityFrameworkCore/)
برای پایگاه داده دوم یا غیره نیست، بلکه به شما این امکان رو میده که داخل پایگاه داده خودتون،‌ اطلاعات رو ذخیره و بازیابی کنید
روال تنظیم کردنش هم کاملا مانند روال عادی کار با 
[EF CORE](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-entityframework-core)
هست

اما اگر بنا به دلایلی که ذکر کردید قصد ندارید که از
EF Core
استفاده کنید، راه حل بهتر اینه که خودتون ذخیره و بازیابی رو انجام بدید به هر شیوه ای که صحیح میدونید
[Custom Storage](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-a-custom-storage)
[نمونه پروژه](https://github.com/Sina-Soltani/Parbad.Samples)

**Comment by msngithub** [comment]
<div dir="rtl" align="right">
چیزی که متوجه شدم از source code باید جداول Payment,Transaction رو در دیتابیس خودم صرفا برای پرباد ایجاد کنم و بجای اینکه از StaticPayments و StaticTransactions استفاده کنم ، از همین جداول در دیتابیس استفاده کنم ؟

و سوال دیگه اینکه با توجه به اینکه دیتابیس پرباد صرفا برای عملیات داخلی خود پرباد هست ، پیشنهاد دیتابیس مشترک برای همه پروژه ها صرفا برای پرباد شدنی هست ؟
</div>

**Comment by Sina-Soltani** [comment]
بله شما در اون مثال باید به جای استاتیک ها که صرفا جنبه مثال دارند، کدهای خودتون رو جایگزین کنید تا داده ها رو در پایگاه داده خودتون ذخیره و بازیابی کنید.

در مورد سوال پایگاه داده مشترک، بله قابل انجام هست.
البته برای کنترل و مدیریت بهتر پایگاه داده، شما میتونید از
Schema
های تنظیم شده برای هر پروژه استفاده کنید
project1.payments
project1.transactions

project2.payments
project2.transactions


اگر تصمیم گرفتید که از مخزن
EF Core
استفاده کنید، موارد بالا به صورت اتوماتیک برای 
Schema
پیاده سازی و مدیریت شده.
میتونید نمونه کدها رو مشاهده کنید

**Comment by Sina-Soltani** [comment]
یک نکته که فراموش کردم بگم
شما میتونید حتی از جداول مشترک هم برای پرباد در پروژه های مختلف استفاده کنید و مشکلی پیش نخواهد آمد
برای مثال اگر در یک پایگاه داده جداول
`[dbo].[payments]`
`[dbo].[transactions]`
داشته باشید،‌میتونید با رشته اتصال به این پایگاه داده و استفاده از همین دو جدول، تمام پروژه ها رو بهش متصل کنید

**Comment by msngithub** [comment]
ممنون از شما ، خیلی لطف کردید
