### ISSUE TITLE
خطا در استفاده از درگاه مجازی

### ISSUE THREAD

**Issue by RezaAVS** [Sina-Soltani/Parbad#21]
بعد از ریدارکت به سمت درگاه مجازی این پیفام نمایش داده می شود
..\Resources\VirtualGatewayRequestHtml.txt;System.String, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089;windows-1256

**Comment by Sina-Soltani** [comment]
مشکل در حال بررسی هست

لطفا از نسخه قبل استفاده کنید

```
Install-Package Parbad -Version 2.0.0
```

**Comment by Sina-Soltani** [comment]
مشکل برطرف شد
 لطفا از آخرین نسخه استفاده کنید

```
Install-Package Parbad -Version 2.2.0
```
