### ISSUE TITLE
آدرس درگاه سداد ملی

### ISSUE THREAD

**Issue by sadeq-qafari** [Sina-Soltani/Parbad#213]
سلام
در استفاده از درگاه سداد در حال حاضر با آدرس
https://sadad.shaparak.ir/VPG/Purchase/Index?token=[Token]
انتقال انجام می پذیرد که در نتیجه‌ی آن خطای زیر مشاهده می‌شود
**خطا در عملیات**
**با عرض پوزش از خطای پیش آمده،لطفاً چند لحظه دیگر دوباره سعی نمایید**
بعد از بررسی مستندات سداد آدرس زیر تست شد که انتقال به درگاه با موفقیت انجام شد
https://sadad.shaparak.ir/Purchase/Index?token=[Token]

جهت اطلاع و بررسی.

**نام و نسخه پکیج**
* Package Name:  Parbad.AspNetCore
* Version: 1.2.0

**نوع برنامه وب**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود

بسته شدن تیکت به معنای اشتباه بودن اطلاعاتی که دادید هست؟ یا اینکه صرفا برای اطلاع بود؟

**Comment by sadeq-qafari** [comment]
اول به اشتباه فکر کردم این قضیه باعث اشکال شده بعد فهمیدم انتقال به درگاه باید با متد گِت* انجام بشه و هر دو آدرس درست هستن
فقط در مستندات آدرسی که تعریف شده آدرس دوم هست.
چون مشکل آدرس تعریف شده نبود تیکت رو بستم.
*get
