### ISSUE TITLE
یک در میان ارور

### ISSUE THREAD

**Issue by mmo1383** [Sina-Soltani/Parbad#216]
در یک کامپیوتر جواب میدهد و در یکی ارور زیر 
InvoiceNotFoundException: No invoice found with the token e408573448d74e82a7dc9368da621d88

یک بار موقع برگشت درست کار میکند و یکبار اشتباه

**Comment by Sina-Soltani** [comment]
درود

این گونه مشکلات، ارتباطی با این پکیج ندارن
برنامتون رو چک کنید ببینید مشکل از کجاست

**Comment by mmo1383** [comment]
من از نسخه قدیمی استفاده می کنم ربطی ندارد

**Comment by Sina-Soltani** [comment]
خیر
همونطور که گفتم،‌چنین مشکلاتی مربوط به پکیج نیست. حتی نسخه های قدیمی چنین مشکلاتی ندارند
اینگونه مشکلات برمیگرده به برنامه شما
