### ISSUE TITLE
سورس Core MVC 5,API Core 5  و سورس React hook برای ارتباط با درگاه

### ISSUE THREAD

**Issue by SayyehBan** [Sina-Soltani/Parbad#217]
<p dir="rtl">سلام و خسته نباشید.<br />
&nbsp;جای داره اول از آقای سینا سلطانی سازنده package درگاه تشکر کنم که ایشان زحمت کشیدن. یک package عالی به نام Parbad&nbsp; طراحی کردن برای ارتباط با درگاه بانکی و تمام سورس ها رو زحمت کشیدن نوشتن که جز ریکت که خودم لازم داشتم درست کردم و قرار میدم که دوستان استفاده کنن.<br />
<a href="https://github.com/Sina-Soltani/Parbad">لینک راهنمای package</a><br />
&nbsp;که شما میتوانید از این package زیبا استفاده کنید و لذت ببرید.<br />
و بنده باز جداگانه سورس آماده کردم و چون بنده درگاه پارسیان نیاز داشتم دستورات پارسیان استفاده کردم و شما هر درگاهی بخواهید استفاده کنید به راحتی میتوانید صدا و استفاده کنید حتی چندین درگاه با هم به صورت همزمان که در Core MVC بنده همه به صورت کامل قرار دادم ولی بگم نمونه برداری شده از سورس آقای سینا سلطانی هستش.<br />
<a href="https://s18.picofile.com/file/8436307200/PaySayyehBanMVC_Core.zip.html">دانلود لینک</a></p>

<p dir="rtl">Core MVC و از آخرین ورژن Core 5 استفاده شده در این سورس.<br />
و دوستانی که علاقه به API Core 5 دارن این با API Core 5 ساخته شده. و این رو هم بگم سورس ارتباط با دیتابیس هم درون فایل هستش که میتوانید برای تست استفاده کنید و نسخه API Core 5 چون فقط درگاه پارسیان نیاز داشتم همه قرار ندادم ولی توسط مستندات سایت راحت میتوانید هر درگاه یا کامل همه درگاه ها رو استفاده کنید. و این رو هم بگم روش ارتباط با دیتابیس به صورت ADO هستش<br />
<a href="https://s18.picofile.com/file/8436307326/APICoreSayyehBanPay.zip.html">سورس API Core 5</a><br />
&nbsp;چون این سورس API Core&nbsp; بود سورس Frontend ریکت ساخته نشده بود بنده سورس react رو ساختم برای ارتباط با ریکت.<br />
<a href="https://s19.picofile.com/file/8436307392/react_sayyehban_pay.zip.html">دانلود سورس ریکت</a><br />
&nbsp;که این سورس فقط هزینه میگیره به درگاه وصل میشه اگر پرداخت موفقیت آمیز بود پیغام موفقیت داده میشه و وارد صفحه میشه که با موفقیت انجام شده است. و اگر شکست بخوره موقع خرید وارد فرم شکست میشه.<br />
و اگر وقت کنم حتما آموزشی API Core و Core MVC و همین طور ریکت رو درست میکنم.<br />
<a href="https://t.me/academy_sayyehban">کانال تلگرام ما</a></p>

**Comment by Sina-Soltani** [comment]
درود

این جهت اطلاع هست؟

**Comment by SayyehBan** [comment]
<div dir="rtl">
سلام و خسته نباشید.
<br/>
من سورس API Core,React و Core MVC که ساخته بودم درون issues  شما قرار دادم که دوستانی که با ریکت نیاز دارن به همراه API Core استفاده کنن شما سورس react شما نداشتید ولی بلخره درست کردم گفتم به شما هم بدم که برای کاربران قرار بدید اونها هم استفاده کنن.
</div>

**Comment by Sina-Soltani** [comment]
تشکر

سورس رو بعدا بررسی میکنم و به نمونه پروژه ها اضافه میکنم

**Comment by SayyehBan** [comment]
<p dir="rtl">سلام و خسته نباشید</p>

<p dir="rtl">فقط سورس API Core با سورس ریکت ارتباط داراه باید باهم قرار بدید.<br />
بابت کمکی که کردید یک دنیا ممنون</p>

**Comment by Sina-Soltani** [comment]
درود
نمونه پروژه ای که آماده کرده بودید رو نگاه کردم
متاسفانه نمیتونم به عنوان نمونه قرارش بدم

نمونه ای که شما آماده کردید روال کارش و طرحش و فرمش و همه چیزش با تمام مثال ها متفاوت هست
در صورتی که تمام نمونه های آماده شده، همشون یک الگو رو طی میکنند

اگر میتونید دقیقا مشابه سایر نمونه ها درستش کنید، میتونم اونوقت قرارش بدم

برای نمونه میتونید نمونه
Angular
رو نگاهی بندازید

این تیکت رو میبندم. اما میتونید همینجا پاسخ بدید
موفق باشید

**Comment by SayyehBan** [comment]
<p dir="rtl">سلام و خسته نباشید</p>

<p dir="rtl">بله ولی الان درگیر یه کاری هستم ولی نمونه سورس Core MVC شبی به الگو های شما هستش ولی بابت API Core و react چون میخوام آموزشی درستم کنم حتما شبی به نمونه های شما کامل درست میکنم به همراه آموزشی میخوام قرار بیدم ولی فعلا درگیری کاری هستم تمام بشه به روی چشم حتما درست میکنم&nbsp; و قرار میدم تا دوستان دیگه هم استفاده کنن.</p>

**Comment by Sina-Soltani** [comment]
نمونه
MVC
و 
Core
در نمونه های فعلی موجود هست و نیازی به اضافه کردن ندارن
صحبت فقط در مورد نمونه پروژه
React
هست که گفتم اگر تمایل داشته باشید و بتونید مطابق سایر نمونه های موجود درستش کنید خوب میشه و میتونم به نمونه ها اضافش کنم

**Comment by SayyehBan** [comment]
سلام بله تمایل دارم چون درگیر چند تا کار هستم با تاخیر قرار ممکن ارسال کنم اگر مشکلی نیست ولی سرم سریع خلوت بشه نمونه ریکت مثل نمونه های شما درست میکنم و قرار میدم تا دوستان هم استفاده کنن.
