### ISSUE TITLE
TrackingNumber DataType

### ISSUE THREAD

**Issue by mmokhtari** [Sina-Soltani/Parbad#235]
با سلام و احترام
از اونجای که درگاه پرداخت پاسارگاد  فیلد 
invoiceNumber 
را به صورت رشته میگیرن  و چرا فقط میتوان به فیلد 
TrackingNumber 
عدد داد

با تشکر فروان

**Comment by Sina-Soltani** [comment]
درود

شماره پیگیری همونطور که از اسمش پیداست یک شماره هست

صرفا به خاطر اینکه درگاه پارسیان این شماره رو به صورت رشته دریافت میکنه، نمیشه نوع این شماره رو در طراحی پَرباد به رشته تغییر داد
چون این ابزار برای تمام درگاه ها پیاده سازی شده و نه فقط درگاه پارسیان

همچنین در صورت تغییر نوع به رشته، قابلیت هایی مانند تولید شماره پیگیری به صورت خودکار، و تولید به صورت تصادفی، دیگه از بین میره. در حال حاضر مصرف کننده های این ابزار خیلی از این قابلیت دارن استفاده میکنن

در نتیجه برای درگاهی مانند پارسیان که رشته هم قبول میکنه، ما فقط عدد رو به صورت رشته تحویل میدیم

**Comment by mmokhtari** [comment]
با سلام و درود

**Comment by Sina-Soltani** [comment]
بله از طریقی که توضیح دادید امکان پذیر هست

اما ویژگی ها و کارها معمولا بر اساس نیاز مصرف کننده ها تولید میشن. چون در ازای اون، زمان و انرژی باید گذاشته بشه تا ویژگی ها توسعه داده بشه

همونطور که مشاهده میکنید تا به امروز هیچ موردی در رابطه با تغییر نوع شماره پیگیری درخواست نشده و همه دارن سفارش هاشون رو به راحتی انجام میدن، حتی برای درگاه پاسارگاد

ضمن اینکه همونطور که در لیست گفتگو ها مشاهده میکنید ۶ تا تیکت در مورد درخواست‌ها و ویژگی‌های مختلف تقاضا شده که هنوز باز مونده، چون بنده زمان آزاد برای انجام اونها رو ندارم

اما در صورتی که کسی توسعه بده و پول ریکوئست ارسال کنه، میشه کارها رو انجام داد

**Comment by mmokhtari** [comment]
اگر مایل باشید یک راه ارتباطی منو و شما ایجاد کنیم برای مشاوره و  پیاده سازی این داستان

**Comment by Sina-Soltani** [comment]
راه ارتباط تلفنی یا پیامی متاسفانه نمیتونم

سوال ها رو داخل تیکت ها بنویسید،‌ من حتما پاسخ میدم
