### ISSUE TITLE
پشتیبانی از ورژن بالاتر .NETStandard

### ISSUE THREAD

**Issue by EliasTaghavi** [Sina-Soltani/Parbad#24]
سلام
وقت بخیر
لطفاً پشتیبانی از ورژن‌های بالاتر .NetStandard را اضافه کنید.
ممنون از کتابخانه کاربری شما

**Comment by Sina-Soltani** [comment]
درود

منظورتون چه ورژنی هست دقیقا؟

**Comment by EliasTaghavi** [comment]
من منظورم NetStandard 2.0 بود
الان دقت کردم شما از قبل این ورژن را پشتیبانی می‌کنید.
ممنون
