### ISSUE TITLE
net::ERR_INCOMPLETE_CHUNKED_ENCODING

### ISSUE THREAD

**Issue by parsintalk** [Sina-Soltani/Parbad#240]
ضمن عرض سلام و احترام و تشکر بیکران از زحمات شما
من امروز بعد از نصب پروژم روی یک سرور ubuntu 20.4 و nginx متوجه شدم که سیستم به درگاه بانک ملت  وارد نمیشه.
بعد از بررسی متوجه شدم مرورگر با پیام net::ERR_INCOMPLETE_CHUNKED_ENCODING علی رغم status 200 جلوی نوشتن فرم برای post رو می گیره.
این مشکل تو iis و windows وجود نداشت.
نهایتا داخل تابع DefaultGatewayTransporter -> TransportAsync  چندین و چند حالت رو تست کردم و متوجه شدم مشکل به خاطر async بودن ماجراست.
از await و getAwaiter().getResult() هم استفاده کردم و نشد.
نهایتا مشکلم با استفاده از روش زیر در خط 34 فایل DefaultGatewayTransporter   حل شد:

                HttpResponseUtilities.AddNecessaryContents(_httpContext, "text/html");

                var form = HtmlFormBuilder.CreateForm(Descriptor.Url, Descriptor.Form);

               // fix  net::ERR_INCOMPLETE_CHUNKED_ENCODING
                var buffer = System.Text.Encoding.UTF8.GetBytes(form);
                _httpContext.Response.Body.Write(buffer,0, buffer.Length);
                return Task.CompletedTask;

                //return _httpContext.Response.WriteAsync(form, cancellationToken);

امکانش هست شما هم این مورد رو به شیوه ای که صلاح می دونید اصلاح بفرمایید تا روی لینوکس و nginx هم بشه از پرباد استفاده کنیم؟
با سپاس فراوان

Package Name:  Parbad
Version: 3.7.0

Web application type:
ASP.NET CORE (.NET 5)

**Comment by Sina-Soltani** [comment]
درود

امکانش هست کد زیر رو هم تست کنید و ببینید کار میکنه یا خیر؟
```c#
return _httpContext.Response.Body.WriteAsync(buffer,0, buffer.Length);
```

**Comment by parsintalk** [comment]
خیلی ممنونم، تست شد و به درستی کار می کنه.
```

public virtual Task TransportAsync(CancellationToken cancellationToken = default)
        {
            if (Descriptor.Type == GatewayTransporterDescriptor.TransportType.Post)
            {
                HttpResponseUtilities.AddNecessaryContents(_httpContext, "text/html");

                var form = HtmlFormBuilder.CreateForm(Descriptor.Url, Descriptor.Form);

                var buffer = System.Text.Encoding.UTF8.GetBytes(form);

                return _httpContext.Response.Body.WriteAsync(buffer,0, buffer.Length);
            }

            HttpResponseUtilities.AddNecessaryContents(_httpContext);

            _httpContext.Response.Redirect(Descriptor.Url);

            return Task.CompletedTask;
        }
```

**Comment by Sina-Soltani** [comment]
پس بنابراین مشکل از نحوه نوشتن اطلاعات در خروجی هست و از async بودن نیست

اصلاحش میکنم به زودی
ممنون برای اطلاع رسانی

**Comment by parsintalk** [comment]
سپاسگزارم
