### ISSUE TITLE
اضافه کردن validCardNumber و nationalCode برای درگاه Pay

### ISSUE THREAD

**Issue by walrusix** [Sina-Soltani/Parbad#250]
با سلام
مطابق مستندات درگاه مذکور و برخی دیگر از دیگر درگاهها می توان واریز کاربر را محدود به یک کارت مقصد کرد و یا این محدودیت را برای شماره ملی واریزکننده اعمال کرد. خواهشمند است در صورت امکان این ویژگی نیز اضافه گردد.

مستندات مذکور: https://docs.pay.ir/gateway/#%D9%85%D8%B1%D8%AD%D9%84%D9%87-%D8%A7%D9%88%D9%84-%D8%A7%D8%B1%D8%B3%D8%A7%D9%84-%D8%AF%DB%8C%D8%AA%D8%A7

با تشکر

**Comment by Sina-Soltani** [comment]
افزوده شد
```
Install-Package Parbad.Gateway.PayIr -Version 1.4.0
```
https://github.com/Sina-Soltani/Parbad/wiki/Gateways-specific-functions#payir
