### ISSUE TITLE
امکان تعریف شناسه پرداخت کننده مربوط به درگاه بانک ملت

### ISSUE THREAD

**Issue by SajjadHosseinPour** [Sina-Soltani/Parbad#252]
با عرض سلام و احترام 
امکان تعریف شناسه پرداخت کننده (PayerId) مربوط به درگاه بانک ملت مدتی قبل به پکیج Parbad اضافه شده (ورژن 3.8.0)، 
بنده از پکیج Parbad.AspNetCore استفاده میکنم و توی این نسخه متاسفانه این امکان وجود نداره (فکر میکنم ورژن 3.7 به عنوان Dependency تعریف شده)، خواستم اگر ممکنه این امکان رو به این پکیج هم اضافه کنید.
ممنون از شما

**Comment by Sina-Soltani** [comment]
درود

بسته‌های نوگت در فریم ورک دات نت مایکروسافت، قابلیت نصب و به روز رسانی به صورت جداگانه دارند
شما باید نوگت پَرباد را نصب کنید تا آخرین نسخه برای شما نصب بشه
```
Install-Package Parbad
```
