### ISSUE TITLE
AddPardakhtNovin System.TypeLoadException

### ISSUE THREAD

**Issue by sadeq-qafari** [Sina-Soltani/Parbad#254]
Hi, I've added PardakhtNovin.Parbad.Gateway to my payment solution and tried to add gateway just like other gateways and I got this error:

> Method 'FetchAsync' in type 'PardakhtNovin.Parbad.Gateway.PardakhtNovinGateway' from assembly 'PardakhtNovin.Parbad.Gateway, Version=0.0.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

did I miss something that I'm not aware of?

**Package name and version**
* PardakhtNovin.Parbad.Gateway Version=0.0.3.0
* Parbad.AspNetCore Version=1.2.0
* Parbad Version=3.7.0

**Web application type:**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
Hi,

This gateway is not developed by Parbad.
It's developed by others.
GitHub: https://github.com/MDP66/PardakhtNovin.Parbad.Gateway

**Comment by sadeq-qafari** [comment]
Yes but I saw you referenced it for novin-pardakht gateways I thought you might have a clue 😅
Thanks for the answer btw.

**Comment by Sina-Soltani** [comment]
I'll remove the link later. Thanks.
