### ISSUE TITLE
مشکل در درگاه بانک ملی

### ISSUE THREAD

**Issue by FatehNezami** [Sina-Soltani/Parbad#255]
با سلام و خسته ناشید
قبل از هرچیزی بابت سیستم خیلی خوبتون تشکر میکنم که این امکان رو فراهم کردید، من برای درگاه بانک ملی راهنمایی میخواستم، تمام مقادیر ارسالی درست می باشند اما خطای زیر رو برمیگردونه :
![image](https://user-images.githubusercontent.com/44225248/135717093-a4ad3d32-7aba-48d9-a66c-61059bd655a5.png)
در حالی که تمامی اطلاعات صحیح میباشد، نمونه کدی نیست که با پرباد درگاه بانک ملی رو استفاده کرده باشد.
باتشکر

**Comment by Sina-Soltani** [comment]
درود
خواهش میکنم

بعید میدونم مشکلی داشته باشه این درگاه
لطفا در قسمت تنظیمات درگاه، اطلاعات درگاه رو چک کنید ببینید تمام اطلاعات رو وارد کردید یا خیر


تنظیمات شامل
TerminalId 
MerchantId 
TerminalKey 
هستند

اطلاعات صورتحساب برای پرداخت نیز شامل
TrackingNumber
Amount
CallbackUrl
هستند

**Comment by FatehNezami** [comment]
ممنونم بابت پاسختون
دقیقا تمامی مواردی که فرمودید رو درست وارد کردم، درگاه زرین پال و ملت هم تو پروژه ازش استفاده میکنیم که مشکلی نداره، فقط برای ملی ارور میده، باتوحه نمونه کدهای ملی که از پرباد استفاده نکردن قبل از درخواست پرداخت اطلاعات رو هش میکنن، آیا پرباد هم برهمین روال درخواست پرداخت رو میفرسته برای ملی؟

**Comment by Sina-Soltani** [comment]
بله
هش انجام میشه
https://github.com/Sina-Soltani/Parbad/blob/master/src/Parbad/src/Gateway/Melli/Internal/MelliHelper.cs#L24

**Comment by Sina-Soltani** [comment]
در صورت تمایل، اطلاعات درگاه رو به ایمیل زیر ارسال کنید تا من تست رو انجام بدم
البته بعید میدونم بتونم کامل تست کنم چون درگاه فقط از آدرس آی پی که شما به بانک دادید ، درخواست رو دریافت میکنه
اما در هر صورت میشه یک امتحان کرد

parbad@outlook.com

**Comment by FatehNezami** [comment]
خیلی ممنونم مشخصات درگاه رو براتون فرستادم
با این ایمیل یراتون فرستادم fateh.nezami115@gmail.com
ممنون بابت وقتی که میزارید

**Comment by Sina-Soltani** [comment]
من دو بار تست رو انجام دادم
یک بار با پَرباد
و یک بار با خود پروژه تست درگاه ملی

در هر دو تست، پیغام خطایی که شما فرستادید رو دریافت کردم
به نظرم باید با پشتیبانی درگاه ملی صحبت کنید و مشکل رو توضیح بدید
چون وقتی اطلاعات شما روی پروژه مثال خودشون هم کار نمیکنه، پس احتمالا مشکل باید از جای دیگه ای باشه

**Comment by FatehNezami** [comment]
خیلی ممنون بابت وقتی که گذاشتید من با پشتیبانی تماس میگیرم نتیجه رو بهتون اعلام میکنم
بازم تشکر میکنم ازتون

**Comment by Sina-Soltani** [comment]
خواهش میکنم

**Comment by FatehNezami** [comment]
مشکل اصلی از کلید پذیرنده IPG قدیمی بود 
که با استفاده از کلید پذیرنده جدید مشکل برطرف شد، بازم ممنون

**Comment by Sina-Soltani** [comment]
موفق باشید
