### ISSUE TITLE
خطلا در ارتباط با درگاه آسان پرداخت

### ISSUE THREAD

**Issue by mohammad-ashrafi2020** [Sina-Soltani/Parbad#259]
سلام ، درگاه آسان پرداخت چندین مشکل داره : 

- تاریخ و زمان ارسال نمیشه و این باعث خطلا میشه
- آدرس درگاه پرداخت اشتباه وارد شده
- RijndaelManaged Not worked in .net Core with BlockSize 256

**Package name and version**
**نام و نسخه پکیج**
* Package Name: Parbad
* Version: 3.8.0

**Web application type:**
**نوع برنامه وب**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
لطفا در صورت امکان کلیدهای رمزنگاری را به آدرس ایمیل زیر ارسال کنید تا مشکلات این درگاه برطرف بشه
parbad@outlook.com

**Comment by mohammad-ashrafi2020** [comment]
سلام ، بله حتما - الان براتون ارسالش میکنم

**Comment by Sina-Soltani** [comment]
سپاس از شما
در حال رفع مشکل هستم
به زودی یک نسخه بتا منتشر میکنم تا ببینیم آیا مشکلات این درگاه کاملا رفع شده یا خیر
اگر شما امکان تست این نسخه رو داشته باشید و نتیجه رو اعلام کنید بسیار عالی میشه

**Comment by mohammad-ashrafi2020** [comment]
چشم ، حتما 
من خودم این مشکل رو حل کردم ، برای رمزنگاری به 
EndPoint ای
که مشخص کردن اطلاعات رو ارسال میکنم و جواب رو برمیگردونه ، ولی اگر بشه توی خود برنامه رمزنگاری انجام بشه بهتره

**Comment by mohammad-ashrafi2020** [comment]
یا اگه وقت داشته باشید که این پکیج رو بیارید روی 
Rest خیلی خوب میشد 
توی Api های رست دیگه نیازی به 
Key و IV نیست

**Comment by Sina-Soltani** [comment]
> چشم ، حتما من خودم این مشکل رو حل کردم ، برای رمزنگاری به EndPoint ای که مشخص کردن اطلاعات رو ارسال میکنم و جواب رو برمیگردونه ، ولی اگر بشه توی خود برنامه رمزنگاری انجام بشه بهتره

بنده هم همین راه رو در نظر داشتم تا انجام بدم که رمزنگاری توسط خودشون انجام بشه
 با توجه به اینکه ممکنه حتی در آینده هم مشکلاتی در الگوریتم‌های رمزنگاری به وجود بیاد بهترین راه حل اینه که به عهده خود درگاه سپرده بشه

همچنین تاریخ و ساعت فعلی هم از خود درگاه گرفته میشه

> یا اگه وقت داشته باشید که این پکیج رو بیارید روی Rest خیلی خوب میشد توی Api های رست دیگه نیازی به Key و IV نیست

آیا شما مستندات REST رو دارید؟ اگه دارید لطفا به ایمیل ارسال کنید تا بررسی کنم

**Comment by mohammad-ashrafi2020** [comment]
>همچنین تاریخ و ساعت فعلی هم از خود درگاه گرفته میشه 
>
 بله دقیقا این نسخه ای که الان دارم باهاش کار میکنم رو با همین روش پیاده کردم ولی 2 تا درخواست اضافی ارسال میشه و باز موقع VeryFy کردن هم باید مقادیر رو ارسال کنیم

> آیا شما مستندات REST رو دارید؟ اگه دارید لطفا به ایمیل ارسال کنید تا بررسی کنم
>
 بله دارم الان براتون ارسالش میکنم

**Comment by Sina-Soltani** [comment]
خواستم بهتون اطلاع بدم که در صورتیکه ایمیلی ارسال کرده باشید، من هنوز چیزی دریافت نکردم

**Comment by mohammad-ashrafi2020** [comment]
متاسفانه حذف اش کردم ایمیل ارسال کردم که دوباره برام ارسالش کنن احتمالا فردا صبح براتون ارسالش میکنم

**Comment by Sina-Soltani** [comment]
سپاس از شما

**Comment by Sina-Soltani** [comment]
در صورت امکان لطفا مقدار merchantConfigurationId رو به ایمیل ارسال کنید تا تست رو انجام بدم
سپاس از شما

**Comment by mohammad-ashrafi2020** [comment]
ارسال شد

**Comment by Sina-Soltani** [comment]
من هیچ ایمیلی از شما دریافت نکردم
لطفا چک کنید ببینید درست ارسال شده یا خیر

**Comment by mohammad-ashrafi2020** [comment]
marchantConfigurationId = 63674

**Comment by mohammad-ashrafi2020** [comment]
ارسال شد ، الان چک کنید

**Comment by Sina-Soltani** [comment]
به یک ایمیل دیگه ارسال کردید.
در هر صورت دریافت شد. سپاس از شما

**Comment by Sina-Soltani** [comment]
من این پیغام خطا رو مرتبا از درگاه دریافت میکنم
![image](https://user-images.githubusercontent.com/10329804/142764326-91ff00c7-d10a-4ada-a3d6-4ce893754f2d.png)

آیا شما اطلاع دارید که علت چی میتونه باشه؟

**Comment by mohammad-ashrafi2020** [comment]
نه متاسفانه ولی الان ایمیل برا پشتیبانیشون ارسال کردم اگر جواب دادن بهتون اطلاع میدم

**Comment by mohammad-ashrafi2020** [comment]
جواب پشتیبان : 
با سلام و احترام
خواهشمند است IP و زمان ارسال درخواست را ارسال فرمایید.
با سپاس
-----------------------------
می خواد لاگ تراکنش رو ببینه

**Comment by Sina-Soltani** [comment]
سیستم من همیشه به VPN وصله و مطمئن نیستم که این IP صحیح هست یا خیر
IP:
159.48.53.119

Local Time:
20211121 171219

**Comment by mohammad-ashrafi2020** [comment]
سلام ، گفتن هیچ درخواستی با اون ip در اون زمان ارسال نشده

**Comment by Sina-Soltani** [comment]
باید دوباره درخواست ارسال کنیم و دوباره ازشون بخوایم بررسی کنن؟

البته راه حل دیگه اینه که من مطابق مستندات خودشون پیاده‌سازی کنم و یک نسخه بتا منتشر کنم که بشه توسط شما و بقیه تست بشه

**Comment by mohammad-ashrafi2020** [comment]
اگر بتونید یه درخواست همین الان ارسال کنید و ip و زمان رو هم به من بدین براشون ارسال کنم که خوبه 

آره اینم فکر خوبیه

**Comment by Sina-Soltani** [comment]
الان ارسال کردم

IP
89.249.65.100

Local Time: 20211124 131055

```
{
  "merchantConfigurationId": 63674,
  "serviceTypeId": 1,
  "localInvoiceId": 10054434,
  "amountInRials": 10000,
  "localDate": "20211124 131435",
  "additionalData": "",
  "callbackURL": "http://www.mywebsite.com/",
  "paymentId": "",
  "useDefaultSharing": false,
  "settlementPortions": null
}
```

**Comment by mohammad-ashrafi2020** [comment]
مهندس گفتن یه شماره اعلام کنید تا تماس بگیریم برا رفع اشکال ، بی زحمت شماره ااتون رو برام ارسال کنید تا براشون ایمیل اش کنم

**Comment by Sina-Soltani** [comment]
من ایران نیستم و متاسفانه شماره ای نمیتونم بدم

باید خودتون پیگیری کنید

اگر میدونید که امکان پذیر نیست، راه حل دوم که توضیح دادم (نسخه بتا و تست توسط شما) رو میتونیم انجام بدیم

**Comment by mohammad-ashrafi2020** [comment]
اوکی پیگیری میکنم اطلاع میدم بهتون

**Comment by mohammad-ashrafi2020** [comment]
مهندس با این ساختار درخواست رو ارسال کنید اوکیه : 
{
  "merchantConfigurationId": 63674,
  "serviceTypeId": 1,
  "localInvoiceId": 10054434,
  "amountInRials": 1000000,
  "localDate": "20211124 190337",
  "callbackURL": "https://codeyad.com/",
  "paymentId": "0"
}

**Comment by mohammad-ashrafi2020** [comment]
فقط خطای ip میده بعد اش اونم بخاطر اینه که ip روی سرور ست شده

**Comment by Sina-Soltani** [comment]
من تست کردم و جواب داد. البته پیغام خطا برای IP داد که خب مشخص هست برای چی هست

بنده پس همین REST رو پیاده‌سازی میکنم و یک نسخه بتا منتشر میکنم برای تست

سپاس از شما برای اطلاع رسانی

**Comment by Sina-Soltani** [comment]
درود
لطفا نسخه جدید بتا رو تست کنید
سپاس از شما

https://www.nuget.org/packages/Parbad/3.8.1-beta1

**Comment by mohammad-ashrafi2020** [comment]
سلام ، ممنون بایت وقتی که میزارید 
بله حتما تست اش میکنم اگر مشکلی داشت بهتون اطلاع میدم

**Comment by Sina-Soltani** [comment]
خطا در مرحله Request دریافت شد؟

**Comment by mohammad-ashrafi2020** [comment]
بله در مرحله Request بود
هم روی لوکال هم روی هاست

**Comment by Sina-Soltani** [comment]
متاسفانه این درگاه فوق العاده افتضاح هست چه در طراحی زیرساخت، چه در پیاده سازی و حتی در مستنداتش.

برای نمونه، هیچ اشاره ای نشده به وضعیت یا Status درخواست هایی که کاربر به درگاه ارسال میکنه 
در واقع باید مشخص باشه که اگر برای مثال IP مجوز استفاده رو نداره، یک کد مشخص برای این منظور به کاربر برگشت داده بشه
در صورتی که نه تنها هیچ کدی دریافت نمیشه، بلکه حتی در بعضی موارد بدنه پاسخ اصلا HTML هست به جای اینکه JSON باشه

من مجبور هستم StatusCode عجیب غریبی که اونا ارسال میکنن رو در متن پیام یعنی پراپرتی Message قرار بدم و شما دوباره روی هاست تست کنید و ببینید چه پیامی دریافت شده

**Comment by Sina-Soltani** [comment]
لطفا نسخه بتا دوم رو تست کنید و ببینید چه پیامی دریافت میشه
https://www.nuget.org/packages/Parbad/3.8.1-beta2
سپاس

**Comment by mohammad-ashrafi2020** [comment]
سلام قیمت رو 1 ملیون زدم این خطلا رو میده
{"error":{"code":1006,"message":"Invalid AmountInRials. (10000 < 1000000 < 50000)","args":{"amountInRials":1000000,"minAmount":10000.0,"maxAmount":50000.0}}}
---------------------------------------
قیمت رو 1,000 تومان زدم رفت تو درگاه ولی گفت
 "خطا شناسه تراکنش معتبر نمی‌باشد"
ولی توی دیتابیس خطلا ثبت نشده این خطلا مربوط به صفحه آسان پرداخته

**Comment by Sina-Soltani** [comment]
خطای شناسه تراکنش معتبر نمی باشد مربوط به شماره پیگیری هست که شما قرار دادید
آیا شماره پیگیری TrackingNumber تکراری ارسال کردید که در واقع قبلا استفاده شده باشه؟

اگر ممکنه لطفا شماره پیگیری رو بررسی کنید که آیا تکراری هست یا خیر و یک تست با مبلغ ۱۰۰۰۰ ریال یا به عبارتی همون ۱۰۰۰ تومان انجام بدید و ببینید چه نتیجه ای داره

**Comment by Sina-Soltani** [comment]
درود
آیا موفق به تست جدید شدید؟

**Comment by mohammad-ashrafi2020** [comment]
سلام ، ببخشید من یادم رفت بهتون اطلاع بدم 
نه مشکل هنوز وجود داره  - از شناسه تراکنش هم مطمعا هستم چون روی دیتابیس اصلی چکش اش کردم

**Comment by mohammad-ashrafi2020** [comment]
درود
مهندس من نسخه soap   آسان پرداخت رو شخصی سازی کردم و داره کار میکنه اگر صلاح میدونید تا pull request بزنم و جایگزین نسخه فعلی بشه

**Comment by Sina-Soltani** [comment]
درود

بله درخواست بفرستید تا جایگزین کنیم. چون بنده متاسفانه فرصتی برای توسعه ندارم
