### ISSUE TITLE
مستندات نسخه‌های قبلی

### ISSUE THREAD

**Issue by husseinjahan** [Sina-Soltani/Parbad#26]
سلام.
مستندات و آموزش‌های مربوط به نسخه‌های قدیم موجود نیست؟
من می‌خوام ازش تو یه پروژه قدیمی استفاده کنم.

**Comment by Sina-Soltani** [comment]
درود.
[لینک آموزش نسخه های یک](https://www.dotnettips.info/post/2880/%d9%be%d8%b1%d8%a8%d8%a7%d8%af-%d8%b1%d8%a7%d9%87%d9%86%d9%85%d8%a7%db%8c-%d8%a7%d8%aa%d8%b5%d8%a7%d9%84-%d9%88-%d9%be%db%8c%d8%a7%d8%af%d9%87%e2%80%8c%d8%b3%d8%a7%d8%b2%db%8c-%d8%af%d8%b1%da%af%d8%a7%d9%87%e2%80%8c%d9%87%d8%a7%db%8c-%d9%be%d8%b1%d8%af%d8%a7%d8%ae%d8%aa-%d8%a7%db%8c%d9%86%d8%aa%d8%b1%d9%86%d8%aa%db%8c-%d8%b4%d8%a8%da%a9%d9%87-%d8%b4%d8%aa%d8%a7%d8%a8)
