### ISSUE TITLE
Payment Refund

### ISSUE THREAD

**Issue by WatchDogsDev** [Sina-Soltani/Parbad#264]
Should I refund payment if user didn't send verify payment request after some amount of time ?
Or it's automatically handled by bank ?

**Comment by Sina-Soltani** [comment]
Not all gateways support the Refund process. Only a few of them support it.

If a user pays the bill inside the gateway and comes back to your website, you must verify it to check if the payment is valid or not.
If you didn't use the Verify method, then the payment will be refunded automatically by the gateway itself. It means no Refund process is needed anymore.

However I'm not completely sure about the 3th-party gateways such as ZarinPal if they refund the bill automatically or not.
You should ask them if they do this themselves or not.

**Comment by WatchDogsDev** [comment]
So I don't need to handle refunds.

Nice & clear answer! Thank you ;)
