### ISSUE TITLE
Method not found: 'Parbad.Internal.PaymentRequestResult Parbad.Internal.PaymentRequestResult.Failed(System.String, System.String)'.

### ISSUE THREAD

**Issue by mahdisky** [Sina-Soltani/Parbad#268]
هنگام ارسال درگاه به زرین پال نتیجه که برمیگرده این خطا  رو میده:

Method not found: 'Parbad.Internal.PaymentRequestResult Parbad.Internal.PaymentRequestResult.Failed(System.String, System.String)'.

* Package Name:  آخرین نسخه beta 2

**نوع برنامه وب**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
نسخه های بتا برای تست هستن و ممکن هست دچار مشکل باشند
لطفا آخرین نسخه غیر بتا رو نصب کنید
