### ISSUE TITLE
بررسی رسید دیجیتالی بانک سامان

### ISSUE THREAD

**Issue by rbsdotnet** [Sina-Soltani/Parbad#27]
سلام
آیا رسید دیجیتالی در بانک سامان توسط خود parbad چک می شود؟
![image](https://user-images.githubusercontent.com/49598914/59462578-44333f00-8e39-11e9-8aa4-0cead8ca556f.png)

یا اینکه باید در بخش callback نوشته شود؟

**Comment by Sina-Soltani** [comment]
درود.

پَرباد از مکانیزم تولید توکن به ازای هر پرداخت جهت ردیابی درخواست‌ها استفاده میکنه به همین دلیل به هیچ وجه کاربر امکان دستکاری و سو استفاده داده‌ها رو نداره. همچنین هر پرداخت توسط یک
boolean
در پایگاه داده علامت گذاری شده که پس از انجام هر گونه تراکنش چه موفق و چه غیر موفق، علامت گذاری میشه تا اون درخواست به هیچ وجه بیشتر از یکبار استفاده نشه.

**Comment by rbsdotnet** [comment]
درود فراوان بر شما 
که انقدر سیستم رو خوب و عالی طراحی کردین تا ما کاربرها راحت و بدون دغذغه استفاده کنیم 
واقعا ممنون جناب سلطانی
من توی تمام پروژه هام از پرباد شما استفاده میکنم
و درگاه های بانکی رو در عرض 1 ساعت نهایتا اجرایی میکنم
تشکر و سپاس فراوان از شما

**Comment by Sina-Soltani** [comment]
خواهش میکنم. خوشحالم که مورد قبول واقع شده.
