### ISSUE TITLE
وابستگی به معماری OWIN

### ISSUE THREAD

**Issue by najafzadeh1055** [Sina-Soltani/Parbad#270]
سلام؛ تشکر بابت پروژه خیلی خوب‌تون و نشر اون به صورت open source
امکان استفاده از پرباد بدون وابستگی به معماری OWIN در ASP.NET Web Forms هست؟

**Comment by Sina-Soltani** [comment]
درود
خواهش میکنم

خیر امکانش نیست.
با توجه به اینکه Parbad قابلیت استفاده در هر ۳ مدل پروژه وب مایکروسافت رو داره،‌ نیازمند به کانتکست وب استاندارد مایکروسافت هست تا در هر ۳ مدل پروژه وب قابلیت خواندن اطلاعات و کار با کانتکست وب رو داشته باشه
این امکان در پروژه‌های MVC و WebForms توسط Owin محیا میشه
