### ISSUE TITLE
Dependency Injection Error

### ISSUE THREAD

**Issue by AliSoltaniorg** [Sina-Soltani/Parbad#274]
Hello Dear

Framework: Asp.net 5
Package Version: Last Version

My Confoguration :

`           services.AddParbad()
                .ConfigureGateways(gateways =>
                {
                    gateways
                        .AddIdPay()
                        .WithAccounts(accounts =>
                        {
                            accounts.AddFromConfiguration(Configuration.GetSection("IdPay"));
                        });
                    gateways
                        .AddZarinPal()
                        .WithAccounts(accounts =>
                        {
                            accounts.AddFromConfiguration(Configuration.GetSection("ZarinPal"));
                        });
                })
                .ConfigureHttpContext(c => c.UseDefaultAspNetCore())
                .ConfigurePaymentToken(c => c.UseGuidQueryStringPaymentTokenProvider())
                .ConfigureStorage(c => c.UseDefaultStorageManager());`

I get an error while runtime:

System.AggregateException: 'Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: Parbad.IOnlinePayment Lifetime: Transient ImplementationType: Parbad.Internal.DefaultOnlinePayment': Unable to resolve service for type 
And four other errors

best regards

**Comment by Sina-Soltani** [comment]
Hi,

Read the tutorials.

**Comment by AliSoltaniorg** [comment]
نمیدونید مشکل از کجاست من تموم پکیج ها رو نصب کردم 
من حتی توضیحی در مورد فایل appsettings.json ندیم که بیام اکانت داخلش درج کنم

**Comment by Sina-Soltani** [comment]
آموزش و مثال های موجود رو نگاه کنید
همه چیز شفاف توضیح داده شده
