### ISSUE TITLE
خطا در تشخیص Method پرداخت

### ISSUE THREAD

**Issue by EliasTaghavi** [Sina-Soltani/Parbad#275]
Method not found: 'Parbad.Internal.PaymentRequestResult Parbad.Internal.PaymentRequestResult.Failed(System.String, System.String)'.

تنها درگاه تنظیم شده زرین پال بود در حالت سندباکس

**Package name and version**
Parbad 3.8.1

**Web application type:**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
مطمئن هستید که نسخه ۳.۸.۱ رو نصب کردید؟

**Comment by EliasTaghavi** [comment]
> درود مطمئن هستید که نسخه ۳.۸.۱ رو نصب کردید؟

بله

**Comment by Sina-Soltani** [comment]
لطفا از نسخه ۳.۸.۰ استفاده کنید
مشکل نسخه ۳.۸.۱ برطرف میشه و به زودی منتشر میشه
سپاس از شما برای اطلاع رسانی

**Comment by WatchDogsDev** [comment]
من هم در محیط Production به این خطا خوردم. لطفا اگر ممکنه 3.8.1 رو از حالت release خارج کنید که به اشتباه آپدیت توسط دوستان دیگه آپدیت نشه.

تشکر
