### ISSUE TITLE
استفاده پایگاه داده اس کیو ال در دات نت6

### ISSUE THREAD

**Issue by feryt20** [Sina-Soltani/Parbad#283]
**Bug description (wIthout specifiing the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**
در دات نت 6 به علت اینکه فایل استارتاپ وجود ندارد هنگام استفاده از کد زیر خطا میدهد

` const string connectionString = "Connection String";
                    var migrationsAssemblyName = typeof(Startup).Assembly.GetName().Name; // An Assembly where your migrations files are in it. In this sample the files are in the same project.

                    options.ConfigureDbContext = db => db.UseSqlServer(connectionString, sql =>
                    {
                        sql.MigrationsAssembly(migrationsAssemblyName);
                        sql.MigrationsHistoryTable("TABLE NAME");
                    });`

**Package name and version**
**نام و نسخه پکیج**
* Package Name: Parbad
* Version: 3.8.3

**Web application type:**
**نوع برنامه وب**
* ASP.NET CORE 6

**Comment by Sina-Soltani** [comment]
var migrationsAssemblyName = typeof(Program).Assembly.GetName().Name;
