### ISSUE TITLE
افزودن درگاه زیبال

### ISSUE THREAD

**Issue by mohammad-ashrafi2020** [Sina-Soltani/Parbad#284]
درگاه زیبال ، یک درگاه واسط مثل زرین پال ه ،  هر چی گشتم توی این ریپازیتوری پیداش نکردم  ، اگر مشکلی نداره و کسی توسعه اش نداده تا من انجام اش بدم

**Comment by Sina-Soltani** [comment]
بله در صورت تمایل میتونید توسعه بدید.
جهت مطالعه: https://github.com/Sina-Soltani/Parbad/wiki/Developing-a-new-Gateway
نمونه درگاه‌ها: https://github.com/Sina-Soltani/Parbad/tree/master/src/Parbad.Gateway

سپاس از شما

**Comment by mohammad-ashrafi2020** [comment]
شرمنده من  این [لینک](https://github.com/Sina-Soltani/Parbad/blob/master/CONTRIBUTING.md) رو خونده بودم و طبق این پیش رفتم  ( تازه لینکی که ارسال کردین رو باز کردم تا فرق داره)
اگر به مشکل می خوره تا طبق لینک بالا تبدیل اش کنم به یه پکیج جدا

**Comment by Sina-Soltani** [comment]
درود
فکر نمیکنم جایی اشتباهی انجام داده باشید.
خودتون متوجه اشتباه خاصی جایی شدید؟

**Comment by mohammad-ashrafi2020** [comment]
نه مشکلی که نداشت ، تست اش هم کردم اوکی بود

**Comment by Sina-Soltani** [comment]
امروز Merge رو انجام میدم.
سپاس از شما برای توسعه
