### ISSUE TITLE
تغییر آدرس سرویس بانک ملت

### ISSUE THREAD

**Issue by RezaAVS** [Sina-Soltani/Parbad#29]
اگر امکان تغییر ادرس توسط کاربر وجود داشته باشه خیلی عالی میشه
چون شرکت درگاه برای خرید بالای 50 میلیون رو ایچاد کرده و برای همین منظور ساختار Url متفاوتی برای اتصال به بانک ایجاد شده
به این صورت
https://bpm.shaparak.ir/pgwchannel2/startpay.mellat
/pgwchannel2/services/pgw
سپاس

**Comment by Sina-Soltani** [comment]
آیا مستندات خاصی هم در این مورد ارائه شده توسط بانک؟
لطفا اگر اطلاع دارید و یا خودتون در اختیار دارید اینجا قرار بدید.

سپاس.

**Comment by RezaAVS** [comment]
فقط Url ها تغییر کرده و این تغییر براساس درخواست شرکت بوده که باید سقف پرداخت بیش از 50 میلیون می شده
که برای این کار عدد 2 رو به 2 آدرس فئق اضافه شده
این بخش به درخواست شرکت بوده
اگر امکان تغییر آدرس توسط کاربر هم باشه عالیه، بعنی پیش فرض آدرس های شما باشه و در صورت نیاز کاربر بتواند آدرس های لازم رو تغییر بده

**Comment by Sina-Soltani** [comment]
البته به جای اینکه تغییر آدرس به عهده کاربر گذاشته بشه، بهتره که این کار به صورت خودکار صورت بگیره با توجه به مبلغ درخواست شده

**Comment by RezaAVS** [comment]
الان من سورس شما رو تغییر دادم و یه عدد 2 رو به سرویس ها اضافه کردم تا کار شرکت انجام بشه درصورت امکان این بحش رو هم اضافه کنید عالی
سپاس از شما

**Comment by Sina-Soltani** [comment]
بله حتما اضافه میشه.
سپاس از شما برای اطلاع رسانی

**Comment by Sina-Soltani** [comment]
آیا سقف تعیین شده برای استفاده از آدرس جدید دقیقا معادل ۵۰ میلیون و بیشتر از اون هست؟
>= 50,000,000 ?

**Comment by RezaAVS** [comment]
بله برای مبلغ بیش از 50 میلیون
همین ساختار رو هم بانک سامان و ملی هم دارن که آدرس جدید رو اعلام میکنن
همچنین در آدرس جدید باید کارت مشتری هم ارسال شود

**Comment by Sina-Soltani** [comment]
> همین ساختار رو هم بانک سامان و ملی هم دارن که آدرس جدید رو اعلام میکنن
> همچنین در آدرس جدید باید کارت مشتری هم ارسال شود

لطفا در صورت قطعی شدن خبر، اینجا عنوان کنید و یا اینکه لینک مربوطه رو بزارید
سپاس از شما

**Comment by RezaAVS** [comment]
چشم حتما
برای بانک ملت محرز شده و قطعی هست
برای بانک ملی و سامان اعلام میکنم

**Comment by RezaAVS** [comment]
با عرض سلام
ساختار بانک ملت تغییر کرده
برای کسب و کارهایی که بالای 50 میلیون تراکنش هست آدرس دوم کلا فعال میشه ئ اگر تراکنش زیر 50 میلیون داشته باشن باز از همان آدرس دوم استفاده میشه
یعنی اگر برای مجموعه ای ساختار آدرس دوم فعال شود چه بالای 50 میلیون چه زیر 50 میلیون ساختارآدرس دوم فعال می شود
---------------------------------
به نظرم شما یه Type برای Url ها در نظر بگیرین که کاربر نوع رو انتخاب کنه براساس نوع شما آدرس رو تغییر بدین
به جای اینکه رقم رو چک کنین
با تشکر

**Comment by Sina-Soltani** [comment]
لطفا آدرس خبر و یا مستندات ارائه شده رو بدین تا بتونم خودم شخصا چک کنم

چون در ازای ورژن‌های پابلیش شده باید پاسخگو بود و زیاد جالب نیست که هر یک روز یکبار ورژن جدیدی ارائه بشه و این کار تجربه کاربری بدی به جا میزاره

اگر امکان داره منبع اطلاعات رو اینجا قرار بدین تا بعد از اطمینان و آگاهی کامل نسبت به تغییرات صورت گرفته از جانب بانک، یک ورژن پایدار و قابل اطمینان ارائه بشه

تشکر از شما

**Comment by RezaAVS** [comment]
سلام
بله حق با شماست
و اینکه متاسفانه این موضوع به صورت تلفنی گفته شده و برای 2 شرکت از آدرس دوم فقط باید استفاده کرد
چه زیر 50 میلیون و چه بالای 50 میلیون
هیچ سندی وجود ندارد
چون مجوز برای این 2مجموعه گرفته شده است

**Comment by Sina-Soltani** [comment]
بنده هم هیچگونه اطلاعیه قابل فهم و معتبری ندیدم و تنها چیزی که در این باره میشه پیدا کرد یک متن کوتاه و نامفهوم از جانب بانک ملت بوده که فقط بین وب سایت‌های مختلف کپی پیست شده

به همین دلیل فعلا جهت اطمینان از عدم بروز مشکل، نسخه اخیر از دسترس خارج میشه تا اینکه خبر قطعی به دست برسه

تشکر از شما
