### ISSUE TITLE
دریافت خطای Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by drspam1991** [Sina-Soltani/Parbad#290]
سلام من در .NetCore در unit test برای initialize از این کد استفاده کردم:

`
var builder = ParbadBuilder.CreateDefaultBuilder()
                .ConfigureGateways(gateways =>
                {
                    gateways
                    .AddParbadVirtual()
                    .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
                })
                .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
                .ConfigureStorage(builder => builder.UseMemoryCache());
            
builder.Build();
`

و در ادامه از StaticOnlinePayment.Instance استفاده کردم و با صدا زدن متد RequestAsync پیغام Object reference not set to an instance of an object را دریافت میکنم. مشکل از کجا میتونه باشه؟
ممنون

**Comment by Sina-Soltani** [comment]
درود
خطایی که دریافت می کنید به احتمال زیاد به خاطر عدم وجود IHttpContextAccessor هست
علت اینه که شما دارید برای ابزاری تست مینویسید که نیاز به یک محیط اجرایی داره.
هدف شما از نوشتن این تست دقیقا چه چیزی هست؟ چون معمولا تست‌ها رو برای تست کردن کدهای خودتون باید بنویسید نه برای تست کردن ابزاری که دانلود یا نصب کردید.

**Comment by Sina-Soltani** [comment]
راهی به جز Mock وجود نداره. روش صحیح نوشتن تست برای عملیاتی که در اون از یک ابزار خارجی استفاده میشه، استفاده از Mock هست.
شما باید اینترفیس IOnlinePayment رو با Mock شبیه سازی کنید و برای این کار کافیه یک خروجی برای متدهای RequestAsnc و VerfyAsync تولید کنید.

**Comment by drspam1991** [comment]
بله درسته. ممنون از شما
