### ISSUE TITLE
ParbadDataContext migration

### ISSUE THREAD

**Issue by drspam1991** [Sina-Soltani/Parbad#291]
با سلام. من در .netCore دوتا sub project دارم به نام های Framework و Infrastructure. 
زیرپروژه Infrastructure به Framework وابسته هست.
در کلاس StartUp که در Framework قرار داره، پرباد رو به این شکل Config کردم:

```
services.AddParbad()
    .ConfigureGateways(gateways =>
    {
        gateways
        .AddParbadVirtual()
        .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
    })
    .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
    .ConfigureStorage(builder => 
    {
        builder.UseEfCore(options => 
        {
            options.ConfigureDbContext = db => db.UseNpgsql(DatabaseConfigurationExtensions.ConnectionString(dbEndpoint, dbName, dbUsername, dbPassword),
            sql =>{
                sql.MigrationsAssembly(migrationAssembly);
            });
        });
    });
```
متغیر migrationAssembly نام زیرپروژه Infrustructre هست.
در زیرپروژه Infrustructre هم Migration ها و DbContext های پروژه خودم قرار دارن. وقتی در مسیر Infrastructure دستور

dotnet ef migrations add AddParbad -c ParbadDataContext
 رو میزنم این خطا رو میگیرم:

No DbContext named 'ParbadDataContext' was found.

به هر دو زیر پروژه کتابخانه های زیر اضافه شدن:

        <PackageReference Include="Parbad.AspNetCore" Version="1.2.0" />
        <PackageReference Include="Parbad.Storage.EntityFrameworkCore" Version="1.3.1" />

**Comment by Sina-Soltani** [comment]
درود
موفق باشید
