### ISSUE TITLE
استفاده از EF6 به جای EF Core

### ISSUE THREAD

**Issue by ghostthug** [Sina-Soltani/Parbad#292]
سلام و خسته نباشید.

برای پروزه‌ای که از .netframework 4.8 استفاده می‌کنه و امکان استفاده از EF Core نیست، چطور میتونیم از Entity Framework به عنوان مخزن استفاده کنیم؟

**Comment by Sina-Soltani** [comment]
درود
پَرباد این قابلیت رو به شما داده که بتونید مخزن رو به هر روشی که میخواین پیاده‌سازی کنید.
اگر مخزن‌های فعلی به کار شما نمیخورن، کافیه خودتون اون رو پیاده‌سازی کنید.

[Using a Custom Storage](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-a-custom-storage)
[Sample](https://github.com/Sina-Soltani/Parbad.Samples/tree/master/Storage/CustomStorage)

در صورت تمایل میتونید حتی مخزنی که کدنویسی کردید رو به عنوان Pull Request ارسال کنید تا منتشر کنیم برای سایر مصرف کنندگان.

[کد مخزن EF Core](https://github.com/Sina-Soltani/Parbad/tree/master/src/Parbad.Storage/EntityFrameworkCore/src)
