### ISSUE TITLE
قابلیت تسهیم در درگاه بانک ملت

### ISSUE THREAD

**Issue by taheretalebii** [Sina-Soltani/Parbad#294]
سلام و وقت بخیر، تشکر از کدی که در اختیار گذاشتید. ایا سرویس تسهیم بانک ملت توی این پروژه دیده شده ؟ منظور متد bpCumulativeDynamicPayRequest هست ، و اگه هست نحوه استفاده  به چه صورتیه؟

**Comment by Sina-Soltani** [comment]
درود. خواهش میکنم
در این آموزش، توضیح داده شده
https://github.com/Sina-Soltani/Parbad/wiki/Gateways-specific-functions#mellat

**Comment by Mr-Mohammad** [comment]
من این ویژگی تست کردم و متاسفانه عمل نمیکند 
با دو متد AddMellatCumulativeAccount و SetMellatAdditionalData  تست کردم و متاسفانه عمل نمیکند
