### ISSUE TITLE
تغییر MerchantId در زمان اجرا

### ISSUE THREAD

**Issue by emdadgar2** [Sina-Soltani/Parbad#295]
سلام

چگونه می توان در درگاه زرین پال کد MerchantId را در زمان اجرا تغییر داد؟

سناریو این شکل است که کاربر کد MerchantId را در پروفایل کاربری خودش وارد می کند (که مسلما هر لحظه امکان اصلاح دارد) و سایر کاربران سایت برای ایشان (از طریق درگاه زرین پال) مستقیم پول واریز می کنند (مانند دونیت کردن)

بنابراین امکان ثبت درگاه کاربران در Startup را نداریم و باید در زمان اجرا -در لحظه ایجاد IOnlinePayment و قبل از ارسال درخواست به زرین پال- کد MerchantId را از بانک بخوانیم و در کامپوننت بی نظیر شما تنظیم کنیم

از برنامه خوبتان کمال تشکر را دارم

**Comment by Sina-Soltani** [comment]
درود
اطلاعات درگاه رو به صورت داینامیک ثبت کنید
https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-the-accounts-dynamically-using-a-custom-source

همچنین در هنگام ایجاد صورت حساب، نام اکانت بانکی رو ذکر کنید تا به صورت دقیق مشخص بشه کدوم اکانت برای صورت حساب فعلی باید در نظر گرفته بشه.

[Requesting a payment with a specific account](https://github.com/Sina-Soltani/Parbad/wiki/Invoice-Builder#requesting-a-payment-with-a-specific-account)
