### ISSUE TITLE
Refund زرین پال

### ISSUE THREAD

**Issue by emdadgar2** [Sina-Soltani/Parbad#296]
سلام

امکان refund در درگاه زرین پال ایجاد شده است. در صورت امکان پشتبانی آن را در پروژه خوبتان فراهم کنید

با تشکر

[مستندات](https://docs.zarinpal.com/paymentGateway/other/#refund)

**Comment by Sina-Soltani** [comment]
درود
سپاس برای اطلاع رسانی
