### ISSUE TITLE
نحوه بدست آوردن URL پرداخت

### ISSUE THREAD

**Issue by reza250prog** [Sina-Soltani/Parbad#298]
سلام خدمت شما اقای سلطانی 
داخل web api ها چطور میشه از این کد های شما استفاده کرد؟
ینی حالتی رو فرض کنید که ما اپ موبایل داریم 
خب اپ موبایل وقتی میخواد بره به درگاه بانک 
نیاز داره که بهش url بدیم و مرورگر رو برای کاربر باز کنه 
اما اون متد Transport شما ظاهرا این کارو نمیکنه یا حداقل من نمیدونم . ممنون میشم بگید چنین امکانی وجود داره که بعد از متد requestPayment به ما یک url بده که حالا هر کاری خواستیم با اون کنیم

**Comment by Sina-Soltani** [comment]
درود
منظور شما در واقع نحوه استفاده برای برنامه های سمت کلاینت هست. (موبایل، Angular و غیره)
لطفا نمونه پروژه Angular رو بررسی کنید همه چیز واضحه. در این نمونه پروژه، اطلاعاتی و نحوه هدایت به درگاه بانکی پس از انجام عمل request به سمت کلاینت ارسال میشن.

جهت آگاهی: البته مسلما فقط یک عدد Url دلیلی بر انجام شدن کار نیست. هر درگاه‌ بانکی با حالت مختلفی کار میکنه. یعنی اینکه شما ممکنه GET انجام بدید و یا اینکه ممکنه باید POST به همراه اطلاعات فرم انجام بدید. بنابراین علاوه بر داشتن آدرس، به یک فرم هم نیاز دارید که شامل مقادیر مختلفی به ازای هر درگاه هست. اگر Parbad به شما بگه که باید GET کنید، پس شما فقط به آدرس نیاز دارید. اگر به شما بگه باید POST کنید، بنابراین شما به فرم و اطلاعات داخل فرم که Parbad به شما میده هم نیاز دارید تا در سمت کلاینت استفاده بشن.

[کد سمت سرور](https://github.com/Sina-Soltani/Parbad.Samples/blob/master/Web/Parbad.Sample.Angular/Controllers/PaymentController.cs#L57)
[کد سمت کلاینت](https://github.com/Sina-Soltani/Parbad.Samples/blob/master/Web/Parbad.Sample.Angular/ClientApp/src/app/payment-request/payment-request.component.ts)

**Comment by reza250prog** [comment]
خیلی ممنون اقای سلطانی

**Comment by Sina-Soltani** [comment]
خواهش میکنم.

**Comment by reza250prog** [comment]
فقط یه مورد دیگه . برای اپ موبایل زمانی که مثلا باید form پست بشه چیکار میشه کرد ؟ چون اپ موبایل که نمیتونه فرم وب پست کنه .

**Comment by Sina-Soltani** [comment]
من متاسفانه در مورد برنامه نویسی موبایل اطلاعاتی ندارم. در اینترنت سرچ کنید و یا از افرادی که برنامه نویس موبایل هستن بپرسید.
هزاران برنامه موبایل هستن که پرداخت درون برنامه ای دارن حالا چه به بازار وصل بشن و چه مستقیم به درگاه بانکی.

**Comment by reza250prog** [comment]
تشکر
