### ISSUE TITLE
RefId & SaleReferenceId

### ISSUE THREAD

**Issue by RezaAVS** [Sina-Soltani/Parbad#30]
با سلام
فیلد های برگشتی از بانک مثل مقادیر 
RefId & SaleReferenceId
در چه بخشی قابل دستیابی می باشد؟

**Comment by Sina-Soltani** [comment]
اگر منظورتون بانک ملت هست،
RefId
فیلد مهمی نیست و صرفا جهت هدایت به درگاه بانکی استفاده میشه
اما شماره تراکنش بانکی و یا همون
SaleReferenceId
معادل
TransactionCode
در پَرباد است

**Comment by RezaAVS** [comment]
سپاس
