### ISSUE TITLE
CORS policy در وصل شدن به درگاه زرین پال

### ISSUE THREAD

**Issue by alisattarzadeh7** [Sina-Soltani/Parbad#301]
سلام وقتتون بخیر, ما در تلاشیم به درگاه زرین پال وصل بشیم که سمت فرانت رو به صورت فرم دیتا ارسال میکنم که اینم کدمه 
  const redirectToBank = (e) => {
        e.preventDefault();

        const formData = new FormData();
        formData.append('price', 100000);
        formData.append('gateway', 'ZarinPal');
        formData.append('bankAccountId', 2);
            axios.post('/InternalPayment/PayByFormData', formData.toString(), {
                headers: formData.getHeaders(),
            })
            
            بعد بک اند درخواست منو دریافت و ریدایرکت میکنه, که اینم کدیه که سمت بک اند درخواست منو هندل میکنه :‌
            [HttpPost("[action]")]
        public virtual async Task<IActionResult> Pay(SomeDto dto,
            CancellationToken cancellationToken)
{
	var request = await _onlinePayment.RequestAsync( invoice => (SomeParams...));
	 if (request.IsSucceed) return (request.GatewayTransporter.TransportToGateway());
}
که کدهای لاجیک و کنترل و ... رو حرف کردیم. و ما خروجی TransportToGateway رو توی پستمن می بینیم ولی جای دیگه نه
بعد از هدایت شدن به صفحه زرین پال بهم اررور cors میده که اینم اررورشه:
Access to XMLHttpRequest at 'https://sandbox.zarinpal.com/pg/StartPay/####' (redirected from 'https://mydomain/api/v1/InternalPayment/Pay) from origin 'http://localhost:8000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource

ما قبلا به درگاه pay.ir با همین روال وصل میشدیم و مشکلی نبود
ممنون میشم راهنماییم کنید 

Package Name: Parbad.Gateway.ZarinPal
 Version:  1.2.0

ASP.NET CORE

**Comment by alisattarzadeh7** [comment]
سلام مجدد
هدایت سمت بک اند انجام میشه که خروجی رو به فرانت میفرسته 
به این صورت که درخواستی که از فرانت میزنم رو ریایرکت میکنه به درگاه زرین پال و من درواقع کد html زرین پال رو دریافت میکنم

**Comment by Sina-Soltani** [comment]
من متوجه منظور شما نمیشم.
اگر هدایت به درگاه زرین پال سمت سرور انجام میشه، پس دیگه چیزی وجود نداره که بخواد دوباره به سمت کلاینت ارسال بشه !!! چون وقتی سمت ریدایرکت انجام میشه، کاربر مستقیما به درگاه زرین پال هدایت میشه.
اما شما میگید خروجی رو به فرانت میفرسته.

**Comment by alisattarzadeh7** [comment]
پروژه ما به صورت rest api هست و درخواست ها همه به صورت ajax فرستاده و دریافت میشه 
و بک اند وقتی درخواست منو دریافت میکنه منو به یه درخواست دیگه هدایت میکنه

**Comment by Sina-Soltani** [comment]
لطفا در قسمت نمونه پروژه‌ها،‌ پروژه Angular رو نگاهی بندازید.

**Comment by Sina-Soltani** [comment]
https://github.com/Sina-Soltani/Parbad/issues/298
