### ISSUE TITLE
Update ZarinPal to use the REST APIs

### ISSUE THREAD

**Issue by AliDeV7** [Sina-Soltani/Parbad#303]
درگاه زرین پال رو پیاده سازی کردم و همه چیز در حالت SandBox = true درست کار میکنه ولی زمانی که Sandbox = false میکنم با خطای

"درخواست مورد نظر يافت نشد." از تابع RequestAsync مواجه میشم!

از داخل کدهای ZarinPal که داخل پکیج بود دیدم کد خطای -11 برمیگرده از طرف درگاه بانک.

[داخل داکیومنت های زرین پال](https://docs.zarinpal.com/paymentGateway/error.html)، کد خطای -11 : "مرچنت کد فعال نیست لطفا با تیم پشتیبانی ما تماس بگیرید." است. 

من درگاه زرین پال رو به صورت مستقیم پیاده سازی کردم و این مرچنت کدی که داشتم رو امتحان کردم ولی مشکلی نداشت و فعاله

میدونین مشکل چیه؟

**Comment by Sina-Soltani** [comment]
> 
> [داخل داکیومنت های زرین پال](https://docs.zarinpal.com/paymentGateway/error.html)، کد خطای -11 : "مرچنت کد فعال نیست لطفا با تیم پشتیبانی ما تماس بگیرید." است.

لینکی که فرستادید ظاهرا صحیح نیست.


> 
> من درگاه زرین پال رو به صورت مستقیم پیاده سازی کردم و این مرچنت کدی که داشتم رو امتحان کردم ولی مشکلی نداشت و فعاله
> 
> میدونین مشکل چیه؟

تنها راهی که من میتونم درگاه حقیقی رو تست کنم اینه که اکانت داشته باشم.
در صورت تمایل میتونید اطلاعات اکانت زرین پال رو به آدرس زیر بفرستید تا تست کنم.
parbad@outlook.com

**Comment by AliDeV7** [comment]
ارسال کردم براتون

**Comment by Sina-Soltani** [comment]
> 
> من درگاه زرین پال رو به صورت مستقیم پیاده سازی کردم و این مرچنت کدی که داشتم رو امتحان کردم ولی مشکلی نداشت و فعاله

از کدوم نسخه برای پیاده‌سازی استفاده کردید؟ REST یا SOAP

**Comment by Sina-Soltani** [comment]
@AliDeV7 

نمونه کد REST که پیاده‌سازی شده باشه و جواب بده سراغ دارید؟ چون روشی که در مستنداتشون ارائه دادن ظاهرا کار نمیکنه و خطای ۵۰۰ میده
https://docs.zarinpal.com/paymentGateway/guide

**Comment by AliDeV7** [comment]
من با پکیج خودشون انجام دادم قبلا

فردا صبح نمونه کد هارو ارسال میکنم براتون الان دسترسی ندارم به کدها

**Comment by AliDeV7** [comment]
نمونه کد با Asp.Net Core 3.1 نوشتم

https://github.com/AliDeV7/Zarinpal-REST

**Comment by Sina-Soltani** [comment]
سپاس برای آپلود فایل‌ها.

آیا امکانش هست براتون از پشتیبانی درگاه زرین پال بپرسید که آیا دسترسی به درگاه تست و عملیاتی (حقیقی) رو برای آی پی های خارج از ایران قطع کردن یا نه؟ چون من دقیقا طبق مستنداتشون و یا همین مثالی که شما آپلود کردید انجام دادم برای درگاه تست. اما مرتبا خطای ۵۰۰ رو میگیرم که متاسفانه هیچ اطلاعاتی هم نمیفرسته که آدم بدونه مشکل از چی بوده.

**Comment by AliDeV7** [comment]
ببخشید دیر جواب دادم

تست کردم بدون مشکل لینک واریز رو بهم میده
توی کدوم قسمت ارور 500 میخورید؟

![image](https://user-images.githubusercontent.com/50456620/172533266-224744b5-44ca-4a0b-a0d9-cb268a4a732e.png)

**Comment by AliDeV7** [comment]
در ضمن من با فیلترشکن هم تست کردم ، فکر نمیکنم مشکل از این باشه، حالا به پشتیباتی پیام میدم ببینم چی میگن

**Comment by AliDeV7** [comment]
پشتیبانی زرین پال :

درگاه تست در حال حاضر غیر فعال می باشد
دسترسی برای ای پی ها خارجی و داخلی مشکلی نمی باشد

**Comment by Sina-Soltani** [comment]
سپاس از شما برای پیگیری.
پس مشکل همونطور که گفتم از سمت درگاه زرین پال بود و درگاه تست خراب بوده.

**Comment by AliDeV7** [comment]
خب الان باید چیکار کنیم؟ هنوز مشکل اصلی من برطرف نشده 

مشکل من با درگاه اصلی بود :(

**Comment by Sina-Soltani** [comment]
درود
نمونه کدی که شما قرار دادید، از آدرس ها و مقادیری داره استفاده میکنه که با مستندات فعلی خود زرین پال متفاوت هست.

مستندات فعلی:
https://docs.zarinpal.com/paymentGateway/guide

لطفا از پشتیبانی زرین پال بپرسید، کدوم API رو باید استفاده کرد و یا جدیدترین کدوم هست؟

**Comment by AliDeV7** [comment]
سلام

ببخشید من چند روز درگیر بودم، امروز یا فردا حتما انجامش میدم

از اون Packageی که زرین پال گذاشتن نمیخواین استفاده کنید؟

**Comment by Sina-Soltani** [comment]
کدوم پکیج؟

**Comment by AliDeV7** [comment]
[Zarinpal-sdk (0.0.8)
](https://www.nuget.org/packages/ZarinPal-SDK/)

**Comment by AliDeV7** [comment]
الان از طرف زرین پال بهم پیام دادن، گفتن که این لینک مستندات که دادید آخرین ورژن هست

اینم نمونه کد : 
https://github.com/erfanad1992/zarinpalasp.netcore

**Comment by Sina-Soltani** [comment]
پس در واقع چه پروژه‌ای که شما آپلود کردید و چه نوگتی که خود زرین پال درست کرده هر دو قدیمی هستن و چیزی که در مستنداتشون قرار دادن آخرین نسخه هست.
بسیار عالی. میخواستم تکلیف همین اول روشن بشه.
من این درگاه رو طبق مستندات جدید پیاده‌سازی میکنم و همون طور که گفتم نسخه بتا برای تست منتشر میکنم.
سپاس از شما

**Comment by AliDeV7** [comment]
ممنون از شما

منتظر شما هستم پس، فقط یه حدود میگید که چقدر ممکنه پیاده سازیش طول بکشه؟

کمکی از دستم برمیاد بهم بگید :)

**Comment by Sina-Soltani** [comment]
همین امروز منتشر میشه. اطلاع رسانی میکنم اینجا


> 
> کمکی از دستم برمیاد بهم بگید :)

در حال حاضر خیر. چون چیز ساده‌ای هست و زیاد زمان نمیبره. در هر صورت سپاس از شما

**Comment by Sina-Soltani** [comment]
![image](https://user-images.githubusercontent.com/10329804/173235357-cc894d62-c05e-44ab-846c-9ac8bca89f2e.png)
این درگاه ظاهرا امکان بازگشت پول رو هم فراهم کرده.
هر چند مشخص نیست که این مقدار Authorization از کجا قراره بیاد.
آیا در اطلاعاتی که این درگاه به شما مانند merchantID داده، چنین مقداری هم موجود هست؟

**Comment by AliDeV7** [comment]
داخل تنظیمات پنل نیست همچین مقداری

تیکت زدم

**Comment by Sina-Soltani** [comment]
پس لطفا اطلاع رسانی کنید اینجا، وقتی که زرین پال پاسخ قطعی داد.
سپاس

**Comment by AliDeV7** [comment]
از داخل پنل اصلی باید "از قسمت نشت های فعال روی ایجاد مجوز دسترسی کلیک کنید و مجوز (Authorization) خود را بسازید"

یدونه Bearer توکن میده

**Comment by Sina-Soltani** [comment]
پس قابل پیاده‌سازی هست.
سپاس برای پیگیری

**Comment by Sina-Soltani** [comment]
لطفا نسخه بتا رو تست کنید و اطلاع بدید
`Install-Package Parbad.Gateway.ZarinPal -Version 1.3.0-beta1`

**Comment by AliDeV7** [comment]
وقتی درگاه در حالت isSandBox = false هست ارور BadRequest دریافت میکنم

![Uploading image.png…]()

در حالت True هم این ارور رو دریافت میکنم

![Uploading image.png…]()

من با همون کدهای قبلی تست کردم، باید کد جدید بنویسم؟

**Comment by AliDeV7** [comment]
وقتی درگاه در حالت isSandBox = false هست ارور BadRequest دریافت میکنم
![image](https://user-images.githubusercontent.com/50456620/173285313-54fb2db9-3fad-4907-9a4e-90cd038d5faa.png)


در حالت True هم این ارور رو دریافت میکنم (Internal Server Error)
![image](https://user-images.githubusercontent.com/50456620/173285153-5d2e10ad-a866-4ffd-bcea-95ea3d768ae6.png)


من با همون کدهای قبلی تست کردم، باید کد جدید بنویسم؟

**Comment by AliDeV7** [comment]
return await _onlinePayment.RequestAsync(invoice =>
            {
                invoice
                    .SetAmount(Amount)
                    .SetCallbackUrl(CallbackURL)
                    .SetGateway(GatewayName.ToString());

                if(GatewayName.ToString().ToLower() == "zarinpal")
                {
                    var ZarinPalInvoice = new ZarinPalInvoice("تست", "a*******@gmail.com", "0937*******");
                    invoice.SetZarinPalData(ZarinPalInvoice);
                }
                //GenerateTrackingNumberAutomatically
                invoice.UseAutoIncrementTrackingNumber();
            });

**Comment by Sina-Soltani** [comment]
برای درگاه تست که همونطور که قبلا گفتم خطای internal server error میده و شما پس از مکالمه با زرین پال گفتید که درگاه تست غیرفعال هست.
اما درگاه اصلی رو من دیروز تست کردم و خطای زیر رو دریافت کردم:
Merchant is not active

آیا Merchant که دارید استفاده می کنید، فعال هست؟

**Comment by AliDeV7** [comment]
الان من با همون ورژن 1.2.0 درگاه زرین پال شما، وارد درگاه تست میشم! خیلی عجیبه فکر کنم کدهاشون خیلی مشکل داره

اونو هم پیگیری میکنم الان بهتون میگم

**Comment by Sina-Soltani** [comment]
ورژن 1.2.0 با همون تکنولوژی قدیمی SOAP کار میکنه و درگاه تست روی اون نسخه به درستی کار میکنه.
سپاس

**Comment by Sina-Soltani** [comment]
`Install-Package Parbad.Gateway.ZarinPal -Version 1.3.0-beta1`

نسخه بتا دوم رو تست کنید لطفا و ببینید Logger چه اطلاعاتی بهتون میده.
باید پیام‌هایی مانند

ZarinPal HTTP request failed. Check the status code {StatusCode} and the HTTP response content {ResponseContent}

رو پیدا کنید

**Comment by AliDeV7** [comment]
این اررور رو میده

![image](https://user-images.githubusercontent.com/50456620/173334209-f03fc493-e840-4df8-8ef3-909d2f84b282.png)

**Comment by Sina-Soltani** [comment]
> کاش شما توی این آپدیت کدهای خطای زرین پال رو هم آپدیت میکردین


بله خطا‌ها رو اضافه میکنم.
این درگاه هم مانند سایر درگاه‌ها متاسفانه به طرز فوق العاده آماتور تولید شده.
همونطور که در لاگ‌ها مشاهده می کنید، هنگامی که نتیجه درخواست HTTP موفق باشه، پراپرتی data در پاسخ،‌ از نوع آبجکت هست.
اما وقتی که نتیجه درخواست HTTP موفق نباشه، این پراپرتی از نوع آرایه میشه.
بنابراین مصرف کننده مجبور میشه کلاس کاملا متفاوت برای حالت خطا درست کنه.

**Comment by Sina-Soltani** [comment]
[پکیج خود زرین پال از نسخه قدیمی داره استفاده میکنه ن](https://github.com/Sina-Soltani/Parbad/issues/303#issuecomment-1153112686)

طبق این بحث، پکیج خودشون از نسخه جدیدشون استفاده نمی کنه. درسته؟

**Comment by Sina-Soltani** [comment]
بهتره ازشون بپرسید که احتمالش وجود داره که مرچنت شما برای نسخه جدید غیرفعال باشه؟
در نهایت اگر تکلیف مشخص نشه، بهتره که از نسخه دومشون استفاده کنیم که از آدرس زیر استفاده میکنه
https://www.zarinpal.com/pg/rest/WebGate/PaymentRequest.json

**Comment by AliDeV7** [comment]
> طبق این بحث، پکیج خودشون از نسخه جدیدشون استفاده نمی کنه. درسته؟

بله استفاده نمیکنه

> بهتره ازشون بپرسید که احتمالش وجود داره که مرچنت شما برای نسخه جدید غیرفعال باشه؟

تیکت زدم برا این

> در نهایت اگر تکلیف مشخص نشه، بهتره که از نسخه دومشون استفاده کنیم که از آدرس زیر استفاده میکنه

لینک برام باز نمیشه، 403 میگیرم

**Comment by AliDeV7** [comment]
اوکی ، حالا من بهتون خبر میدم که پشتیانی چی گفت

**Comment by AliDeV7** [comment]
آقا سینا مشکل از همون MerchantId بود، با پشتیانی صحبت کردم اینو درستش کردن برام

الان تست کردم نسخه بتا 3 رو بدون مشکل وارد درگاه شد ولی نسخه sandbox همونطور که میدونید ارور میخوره

**Comment by AliDeV7** [comment]
نمتونم وارد درگاه بشم با همچین اروری مواجه میشوم

![image](https://user-images.githubusercontent.com/50456620/173508472-358fe9b5-ad82-4acd-a5e7-76f8a5264e43.png)

![image](https://user-images.githubusercontent.com/50456620/173509167-842e41d8-868a-43c4-9299-208ddbc2bb5f.png)

**Comment by AliDeV7** [comment]
وقتی از بانک برمیگردم، به همچنین اروری برخورد میکنم، فکر میکنم مشکل از سمت کدهای شما باشه

![image](https://user-images.githubusercontent.com/50456620/173515362-a1fc442a-6dcc-4d77-b3bd-5834e312df88.png)

**Comment by AliDeV7** [comment]
وقتی هم SandBox = true یک ارور با پیغام خطای زیر میاد
![image](https://user-images.githubusercontent.com/50456620/173528846-c63494ca-173b-4fab-be2b-9a412df8d48b.png)

میدونم SandBox کار نمیکنه تو این حالت ، گفتم در جریان باشید

**Comment by Sina-Soltani** [comment]
درود
خطای مربوط به Sandbox در کدوم متد به وجود میاد؟
Request
Verify
?

**Comment by AliDeV7** [comment]
سلام

در متود Request

**Comment by Sina-Soltani** [comment]
مشکل در نوع فرمت متنی هست که زرین پال در حالت خطای ۵۰۰ ارسال میکنه.
به جای اینکه از نوع json باشه، از نوع html هست. این درگاه‌ها متاسفانه افتضاح هستن.
من یک نسخه الان منتشر میکنم برای رفع مشکل

**Comment by AliDeV7** [comment]
چی بگم والا، از جواب هایی که تیم پشتیبانی بهم میدن مشخصه که زیاد وارد نیستن به قضیه

باشه منتشر کردید بگید تست میکنم

**Comment by Sina-Soltani** [comment]
بتا جدید آماده هست
`Install-Package Parbad.Gateway.ZarinPal -Version 1.3.0-beta4`

**Comment by AliDeV7** [comment]
سینا جان حالت اصلی درست شد، پرداخت هم انجام شد. من هنوز حالت هایی که از بانک ارور دریافت میکنن رو تست نکردم.شما پیغام خطا و کد خطا رو هم داخل این آپدیت گذاشتید؟

![image](https://user-images.githubusercontent.com/50456620/173579908-6682461f-b775-4915-b320-8707cef2642f.png)

**Comment by Sina-Soltani** [comment]
بله پیام‌ها به روز رسانی شدن.
اگر تست موفقیت آمیز هست پس من الان نسخه نهایی رو منتشر کنم

**Comment by AliDeV7** [comment]
فردا بیشتر تست میکنم، مشکلی بود میگم بهتون
