### ISSUE TITLE
چگونه از SQLServer استفاده کنیم؟

### ISSUE THREAD

**Issue by asadsamarian** [Sina-Soltani/Parbad#31]
در مستندات این نمونه کد نوشته شده است.
```
services.AddParbad()
        .ConfigureStorage(builder => builder.UseParbadSqlServer("ConnectionString"));
```
 `UseParbadSqlServer `اما انگار  
وجود ندارد.
آیا جایگزینی دارد؟

**Comment by Sina-Soltani** [comment]
احتمالا مستندات ورژن های قدیمی رو شما مطالعه کردید
نحوه کار و نمونه کدهای به روز شده رو در همین گیت هاب دنبال کنید

[Storage - EntityFramework CORE](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-entityframework-core)
