### ISSUE TITLE
وقوع خطا هنگام برگشت دادن پول در درگاه زرین پال

### ISSUE THREAD

**Issue by mirshekarm** [Sina-Soltani/Parbad#314]
با سلام هنگام استفاده از متد RefundCompletlyAsync به خطای زیر برمیخورم :

JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Parbad.Gateway.ZarinPal.Internal.ZarinPalErrorModel' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path 'errors', line 1, position 23.

**Package name and version**

* Package Name: Parbad.ZarinPal
* Version: 1.3.0

**Web application type:**

* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
این نسخه ظاهرا باگ داره.
من متاسفانه تا حداقل ۲ هفته دیگه فرصتی برای برطرف کردن مشکل ندارم.
لطفا یا از نسخه قبلی استفاده کنید و یا باید صبر کنید.
سپاس

**Comment by emdadgar2** [comment]
این باگ در نسخه 1.4 هم مشاهده شد

**Comment by Sina-Soltani** [comment]
درود در چه زمانی؟

**Comment by emdadgar2** [comment]
هنگام verify کردن پرداخت این خطا را می دهد

**Comment by Sina-Soltani** [comment]
> هنگام verify کردن پرداخت این خطا را می دهد

این شرکت اخیرا ساختار پاسخ رو تغییر داده و همچنین درگاه تست رو غیرفعال کرده که باعث شده که تست برنامه دیگه امکان پذیر نباشه. متاسفانه کاری نمیشه کرد مگر اینکه کسی زحمت بکشه و پاسخی که از درگاه موقع وریفای دریافت میشه رو لاگ کنه تا من ببینم ساختار چه تغییری کرده.

**Comment by emdadgar2** [comment]
> > هنگام verify کردن پرداخت این خطا را می دهد
> 
> این شرکت اخیرا ساختار پاسخ رو تغییر داده و همچنین درگاه تست رو غیرفعال کرده که باعث شده که تست برنامه دیگه امکان پذیر نباشه. متاسفانه کاری نمیشه کرد مگر اینکه کسی زحمت بکشه و پاسخی که از درگاه موقع وریفای دریافت میشه رو لاگ کنه تا من ببینم ساختار چه تغییری کرده.

این آدرس را چک کردید؟

https://docs.zarinpal.com/paymentGateway/sandbox.html

**Comment by Sina-Soltani** [comment]
> این آدرس را چک کردید؟
> 
> https://docs.zarinpal.com/paymentGateway/sandbox.html

https://github.com/Sina-Soltani/Parbad/blob/master/src/Parbad.Gateway/ZarinPal/src/ZarinPalGatewayOptions.cs
