### ISSUE TITLE
how to send user data to IDPay

### ISSUE THREAD

**Issue by feryt20** [Sina-Soltani/Parbad#317]
سلام
اول متشکرم بابت این کتابخونه
میخواستم بپرسم چجوری اطلاعات کاربر  مثل تلفن و ایمیل و .. رو به ایدی پی بفرستم؟

گزینه ای برای این کار پیدا نکردم ولی توی زرین پال و بقیه هست

**Comment by Sina-Soltani** [comment]
درود
باید توسعه داده بشه تا این مقادیر در هنگام ارسال درخواست پرداخت، به بدنه درخواست اضافه بشن.
