### ISSUE TITLE
اصلاح داینامیک اطلاعات حساب درگاه

### ISSUE THREAD

**Issue by RezaAVS** [Sina-Soltani/Parbad#32]
سلام
من از این بخش استفاده کردم
gateways
        .AddMellat()
        .WithAccounts(accounts =>
        {
           accounts.Add<MellatAccountSource>(ServiceLifetime.Transient);
        });
اگر تغییری در اطلاعات درگاه در سیستم رخ دهد با فراخوانی کلاس
MellatAccountSource
اطلاعات دوباره بروزرسانی می شود؟

**Comment by Sina-Soltani** [comment]
بله
هر بار که دستور پرداخت اجرا بشه، اطلاعات درگاه هم از سرویس شما خوانده میشه
طول عمر سرویس دیگه بستگی به خودتون داره که
Transient
باشه یا
Singleton

**Comment by RezaAVS** [comment]
accounts.Clear();
            accounts.Add(new MellatGatewayAccount
            {
                Name = GatewayType.MellatGateway.Name,
                TerminalId = parbadGatewayViewModel.MerchentId.ToLong(),
                UserName = parbadGatewayViewModel.UserName,
                UserPassword = parbadGatewayViewModel.Password
            });

من برای اینکه بروزرسانی اطلاعات درگاه شود آنرا پاک میکنم
آیا لازم هست؟
یا اینکه این بروزرسانی خودکار هست؟
چون این
accounts
یک آرایه هست به نظرم باید قبلش پاک شود یا اینکه اگر اطلاعات با همان نام هست به صورت خودکار بروزرسانی شود

**Comment by Sina-Soltani** [comment]
خیر نیازی به پاک کردن نیست.

دستور
accounts.Clear()
برای پاک کردن اکانت نیست. بلکه برای پاک کردن روش‌های ثبت شده برای خواندن اطلاعات درگاه هست.

برای مثال

accounts.AddInMemory(account =>
{
  TerminalId = 123,
  UserName = "abc",
  UserPassword = "xyz"
});

accounts.Clear();

accounts.Add<MyMellatAccountSource>(ServiceLifetime.Transient);

در کد بالا ابتدا خواندن اطلاعات درگاه به روش دستی یا استاتیک ثبت شده
اما در خط بعدی دستور پاک کردن، همه روش‌های قبلی رو پاک میکنه
و در خط سوم روش خواندن از یک منبع سفارشی مثل دیتابیس ثبت میشه
