### ISSUE TITLE
IranKish Payment Gateway v3 (REST)

### ISSUE THREAD

**Issue by mrmashal** [Sina-Soltani/Parbad#322]
سلام و عرض ادب،

برای پروژه‌ای نیاز به درگاه پرداخت ایران کیش داشتم که نسخه فعلی پیاده سازی شده در پرباد پاسخگو نبود و نسخه جدید رو پیاده سازی کردم. این تیکت برای ارجاع پول ریکوئست مربوطه ایجاد شده.

فقط نکته ای که وجود داره با توجه به این که این درگاه از رمزنگاری نامتقارن هم استفاده میکنه و کلید عمومی مربوطه در قالب PEM در اختیار پذیرنده قرار میگیره، نیاز به خواندن کلید عمومی و استفاده در الگوریتم RSA هست که در دات نت 5 به بالا پیاده سازی شده. با توجه به این که در تارگت پرباد نسخه های پایین تر دات نت هم هست، لازم شد به پکیج Portable.BouncyCastle رفرنس ایجاد بشه که یکی از پکیج های شناخته شده برای رمزنگاری هست و گمان میکنم برای توسعه های آتی هم مفید باشه.

اگر از این نظر ایرادی وجود نداشته باشه، کد به صورت عملیاتی با موفقیت تست شده و میتونید ادغام کنید.

**Comment by Sina-Soltani** [comment]
درود
سپاس از شما برای توسعه
به زودی نگاه میکنم کدها رو.

**Comment by Sina-Soltani** [comment]
درود
لطفا مستندات بانکی مربوط به این نسخه که پیاده سازی کردید رو اینجا آپلود کنید و یا لینک اون رو قرار بدید.
سپاس

**Comment by mrmashal** [comment]
[IPG_TechnicalGuide.V9 [IRANKISH V3].pdf](https://github.com/Sina-Soltani/Parbad/files/9969787/IPG_TechnicalGuide.V9.IRANKISH.V3.pdf)

**Comment by mrmashal** [comment]
با سپاس از بررسی شما، به روز رسانی تست ها فراموش شده بود که انجام شد

**Comment by Sina-Soltani** [comment]
مشکلی نیست.
این درگاه به خاطر اینکه از یک کتابخانه استفاده کرده، به صورت مجزا ارائه میشه، چون سایر بخش های دیگه نیازی به اون کتابخانه ندارند.

به همین خاطر کدهای شما رو پس از مرج انتقال دادم به یک بخش دیگه ای. به زودی به همراه تغییراتی در قسمت های دیگه همشون منتشر میشن.

سپاس از شما برای توسعه.
موفق باشید

**Comment by msngithub** [comment]
با تشکر از زحمات شما ، راهنمایی میفرمایید نحوه استفاده به چه صورت هست ؟ چون توی ReadMe  که همون اول آورد فقط گفته TerminalId تنظیم بشه در حالی که بانک کد پذیرنده ، کلمه عبور و کلید عمومی میده جدا از کد پایانه ( TerminalId ) بقیه مقادیر کجا باید وارد بشه ؟
