### ISSUE TITLE
خطای Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by rh1376** [Sina-Soltani/Parbad#329]
**Bug description (wIthout specifiing the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**

سلام
من پکیج رو آپدیت کردم تا از متد ()GetZarinPalOriginalVerificationResult استفاده کنم و مشکلی که هست موقع ارسال درخواست به درگاه داخل پیامی که برمیگردونه خطای "Object reference not set to an instance of an object." رو میده.

![Capture](https://user-images.githubusercontent.com/42977125/205593701-2020a3da-9f6f-4e49-9586-831a8f290f37.PNG)

برای اطلاعات بیشترهم این خطا رو در قسمت پنجره دیباگ نمایش میده:

![Capture1](https://user-images.githubusercontent.com/42977125/205594291-89d294be-9c26-42ef-ba73-1f6c318df8c2.PNG)

**Package name and version**
**نام و نسخه پکیج**
* Package Name: Parbad.ZarinPal
* Version: 1.4.0

**Web application type:**
**نوع برنامه وب**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
احتمالا در آخرین به‌ روز‌ رسانی، دچار مشکل شده.
اصلاح میشه به زودی.
سپاس برای اطلاع رسانی.

**Comment by rh1376** [comment]
ممنون
آیا نمیشه به روشی در ورژن قبلی شماره کارت فرد رو دریافت کرد؟ فقط تو ورژن جدید امکان داره؟

**Comment by Sina-Soltani** [comment]
بله میشه.
قبل یا بعد از استفاده از دستور Fetch، خودتون مقادیری که زرین پال فرستاده رو بخونین.
نام مقادیری که ارسال میکنه رو یا داخل سورس کد پیدا کنید و یا اینکه مستندات خود زرین پال رو ببینید تا اسمشون رو پیدا کنید.

**Comment by rh1376** [comment]
سلام و خسته نباشید. مشکل هنوز برطرف نشده؟ما تو پروژه گیر این هستیم!

**Comment by Sina-Soltani** [comment]
درود
نسخه جدید منتشر میشه امروز.

**Comment by Sina-Soltani** [comment]
ذرگاه تست زرین پال ظاهرا دچار مشکلاتی هست و نمیشه تستی انجام داد.
لطفا متن خطا رو اینجا کامل کپی کنید (عکس نگیرید) تا من شماره خط مربوط به خطا رو ببینم. همچنین می تونید شماره خط رو خودتون اینجا اعلام کنید. در خطی که نوشته ZarinPalHelper.CreateReuqestResult ببینید چه شماره خطی نوشته شده.

**Comment by Sina-Soltani** [comment]
@erfandiakoo سپاس برای اطلاع رسانی

لطفا نسخه بتا رو نصب کنید ببینید مشکل برطرف شده یا خیر
`Install-Package Parbad.Gateway.ZarinPal -Version 1.4.1-beta1`

@rh1376

**Comment by rh1376** [comment]
سلام خسته نباشید.
