### ISSUE TITLE
به درگاه مجازی منتقل نمی شود!

### ISSUE THREAD

**Issue by asadsamarian** [Sina-Soltani/Parbad#33]
در مثال های انتقال به درگاه از خط زیر استفاده شده است:

`  return result.GatewayTransporter.TransportToGateway();`
ولی به نظر میاد که در آخرین نسخه این متد  عوض شده و خروجی هم ندارد:
`  result.GatewayTransporter.Transport();`
آیا نمونه ای که با آخرین نسخه پرباد و MVC باشه جایی هست؟

**Comment by Sina-Soltani** [comment]
پروژه بدون مشکل کار میکنه
بررسی کنید یکبار دیگه احتمالا جایی دارید اشتباه می‌کنید

[MVC Controller Sample](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Controllers/PaymentController.cs)
[All Samples](https://github.com/Sina-Soltani/Parbad/wiki/Samples)
