### ISSUE TITLE
خطا در درگاه پرداخت آسان پرداخت

### ISSUE THREAD

**Issue by sina-ssghm** [Sina-Soltani/Parbad#332]
سلام ممنون از پکیج خوبتون
من دارم درگاه آپ رو راه اندازی میکنم و با نسخه 3.9.0 پرباد کار میکنم.
اطلاعات درگاه هم به شکل زیر انجام شده:
`accounts.Add(new AsanPardakhtGatewayAccount
                {
                    Name = gateway.FaTitle,
                    UserName = "***",
                    MerchantConfigurationId = "***",
                    Password = "***",
                    IV = "***",
                    Key = "***",
                });`
تمامی مقادیر پر شده ولی زمان اجرا و درخواست انتقال به درگاه متد onlinePayment.RequestAsync خطای زیر رو میده:
Value cannot be null. (Parameter 'xml')

اگر نیاز هست بفرمایید تا مقادیر درگاه رو بفرستم تا بررسی کنید

**Comment by Sina-Soltani** [comment]
درود
مقادیر تنظیمات درگاه رو به آدرس زیر ارسال کنید تا تست کنم. البته اگر فقط با آی پی فروشنده کار بکنه که دیگه نیازی نیست بفرستید
parbad@outlook.com

**Comment by sina-ssghm** [comment]
خدمتتون ارسال شد

**Comment by Sina-Soltani** [comment]
درود
فایلی که ارسال کردید شامل Key و IV نبود
آیا این پارامترها رو در تنظیمات درگاه مقدار دهی کردید یا خیر؟

**Comment by sina-ssghm** [comment]
سلام بله مقدار دهی شده الان براتون میفرستم

موارد اعلامی به شرح ذیل حضورتان ارسال می گردد:

EncryptionKey

eYf3Q8OD4b6EexXgHxwboIkgU02mBf8JHz62438GvfY=

EncryptionVector

vViH8Oy1sYEOPdwhFccYzLrNzvfJnit9AEn/ALQLZZQ=



Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Sina-Soltani** [comment]
اطلاعات خصوصی رو نباید در مکان عمومی قرار بدید.
من پیام شما رو پاک میکنم. لطفا به ایمیلی که داده شد ارسال کنید.

**Comment by Sina-Soltani** [comment]
من تست رو انجام دادم. به من خطای زیر رو میده:
«سرور پذيرنده نامعتبر است»
اما اون خطای کدنویسی که شما گفتید رو نمیگیرم.

شما مطمئن هستید که تمام مقادیری که برای من ارسال کردید رو، در قسمت تنظیمات این درگاه وارد کردید؟

**Comment by sina-ssghm** [comment]
ممنون میشم به ایمیلم مقادیری که ست کردین رو بفرستید تا مقایسه کنم. تا جایی که من متوجه میشم همه چیز رو درست ست کردم

**Comment by Sina-Soltani** [comment]
ارسال کردم براتون قسمت تنظیمات این درگاه رو.

**Comment by Sina-Soltani** [comment]
من متاسفانه خطایی که شما ذکر کردید رو نمیگیرم که بخوام ببینم مشکل از کجاست.
البته این درگاه باید به روز رسانی بشه تا از API جدیدی که این شرکت فراهم کرده استفاده بشه. پیاده‌سازی فعلی، بر اساس تکنولوژی قدیمی اون شرکت هست که احتمالش هست درست کار نکنه.
یک پول ریکوئست برای این درگاه ارسال شده و شخصی زحمت کشیدن و پیاده‌سازی کردن. اما چون هیچ تستی انجام ندادن، اون پول ریکوئست رو من مرج نکردم.

**Comment by sina-ssghm** [comment]
ممنون از لطفتون و پیگیریتون

**Comment by Sina-Soltani** [comment]
خواهش میکنم
