### ISSUE TITLE
برگشت پول

### ISSUE THREAD

**Issue by rh1376** [Sina-Soltani/Parbad#333]
سلام و خسته نباشید و تشکر بابت پکیج خوبتون.
شاید سوالم به شما مربوط نباشه ولی با توجه به تجربه شما میپرسم که
امکان برگشت پول در سفارشاتی که لغو شده و یا مرجوع شده که شامل کل پول یا بخشی از مبلغ سفارش بوده هستش؟یعنی اینکه درگاه های بانکی چنین امکانی رو فراهم کردن که بشه مثلا بعد از چند روز کل مبلغ یا بخشی از مبلغ رو بشه برگردوند؟ البته نکتش اینه که بشه فرصت داشته باشیم تا چند روز بعد برگشت پول رو انجام بدیم
اگر هست کدوم بانک و چطوری میتونم با پکیج شما پیاده سازی کنم؟

**Comment by Sina-Soltani** [comment]
درود
تمام درگاه‌ها خیر، فقط تعدادی از اونها چنین امکانی رو فراهم کردن. درگاه‌هایی که در این پکیج وجود دارن که این قابلیت رو پشتیبانی میکنن شامل درگاه‌های زیر هستن:

فن آوا
سپهر
زرین پال
ملت
پارسیان
پاسارگاد
سامان

برگشت پول، فقط تا مدت زمان مشخصی پس از پرداخت قابل انجام هست که این زمان برای هر درگاه متفاوت هست. در مستندات هر درگاه، این مدت زمان نوشته شده.
