### ISSUE TITLE
خطای An error occurred در ورژن 1.2.0 

### ISSUE THREAD

**Issue by AliSeydnezhad** [Sina-Soltani/Parbad#339]
سلام و احترام

من از کتابخانه جهت پرداخت درگاه به پرداخت ملت در یک پروژه با نسخه های کتابخانه زیر استفاده کردم و روند ۴ سال بدون مشکل بود اما به تازگی خطای زیر نمایش داده می شه ( تغییری در پروژه داده نشده ) و با بانک هم که تماس گرفتم پاسخ دادن که درخواست به بانک نمی رسه که Log داشته باشند . خطا در پاسخ متد Payment.Request تولید می شه و هر آنچه که در پاسخ بود و ارزشی داشت من به عنوان یک رشته در همینجا قرار دادم بیشتر از این نمی دونستم چطور باید دقیق تر خطا را بررسی کنم . 
در ضمن پروژه امکان آبدیت به ورژن خیلی بالاتر که منجر به تغییر پیاده سازی بشه رو نداره و مربوط به یک خیریه مردم نهاد هست . 

Error Message :
`Message :An error occurred. | Status : Failed | OrderNumber : 246467 | Amount : 10000 | CallbackUrl : https://yaas.org.ir/Payment/Verify?paymentID=29565dd22e284c04a99584e0524a59b3`

Payment Link : 
`https://yaas.org.ir/Donate`

Package Name: Parbad 
Version: 1.2.0

Package Name:  Parbad.MVC
Version:  1.0.2

Type : ASP.NET MVC

**Comment by Sina-Soltani** [comment]
درود
نام درگاه رو ذکر نکردید در توضیحات این تیکت.

همچنین باید در نظر داشته باشید که ورژنی که اینجا ذکر کردید برای سال ۲۰۱۸ بوده و تا امروز مسلما خیلی تغییرات چه از جانب خود درگاه‌ها و چه از جانب این کتابخانه صورت گرفته.
بنابراین راهی جز آپدیت به آخرین نسخه ندارید،‌ چون اون نسخه ۲۰۱۸ اصلا وجود نداره که بخواد عیب یابی یا رفع ایراد بشه.

**Comment by AliSeydnezhad** [comment]
سلام مجدد 
در ابتدای توضیحات گفتم خدمتتون درگاه به پرداخت بانک ملت هستش . 

بله متوجه این داستان هستم . فقط این نکته آیا راهکاری وجود داره که بتونم متوجه بشم An error occurred به صورت جزئی تر مربوط به چه خطایی هست ؟ 

یا اینکه ورژن ۱.۲.۰ رو به چه ورژنی ارتقا بدم که نیازی به تغییر کد ها نباشه ؟ 

ممنون بابت وقتی که گذاشتید

**Comment by Sina-Soltani** [comment]
تا جایی که به یاد دارم اون نسخه قابلیت لاگ کردن رو نداشت.
فکر میکنم شما راه کاری جز آپدیت کردن به آخرین نسخه نداشته باشید.
