### ISSUE TITLE
MyVirtualGateway  برای مدت زیادی در حالت پندینگ می ماند.

### ISSUE THREAD

**Issue by asadsamarian** [Sina-Soltani/Parbad#34]
در هنگام ارسال به درگاه مجازی 
/MyVirtualGateway  
برای مدت زیادی در حالت پندینگ می ماند.
کسی در این زمینه تجربه ای داره؟

**Comment by RezaAVS** [comment]
اگر طبق آخرین نسخه پیش برید هیچ مشکلی پیش نمیاد
حتما آخرین نسخه رو مشاهده کنید
[فیلم آموزشی](https://youtu.be/zGGpf-Csj8Y)

**Comment by asadsamarian** [comment]
فیلم برای .netCore  هست.
من از MVC  استفاده می کنم.

**Comment by Sina-Soltani** [comment]
[ASP.NET MVC Sample](https://github.com/Sina-Soltani/Parbad/tree/master/samples/Parbad.Sample.Mvc)
[Video - ASP.NET MVC](https://youtu.be/gnofCtdPP5k)

هر کاری که تا الان کردید را حذف کنید و طبق فیلم و یا آموزش ها پیش برید تا به مشکلی برنخورید
[صفحه آموزش تمام مطالب در گیت هاب](https://github.com/Sina-Soltani/Parbad/wiki)

**Comment by asadsamarian** [comment]
مشکل اصلی من اینه که درگاه مجازی پاسخ نمی دهد.
به درگاه منتقل می شود. 
ولی من برای تست می خوام از درگاه مجازی استفاده کنم.

**Comment by Sina-Soltani** [comment]
لطفا یکبار پَرباد رو کامل پاک کنید از پروژه
طبق فیلم پیش برید
اگر موفق نشدید اعلام کنید تا بررسی کنیم

**Comment by asadsamarian** [comment]
دقیقا همان کد های مثال 
`Parbad.Sample.Mvc`
را در پروژه خودم اضافه کردم .  هنگام اجرا  خطای زیر رو  دارم:.


```
 Server Error in '/' Application.
Compilation Error
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately. 

Compiler Error Message: CS0012: The type 'Enum' is defined in an assembly that is not referenced. You must add a reference to assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
```

آیا باید netstandard اضافه شود؟

**Comment by Sina-Soltani** [comment]
پروژه شما احتمالا مشکلاتی در زیر ساخت تنظیمات داره
این روش رو امتحان کنید نتیجه رو اعلام کنید

فایل
.csproj
پروژه رو باز کنید با
notepad
و کد زیر رو اضافه کنید

```
<ItemGroup>
   <Reference Include="netstandard" />
</ItemGroup>
```

**Comment by asadsamarian** [comment]
یک پروژه جدید با الگوی .NetFramework4.8 ایجاد کردم.
web.config  را به شکل زیر تغییر دادم درست شد:

و کدهای مثال MVC  رو در آن کپی کردم.
اینجوری کار می کنه.

**Comment by Sina-Soltani** [comment]
پس به تنظیمات پروژه برید و 
Target Framework
رو به
.NET Framework 4.7.1
و یا نسخه‌های بالاتر تغییر بدید
اگر از ویژوال استودیو پیغام تغییر در تنظیمات دریافت کردید، بله رو انتخاب کنید
