### ISSUE TITLE
ایجاد اکسپشن اگه توکن اشتباه باشه

### ISSUE THREAD

**Issue by miladahmadi33** [Sina-Soltani/Parbad#340]
سلام خدا قوت.
هنگام بررسی
```
var invoice = await _onlinePayment.FetchAsync();
```
اگه payment token داخل url اشتباه باشه، برنامه دچار Exception میشه، آیا برای حل این مشکل باید try catch استفاده کنیم یا میشه از روش دیگه ایی استفاده کرد که برنامه در صورت اشتباه بودن payment token دچار exception نشه ؟

**Comment by Sina-Soltani** [comment]
درود
بله.
در صورتی که توکن دریافت نشه و یا صورت حساب در پایگاه داده پیدا نشه، خطا ایجاد میشه.

**Comment by miladahmadi33** [comment]
بزرگوار برای جلوگیری از خطا شما try catch رو پیشنهاد میکنید یا روش خاص دیگه ای رو در نظر گرفتید ؟

**Comment by Sina-Soltani** [comment]
خیر در حال حاضر روش دیگه ای نیست،‌ مگر اینکه در آینده تغییراتی ایجاد بشه که خطا صادر نشه.

**Comment by miladahmadi33** [comment]
تشکر فراوان.
آرزوی موفقیت بیشتر.
