### ISSUE TITLE
شماره کارت و نا همخوانی اطلاعات

### ISSUE THREAD

**Issue by SayyehBan** [Sina-Soltani/Parbad#343]
درود و خسته نباشید بابت درگاه های که پیاده کردید امکانش باشه تو پارسیان امکان بازگشت کارت هم بزارید و یک مسئله که هستش
من خواستم تو API ام بگم این درخواستی که داره از order بر میگرده به متعلق به این شماره پیگیری هستش

![2023-04-16_21-57-40](https://user-images.githubusercontent.com/38620223/232340104-bf38c58e-47ca-46fd-8b75-11f44dcd6b34.jpg)
همین طور در تصویر بالا مشاهده میکنید این شماره پیگیری ساخته شده و ارسال شده به سمت فرانت

و حالا کار تمام شده و درخواست از order بر میگرده
![2023-04-16_21-58-36](https://user-images.githubusercontent.com/38620223/232340158-03a404c0-909d-4447-9503-d2e9f9330db4.jpg)
همین طور که توجه میکنید شناسه ها یکی نیست من خواستم موقع برگشت درخواست برگشتی که شامل کدپیگیری و شماره مرجع و شماره کارت ذخیره کنم ولی دیدم هیچ چیز یکسانی در ارسال و برگشت نیست که معلوم کنم این رسید کدام مشتری هستش حساب کنید در آن واحد هزاران درخواست بابت پرداخت بره درگاه اون موقع چطور میتوانم بگیم این شماره پیگیری که مربوط به این درخواست مشتری هستش و الان اون درخواست برگشت خورده مربوط به کدام مشتری هستش 
![2023-04-16_21-59-24](https://user-images.githubusercontent.com/38620223/232340285-b0bf0593-1929-4da5-ac4a-cfc93951187d.jpg)
بررسی کردم موقع برگشت با اون که در سامانه هستش یکی هستش ولی مسئله که هستش تو برگشت  کد پیگیری ارسال و بازگشتی یکی نیست که با اون شناسه متطبق بدم و اطلاعات ذخیره کنم و بگه این مشتری که درخواست رفته و برگشته این شناسه درخواست ارسال و برگشت یکی هستش و خرید موفق بوده یا شکست خورده

**Comment by SayyehBan** [comment]
من از درگاه بانکی استفاده میکنم و درخواست order دارم از مرکز میگیرم که این خروجی بهم داده
{
  "payment": {
    "orderPayID": 7,
    "payID": 18,
    "trackingNumber": "7009497476817595832",
    "trackingNumberCenter": 7009497476817595000,
    "isPaid": true,
    "transactionCode": "737616345807",
    "gatewayName": "Parsian",
    "gatewayAccountName": "پارسیان",
    "message": "Payment is successful.",
    "insertDate": "2023-04-17T00:00:00",
    "insertTime": "17:59:56"
  },
  "order": {
    "trackingNumber": 7009497476817595000,
    "amount": 1000,
    "isPaid": true,
    "transactionCode": "737616345807",
    "gatewayName": "Parsian",
    "gatewayAccountName": "پارسیان",
    "message": "Payment is successful."
  }
}
ولی تو این خروجی از payment فیلد trackingNumberCenter این خروجی داده 7009497476817595000 و در خروجی order این فیلد هم trackingNumber این مقدار خروجی داده 7009497476817595000 ولی مقدار تو دستورات خط به خط دستورات Trace میکنم مقدار این هستش 7009497476817595832 ولی من دنبال مقدار دومی که از سرور بر میگرده یعنی این 7009497476817595000 ولی تو خط به خط Trace که انجام دادم مقدار این بود 7009497476817595832 ماندم بعد تمام شدن Trace این مقدار میده 7009497476817595000
این کد سی شارپ من
  [HttpGet]
        public async Task<IActionResult> Result()
        {

            OrderPay.OrderPayGet payment = null;
            var order = _orderRepository.GetOrder();

            if (order != null)
            {
                payment = new OrderPay.OrderPayGet
                {
                    TrackingNumber = StringExtensions.CleanString(order.TrackingNumber.ToString()),
                    TrackingNumberCenter = order.TrackingNumber == null ? 0 : Convert.ToInt64(order.TrackingNumber),
                    IsPaid = order.IsPaid,
                    TransactionCode = StringExtensions.CleanString(order.TransactionCode),
                    GatewayName = StringExtensions.CleanString(order.GatewayName),
                    GatewayAccountName = StringExtensions.CleanString(order.GatewayAccountName),
                    Message = StringExtensions.CleanString(order.Message),
                };
                await tbl_OrderPay.Insert(payment);
            }

            return Ok(new
            {
                payment = payment,
                order = order
            });
        }

**Comment by Sina-Soltani** [comment]
درود

متاسفانه من به خاطر نحوه نگراش، جمله بندی و توضیحاتی که اینجا عنوان کردید به هیچ وجه متوجه مشکل نشدم.
لطفا سعی کنید مشکل رو با جمله بندی و نگراش صحیح توضیح بدید تا بتونم بهتون کمک کنم.

موفق باشید.

**Comment by SayyehBan** [comment]
درود و عرض ادب من اینجا دارم درخواست میدم به بانک و بانک هم لینکی به من بر میگردانه برای پرداخت هزینه

![2023-04-17_23-56-40](https://user-images.githubusercontent.com/38620223/232602460-f1526d78-6886-4e51-9630-e2cbf5a8755a.jpg)
همین طور که در تصویر بالا مشاهده میکنید یک درخواست رفت و با شماره پیگیری "trackingNumber": "8669708862835380656" درخواستی برام به وجود امدم و حالا میام تو قسمت order میگم درخواستی که رفت موفق شد یا شکست رسید برای من برگردان

همین طور که در تصویر زیر مشاهده میکنید درخواست بنده که با این شماره پیگیری بود برگشت
"trackingNumber": "8669708862835380656",
![2023-04-17_23-59-10](https://user-images.githubusercontent.com/38620223/232602949-93f37265-da8f-4feb-940e-4ede9e318eb0.jpg)
ولی تو این برگشت یک شناسه هم تولید شده که از سمت بانک هستش
   "trackingNumber": 8669708862835380000
و درست همین شناسه من سعی کردم بگیرم نمیشه هیچ جوره انگار این شماره پیگیری
    "trackingNumber": 8669708862835380000

حکم شبح داره و وجود نداره در دستور مشاهده کنید این شماره پیگیری هستش 
  "trackingNumber": "8669708862835380656" 
ولی این شماره پیگیری نیست 
در این تصاویر زیر مشاهده کنید
![2023-04-18_00-02-41](https://user-images.githubusercontent.com/38620223/232604981-95d0fccd-c25b-445f-b157-404a32b5cda6.jpg)
این شماره پیگیری هستش
"trackingNumber": "8669708862835380656"
وقتی درخواست میخواد نشان بده
![2023-04-18_00-03-05](https://user-images.githubusercontent.com/38620223/232605214-c62770ce-00ad-4da7-80b8-084e0cec201c.jpg)
![2023-04-18_00-03-32](https://user-images.githubusercontent.com/38620223/232605294-e2d5e4a1-8c6c-4d48-ac26-71139ee31355.jpg)
همین طور که در تصویر آخر مشاهده میکنید این شماره پیگیری هستش
"trackingNumber": "8669708862835380656"
ولی این شماره پیگیری 
   "trackingNumber": 8669708862835380000
نیست خط به خط تمام دستورات Interface و Repository یعنی از شروع کار تا پایان کار این شماره پیگیری هستش 8669708862835380656 هستش ولی وقتی نشان میده شماره پیگیری 8669708862835380000 هستش ولی تو ارسال پارامتر نیست که من بتوانم بگیرم 
و یک خواهش دارم امکان گرفتن شماره کارت کاربر نیست که شماره کارتها رو هم بگیرم که بدانم از کدام بانک پردات انجام شده

**Comment by Sina-Soltani** [comment]
درود
آیا مشکلاتی که اینجا عنوان کردید مربوط به درگاه پارسیان هست یا مربوط به چیز دیگری هست؟
در توضیحاتی که ارائه دادید از Order و چیزهایی نام بردید که اصلا هیچ ارتباطی با این پکیج ندارن و کاملا مربوط به برنامه شما هست.
بنابراین من همچنان متوجه این مساله نمیشم.
آیا مشکلاتی که عنوان کردید با درگاه‌های دیگه هم به وجود میاد؟
لطفا برنامتون رو با درگاه مجازی تست کنید و اطلاع بدید.

**Comment by SayyehBan** [comment]
درود و عرض ادب و خسته نباشید

این دستور مشاهده میکنید
 public class OrderController : ControllerBase
    {
        private readonly IOrderRepository _orderRepository;

        Tbl_OrderPay tbl_OrderPay = new Tbl_OrderPay();
        public OrderController(IOrderRepository orderRepository)
        {
            _orderRepository = orderRepository;

        }
        /// <summary>
        /// نمایش نتیجه خرید
        /// </summary>
        /// <param name="trackingNumber">شماره میگیری</param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> Result(long trackingNumber)
        {
            OrderPay.OrderPayGet payment = null;
            var order = _orderRepository.GetOrder(trackingNumber);

            if (order != null)
            {
                payment = new OrderPay.OrderPayGet
                {
                    TrackingNumber = StringExtensions.CleanString(order.TrackingNumber.ToString()),
                    TrackingNumberCenter = order.TrackingNumber == null ? 0 : Convert.ToInt64(order.TrackingNumber),
                    IsPaid = order.IsPaid,
                    TransactionCode = StringExtensions.CleanString(order.TransactionCode),
                    GatewayName = StringExtensions.CleanString(order.GatewayName),
                    GatewayAccountName = StringExtensions.CleanString(order.GatewayAccountName),
                    Message = StringExtensions.CleanString(order.Message),
                };
                await tbl_OrderPay.Insert(payment);
            }

            return Ok(new
            {
                payment = payment,
                order = order
            });
        }
میشه گفت به کل دستور شما هستش و مقدار order همون مقدار بازگشتی از سمت IOrderRepository  شما هستش یعنی از دستورات شما هستش ولی چیزی ه عجیب هستش این هستش که من درخواست با یک شماره پیگیری میفرستم و اون درخواست تو Repository شما قرار میگیره و وقتی درخواست تمام میشه و قرار هستش order اون درخواست برگشتی نشان بده و بگه آیا این درخواست تمام شده چه جوابی داره خرید موفق بوده یا شکست خورده  همین طور در پست قبلی مشاهده کنید 
"trackingNumber": "8669708862835380656"
که من ایجاد میکنم این هستش در بالا ولی موقع اتمام از سمت بانک شماره پیگیری از سمت بانک به وجود میاد یعنی این
 "trackingNumber": 8669708862835380000
ولی موضوعی که در IOrderRepository  شما هستش و داره Order شما میبره نشان بده تا وقتی تو محیط کد هستم 
به کل این شناسه هستش 
"trackingNumber": "8669708862835380656"
ولی وقتی trace کد تمام میشه این شناسه نشان میده
 "trackingNumber": 8669708862835380000
چیزی که برام عجیب هستش از اول که داره IOrderRepository  شما مقدار که میخواد نشان بده تا موقع نمایش نهایی که میخواد return ok صورت بگیره داخل خودش order  شما مقدار
"trackingNumber": "8669708862835380656"
داره ولی وقتی return ok تمام میشه و JSON میخواد نشان بده مقدار "trackingNumber": "8669708862835380656" تبدیل میشه به  "trackingNumber": 8669708862835380000 فقط من ماندم این  "trackingNumber": 8669708862835380000 از کجا این میاره نشان میده من تا آخرین لحظه که Trace میکنم مقدار "trackingNumber": "8669708862835380656" دارم ولی وقتی تمام میشه این مقدار هم اضافه میشه  "trackingNumber": 8669708862835380000 که خیلی برام عجیب هستش این موضوع 
و خواهشی که داشتم تو موقع برگشت امکان برگشت شماره کارت هم هستش یا نه به بانک پارسیان اضافه کنید یا نه

**Comment by Sina-Soltani** [comment]
درود
شما همچنان دارید از Order و Repository صحبت می‌کنید.
همونطور که گفتم چنین چیزهایی اصلا در این پکیج وجود نداره.
