### ISSUE TITLE
تغییر مسیر های درگاه سپهر

### ISSUE THREAD

**Issue by pineportal** [Sina-Soltani/Parbad#345]
1  سرویس  توکن رو با ادرس به ادرس زیر تغییر دهید
https://sepehr.shaparak.ir:8081/V1/PeymentApi/GetToken            rest>
  soap>                https://sepehr.shaparak.ir:8082/Token.svc?wsdl

   2  فرم پست ارسالی به صفحه پرداخت رو  به ادرس زیر تغییر دهید
 https://sepehr.shaparak.ir:8080/Pay

   3  تایید تراکنش  رو بصورت ادرس های زیر ارسال بفرمایید
https://sepehr.shaparak.ir:8081/V1/PeymentApi/Advice           rest>
https://sepehr.shaparak.ir:8082/ipg.svc?wsdl    soap>                

مستندات درگاه سپهر یک تغییر کوچک داشته و سابدامین شاهپرک از مبنا به سپهر تغییر کرده

**Comment by Sina-Soltani** [comment]
درود و سپاس برای اطلاع رسانی.
لطفا لینک معتبر این خبر رو ارسال کنید.

**Comment by pineportal** [comment]
برای تمامی افرادی که از این درگاه استفاده میکنن ایمیل شده.
خودم هم چند روز پیش که کلا درگاه های سپهر قطع شده بود با پشتیبانیش صحبت کردم. گفتم از سمت شاهپرک هم مشکل پیدا کردن. چون قبلا به اسم مبا کار میکردن و اسم شرکت به سپهر پی تغییر کرده. سر همین موضع قطع شده بود.

**Comment by pineportal** [comment]
من چک کردم داخل سمپل های داخل سایت سپهر هم این مسیر ها درست شدن.

https://www.sepehrpay.com/module/

**Comment by Sina-Soltani** [comment]
در صورت امکان لطفا لینک مستقیم به این سمپل در وب سایت سپهر رو اینجا قرار بدید.

**Comment by pineportal** [comment]
https://www.sepehrpay.com/wp-content/uploads/2022/01/net-Ipg-rest.rar

**Comment by Sina-Soltani** [comment]
با توجه به تاریخ ثبت شده برای تغییر فایل های موجود در این سمپل، لینک ها بیش از یک سال هست که از مبنا به سپهر تغییر داده شده.
آیا اطلاع دارید که چرا بعد از یک سال به شما و بقیه اطلاع رسانی کردند؟

**Comment by pineportal** [comment]
تاریخش بررسی نکردم. کدهای خودم اصلاح کردم. شاید برای این باشه که من کدهام برای 6 یا 7 سال پیش هست.
