### ISSUE TITLE
استفاده از یک درگاه با  چند کلید

### ISSUE THREAD

**Issue by ShahramNo** [Sina-Soltani/Parbad#347]
سلام 
من در پروژه خودم چندین شعبه ایجاد کردم که هر شعبه میتونه درگاه پرداخت خودشو داشته باشه 
ایا امکانش هست من از طریق di اطلاعات درگاه  بر اساسid شعبه ارسال کنم؟
     
       public async Task AddAccountsAsync(IGatewayAccountCollection<SamanGatewayAccount> accounts)
            {
                    var settings = await _paymentGateway.GetSettingByBranchId(1);
                      accounts.Add(new SamanGatewayAccount
                {
                    MerchantId = settings.SamanPaymentMerchantId,
                    Name = collection.CollectionName,
                    Password = settings.SamanPaymentPassword
                });
            }

**Comment by Sina-Soltani** [comment]
درود
در صفحه آموزش و تنظیمات، بخش استفاده از چند اکانت رو بررسی کنید.

**Comment by ShahramNo** [comment]
ممنونم از پاسختون امکانش هست لینک صفحه مربوطه ارسال فرمایید ممنونم
