### ISSUE TITLE
شخصی سازی جداول دیتابیس

### ISSUE THREAD

**Issue by ebrahimkhodadadi** [Sina-Soltani/Parbad#349]
برای این که به _جداول Transaction و Payment_ **فیلد اضافه** بشه بهتر نیست به شکل **Partial** تعریف بشن؟ چون در IStorage برای IQueryable این دو جدول اگر جداول خودمون رو داشته باشیم به مشکل میخوریم

**Comment by Sina-Soltani** [comment]
درود
دیتابیس پرباد برای مصرف داخلی خود پرباد هست.
