### ISSUE TITLE
فرم های اجاکسی

### ISSUE THREAD

**Issue by RezaAVS** [Sina-Soltani/Parbad#35]
سلام
آیا در فرم هایی که به صورت اجاکسی فراخوانی می شود 
مییشه از پرباد استفاده کرد؟ به چه شکل؟

**Comment by Sina-Soltani** [comment]
درود.
بله.
روال کار هیچ تفاوتی با حالت عادی نداره و اهمیتی نداره که تکنولوژی و روشی که شما استفاده میکنین چه چیزی هست (وب پیج، انگیولار، اجاکس، اندروید و غیره) چون کاربر در هر صورت باید به سمت درگاه پرداخت هدایت بشه و همچنین پس از پرداخت باید به یک سرور یعنی همون وب سایت شما هدایت بشه. در واقع اگر برای مثال شما یک دکمه داشته باشید که با کلیک روی اون، کاربر باید به درگاه پرداخت بره، کافیه که برای اون دکمه رویداد کلیک تعریف کنید تا ریدایرکت بشه به آدرس وب سایت شما. برای مثال اگر شما درخواست پرداخت رو در آدرس
/payment/request
نوشته باشید، کافیه که بعد از کلیک روی دکمه، کاربر به همین آدرس ریدایرکت بشه و باقی کار کاملا مانند همون حالت عادی هست. یعنی کاربر هدایت میشه به درگاه پرداخت و برمیگرده به آدرس وب سایت شما و شما در اون مرحله
Verify
میکنین و دوباره همون صفحه مورد نظر خودتون رو نمایش میدین.

به صورت خلاصه

با استفاده از
window.location
کاربر به آدرس وب سایت شما که درخواست پرداخت رو اونجا نوشتین هدایت میشه
در نتیجه کاربر هدایت میشه به درگاه پرداخت

کاربر پرداخت رو انجام میده و به وب سایت شما برمیگرده (در نظر داشته باشید که شما در این مرحله همه چیز رو دارید، یعنی شماره تراکنش شماره رهگیری و غیره)

درخواست
Verify
در این مرحله انجام میدین

نتیجه رو به هر صورتی که دوست دارین میتونین دوباره نمایش بدین.
برای مثال میتونین، همون صفحه ای که کاربر داخلش بوده رو دوباره نشون بدین

**Comment by RezaAVS** [comment]
من کنترلری دارم که به صورت زیر می باشد

[HttpPost, AjaxOnly, ValidateAntiForgeryToken, ValidateModelState]
        public virtual async Task<IActionResult> Create(CreateCreditIncreaseViewModel creditIncreaseViewModel)

و داخل کد به صورت زیر نوشته شده:
return requestResult.GatewayTransporter.TransportToGateway()

الان به صورت اجاکسی به سمت درگاه ریداریکت نمی شود
به چه صورت باید به سمت درگاه ریداریکت بشه؟

**Comment by Sina-Soltani** [comment]
همونطور که گفتم
با استفاده از
window.location

window.location.href = "http://www.mywebsite.com/payment/create";

اطلاعاتی هم که در اکشن متد دریافت میکنید رو میتونید به صورت پارامتر ارسال کنید
window.location.href = "http://www.mywebsite.com/payment/create?Price=1000&Gateway=1";

**Comment by RezaAVS** [comment]
به اکشن ارسال میشه اما زمانی که این خط رو مینویسم به سمت درگاه ارسال نمیشه
return requestResult.GatewayTransporter.TransportToGateway()

**Comment by Sina-Soltani** [comment]
لطفا کد جاوا اسکریپت که برای هدایت کاربر نوشتید رو اینجا قرار بدید

**Comment by RezaAVS** [comment]
مشکل برطرف شد
ایراد از یک اسلش اضافی بود
تشکر از راهنمایی

**Comment by RezaAVS** [comment]
مشکل برطرف شد
ایراد از یک اسلش اضافی بود
تشکر از راهنمایی
