### ISSUE TITLE
استفاده از چند اکانت

### ISSUE THREAD

**Issue by ShahramNo** [Sina-Soltani/Parbad#350]
ممنونم از پاسختون امکانش هست لینک صفحه مربوطه استفاده از چند اکانت   ارسال فرمایید ممنونم
`              
_Originally posted by @ShahramNo in https://github.com/Sina-Soltani/Parbad/issues/347#issuecomment-1609794381_

**Comment by Sina-Soltani** [comment]
درود
شما باید تمام درگاه‌ها و اکانت های مربوطه رو در داخل کلاسی که نوشتید معرفی و ثبت کنید. همچنین این اکانت ها باید نام مشخصی داشته باشند که توسط پراپراتی Name قابل انجام هست.
سپس در هنگام ایجاد درخواست پرداخت، نام درگاه و نام اکانت مورد نظر رو باید مشخص کنید.

https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-the-accounts-dynamically-using-a-custom-source
https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-multiple-accounts-for-a-gateway
https://github.com/Sina-Soltani/Parbad/wiki/Invoice-Builder#requesting-a-payment-with-a-specific-account

**Comment by ShahramNo** [comment]
متشکرم

**Comment by Sina-Soltani** [comment]
خیر. در حال حاضر این مورد امکان پذیر نیست.
