### ISSUE TITLE
خطا در ارتباط با سپ(سامان)

### ISSUE THREAD

**Issue by ShahramNo** [Sina-Soltani/Parbad#354]
درورد .
زمانی که وارد درگاه سپ میشوم این ارور را دارم . و اصلا وارد صفحه دریافت اطلاعات نمیشه مستقیم این صفحه میاد
![Screenshot 2023-07-20 092907](https://github.com/Sina-Soltani/Parbad/assets/46740212/a2bbfb0a-1cf6-45da-9508-be25f75011a3)

این هم تنظیمات من هست:

     `
       builder.Services.AddParbad()
        .ConfigureGateways(gateways =>
        {

            gateways.AddSaman()
                .WithAccounts(source => source.Add<GatewaysAccounts>(ServiceLifetime.Transient));

            

        })
        .ConfigureHttpContext(httpContextBuilder => httpContextBuilder.UseDefaultAspNetCore())

    .ConfigureOptions(options =>
    {
      options.EnableLogging = true;
      
    })
    .ConfigureAutoIncrementTrackingNumber(options =>
    {
        options.MinimumValue = 1000;
        options.Increment = 1;
    })
    .ConfigureStorage(storageBuilder => storageBuilder.UseEfCore(options =>
    {
        string connectionString = builder.Configuration.GetConnectionString(name: "Web");
        var migrationsAssemblyName = typeof(BranchConfig).Assembly.GetName().Name; 

        options.ConfigureDbContext = db => db.UseSqlServer(connectionString, sql =>
        {
            sql.MigrationsAssembly(migrationsAssemblyName);
            sql.MigrationsHistoryTable("ParbadMigration");
        });

        options.DefaultSchema = "parbad";

        options.PaymentTableOptions.Name = "Payments";
        options.PaymentTableOptions.Schema = "parbad";

        options.TransactionTableOptions.Name = "Transactions";
        options.TransactionTableOptions.Schema = "parbad";
    }));`

       ` public async Task AddAccountsAsync(IGatewayAccountCollection<SamanGatewayAccount> accounts)
    {
        var payment = await _businessService.GetPaymentMethods(CancellationToken.None);
        var info = await _businessService.GetCurrentBusinessInfoForFront(CancellationToken.None);
        accounts.Add(new SamanGatewayAccount()
        {
            Name = info.Name,
            Password = payment.SamanGateway.Password,
            MerchantId = payment.SamanGateway.MerchantId,
            
       
        });
    }`

**Comment by ShahramNo** [comment]
ممنون اگه تغییری باشه خدمتتون اعلام میکنم

**Comment by pineportal** [comment]
این داکیومنت جدید درگاه هست و کاملا تغییر کرده
[SEP_OnlinePG_Merchant Document_Minimal_Current_3.2.pdf](https://github.com/Sina-Soltani/Parbad/files/12389013/SEP_OnlinePG_Merchant.Document_Minimal_Current_3.2.pdf)

**Comment by ShahramNo** [comment]
جناب مهندس مشخض هست تغییرات سپ چه زمانی انجام میشه؟

**Comment by Sina-Soltani** [comment]
@ShahramNo 
درود
آیا در صورت به روز رسانی و اعمال تغییرات بر روی این درگاه، شما قادر به تست نوگتی که ارائه میشه هستید؟

**Comment by ShahramNo** [comment]
> @ShahramNo درود آیا شما حسابی در این درگاه دارید؟ همچنین در صورت به روز رسانی و اعمال تغییرات بر روی این درگاه، شما قادر به تست نوگتی که ارائه میشه هستید؟

بله . مشکلی نداره

**Comment by Sina-Soltani** [comment]
@pineportal 
@ShahramNo 
درود
لطفا نسخه جدید رو تست کنید و نتیجه رو اعلام کنید
https://www.nuget.org/packages/Parbad/3.9.2-beta1

**Comment by msngithub** [comment]
سلام وقت شما بخیر ، من درگاه سامان گرفتم ولی اینجوری که متوجه شدم ساختار تغییر کرده و توی نسخه بتا شما گذاشتید ، نسخه بتا رو تست گرفتم اما خطای زیر از سمت درگاه میاد
"پارامترهای ارسال شده نامعتبر است.; آدرس سایت پذیرنده الزامی است"

**Comment by MR-MAP** [comment]
من الان چک کردم مثل اینکه هنوز حل نشده:
این نمونه پارامتر هایی که برای گرفتن توکن باید ارسال بشه : 
requset.AddParameter("undefined", "{\r\n  \"Action\": \"Token\",\r\n  \"TerminalId\": \"" + Termid + "\",\r\n  \"RedirectUrl\": \"" + RedirectURL + "\",\r\n  \"ResNum\": \"" + Resnum + "\",\r\n  \"Amount\": \"" + Amount + "\",\r\n  \"CellNumber\":\"" + CellNumber + "\"\r\n}", ParameterType.RequestBody);

**Comment by castell0riz0n** [comment]
بنظر میرسه بانک سامان تغییراتی داده که خودشون گویا بهش میگن KVC که باید یسری تغییرات کلی در احراز هویت داده بشه اصلا هم داکیومنت واضح و قابل فهمی براش ارائه ندادن و بنظر میرسه سایر بانک ها هم دارن همین کار رو میکنن

**Comment by Sina-Soltani** [comment]
fixed with #398
