### ISSUE TITLE
خطای در دسترسی به درگاه بانک پاسارگاد

### ISSUE THREAD

**Issue by cci-rdavoudi** [Sina-Soltani/Parbad#355]
**Bug description (wIthout specifiing the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**
سلام
در درگاه پاسارگاد با تنظیم کردن تنظیمات مورد نیاز همواره خطای: "فروشگاه ارسال کننده اطلاعات قابل شناسايي نيست." دریافت می کنیم. با تنظیمات فعلی در گذشته می توانستیم به درگاه متصل شویم ولی مدتی است که بدون تغییر دادن تنظیمات، از کار افتاده است. 

**Package name and version**
**نام و نسخه پکیج**
* Package Name:  Parbad
* Version: 3.4.0

**Web application type:**
**نوع برنامه وب**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
با توجه به اینکه شما این درگاه رو دارید، در صورت امکان پرس و جو کنید از درگاه که آیا تغییراتی در سیستمشون دادن یا خیر.
چون از سمت این پکیج هیچگونه تغییری اخیرا داده نشده.

**Comment by cci-rdavoudi** [comment]
سلام
متاسفانه جوابگو نیستند و جوابهای کلی میدن. من رو به آخرین داکیومنت شون ارجاع دادند. با توجه به اینکه شما اون رو پیاده سازی کردید برای شما ارسال می کنم شاید متوجه تغییراتی که دادند بشید. 
[1-__PEP_IPG_REST-13971020.Ver3_.00.pdf](https://github.com/Sina-Soltani/Parbad/files/12217802/1-__PEP_IPG_REST-13971020.Ver3_.00.pdf)

**Comment by Sina-Soltani** [comment]
Fixed with https://github.com/Sina-Soltani/Parbad/releases/tag/v3.10.0

**Comment by PooriaShariatzadeh** [comment]
@Sina-Soltani سلام و عرض ادب جناب سلطانی من ورژن 3.10 رو هم نصب کردم اما مشکل اونجاست که بانک پاسارگاد کلا روش پرایوت کی رو قطع کرده چند ماهی هست و از احرازش با نام کاربری و گذر واژه انجام میشه من ارتباط خوب و نزدیکی دارم با دوستان در پاسارگاد هر کمکی از من بر میاد بفرمایید تا به روز کنیم واقعا حیف این ریپاسیتوری به نظرم بهترین و کاربردی ترین ریپو ایرانی روی گیتهاب هست و واقعا حیفه اگر نتونیم به روز نگهش داریم
https://pep.co.ir/wp-content/uploads/2024/01/Parsa-IPG-2.pdf
یکی از دوستان هم یه ریپو زده برای این ورژن اما متاسفانه من نصب کردم خطا داره توی کالبکش
https://github.com/ezargar377/ParbabGateway.PasargadRest
