### ISSUE TITLE
SameSiteMode.Strict عدم بازگشت در صورت فعال سازی

### ISSUE THREAD

**Issue by KAJOOSH** [Sina-Soltani/Parbad#356]
سلام

احتراما وقتی کوکی را روی SameSiteMode.Strict تنظیم میکنم زمانی که از درگاه بازگشت داده می شود به صفحه لاگین منتقل می شود و کوکی identity شناسایی نمی شود.
راهکار رفع آن چی پیشنهاد می شود ؟!

**Comment by Sina-Soltani** [comment]
درود
باید در گوگل یا فروم‌های برنامه نویسی جستجو و پیگیری کنید. متاسفانه کمکی از دست من برنمیاد.
