### ISSUE TITLE
کانفیگ چندین ترمینال

### ISSUE THREAD

**Issue by Mr-Mohammad** [Sina-Soltani/Parbad#357]
سلام وقت بخیر 
من چندین ترمینال از بانک ملت دارم و ترمینال توسط کاربر باید انتخاب بشه چه پیشنهادی برای کانفیگ کردن این موضوع دارین ؟
مرسی

**Comment by Sina-Soltani** [comment]
درود

از قابلیت افزودن درگاه ها به صورت داینامیک میتونید استفاده بکنید. این قابلیت در قبل از ایجاد هر گونه درخواست بانکی، اطلاعات حساب درگاه رو در همون لحظه از کلاسی که شما معرفی کردید میگیره.

اما اگر منظورتون این هست که با توجه به ورودی اطلاعات کاربر، اکانت مورد نظر باید انتخاب بشه، خیر، در حال حاضر این امکان موجود نیست.

موفق باشید.

**Comment by Mr-Mohammad** [comment]
مچکرم از پاسختون من از بانک ملت نزدیک به 32 عدد ترمینال دارم 
من میخوام اگر کاربر که درخواست پرداخت داره بر اساس مثلا استانش من بیام ترمینال پرداختمو تنظیم کنم 
آیا مناسب کار من هست پرباد ؟ 
چه راهکاری پیشنهاد میدید ؟
مچکرم

**Comment by Sina-Soltani** [comment]
درود
همونطور که براتون توضیح دادم، میتونید از ویژگی حساب داینامیک استفاده کنید تا حساب های هر درگاه رو در زمان ایجاد درخواست پرداخت وارد کنید.
در هنگام وارد کردن این اطلاعات، نام حساب رو بسته به اون چیزی که نیاز دارید میتونید تنظیم کنید.
در نهایت هنگام ایجاد درخواست پرداخت و استفاده از متد Request ، میتونید علاوه بر مشخص کردن درگاه، نام حساب اون درگاه که باید استفاده بشه رو هم توسط متد UseAccount مشخص کنید.
