### ISSUE TITLE
Error On Create and migrate database

### ISSUE THREAD

**Issue by castell0riz0n** [Sina-Soltani/Parbad#36]
سلام و وقت بخیر . بعد از انجام تنظیمات اولیه در هر حالتی که تلاش میشه خطای
"Error: The new name 'transaction' is already in use as a object name and would cause a duplicate that is not permitted."}
دریافت میشه

![error](https://user-images.githubusercontent.com/28252141/62830732-a1285700-bc28-11e9-90c2-38b86c9d0852.png)

**Comment by Sina-Soltani** [comment]
درود.
آیا دیتابیسی که دارید برای پَرباد استفاده میکنین مشترکه با دیتابیس برنامتون؟

**Comment by castell0riz0n** [comment]
نه مشترک نیستش و یه دیتابیس خام و جدیده
![Db](https://user-images.githubusercontent.com/28252141/62831559-b4daba00-bc36-11e9-868a-b70927fa0553.png)

**Comment by Sina-Soltani** [comment]
برنامه مجددا الان تست شد و مشکلی نداره

لطفا کد مربوط به کانفیگ پَرباد رو اینجا قرار بدید تا بررسی کنیم
(در صورت نیاز میتونین کانکشن استرینگ رو خالی بزارید. فقط کد مهمه)

**Comment by castell0riz0n** [comment]
جناب سلطانی . من تشکر شدید میکنم ازتون بابت این پروژه و زحمتاتون و جوابی که زحمت میکشین و میدین .
کد کانفیگ

`            services.AddParbad().ConfigureGateways(gw =>
            {
                gw.AddMellat().WithAccounts(source =>
                {
                    source.AddFromConfiguration(Configuration.GetSection("Mellat"));
                });
                gw.AddSaman().WithAccounts(source =>
                {
                    source.AddFromConfiguration(Configuration.GetSection("Saman"));
                });
                gw.AddParbadVirtual().WithOptions(options => options.GatewayPath = "/MyVirtualGateway");

            }).ConfigureHttpContext(builder => builder.UseDefaultAspNetCore()).ConfigureStorage(builder =>
            {
                builder
                    .UseEntityFrameworkCore(ef => ef.UseSqlServer(Configuration.GetConnectionString("PaymentContext"),
                        options => options.UseParbadMigrations()))
                .ConfigureDatabaseInitializer(init =>
                {
                    // For creating
                    // init.CreateDatabase();

                    // For creating and migrating
                    //init.CreateAndMigrateDatabase();

                    // For deleting and recreating
                    // init.DeleteAndCreateDatabase();

                    // Define a custom database initializer
                    init.AddInitializer(async context =>
                    {
                        await context.Database.EnsureDeletedAsync();
                        await context.Database.EnsureCreatedAsync();
                        await context.Database.MigrateAsync();
                    });
                });
            });
        }`

![Parbad Config](https://user-images.githubusercontent.com/28252141/62831844-4861ba00-bc3a-11e9-8225-02c34201b40d.png)

**Comment by Sina-Soltani** [comment]
> جناب سلطانی . من تشکر شدید میکنم ازتون بابت این پروژه و زحمتاتون و جوابی که زحمت میکشین و میدین .

خواهش میکنم.

مشکل کد شما در قسمت
Initializer
است

دستور
context.Database.MigrateAsync()
در
EntityFramework CORE
خودش هم دیتابیس رو ایجاد میکنه و هم میگریت میکنه
بنابراین دیگه نباید دستور
context.Database.CreateAsync()
رو دیگه استفاده کنین
