### ISSUE TITLE
خطا در MyVirtualGateway

### ISSUE THREAD

**Issue by Mr-Mohammad** [Sina-Soltani/Parbad#368]
سلام پروژه بک من Asp.net core WebApi  هست و فرانت هم react 
همه چیز به درستی عمل میکند فقط زمانی ریدایرکت به آدرس MyVirtualGateway خطا رخ می دهد 
![image](https://github.com/Sina-Soltani/Parbad/assets/37229045/54d4b9f2-618a-4269-96fd-a5b3c94868c4)

پاسخ سرور به شرح زیر است :

```
{
  "data": {
    "isSucceed": true,
    "message": null,
    "transporter": {
      "type": 0,
      "url": "https://localhost:7079/MyVirtualGateway",
      "form": [
        {
          "key": "CommandType",
          "value": "request"
        },
        {
          "key": "trackingNumber",
          "value": "1000"
        },
        {
          "key": "amount",
          "value": "15000"
        },
        {
          "key": "redirectUrl",
          "value": "https://localhost:7079/api/Payment/verify?paymentToken=fbf25f23c32048ddab6c5c94e6a84470"
        }
      ]
    }
  },
  "isSuccess": true,
  "statusCode": 0,
  "message": "عملیات با موفقیت انجام شد",
  "trackingCode": "00000000-0000-0000-0000-000000000000"
}
```

**Comment by Sina-Soltani** [comment]
درود
نمونه پروژه انگولار رو دانلود و اجرا کنید.
درگاه مجازی رو انتخاب کنید و پرداخت رو بزنید.
اگر کار میکنه، پس مشکل جایی در برنامه شما هست که باید پیگیری کنید.
نحوه ریدایرکت و همه چیز در برنامه انگولار مشخص هست.

**Comment by Mr-Mohammad** [comment]
من کد های نمونه ای که قرار دادین نگاه کردم 
مشکلی که من دارم اینه که پس از ریدایرکت به MyVirtualGateway با خطای 404 میده 
تمام پارامتر ها هم به درستی ارسال میشه
