### ISSUE TITLE
خطا هنگام ثبت دستی در دیتابیس

### ISSUE THREAD

**Issue by ghayoori67** [Sina-Soltani/Parbad#369]
```
public async Task<IActionResult> Verify()
{

    
    var invoice = await _onlinePayment.FetchAsync();

    var verifyResult = await _onlinePayment.VerifyAsync(invoice);
    string PaymentPlanId = TempData["PaymentPlanId"].ToString();

    //if (verifyResult.IsSucceed)
    //{
    //    var userPayment = new UserPayment()
    //    {
    //        Amount = Convert.ToInt32(verifyResult.Amount),
    //        GatewayName = verifyResult.GatewayName,
    //        IsSucceed = verifyResult.IsSucceed,
    //        Message = verifyResult.Message,
    //        TrackingNumber = verifyResult.TrackingNumber,
    //        TransactionCode = verifyResult.TransactionCode,
    //        PaymentPlanId = Convert.ToInt16(PaymentPlanId)
    //    };

    //    await _userPaymentRepository.InsertAsync(userPayment);
        
    //}

    if (!IsEveryThinkOk(invoice.TrackingNumber))
    {
        var cancelResult = await _onlinePayment.CancelAsync(invoice, cancellationReason: "متاسفانه عملیات پرداخت ناموفق بود");
        return View("CancelResult", cancelResult);
    }

        return View(verifyResult);
}
```
درود برشما و خسته نباشید بابت توسعه این پکیج عالی.
در کد بالا من میخوام بصورت دستی توی دیتابیس خودم اطلاعات رو ذخیره بکنم ولی فقط وقتی کامنت میکنم برنامه درست کار میکنه و صفحه verify میاد بالا. ولی اگر از کامنت دربیارم با اینکه insert درست انجام میشه خطای 500 برمیگردونه.  نمیخوام از storage خود پکیج استفاده بکنم و بخاطر بیزینس برنامه باید از جداول خودمون استفاده کنم.

* Package Name:  Parbad 3.9.0 and Parbad.AspNetCore 1.3.0

* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
متوجه منظورم شما نمیشم.
کدی که اینجا قرار دادید هیچگونه ارتباطی با این پکیج نداره.
در این پکیج چیزی به اسم UserPayment یا UserPaymentRepositroy وجود نداره.

**Comment by ghayoori67** [comment]
درسته مهندس اون ریپازیتوری خودمه.  منظورم اینه میخوام شئ verifyResult رو ثبت دیتابیس خودم بکنم  ولی خطا میده. مجبور شدم کامنت کنم که صفحه verify نمایش بده

**Comment by Sina-Soltani** [comment]
دوست گرامی من چطور میتونم به شما کمک کنم زمانی که هیچ اطلاعاتی در مورد خطا، نوع و مکان خطا ارائه ندادید؟
