### ISSUE TITLE
درگاه پرداخت پاسارگاد

### ISSUE THREAD

**Issue by omidpirgazi92** [Sina-Soltani/Parbad#37]
سلام وقتتون بخیر درگاه پرداخت پاسارگاد برای دات نت کور  راه اندازی نشده ؟

`

Tracking number | 1002
-- | --
Amount | 2500
Gateway | PasargadGateway
Gateway account name |  
Is succeed | False
Message | Operation is not supported on this platform.

`

چون من همچین خطایی رو دارم دریافت میکنم.

**Comment by Sina-Soltani** [comment]
درود.
عذرخواهی می‌کنم بخاطر تاخیر در پاسخ
بررسی میکنم و اطلاع میدم.
موفق باشید.

**Comment by Sina-Soltani** [comment]
مشکل بررسی و رفع شد
اما بسته
Nuget
تا روز شنبه آماده و آپلود میشه

**Comment by PERSIANGOROUH** [comment]
سلام 
خسته نباشید 
ایا در برنامه امکان دریافت یا برداشت نیز وجود دارد و همچنین چگونه اتصال برقرار میشه ،من هر کاری کردم نتوانستم نصب و اجرا کنم

**Comment by Sina-Soltani** [comment]
> 
> 
> سلام
> خسته نباشید
> ایا در برنامه امکان دریافت یا برداشت نیز وجود دارد و همچنین چگونه اتصال برقرار میشه ،من هر کاری کردم نتوانستم نصب و اجرا کنم

خیر امکان برداشت یا دریافت وجود نداره.

در صورت نیاز به راهنمایی میتونید از صفحه راهنما و یا ویدیوهای آموزشی استفاده کنید
[آموزش ها و ویدیوها](https://github.com/Sina-Soltani/Parbad/wiki)

**Comment by PERSIANGOROUH** [comment]
باز تشکر از پاسخگویی شما اگر من در این درگاه شماره کارت و رمز دوم خودمو بزنم میتونم جابجایی وجه داشتع باشم و ایا با شماره حساب و بدون کارت باز انتقال وجه صورت میگیره یا نع

**Comment by Sina-Soltani** [comment]
> 
> 
> باز تشکر از پاسخگویی شما اگر من در این درگاه شماره کارت و رمز دوم خودمو بزنم میتونم جابجایی وجه داشتع باشم و ایا با شماره حساب و بدون کارت باز انتقال وجه صورت میگیره یا نع

فکر میکنم که شما شاید دقیقا متوجه کاربرد این ابزار نشده باشید
این ابزاری هست برای صاحبان وب سایت و برنامه نویسان جهت افزودن امکان پرداخت آنلاین به برنامه هاشون

در نتیجه چیزی مانند انتقال وجه یا برداشت وجه و اینگونه موارد وجود نداره

**Comment by PERSIANGOROUH** [comment]
من متوجه شدم من شرکت هولپیمایی دارم که میخوام این سورس را جایگزین کنم و از
لن استفاذه کنم . برای همین پرداخت نمایم .
در تاریخ 19 سپتامبر 2019 13:26، "eghbali" <notifications@github.com> نوشت:

**Comment by Sina-Soltani** [comment]
> 
> من متوجه شدم من شرکت هولپیمایی دارم که میخوام این سورس را جایگزین کنم و از لن استفاذه کنم . برای همین پرداخت نمایم

 موفق باشید
اگر سوالی داشتید در خدمت هستم

**Comment by Sina-Soltani** [comment]
@omidpirgazi1 
نسخه بتا جدید آماده شده
`Install-Package Parbad -Version 3.1.1-beta1`

لطفا بعد از تست، نتیجه رو اعلام کنید
موفق باشید

**Comment by omidpirgazi1** [comment]
> @omidpirgazi1
> نسخه بتا جدید آماده شده
> `Install-Package Parbad -Version 3.1.1-beta1`
> 
> لطفا بعد از تست، نتیجه رو اعلام کنید
> موفق باشید

متاسفانه در زمان درخواست خطای زیر رو میده

{
  "GatewayTransporter": {},
  "TrackingNumber": 1165,
  "Amount": {},
  "IsSucceed": false,
  "GatewayName": "PasargadGateway",
  "GatewayAccountName": null,
  "Message": "Data at the root level is invalid. Line 1, position 1.",
  "AdditionalData": {},
  "DatabaseAdditionalData": {}
}

**Comment by Sina-Soltani** [comment]
> 
> متاسفانه در زمان درخواست خطای زیر رو میده

آیا کلید رمزنگاری که از بانک دریافت کردید، فایل
XML
هست و یا نوع دیگه ای هست؟

**Comment by omidpirgazi92** [comment]
> > متاسفانه در زمان درخواست خطای زیر رو میده
> 
> آیا کلید رمزنگاری که از بانک دریافت کردید، فایل
> XML
> هست و یا نوع دیگه ای هست؟

نه فایل خاصی نیست کلا بانک به ما دوتا کد داده شماره پذیرنده هست و شماره ترمینال هستش که به ما دادند.

**Comment by Sina-Soltani** [comment]
باید کلید رمز نگاری هم از بانک دریافت کرده باشید چون برای تبادل اطلاعات بهش نیازمند هست

**Comment by Sina-Soltani** [comment]
پس اطلاعات را در فیلد اشتباه وارد کردید احتمالا

PrivateKey
کلید رمزنگاری

TerminalCode
شماره ترمینال

MerchantCode
شماره پذیرنده

**Comment by Sina-Soltani** [comment]
@omidpirgazi92 
آیا مشکل برطرف شده؟
