### ISSUE TITLE
توکن بانک پاسارگاد

### ISSUE THREAD

**Issue by mahdisky** [Sina-Soltani/Parbad#373]
سلام
برای استفاده از بانک پاسارگاد یک توکن نیاز هست که بر اساس نام کاربر و پسورد از کاربر دریافت میشه و توکن رو بانک میسازه، این هست توی parbad؟
ندیدم

**Comment by Sina-Soltani** [comment]
fixed with https://github.com/Sina-Soltani/Parbad/releases/tag/v3.10.0

**Comment by PooriaShariatzadeh** [comment]
@Sina-Soltani سلام و عرض ادب جناب سلطانی  مشکل اونجاست که بانک پاسارگاد کلا روش پرایوت کی رو کلا قطع کرده چند ماهی هست و از احرازش با نام کاربری و گذر واژه انجام میشه من ارتباط خوب و نزدیکی دارم با دوستان در پاسارگاد هر کمکی از من بر میاد بفرمایید تا به روز کنیم واقعا حیف این  ریپاسیتوری به نظرم بهترین و کاربردی ترین ریپو ایرانی روی گیتهاب هست و واقعا حیفه اگر نتونیم به روز نگهش داریم
https://pep.co.ir/wp-content/uploads/2024/01/Parsa-IPG-2.pdf
یکی از دوستان هم یه ریپو زده برای  این ورژن اما متاسفانه من نصب کردم خطا داره توی کالبکش
https://github.com/ezargar377/ParbabGateway.PasargadRest

**Comment by Sina-Soltani** [comment]
@PooriaShariatzadeh 
درود

آیا مستندات رسمی جدید که توسط خود پاسارگاد ارائه شده باشه موجود هست که اینجا قرار بدید؟

همچنین سپاس از شما بابت نظرتون در مورد این پکیج.
متاسفانه فرهنگ تشکر آنلاین (لایک و ستاره) در کشور ما همچنان جا نیوفتاده و توسعه دهندگان و مصرف کنندگان حتی این زحمت رو به خودشون نمیدن که یک ستاره یا لایک بدن به چیزی که دارن ازش کاملا رایگان استفاده میکنن، با وجود اینکه این کتابخانه اولین کتابخانه در ایران بود که این ایده رو در سال ۱۳۹۵ پیاده سازی و منتشر کرد، و باعث شد افراد دیگری این ایده رو برای سایر زبان های برنامه‌ نویسی و فریم ورک های دیگه پیاده سازی کنن.

**Comment by PooriaShariatzadeh** [comment]
سلامو درود مجدد سینا جان از اونجایی که خبری نشد از شما من از ریپاسیتوری یک کلون گرفتم و بر مبنای گیتوی قبلی پاسارگاد یک گیتوی جدید ایجاد کردم 
https://github.com/PooriaShariatzadeh/PasargadRest.Parbad.Gateway
فعلا کار خودم رو راه انداختم ولی خوشحال میشم بتونم کمک کنم آپدیت نگه دارید ریپاسیتوری اصلی رو
