### ISSUE TITLE
دریافت درگاه پرداخت

### ISSUE THREAD

**Issue by mottaghipour** [Sina-Soltani/Parbad#375]
سلام دوستان امیدوارم که همیشه سلامت باشید.

**Comment by mottaghipour** [comment]
خیلی عذر خواهی میکنم میدونم که اینجا ممکنه جاش نباشه ولی گفتم شما میتونید بهتر منو راهنمایی کنید.

من یک ربات تلگرام دارم و میخوام براش درگاه پرداخت بگیرم. وب سایتی ندارم که بگم مثلا این صفحه ی لندنینگه و کسب و کار من همچین چیزیه.

موقع اپلود مدارک از من آدرس وب سایت میخوان و نماد اعتماد الکترونیک. من باید چکار کنم؟ چه راه حلی برای من دارید عزیزان؟

**Comment by mottaghipour** [comment]
راهی هست که نیاز نباشه صفحه ی نمادین استفاده کنم؟ ساده تر درگاه پرداخت بگیرم؟

**Comment by Sina-Soltani** [comment]
درود
بدون داشتن یک وب سایت یا سرور،‌ چنین چیزی اصلا چطور امکان پذیر میتونه باشه؟ شما حتما باید یک وب سایت داشته باشید که درخواست و تایید پرداخت و ارتباط با درگاه بانکی رو برای شما میسر کنه.
وقتی از وب سایت صحبت میکنیم منظور این نیست که مثلا یک وب سایت فروشگاهی یا چیز خاصی باید داشته باشید، بلکه فقط یک آدرس و یک برنامه روی وب سایت که پرداخت رو برای شما در پشت صحنه مدیریت کنه.
اون برنامه میتونه با هر زبانی نوشته شده باشه اهمیتی نداره.
بانک با شما تماس برقرار میکنه و به شما میگه مثلا یک درخواست پرداخت الان بفرستید. برنامه سرور شما باید درخواست رو به درگاه بانکی ارسال کنه. سپس بانک چک میکنه ببینه آیا درخواست از آدرسی که شما داده بودید بهشون میاد یا خیر. بعد از اون مراحل پرداخت رو یک بار با شما چک میکنن و در صورت موفقیت تمام مراحل تا اتمام پرداخت، به شما اجازه استفاده رو میدن.

**Comment by mottaghipour** [comment]
> درود
> بدون داشتن یک وب سایت یا سرور،‌ چنین چیزی اصلا چطور امکان پذیر میتونه باشه؟ شما حتما باید یک وب سایت داشته باشید که درخواست و تایید پرداخت و ارتباط با درگاه بانکی رو برای شما میسر کنه.
> وقتی از وب سایت صحبت میکنیم منظور این نیست که مثلا یک وب سایت فروشگاهی یا چیز خاصی باید داشته باشید، بلکه فقط یک آدرس و یک برنامه روی وب سایت که پرداخت رو برای شما در پشت صحنه مدیریت کنه.
> اون برنامه میتونه با هر زبانی نوشته شده باشه اهمیتی نداره.
> بانک با شما تماس برقرار میکنه و به شما میگه مثلا یک درخواست پرداخت الان بفرستید. برنامه سرور شما باید درخواست رو به درگاه بانکی ارسال کنه. سپس بانک چک میکنه ببینه آیا درخواست از آدرسی که شما داده بودید بهشون میاد یا خیر. بعد از اون مراحل پرداخت رو یک بار با شما چک میکنن و در صورت موفقیت تمام مراحل تا اتمام پرداخت، به شما اجازه استفاده رو میدن.

ممنونم از شما بابت پاسخگویی.
متوجه هستم قربان. منظورم از وب سایت چیزی بود که جدیدا شنیدم. یکی میگفت حتما باید احراز بشه که شما چه کار اقتصادی دارید انجام میدید.

پس اگر من یک وب سرویس معمولی داشته باشم بدون ui موردی پیش نمیاد؟

**Comment by mottaghipour** [comment]
چجوری میتونم بدون ui نماد اعتماد الکترونیک بگیرم؟

**Comment by Sina-Soltani** [comment]
همونطور که گفتم من اطلاعات کافی در این مورد ندارم. فقط میدونم که شما باید اون وب سایت و آدرس رو داشته باشید چون در غیر اینصورت به هیچ وجه نمیشه.
در مورد اینکه کدوم درگاه بهتره، این رو باید از کسانی که تجربه کار با بانک های مختلف رو دارن بپرسید چون من با هیچکدوم کار نکردم.
از لحاظ تکنیکی فقط میتونم پیشنهاد کنم که بانک سامان بهتر کار کرده طی سال های اخیر.
همچنین پیشنهاد میکنم که نگاهی به درگاه های واسط پرداخت مثل زرین پال و بقیه هم بندازید چون دیگه نیازی به سرور یا وب سایت و این چیزا ندارید.

**Comment by mottaghipour** [comment]
> همونطور که گفتم من اطلاعات کافی در این مورد ندارم. فقط میدونم که شما باید اون وب سایت و آدرس رو داشته باشید چون در غیر اینصورت به هیچ وجه نمیشه.
> در مورد اینکه کدوم درگاه بهتره، این رو باید از کسانی که تجربه کار با بانک های مختلف رو دارن بپرسید چون من با هیچکدوم کار نکردم.
> از لحاظ تکنیکی فقط میتونم پیشنهاد کنم که بانک سامان بهتر کار کرده طی سال های اخیر.
> همچنین پیشنهاد میکنم که نگاهی به درگاه های واسط پرداخت مثل زرین پال و بقیه هم بندازید چون دیگه نیازی به سرور یا وب سایت و این چیزا ندارید.

مرسی که وقت گذاشتید.

پیگیری میکنم به یک نتیجه ای میرسم.
