### ISSUE TITLE
Saman Gateway files not the same in nuget.org and Github source code

### ISSUE THREAD

**Issue by Amirghk** [Sina-Soltani/Parbad#379]
**Bug description (wIthout specifiing the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**
Saman gateway files aren't the same in nuget.org (version 3.9.1) and latest on github (or release version 3.9).
for example the file SamanGatewayAccount.cs has the following implementation in github:

```C#
using Parbad.Abstraction;

namespace Parbad.Gateway.Saman
{
    public class SamanGatewayAccount : GatewayAccount
    {
        public string TerminalId { get; set; }

        public string Password { get; set; }
    }
}
```
an in  nuger.org it has the following implementation:
```C#
using Parbad.Abstraction;

namespace Parbad.Gateway.Saman
{
    public class SamanGatewayAccount : GatewayAccount
    {
        public string MerchantId { get; set; }

        public string Password { get; set; }
    }
}
```

**Package name and version**
**نام و نسخه پکیج**
* Package Name: Parbad
* Version: 3.9.0

**Web application type:**
**نوع برنامه وب**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
fixed with https://github.com/Sina-Soltani/Parbad/releases/tag/v3.10.0
