### ISSUE TITLE
درگاه پارسیان

### ISSUE THREAD

**Issue by omidpirgazi92** [Sina-Soltani/Parbad#38]
زمانی که از درگاه پارسیان بعد از پرداخت بازگشت میخورد به سایت خطای  زیر رو نشون میده
در صورتی که در زمانی که در درگاه دکمه انصراف رو میزنی و برمیگرده به سمت سایت همچین خطایی نمیده  و اوکی به نظر میرسه 

#asp.core  #درگاه_پارسیان

`
     {
  "TransactionCode": null,
  "TrackingNumber": 1159,
  "Amount": {},
  "IsSucceed": false,
  "GatewayName": "ParsianGateway",
  "GatewayAccountName": "گیمستان",
  "Message": "Invalid data is received from the gateway",
  "AdditionalData": {},
  "DatabaseAdditionalData": {}
}
`

**Comment by Sina-Soltani** [comment]
درود
بررسی میکنم

**Comment by Sina-Soltani** [comment]
آیا برای پروژه غیر از دات نت کور هم این مشکل به وجود میاد؟

**Comment by omidpirgazi92** [comment]
> آیا برای پروژه غیر از دات نت کور هم این مشکل به وجود میاد؟

**Comment by omidpirgazi92** [comment]
.
