### ISSUE TITLE
خطای 400 در بازگشت از درگاه بانک سامان به اپلیکیشن

### ISSUE THREAD

**Issue by msavarian** [Sina-Soltani/Parbad#380]
**Bug description (wIthout specifiing the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**

از پرباد برای اتصال به درگاه پاسارگاد استفاده میکنم و مشکلی وجود ندارد، ولی در درگاه بانک سامان، پس از پرداخت موفق و در بازگشت به اپلیکیشن خودم، خطای 400 زیر رخ می دهد

![image](https://github.com/Sina-Soltani/Parbad/assets/648468/866519a5-1057-4fc4-9981-01a601b9f197)

نکته ی مهمی که وجود دارد، آخرین تغییرات سورس کد مربوط به درگاه سامان که روی گیت هاب هست با آنچه در پکیج نوگت وجود دارد متفاوت است و بیلد درستی در نوگت قرار نگرفته است.

برای مثال در نوگت کلاس SamanGatewayAccount به شکل زیر وجود دارد

```
using Parbad.Abstraction;

namespace Parbad.Gateway.Saman
{
    public class SamanGatewayAccount : GatewayAccount
    {
        public string MerchantId { get; set; }

        public string Password { get; set; }
    }
}
```

اما در آخرین نسخه سورس کد همین کلاس به شکل زیر تعریف شده است

```
using Parbad.Abstraction;

namespace Parbad.Gateway.Saman
{
    public class SamanGatewayAccount : GatewayAccount
    {
        public string TerminalId { get; set; }

        public string Password { get; set; }
    }
}

```

**Package name and version**
**نام و نسخه پکیج**
* Package Name: Parbad
* Version: 3.9.0

* Package Name: Parbad.AspNetCore
* Version: 1.3.0

* Package Name: Parbad.Storage.EntityFrameworkCore
* Version: 1.4.0

**Web application type:**
**نوع برنامه وب**
* ASP.NET CORE 6.0

**Comment by Sina-Soltani** [comment]
fixed with #398
