### ISSUE TITLE
تغییر ساعت از UTC به ساعت ایران

### ISSUE THREAD

**Issue by msngithub** [Sina-Soltani/Parbad#381]
عرض سلام و ادب

احتراما به چه صورت میتوان ساعت هایی که در 2 تا جدول در دیتابیس درج می شود را تعیین کرد که ساعت ایران باشد نه UTC ؟

**Comment by Sina-Soltani** [comment]
درود.
۱) دیتابیس پربار برای مصرف داخلی خود پرباد هست نه برای مصرف توسط کاربر. پربار به اون دیتابیس جهت مدیریت تراکنش ها نیاز داره.
تاریخ و ساعت باید در هر سیستمی UTC باشه چون مصرف کننده ممکنه هاست و سرور رو در هر نقطه ای در دنیا تهیه بکنه.
تاریخ و ساعت محلی، باید فقط در هنگام مصرف یا استفاده تبدیل بشه از UTC به وقت محلی.

**Comment by msngithub** [comment]
اگر به عنوان Setting اضافه میشد به سیستم خوب بود چون ما در دیتابیس خودمون ساعت های ایران ذخیره میکنیم و مقایسه رکورد های پرباد با رکوردهای خودمون از دیتابیس یک مقدار سخت میشه ، میشه یک بخش مدیریتی واسه این جداول درست کنم جهت کنترل که اونجا تبدیل رو انجام بدم
با تشکر از شما
