### ISSUE TITLE
multi tenancy

### ISSUE THREAD

**Issue by ShahramNo** [Sina-Soltani/Parbad#389]
As our application is designed to serve multiple tenants, we need to ensure that each tenant can have a separate database connection. Therefore, I would like to know if Parbad currently supports or has plans to support the following features:

Multi-Tenancy: The ability to manage multiple tenants with isolated data and configurations within the same application instance.
Dynamic Connection Strings: The ability to dynamically set and switch database connection strings based on the tenant context.
If these features are not currently supported, are there any recommended workarounds or upcoming updates that might address these needs?

Thank you for your assistance. I look forward to your response.

Best regards,

**Comment by Sina-Soltani** [comment]
If the currently implemented Storage providers don't help you, you can implement the Storage yourself with your own conditions. 

Please take a look at Custom Storage.
