### ISSUE TITLE
جواب اشتباه از بانک سامان

### ISSUE THREAD

**Issue by castell0riz0n** [Sina-Soltani/Parbad#39]
سلام . وقت بخیر
وقتی در درگاه بانک سامان دکمه انصراف انتخاب میشه هنگام برگشت در متد وری فای جواب رو به صورت تصویر زیر دریافت میکنم

![samanProblem](https://user-images.githubusercontent.com/28252141/66026730-5202f200-e506-11e9-86ae-1ef4936792d0.jpg)

**Comment by Sina-Soltani** [comment]
درود
نتیجه تراکنش شما در متغیر
result
هست و نه در اینجایی که
breakpoint
گذاشتید

طبق مستندات، درون متد
Verify
شما این قابلیت رو دارید تا تراکنش ارسال شده به وب سایتتون رو بررسی کنید و در صورت لزوم اون رو کنسل کنید تا دستور تایید تراکنش به بانک ارسال نشه

هر چند که اگر کاربر در بانک پرداخت رو انجام نده و به وب سایت شما برگرده، مسلما هیچ درخواست تاییدی هم به بانک ارسال نمیشه

در نتیجه همونطور که گفتم، نتیجه تراکنش رو شما در متغیر
result
میتونید مشاهده کنید و در درون متد
Verify
شما قابلیت ردیابی تراکنش ارسال شده به سایتتون رو دارید و همچنین قابلیت کنسل کردنش رو

موفق باشید

**Comment by castell0riz0n** [comment]
مرسی از جواب سریعتون .  فقط یه نکته ای میمونه : اگر من بعد از وریفای شدن نتونستم  به هر نحوی فروش رو نهایی رو انجام بدم از متد ریفاند استفاده کنم؟

**Comment by Sina-Soltani** [comment]
بله میتونید تراکنش رو ریفاند کنید.
معمولا تا پایان روز جاری قابل انجام هست

هر چند که بهتر هست که تمام چک کردن های مربوط به بیزینس خودتون رو درون متد وریفای انجام بدید تا در صورت لزوم مستقیما تراکنش رو کنسل اعلام کنید و نیازی به ریفاند نداشته باشید

**Comment by castell0riz0n** [comment]
و یه سوال دیگه راجع به ریفاند
این متد ریفاندی که زحمت پیاده سازیش رو کشیدین در واقع همون
reverse transaction 
هستش یا همون از همون کنسلی تراکنش استفاده میکنه ؟
و دیگه اینکه اگر بعضی از خرید ها جریمه کنسلی داشته باشه آیا میشه از پرباد برای اونها استفاده کرد ؟

**Comment by Sina-Soltani** [comment]
> 
> 
> و یه سوال دیگه راجع به ریفاند
> این متد ریفاندی که زحمت پیاده سازیش رو کشیدین در واقع همون
> reverse transaction
> هستش یا همون از همون کنسلی تراکنش استفاده میکنه ؟

بله همون
reverse
هست

> و دیگه اینکه اگر بعضی از خرید ها جریمه کنسلی داشته باشه آیا میشه از پرباد برای اونها استفاده کرد ؟

در حال حاضر میشه مبلغ رو به صورت کامل برگشت داد
اما در نسخه جدیدی که در حال آماده‌سازی هست، میشه بخشی از مبلغ رو برگشت داد

**Comment by castell0riz0n** [comment]
عالیه و ممنون از شما
و اینکه فکر میکنید چقدر زمان میبره تا آماده سازیش  و نهایی شدنش ؟

**Comment by Sina-Soltani** [comment]
> عالیه و ممنون از شما
> و اینکه فکر میکنید چقدر زمان میبره تا آماده سازیش و نهایی شدنش ؟

آماده سازی نسخه جدید احتمال داره بین امروز و در نهایت تا یکشنبه صورت بگیره

البته در نظر داشته باشید که برگشت بخشی از مبلغ به خریدار، توسط سایر بانکها پشتیبانی نمیشه و فقط بانک سامان این قابلیت رو داره

**Comment by castell0riz0n** [comment]
متشکر از شما و راهنمایی هاتون .

**Comment by Sina-Soltani** [comment]
> 
> 
> متشکر از شما و راهنمایی هاتون .

خواهش میکنم

**Comment by Sina-Soltani** [comment]
لطفا نسخه جدید بتا رو تست کنید و نتیجه رو گزارش بدید

`Install-Package Parbad -Version 3.1.1-beta2`

موفق باشید

**Comment by castell0riz0n** [comment]
در مورد تغییراتش یا چیزایی که بهش اضافه شده داکیومنت رو بروز رسانی میکنید ؟

**Comment by Sina-Soltani** [comment]
بله داکیومت در حال بروز رسانی هست

البته چیزی حذف نشده و حالات قبلی همچنان ساپورت میشه

همچنین شما میتونید برای برگشت مبلغ به خریدار از متدهای
RefundCompletely
RefundSpecificAmount
استفاده کنید

**Comment by castell0riz0n** [comment]
گفتید که 
RefundSpecificAmount
فقط برای بانک سامان قابل استفاده هستش دیگه ؟

**Comment by Sina-Soltani** [comment]
بله
