### ISSUE TITLE
Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

### ISSUE THREAD

**Issue by moortezaa** [Sina-Soltani/Parbad#393]
توضیح خطا
توسط این کد درخواست پرداخت را ایجاد کردم
```
var gateWayResult = await _onlinePayment.RequestAsync(invoice =>
{
    invoice.UseAutoIncrementTrackingNumber()
        .SetAmount(new Money(250000))
        .SetCallbackUrl("https://127.0.0.1:8970/PaymentCallBack")
        .SetGateway("ZarinPal")
        .UseAccount("زرین پال")
        .SetZarinPalData(string.Format(_localizer["Reserving {0} from doctor {1}"].Value, visitDateTime.ToPersianDateString("yyyy/MM/dd dddd HH:mm:ss"), doctor.DisplayName), mobile: user.PhoneNumber);
});
```

اما در `gateWayResult `مقدار `status `برابر `false `هست و مقدار `message `برابر `"Unexpected character encountered while parsing value: <. Path '', line 0, position 0."` می باشد
پیام خطا نشان دهنده وجود یک تبدیل از `json string` به `object` توسط کتابخانه NewtonSoft.Json می باشد. اما در ورودی های ارائه شده من هیچ جا کاراکتر `>` را استفاده نکردم و نمی دانم در کجای کتابخانه parbad این متن ساخته شده.

> احتمال دارد که خطا به دلیل مقدار بازگشتی از زرین پال به کتابخانه پرباد باشد زیرا من مقدار sandbox را در تنظیمات اکانت برابر true قرار دادم

تنظیمات سرویس پرباد
```
services.AddParbad()
    .ConfigureGateways(gw =>
    {
        gw.AddZarinPal().WithAccounts(s => s.Add<GatewayAccounts>(ServiceLifetime.Transient));
        gw.AddSaman().WithAccounts(s => s.Add<GatewayAccounts>(ServiceLifetime.Transient));
    })
    .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
    .ConfigureStorage(builder => builder.UseMemoryCache())
    .ConfigureOptions(options =>
    {
        options.EnableLogging = true;
    })
    .ConfigureAutoIncrementTrackingNumber(options =>
    {
        options.MinimumValue = 1000;
        options.Increment = 1;
    }); 
```

تنظیم اکانت زرین پال:
```
accounts.Add(new ZarinPalGatewayAccount()
{
    AuthorizationToken = "123456",
    MerchantId = "123",
    Name = "زرین پال",
    IsSandbox = true
});
```

**Package name and version**
**نام و نسخه پکیج**
Parbad (3.9.1)
Parbad.AspNetCore (1.3.0)
Parbad.Gateway.ZarinPal (1.4.1)
Parbad.Storage.Cache (1.3.1)

نوع برنامه وب
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
درگاه زرین پال همیشه مشکلات برای توسعه دهندگان داشته و یا تغییراتی داشته که توسعه دهنده را وادار به تغییر کدها کرده.
به همین دلیل مدت زیادی هست که هیچ توسعه ای برای این درگاه در کتابخانه Parbad صورت نگرفته. و اصلا معلوم نیست که وضعیت فعلی به چه صورت هست. 
ظاهرا نسخه غیر بتا میگن کار میکنه انگار.
