### ISSUE TITLE
استفاده از context دیگر

### ISSUE THREAD

**Issue by itsoli91** [Sina-Soltani/Parbad#395]
با سلام
آیا امکانش هست از یک contex دیگر به غیر از ParbadContex استفاده کرد؟
هدف من اینه یه table های که ساخته میشه دسترسی داشته باشم برای table navigation و یا Foreign key.
آیا راهی برای این موضوع هست ؟

**Comment by Sina-Soltani** [comment]
درود
پایگاه داده پَرباد برای مصرف داخلی خود پَرباد هست.
هر گونه اطلاعات لازم و مهم بانکی در هنگام ارسال درخواست ها به شما برگشت داده خواهد شد که میتونید اونها رو ذخیره و استفاده کنید.
