### ISSUE TITLE
واحد پول در PayPing

### ISSUE THREAD

**Issue by ShahramNo** [Sina-Soltani/Parbad#396]
در PayPing تمام مقادیر ورودی بر اساس تومان هست . اما واحد اصلی ریال هست و این مقدار زمانی که به درگاه انتقال داده مشود به تومان تبدیل میشود . 
در قسمت فراخوانی میشه  .SetAmount(currentOrder.TotalAmount/10) استفاده کرد. ولی در وریفای به مشکل میخوره . آیا راهی برای این مشکل هست؟

**Comment by Sina-Soltani** [comment]
درود
متوجه منظور شما نمیشم.

پَرباد هیچ تبدیل یا پردازش واحد پولی انجام نمیده، و هر مقداری که بهش بدید همون رو به درگاه مورد نظر ارسال میکنه.

واحد پول درگاه هر چیزی که باشه همون رو براش ارسال کنید.

**Comment by ShahramNo** [comment]
مشکل اینجاست که اگر همزمان با چند درگاه بانکی کار کنیم، همه آن‌ها مبلغ را به ریال دریافت می‌کنند، در حالی که پی‌پینگ واحدش تومان است. وقتی مبلغی به پی‌پینگ ارسال می‌شود، آن را به تومان می‌گیرد. به عنوان مثال، اگر مبلغ ۲۰,۰۰۰ ریال باشد، هنگام ارسال به پی‌پینگ به‌عنوان ۲۰,۰۰۰ تومان در نظر گرفته می‌شود.

به نظرم نیاز است که تبدیل ریال به تومان و برعکس به درستی انجام شود.

این پاسخ واحد فنی است: ما در APIهای خود تمامی مبالغ ورودی را به تومان دریافت می‌کنیم.

**Comment by Sina-Soltani** [comment]
درود
پَرباد هیچگونه تبدیل نرخ و واحدی انجام نمیده.
بنابراین در هنگام استفاده از متد SetAmount با توجه به اینکه آگاه هستید از اینکه درگاه پی پینگ قراره انتخاب بشه، مقدار رو باید خودتون تبدیل بکنید.

**Comment by ShahramNo** [comment]
توی متد وریفای چی؟ اونجا به مشکل میخوره جون با هم نمیخونه

**Comment by Sina-Soltani** [comment]
اگر در متد وریفای به مشکلی برخورد لطفا خطا رو اعلام کنید.
موفق باشید
