### ISSUE TITLE
سوال در خصوص نحوه جلوگیری از استفاده مجدد از یک رسید تولید شده توسط بانک در درگاه سامان

### ISSUE THREAD

**Issue by dehghani-mehdi** [Sina-Soltani/Parbad#399]
براساس توضیحات مندرج در تیکت شماره #319 و همچنین کدهای نوشته شده در سورس کد پرباد، 2 سوال همچنان برای من بدون پاسخ مانده است:

1. براساس مستندات درگاه بانک سامان و در جهت جلوگیری از Double Spending لازم است که مقدار RefNum قبل از Verify تراکنش بررسی شود، اما براساس توضیحات (و همچنین سورس کد پروژه) ظاهرا مبنای تشخیص کد ارجاع است و نه RefNum، که به نظر صحیح نیست.
2. با فرض تصحیح مورد بالا (یا درست بودن کدهای جاری پروژه)، چنانچه Storage بر روی memory تنظیم شود، با ریست شدن وب سایت و از بین رفتن اطلاعات حافظه، عملا دسترسی به اطلاعات تراکنش های قبلی ممکن نیست و این به این معنا است که امکان تشخیص یک رسید استفاده شده در این شرایط ممکن نیست، اگر شرایط اعلامی درست است، به نظر این ایراد نیاز به رفع شدن دارد، اگر نه، لطفا توضیح بدید که به چه شکلی در پرباد از بروز این مشکل جلوگیری شده (ترجیحا خطوط کدی که مرتبط هستند هم اگر ذکر کنید ممنون میشم)

**Comment by Sina-Soltani** [comment]
درود
لطفا مستندات بانک سامان رو در صورت فراهم بودن اینجا اتچ کنید تا بررسی کنم، چون در حال حاضر دسترسی به مستندات ندارم.

**Comment by dehghani-mehdi** [comment]
[Uploading SEP_OnlinePG_Merchant Document_Minimal_Current  3.1.pdf…](خدمت شما)

**Comment by dehghani-mehdi** [comment]
خدمت شما
[SEP_OnlinePG_Merchant Document_Minimal_Current  3.1.pdf](https://github.com/user-attachments/files/17663332/SEP_OnlinePG_Merchant.Document_Minimal_Current.3.1.pdf)

**Comment by Sina-Soltani** [comment]
> براساس مستندات درگاه بانک سامان و در جهت جلوگیری از Double Spending لازم است که مقدار RefNum قبل از Verify تراکنش بررسی شود، اما براساس توضیحات (و همچنین سورس کد پروژه) ظاهرا مبنای تشخیص کد ارجاع است و نه RefNum، که به نظر صحیح نیست.

مبنای تشخیص Double Spending برای تمام درگاه‌های پیاده سازی شده، بر اساس داده های موجود در خود پَرباد هست از جمله:
TrackingNumber
PaymentToken
IsCompleted

> با فرض تصحیح مورد بالا (یا درست بودن کدهای جاری پروژه)، چنانچه Storage بر روی memory تنظیم شود، با ریست شدن وب سایت و از بین رفتن اطلاعات حافظه، عملا دسترسی به اطلاعات تراکنش های قبلی ممکن نیست و این به این معنا است که امکان تشخیص یک رسید استفاده شده در این شرایط ممکن نیست، اگر شرایط اعلامی درست است، به نظر این ایراد نیاز به رفع شدن دارد، اگر نه، لطفا توضیح بدید که به چه شکلی در پرباد از بروز این مشکل جلوگیری شده (ترجیحا خطوط کدی که مرتبط هستند هم اگر ذکر کنید ممنون میشم)

عملیاتی که شما در اینجا به اون اشاره میکنید اصولا تحت نام «پیگیری‌های پس از پرداخت در زمان آینده» شناخته میشه که این متدی جداگانه از ۳ عملیات اصلی (پرداخت، بازگشت، تایید) هست که توسط بانک سامان فراهم شده.

تمرکز پَرباد بر روی ۳ عملیات اصلی هست و متدهای اختصاصی یک درگاه خاص مانند «پیگیری‌های پس از پرداخت در زمان آینده» پیاده‌سازی نشده و نمیشه، چون با معماری اصلی پروژه که بر روی ۳ عمل اصلی تمرکز داره همخوانی نداره.

**Comment by Sina-Soltani** [comment]
مبنای تشخیص Double Spending برای تمام درگاه‌های پیاده سازی شده در پَرباد اول از همه در هنگام تایید اتفاق میوفته (اگر که درگاه مورد نظر چنین قابلیتی رو ارائه کرده باشه)
پس از اتمام عملیات از اون به بعد بر اساس داده های موجود در خود پَرباد چک میشه از جمله:
TrackingNumber
PaymentToken
IsCompleted

عملیات Double Spending توسط بانک سامان کنترل نمیشه و طبق مستندات، هر بار که درخواست تایید به این درگاه ارسال بشه، پاسخ مثبت دریافت میشه، حتی اگر refnum قبلا تایید شده باشه.
طبق مستندات، چک کردن این مورد به فروشنده واگذار شده.

پس بنابراین اگر پایگاه داده از بین بره، امکانی برای چک کردن تراکنشی که در گذشته‌ها اتفاق افتاده میسر نیست.

**Comment by dehghani-mehdi** [comment]
> عملیات Double Spending توسط بانک سامان کنترل نمیشه و طبق مستندات، هر بار که درخواست تایید به این درگاه ارسال بشه، پاسخ مثبت دریافت میشه، حتی اگر refnum قبلا تایید شده باشه.
طبق مستندات، چک کردن این مورد به فروشنده واگذار شده.

درست هست، شما در تیکت شماره 319 اعلام کردید که هدف اصلی ایجاد پرباد بحث امنیت هست و تمامی بررسی های امنیتی به صورت پیش فرض در پرباد انجام میشه (تا اونجایی که درگاه امکان ش رو فراهم کرده)
حالا در همین بانک سامان، باید RefNum (یا همون رسید دیجیتالی) قبل از تایید نهایی با رسیدهای دیجیتالی تراکنش های قبلی مقایسه بشه، با توجه به یکتا بودن این مقدار، در صورتی که مقداری مشابه در دیتابیس فروشنده پیدا بشه به معنی نامعتبر بودن تراکنش انجام شده است. اولین موردی که هست اینه که در کد شما در خصوص بانک سامان کلا این بررسی انجام نمیشه.

مورد دوم (با توجه به اعلان شما در خصوص بحث امنیت در پرباد) همین موضوعی هست که شما در جمله زیر اشاره کردید:

> پس بنابراین اگر پایگاه داده از بین بره، امکانی برای چک کردن تراکنشی که در گذشته‌ها اتفاق افتاده میسر نیست.

لذا اینکه استفاده از memory به عنوان دیتابیس جز آپشن های پرباد هست و عدم توضیح کافی شما در خصوص ریسک انتخاب این گزینه به عنوان دیتابیس، به نظر با انتخاب این گزینه بحث امنیت یا حداقل درستی تراکنش ها زیر سوال میره.

**Comment by Sina-Soltani** [comment]
درود

> حالا در همین بانک سامان، باید RefNum (یا همون رسید دیجیتالی) قبل از تایید نهایی با رسیدهای دیجیتالی تراکنش های قبلی مقایسه بشه، با توجه به یکتا بودن این مقدار، در صورتی که مقداری مشابه در دیتابیس فروشنده پیدا بشه به معنی نامعتبر بودن تراکنش انجام شده است. اولین موردی که هست اینه که در کد شما در خصوص بانک سامان کلا این بررسی انجام نمیشه.

بله، این مورد میتونه داخل این درگاه پیاده‌سازی بشه.


> لذا اینکه استفاده از memory به عنوان دیتابیس جز آپشن های پرباد هست و عدم توضیح کافی شما در خصوص ریسک انتخاب این گزینه به عنوان دیتابیس، به نظر با انتخاب این گزینه بحث امنیت یا حداقل درستی تراکنش ها زیر سوال میره.

[Memory Cache](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-cached-storage)
![image](https://github.com/user-attachments/assets/5f6b79f2-dc26-4db3-96ff-acb1a20afe33)
