### ISSUE TITLE
بیلد و انتشار پکیج به صورت اتوماتیک

### ISSUE THREAD

**Issue by Hameds** [Sina-Soltani/Parbad#4]
<div dir="rtl">
به دلیل استفاده نکردن از CI، هر زمان که سورس آپدیت می‌شه باید پکیج nuget به صورت مجزا آپدیت بشه. پیشنهاد من استفاده از appveyor و اتوماتیک کردن پروسه build و انتشار پکیج در nuget.org است.
من پیشتر این کار رو برای پروژه‌های دیگه‌ای انجام داد و اگر نیاز به راهنمایی بود در خدمتم
</div>

**Comment by Sina-Soltani** [comment]
ممنون بابت پیشنهاد
بله اگر مقدور هست راهنمایی کنید

**Comment by Hameds** [comment]
<div dir="rtl">
حتماً. تلاش می‌کنم این آخر هفته یک پست وبلاگ درباره این موضوع بنویسم که برای سایر دوستان هم قابل استفاده باشه
</div>

**Comment by Hameds** [comment]
<div dir="rtl">

سینا جان بسیار عذرخواهم که فراموش شد. بعد از اینکه issue بسته شد، دوباره یادم آمد که قول داده بودم پست بنویسم. خدمت شما، اگر سوال یا ابهامی بود در خدمتم: [https://elmah.ir/post/nuget-package-publish/](https://elmah.ir/post/nuget-package-publish/)

</div>

**Comment by Sina-Soltani** [comment]
مشکلی نیست. بنده هم خودم فرصتی برای انجام و پیگیری این کار نداشتم
تشکر بابت راهنمایی
