### ISSUE TITLE
خطای برگشت به سایت درگاه پارسیان

### ISSUE THREAD

**Issue by omidpirgazi92** [Sina-Soltani/Parbad#40]
باسلام. زمانی که از درگاه پارسیان بعد از پرداخت بازگشت میخورد به سایت خطای زیر رو نشون میده
در صورتی که در زمانی که در درگاه دکمه انصراف رو میزنی و برمیگرده به سمت سایت همچین خطایی نمیده و اوکی به نظر میرسه

#asp.core #درگاه_پارسیان

{ "TransactionCode": null, "TrackingNumber": 1159, "Amount": {}, "IsSucceed": false, "GatewayName": "ParsianGateway", "GatewayAccountName": "گیمستان", "Message": "Invalid data is received from the gateway", "AdditionalData": {}, "DatabaseAdditionalData": {} }

و اصلا تایید نمیشه در صورتی که پرداخت موفق آمیز بوده ولی خطا میده

**این مورد مشکلش برطرف نشد؟**

**Comment by Sina-Soltani** [comment]
درود

متاسفانه در 
[این قسمت](https://github.com/Sina-Soltani/Parbad/issues/38)
 پاسخی از شما دریافت نشد و به همین دلیل، مشکل بسته شد

نسخه جدیدی در حال آماده‌سازی هست بین ۱ تا ۳ روز آینده که مشکل رو برطرف میکنه

**Comment by omidpirgazi92** [comment]
عذر خواهی میکنم. من روی دات نت کر کار میکنم برای همین فکر میکردم از بقیه دوستان دارین سوالتونو میپرسید. خیلی ممنونم هر زمان درست شد خبربدید .

**Comment by Sina-Soltani** [comment]
لطفا نسخه جدید بتا رو تست کنید و نتیجه رو گزارش بدید

`Install-Package Parbad -Version 3.1.1-beta2`

موفق باشید

**Comment by omidpirgazi92** [comment]
> لطفا نسخه جدید بتا رو تست کنید و نتیجه رو گزارش بدید
> 
> `Install-Package Parbad -Version 3.1.1-beta2`
> 
> موفق باشید

متاسفانه همون خطای قبلی رو میده 
Invalid data is received from the gateway

**Comment by Sina-Soltani** [comment]
یک نسخه جدید امشب منتشر میشه که احتمالا این باگ رو هم فیکس میکنه
بهتون خبر میدم

**Comment by Sina-Soltani** [comment]
نسخه جدید رو میتونید تست کنید

`Install-Package Parbad -Version 3.1.1-beta3`

لطفا نتیجه رو اطلاع بدید

**Comment by omidpirgazi92** [comment]
> نسخه جدید رو میتونید تست کنید
> 
> `Install-Package Parbad -Version 3.1.1-beta3`
> 
> لطفا نتیجه رو اطلاع بدید


کماکان خطا میده ولی این دفعه این خطا رو داد

`
        {"TransactionCode":"","TrackingNumber":1212,"Amount":{},"IsSucceed":false,"GatewayName":"ParsianGateway","GatewayAccountName":"گیمستان","Message":"Error ","AdditionalData":{},"DatabaseAdditionalData":{"token":""}}
    `

**Comment by Sina-Soltani** [comment]
لطفا تنظیمات مربوط به پَرباد رو اینجا قرار بدید تا بررسی کنیم

**Comment by omidpirgazi92** [comment]
> لطفا تنظیمات مربوط به پَرباد رو اینجا قرار بدید تا بررسی کنیم

`
services.AddParbad()
    .ConfigureGateways(gateways => {
        gateways
            .AddParsian()
            .WithAccounts(source => {
                source.AddInMemory(account => {
                    account.Name = "گیمستان";
                    account.LoginAccount = "22222";
                });
            });

        gateways
            .AddPasargad()
            .WithAccounts(source => {
                source.AddInMemory(account => {
                    account.Name = "گیمستان";
                    account.TerminalCode = "222222";
                    account.PrivateKey = "222222";
                });
            });

        gateways
            .AddParbadVirtual()
            .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
    })
    .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
    .ConfigureStorage(builder => builder.UseMemoryCache());

`


این کانفیگی هست که داخل startUp گذاشتم  که البته کدها رو اینجا عوض کردم

**Comment by Sina-Soltani** [comment]
متاسفانه نمیدونم دقیقا مشکلی که بهش برمیخورین در کجا اتفاق میوفته چون تا به حال چنین موردی به این صورت گزارش نشده

تست رو به صورت آنلاین دارید انجام میدید یا لوکال؟
اگر آنلاین انجام میدید بگید لطفا که آیا امکان تست لوکال هم براتون محیا هست یا خیر

**Comment by omidpirgazi92** [comment]
> متاسفانه نمیدونم دقیقا مشکلی که بهش برمیخورین در کجا اتفاق میوفته چون تا به حال چنین موردی به این صورت گزارش نشده
> 
> تست رو به صورت آنلاین دارید انجام میدید یا لوکال؟
> اگر آنلاین انجام میدید بگید لطفا که آیا امکان تست لوکال هم براتون محیا هست یا خیر


روی لوکال نمیتونم تست کنم چون خطا میده که ip سرور درست نیست بخاطر همین آنلاین انجام میدم

**Comment by Sina-Soltani** [comment]
اگر ممکنه کد مربوط به تایید تراکنش رو هم قرار بدید تا بررسی کنیم
(لزومی نیست تمام کد رو قرار بدین. فقط بخش هایی که به پَرباد مربوط هست)

**Comment by omidpirgazi92** [comment]
> اگر ممکنه کد مربوط به تایید تراکنش رو هم قرار بدید تا بررسی کنیم
> (لزومی نیست تمام کد رو قرار بدین. فقط بخش هایی که به پَرباد مربوط هست)
> 
> و همچنین اگر از بانک پارسیان مستندات درگاه رو دریافت کردید اینجا قرار بدید،
> (PDF, Word)
> شاید تغییر جدیدی داده باشند

کدی که زمان verify  گذاشتم
`
var result = await _onlinePayment.VerifyAsync(invoice =>
            {
                // You can check your database, whether or not you have still products to sell
                // در این مرحله هنوز درخواست تأیید و واریز وجه از وب سایت شما به بانک ارسال نشده است
                // بنابراین شما می توانید اطلاعات صورتحساب را با پایگاه داده خود چک کنید
                // و در صورت لزوم تراکنش را لغو کنید
                if (!Is_There_Still_Enough_SmartPhone_In_Shop(invoice.TrackingNumber))
                {
                    invoice.CancelPayment("We have no more smart phones to sell.");
                }
            });
`
نمونه کدها و مستنداتی که بانک برام فرستاده.
[دانلود مستندات سرویس خرید معمولی](https://pgw.pec.ir/IPG/Docs/IPGSW1/IPGSW1Sale.zip)
[نمونه کد دات نت ](https://pgw.pec.ir/IPG/PecPGW.Samples.zip)

**Comment by Sina-Soltani** [comment]
فکر میکنم مشکل شما حل شده باشه

لطفا آخرین نسخه بتا رو نصب کنید
`Install-Package Parbad -Version 3.1.1-beta4`

البته چون این نسخه‌های بتا در حال توسعه به ساختار و تغییرات جدید هستن (از جمله مشکل شما)، یک سری تغییر جزئی هم شما باید در کد‌هاتون بدین در قسمت درخواست پرداخت

نمونه مثال کامل رو میتونید در صفحه راهنما مشاهده کنید
[راهنما](https://github.com/Sina-Soltani/Parbad/wiki/Invoice-Builder)

نتیجه رو لطفا گزارش بدید

**Comment by omidpirgazi92** [comment]
> فکر میکنم مشکل شما حل شده باشه
> 
> لطفا آخرین نسخه بتا رو نصب کنید
> `Install-Package Parbad -Version 3.1.1-beta4`
> 
> البته چون این نسخه‌های بتا در حال توسعه به ساختار و تغییرات جدید هستن (از جمله مشکل شما)، یک سری تغییر جزئی هم شما باید در کد‌هاتون بدین در قسمت درخواست پرداخت
> 
> نمونه مثال کامل رو میتونید در صفحه راهنما مشاهده کنید
> [راهنما](https://github.com/Sina-Soltani/Parbad/wiki/Invoice-Builder)
> 
> نتیجه رو لطفا گزارش بدید

ممنون ولی خطا داره هنوز  خطای زیر رو میده که میگه مبلغ با مبلغ پرداختی یکی نیست در صورتی که با هم برابر هستند.

`
        {"TransactionCode":null,"TrackingNumber":1224,"Amount":{},"IsSucceed":false,"GatewayName":"Parsian","GatewayAccountName":"گیمستان","Message":"Error in Callback section. Amount is not equal with the data in database.","AdditionalData":{},"DatabaseAdditionalData":{}}
    `

**Comment by Sina-Soltani** [comment]
پس باگ اصلی رفع شده اگر این پیام رو گرفتید

بررسی میکنم ببینم چرا مبلغ ها برابر نیستن بهتون خبر میدم امروز

**Comment by Sina-Soltani** [comment]
نسخه جدید رو لطفا نصب کنید و امتحان کنید

`Install-Package Parbad -Version 3.1.1-beta5`

**Comment by omidpirgazi92** [comment]
> نسخه جدید رو لطفا نصب کنید و امتحان کنید
> 
> `Install-Package Parbad -Version 3.1.1-beta5`

ممنونم درست شد  دست شما دردنکنه  مرسی از پیگیری سریعتون

**Comment by Sina-Soltani** [comment]
خواهش میکنم
موفق باشید

**Comment by Sina-Soltani** [comment]
@omidpirgazi92 
درود

شما قبلا مثل اینکه مشکلی با درگاه بانک پاسارگاد پیدا کرده بودید
آیا مشکل برطرف شده بود؟
