### ISSUE TITLE
خطا در ارسال به بانک پاسارگاد

### ISSUE THREAD

**Issue by alisalmani** [Sina-Soltani/Parbad#41]
با سلام 
در متد 
 _onlinePayment.Request(Gateway.Pasargad, Convert.ToInt64(myclass.classes.FirstOrDefault().intClassId), (decimal)myclass.classes.FirstOrDefault().dPrice, "http://........./registerClass/Verify");

به خطای 
Operation is not supported on this platform 
میرسم.

لطفا راهنمایی نمایید

**Comment by Sina-Soltani** [comment]
درود

کدوم نسخه از پَرباد رو دارید استفاده می‌کنید؟

در چه برنامه ای؟
(ASP.NET WebForms, MVC, CORE)?

**Comment by alisalmani** [comment]
ممنون از پیگیری سریع
نسخه .netCore

**Comment by Sina-Soltani** [comment]
لطفا آخرین نسخه رو تست کنید و نتیجه رو گزارش بدید

Install-Package Parbad -Version 3.1.1-beta2

موفق باشید

**Comment by alisalmani** [comment]
به خطای 
Data at the root level is invalid. Line 1, position 1
رسیدم که به نظر بخاطر اطلاعات تستی اکانت پاسارگاد باشد وقتی اطلاعات درست درگاه رو از بانک گرفتم حتما اعلام میکنم
بازم ممنون

**Comment by Sina-Soltani** [comment]
توجه داشته باشید که مقادیر رو جا به جا وارد نکنید

PrivateKey
کلید رمزنگاری

TerminalCode
شماره ترمینال

MerchantCode
شماره پذیرنده

**Comment by Sina-Soltani** [comment]
مشکل شما برطرف شد؟

**Comment by alisalmani** [comment]
متاسفانه درگیر پروسه اداری گرفتن درگاه بانکی هستم
درخواستم هنوز تایید نشده و عملا امکان بررسی دقیق ندارم

**Comment by mehrdadshirvan** [comment]
سلام برای درگاه پاسارگاد مشکل دارم

میره رو درگاه ولی عرور میده  

> خطا در ارسال اطلاعات

در ابتدا عرور این بود که نمیرفت رو درگاه 

`Declaration of Larabookir\Gateway\Pasargad\Pasargad::ready($payment_id, $callback_url) must be compatible with Larabookir\Gateway\PortInterface::ready()`

بعد تابع 

```
public function ready($payment_id, $callback_url)
    {
        $this->sendPayRequest($payment_id, $callback_url);

        return $this;
    }
```

رو کامنت کردم و اینو نوشتم و رفت رو درگاه اما عرور اینه الان 

```
public function ready()
    {
        return $this;
    }
```

عروری که درگاه میده 
> خطا در ارسال اطلاعات

هم کد خصوصی و مرچند کد و شماره ترمینال ارسال میشه به درگاه

**Comment by Sina-Soltani** [comment]
> 
> 
> سلام برای درگاه پاسارگاد مشکل دارم
> 
> میره رو درگاه ولی عرور میده
> 

درود

شما در مورد چه پروژه‌ای صحبت میکنید؟ فکر کنم احتمالا اشتباهی پیام فرستادید اینجا

**Comment by mehrdadshirvan** [comment]
> > سلام برای درگاه پاسارگاد مشکل دارم
> > میره رو درگاه ولی عرور میده
> 
> @mehrdadshirvan
> درود
> 
> شما در مورد چه پروژه‌ای صحبت میکنید؟ فکر کنم احتمالا پیامتون رو اشتباهی به این صفحه فرستادید

در مورد پروژه ایی نیست سرچ کردم اینجا رو پیدا کردم گفتم بپرسم اگ کسی میدونه راهنماییم کنه
