### ISSUE TITLE
افزودن زرین پال

### ISSUE THREAD

**Issue by RaminMT** [Sina-Soltani/Parbad#42]
سلام
توی موارد قبلی دیدم که نوشتید قصد اضافه کردن زرین پال و درگاه های واسط رو به این کتابخانه عالی دارید، اما خبری نیست ظاهرا خواستم اطلاعات بگیرم و ببینم که کاری در این باره در جریان هست یا نه؟
و اگر نیست اجازه هست که زرین پال رو اضافه کنم و پول ریکوئست بفرستم خدمتتون؟!

با تشکر

**Comment by Sina-Soltani** [comment]
درود

خیر درگاه های واسط پرداخت، به دلایل متعددی که چند نمونش را پایین ذکر میکنم، به این ابزار اضافه نخواهند شد

* درگاه‌های واسط رسمی نیستند
* به دلایل مختلفی توسط بانکداری کل، فیلتر و یا خارج از دسترس میشن
* ثابت و ماندگار نیستن (اهمیتی نداره که چه مدتی همچنان فعال هستن)
* طی ده سال گذشته ده‌ها درگاه واسط ایجاد شدن و از بین رفتن

بنابراین جهت حفظ نظم و یکپارچگی این ابزار، این درگاه‌ها اضافه نخواهند شد

هر چند که شما میتونید سورس رو دانلود کنید و درگاه مورد نظر خودتون رو اضافه کنید و در پروژه خودتون استفاده کنید

البته طبق لایسنس برنامه، حق انتشار مجدد به شخصی داده نمیشه

موفق باشید

**Comment by RaminMT** [comment]
سلام مجدد و خیلی ممنون از پاسخ سریعتون
حقیقتش پاسختون بنده رو قانع نکرد. درگاه واسطی مثل زرین پال حدود 10 سال داره فعالیت میکنه و فکر نمیکنم که از نظر ماندگاری مشکلی داشته باشه همینطور نمیدونم منظورتون از رسمی چی هست چون مجوز داره و مشکلات مثل فیلتر و خارج شدن از دسترس به دفعات خیلی معدودی برای این درگاه اتفاق افتاده
یا مثلا pay.ir که متعلق به خود بانک سامان هست فکر نمیکنم مشکلاتی که ذکر کردید براش مطرح باشه

ولی دست کم ای کاش تدبیری توی توسعه این کتابخونه اندیشه بشه که درگاه های واسط رو به شکل ماژول یا پلاگین یا اکستنشن بتونیم اضافه و استفاده کنیم
اینطوری هم چیزی که دلخواه هست میتونه مورد استفاده قرار بگیره هم اینکه از تغییرات این کتابخونه جا نمیمونیم (بدلیل توسعه شخصی)

باز هم ممنون

**Comment by Sina-Soltani** [comment]
شاید درست نتونستم منظورم رو خدمتتون بگم
منظور بنده از رسمی بودن، یعنی جز سیستم بانکی کشور (شبکه شتاب) هست

در مورد توسعه پذیر بودن:
این ابزار به صورت ۹۹.۹۹ درصد توسعه پذیر هست
درگاه ها قابلیت اضافه شدن به صورت پلاگین را دارند
همچنین محل ذخیره‌سازی داده‌ها کاملا پلاگین پذیر هست که در حال حاضر دو نوع قابل استفاده هم موجود هستند

افزودن درگاه
```csharp
ConfigureGateways(gateways =>
{
   gateways.Add<MyGateway>();
}
```
افزودن منبع ذخیره سازی
```csharp
ConfigureStorage(storages =>
{
   storages.Add<MyStorage>();
}
```

شما در صورت تمایل میتونید درگاه‌های واسط پرداخت رو توسعه بدید و به صورت نوگت منتشر کنید
برای مثال
Parbad.Gateways.ZarinPal
Parbad.Gateway.ABCD

البته طبق لایسنس برنامه، شرایط زیر باید رعایت بشه

* سورس پلاگین باید متن باز باشه و در منبع معتبر (مثل گیت هاب) قابل دسترسی باشه
* فایل لایسنس اصلی پَرباد که در همین سورس در گیت هاب قابل مشاهده هست، باید به محتویات پلاگین افزوده بشه و همچنین در صورت بازنشر به صورت نوگت، باید لایسنس اصلی پَرباد ذکر بشه

**Comment by RaminMT** [comment]
سلام مجدد
بسیار عالی
خیلی ممنون از شما

برنامه ای برای انتشار نسخه ای برای dotnet core 3 دارید؟ خوشحال میشم اگر بتونم کمکی توی توسعه این کتابخونه بکنم

**Comment by Sina-Soltani** [comment]
بله برای
.NETCORE 3
هم منتشر میشه

> برنامه ای برای انتشار نسخه ای برای dotnet core 3 دارید؟ خوشحال میشم اگر بتونم کمکی توی توسعه این کتابخونه بکنم

تشکر از شما. در حال حاضر مشکل خاصی وجود نداره اما در صورت نیاز حتما اطلاع رسانی میکنم
ممنون

**Comment by Sina-Soltani** [comment]
@RaminMT 

درود

صفحه راهنمای پَرباد برای ایجاد درگاه اضافه شده و در حال به روز رسانی هست
در صورتیکه نیاز به کمک برای ایجاد درگاه داشته باشید، میتونید از این صفحه کمک بگیرید
[راهنمای ایجاد درگاه](https://github.com/Sina-Soltani/Parbad/wiki/Developing-a-new-Gateway)
موفق باشید
