### ISSUE TITLE
سوال در مورد نحوه تنظیم DistributedCache

### ISSUE THREAD

**Issue by RaminMT** [Sina-Soltani/Parbad#43]
و یک سوال دیگه داشتم
من فلسفه storage رو درک نکردم، الان ما خودمون در جدول تنظیمات اطلاعات اکانتهای درگاه رو ثبت کردیم و برای استفاده هم یه AccountSource ساختیم و معرفی کردیم، حالا چه لزومی به استفاده از storage هست؟ و اگر قصد استفاده از dist cache داشته باشیم تنظیم خاصی باید برای انجام بدیم؟
ما از ردیس توی پروژه استفاده کردیم اما چیزی ندیدم که مثلا ردیس رو معرفی کنم.

**Comment by Sina-Soltani** [comment]
Storage
در واقع محلی هست که ما داده‌هایی که از بانک دریافت میکنیم و یا خودمون تولید میکنیم رو ذخیره میکنیم
به اینصورت دیگه نیازی نیست که کاربر مصرف کننده، درگیر مسائلی مثل خواندن فلان دیتا از دیتابیس رو داشته باشه
در واقع همه عملیات رو خود پَرباد انجام میده
برای مثال زمانیکه کاربر از بانک به وب سایت برمیگرده، تنها کاری که کاربر باید انجام بده صدا زدن متد
Fetch
هست
و در نهایت صدا زدن متد
Verify
در نتیجه کاربر درگیر اینگونه مسائل نیست

AccountSource
فقط برای ایجاد و معرفی اکانت توسط مصرف کننده هست که میتونه در حال حاضر به سه روش مورد مصرف قرار بگیره
وارد کردن اکانت بانکی به صورت دستی (استاتیک)
وارد کردن اکانت بانکی توسط تنظیمات
IConfiguration

و وارد کردن اکانت از روش‌های دیگه مانند خواندن از دیتابیس خوده مصرف کننده


DistributedCache
در صورتیکه  پکیج
Parbad.Storage.Cache
نصب بشه و استوریج به صورت زیر تنظیم بشه
```csharp
ConfigureStoage(storage =>
{
   storage.AddDistributedCache();
});
```
در اینصورت پَرباد هنگام ذخیره سازی یا بازیابی اطلاعات از اینترفیس
IDistributedCache
استفاده میکنه
این به این معنی هست که کاربر هر گونه کش
DistributedCache (MemoryCache, Redis, SQL Server,...)
رو نصب کرده باشه، میتونه ازش بهره ببره

**Comment by Sina-Soltani** [comment]
در صورتیکه نیاز به کمک برای توسعه داشتید، میتونید سوال بپرسید تا کمکتون کنم
موفق باشید

**Comment by RaminMT** [comment]
راستش درست متوجه نشدم که قسمت dist cache چطور کار میکنه اما از توضیحات کاملتون احساس کردم که دیتابیس گزینه مناسبتری هست.

**Comment by Sina-Soltani** [comment]
شاید علتش این باشه که احتمالا
IDistributedCache
رو درست نشناخته باشید (البته حدس میزنم فقط)

زمانیکه شما در یک پروژه پکیج
Microsoft.Extensions.Caching.Redis
رو نصب و تنظیم میکنید، از اون به بعد هر موقع که دیتایی رو توسط
IDistributedCache
ذخیره و یا بازیابی می‌کنید، در واقع
Redis
اون کار رو برای شما انجام میده

**Comment by RaminMT** [comment]
متشکر از شما
ما تا همین چند وقت پیش مستقیما از Redis استفاده میکردیم الان هم به کتابخونه دیگه ای مهاجرت کردیم به همین علت با `Microsoft.Extensions.Caching.Redis` آشنایی نداشتم

ممنون بابت توضیحات و راهنمایی
