### ISSUE TITLE
عدم وجود متد FetchAsync

### ISSUE THREAD

**Issue by RaminMT** [Sina-Soltani/Parbad#44]
### توضیح خطا
در مثالها برای تایید یک تراکنش، تابعی به نام FetchAsync صدا زده شده است اما چنین تابعی ظاهرا وجود ندارد.

### نسخه پَرباد
1.0.1

### نوع برنامه
ASP.NET CORE

**Comment by Sina-Soltani** [comment]
ورژنی که ذکر کردید برای سال ۲۰۱۶ بوده و اون زمان چنین متدی نبوده
این متد در آخرین نسخه بتا اضافه شده

**Comment by RaminMT** [comment]
آها، درسته
خب من چک کردم ظاهرا فقط پکیج Parbad هست که نسخه بتا داره و برای asp.ner core چیزی نیست

**Comment by Sina-Soltani** [comment]
> 
> ### توضیح خطا
> 
> در مثالها برای تایید یک تراکنش، تابعی به نام FetchAsync صدا زده شده است اما چنین تابعی ظاهرا وجود ندارد.
> ### نسخه پَرباد
> 
> 1.0.1
> ### نوع برنامه
> 
> ASP.NET CORE

فکر کنم شما اینجا به جای نسخه پَرباد، نسخه مربوط به پکیج
Parbad.AspNetCore
رو درج کردید و به همین علت من گفتم برای سال ۲۰۱۶ بوده

در هر صورت متدی که ذکر کردید در نسخه بتا اضافه شده که بعد از بتا یعنی پس از تست‌ها، به صورت نسخه پایدار قابل دسترسی نیز خواهد بود

**Comment by RaminMT** [comment]
آها
من اصلا خب پکیج Parbad رو نصب نکردم و فقط `Parbad.AspNetCore` رو نصب کردم
پس با این اوصاف من باید خود Parbad رو هم نصب کنم و اون هم نسخه بتا

خیلی ممنون
