### ISSUE TITLE
نحوه عملکرد اپلیکیشن

### ISSUE THREAD

**Issue by alirezaseif28** [Sina-Soltani/Parbad#48]
سلام 
با عرض معذرت از این که وقت شما رو می گیرم
می خواستم از شما این سوال بپرسم
که چطور بدون اضافه کردن وب سرویس بانک میشه از در گاه پرداختش استفاده کرد.؟
اگر لطف کنید مقاله و سر نخ برای تحقیق ارایه بدید
تشکر
مرسی

**Comment by Sina-Soltani** [comment]
درود

کافیه که اطلاعات رو با استفاده از ابزارهای مختلف مانند
HttpClient
یا
WebRequest
به آدرس وب سرویسشون ارسال کنید و پاسخ دریافت شده رو پردازش کنید
پاسخی که ارسال میکنن بستگی داره به چه فرمتی باشه
برای مثال اگر
XML
ارسال میکنن، اونوقت شما باید با ابزارهایی مثل
XmlDocument
اونها رو پردازش کنید و نتایج رو ازش بیرون بکشید
و یا اگر که پاسخ رو به صورت
JSON
میفرستن اونوقت میتونید از
Newtonsoft.Json
استفاده کنید

**Comment by alirezaseif28** [comment]
مرسی
