### ISSUE TITLE
خطا در ارجاع  به صفحه پرداخت

### ISSUE THREAD

**Issue by zaarei** [Sina-Soltani/Parbad#49]
متاسفانه کد زیر اجرا نمیشه 
return result.GatewayTransporter.TransportToGateway();
non-public members
برای GatewayTransporter

**Comment by Sina-Soltani** [comment]
درود

چنین خطایی وجود نداره
طبق آموزش‌‌ها پیش برید

[آموزش](https://github.com/Sina-Soltani/Parbad/wiki)
