### ISSUE TITLE
اضافه کردن درگاه آسان پرداخت

### ISSUE THREAD

**Issue by Ali-Rezaeii** [Sina-Soltani/Parbad#5]
اولا ممنون بابت پرباد!

دوستان درگاه هایی رو گفتن اضافه بشن که خیلی عالین اما یه درگاه پرکاربرد که این روزا خیلی ازش استفاده میشه `آسان پرداخت` هستش. ممنون میشم این درگاه رو هم به پرباد اضافه کنید

**Comment by Sina-Soltani** [comment]
ممنون بابت پیشنهاد.
بررسی میکنم و در صورتیکه مشکلی نباشه حتما اضافه میشه

**Comment by Ali-Rezaeii** [comment]
@Sina-Soltani ممنون. حتی این روزا همه سرویس های محبوب مثل دیجی کالا، اسنپ و ... از `آسان پرداخت` به عنوان پیشنهاد اول استفاده می کنن.

**Comment by homayon1369** [comment]
سلام وقت بخیر. اگه امکانش هست یه آموزش قدم به قدم بذارید چون بعضی وقتها خطاهایی میده که آدم متوجه نمیشه. الان مثلا من میتونم به درگاه وصل بشم و تمام مراحل انجام میشه ولی زمانیکه برمیگرده سمت سایت خطای 
invalid data received ..... 
رو میده. دیگه واقعا نمیدونم باید چیکارش کنم

**Comment by Sina-Soltani** [comment]
> 
> 
> سلام وقت بخیر. اگه امکانش هست یه آموزش قدم به قدم بذارید چون بعضی وقتها خطاهایی میده که آدم متوجه نمیشه. الان مثلا من میتونم به درگاه وصل بشم و تمام مراحل انجام میشه ولی زمانیکه برمیگرده سمت سایت خطای
> invalid data received .....
> رو میده. دیگه واقعا نمیدونم باید چیکارش کنم

سعی میکنم به زودی یک آموزش ویدئویی آماده کنم.

از چه درگاهی استفاده می‌کنید؟

**Comment by majidjezlani** [comment]
سلام وقت بخیر
آموزشی هم برای استفاده در زامارین فرم دارید ؟

**Comment by Sina-Soltani** [comment]
> سلام وقت بخیر آموزشی هم برای استفاده در زامارین فرم دارید ؟


درود
لطفا در تیکت های نامربوط سوال طرح نکنید.

پاسخ: برای برنامه های سمت کلاینت می تونید نمونه پروژه Angular رو مشاهده و بررسی کنید و مشابه اون رو در زامارین یا هر برنامه کلاینت دیگه ای پیاده‌سازی کنید.
[کد سمت سرور](https://github.com/Sina-Soltani/Parbad.Samples/blob/master/Web/Parbad.Sample.Angular/Controllers/PaymentController.cs)
[کد سمت کلاینت](https://github.com/Sina-Soltani/Parbad.Samples/blob/master/Web/Parbad.Sample.Angular/ClientApp/src/app/payment-request/payment-request.component.ts)
