### ISSUE TITLE
برگشت هزینه

### ISSUE THREAD

**Issue by RezaAVS** [Sina-Soltani/Parbad#50]
<div dir="rtl">
وقتی از متد CancelAsync استفاده مکنیم آیا لازم هست متد RefundCompletelyAsync رو فراخوانی کنیم؟

**Comment by Sina-Soltani** [comment]
درود

خیر نیازی نیست
مبلغ به صورت خودکار توسط خود بانک به حساب مشتری برگشت داده میشه.
مدت زمان برگشت، بین ۱۵ دقیقه تا سه روز هست بستگی به بانک داره

موفق باشید
