### ISSUE TITLE
EntityFrameworkCore 3 Exception

### ISSUE THREAD

**Issue by adbdehghan** [Sina-Soltani/Parbad#51]
I had updated my project to .net core 3 but in my program.cs i get this exception :

◢ | $exception | {"Method not found: 'Microsoft.EntityFrameworkCore.Metadata.Builders.IndexBuilder Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.HasIndex(System.Linq.Expressions.Expression`1<System.Func`2<!0,System.Object>>)'."} | System.MissingMethodException

when i remove this line from configuration the error will gone:
.ConfigureDatabaseInitializer(a => a.CreateAndMigrateDatabase())

Please help to solve this issue.

Thanks

**Comment by Sina-Soltani** [comment]
The current version doesn't support the .NETCORE3. A new version must be released.
I will inform you later.

**Comment by adbdehghan** [comment]
OK thank you, do you have any idea of new version release date?

**Comment by Sina-Soltani** [comment]
No unfurtunately. I'm very busy

**Comment by hoseineghbal** [comment]
any idea for this error ???

**Comment by Sina-Soltani** [comment]
Well this is a problem by EntityFramework Team and not me!
But the current solution is: Don't upgrade the EntityFramework to version 3.
I will release a new version some time later to fix this problem.

**Comment by Sina-Soltani** [comment]
This problem is fixed now.
You can upgrade the Parbad.Storage.EntityFrameworkCore package to version 1.0.2.

**Comment by adbdehghan** [comment]
Hi sina
Thanks you so much for your great work.

 Best regards
Adib dehghan
