### ISSUE TITLE
How to add gateway (or change gateway settings) right before payment request?

### ISSUE THREAD

**Issue by hatami57** [Sina-Soltani/Parbad#52]
Hi,

I want somehow set the gateway settings dynamically for each payment separately. In other words, I need to add a gateway or change the predefined gateways' settings, just before doing a payment.
Is this possible with your package?

Let's say I have hundreds of bank accounts and I cannot add all of them in advance with `services.AddParbad().ConfigureGateways`.

The gateway settings should be set when a payment operation have to be done...

Thank you for your great work.

**Comment by Sina-Soltani** [comment]
No currently it's not possible.
Maybe in future versions.

**Comment by hatami57** [comment]
Thank you for your prompt response.

Is there any simple hacky way to achieve such a thing with the source code? if so, I will appreciate any hint to accomplish this...

**Comment by Sina-Soltani** [comment]
There is no easy solution for this and lots of things must be changed.
