### ISSUE TITLE
Unable to resolve service

### ISSUE THREAD

**Issue by rbsdotnet** [Sina-Soltani/Parbad#53]
### توضیح خطا
[Saman.txt](https://github.com/Sina-Soltani/Parbad/files/3950028/Saman.txt)

Unable to resolve service for type 'AVS.ServiceLayer.Services.BankGatewayService' while attempting to activate 'AVS.ServiceLayer.Services.SamanGatewayAccountService'.

     services.AddParbad()
                .ConfigureGateways(gateways =>
                {
                    //gateways
                    //    .AddMellat()
                    //    .WithAccounts(accounts =>
                    //    {
                    //        accounts.Clear();
                    //        accounts.Add<MellatGatewayAccountService>(ServiceLifetime.Transient);
                    //    });
                    gateways
                        .AddSaman()
                        .WithAccounts(accounts =>
                        {
                            accounts.Clear();
                            accounts.Add<SamanGatewayAccountService>(ServiceLifetime.Transient);
                        });
                    //gateways
                    //    .AddMelli()
                    //    .WithAccounts(accounts =>
                    //    {
                    //        accounts.Clear();
                    //        accounts.Add<MelliGatewayAccountService>(ServiceLifetime.Transient);
                    //    });
                    gateways
                        .AddParbadVirtual()
                        .WithOptions(options => options.GatewayPath = "/virtualgateway");
                })

### نام و نسخه پکیج
[Parbad.AspNetCore]
[1.0.1]

### نوع برنامه وب
ASP.NET CORE 3.1

**Comment by Sina-Soltani** [comment]
مشکل شما حل شد؟
