### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by PooriaShariatzadeh** [Sina-Soltani/Parbad#54]
سلام و خسته نباشید البته این ایراد در کد نیست اما گفتم شاید شما راحت بتونید حلش کنید چون دو روزه من رو گیر انداخته ور هرچی سرچ کردم و امتحان کردم نتونستم حلش کنم با ویرچوال هیچ مشکلی ندارم و خیلی راحت روی لوکال  فرایند به درستی طی میشه اما روی سرور پروداکشن  با ایراد زیر برخورد میکنم که البته تلاش زیاد کردم برای حلش اما نشد
 Access to XMLHttpRequest at 'https://pec.shaparak.ir/NewIPG/?Token=470472695' (redirected from 'https://betaapi.2ristpanel.com/api/v1/TRMS/Financial/AddCredit') from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

توی استارت اپ پروژه اکسس به * دادم  
       services.AddCors(options =>
            {
                options.AddPolicy("CorsPolicy",
                    builder => builder.AllowAnyOrigin()
                    .AllowAnyMethod()
                    .AllowAnyHeader()
                    .SetIsOriginAllowedToAllowWildcardSubdomains().WithOrigins("https://*.2ristpanel.com")
                    );
            });
و بالای متد هم اتریبیوت 
        [EnableCors("CorsPolicy")]
به کار بردم و خیلی را های دیگه اما نشد اگر راهنمایی بفرمایید خیلی ممنون میشم

**Comment by Sina-Soltani** [comment]
درود

آیا این خطا در رابطه با استفاده از این پکیج رخ داده یا سوال شما یک سوال عمومی در مورد
ASP.NET CORE
هست؟

لطفا توضیحات خطا
Stack Trace
رو اینجا کپی کنید تا بررسی کنیم

**Comment by PooriaShariatzadeh** [comment]
سلام بله در زمان استفاده از پکیج بر روی سرور پروداکشن این اتفاق میافته 
مشکل در ریدایرکت شدن به صفحه بانکه یعنی حتی زمانی که روی لینک مربوط به شاپرک که در ارور بالا هست میزنیم به صفحه بانک ربدایرکت میشه اما در خواست به صورت اتوماتیک به صفحه بانک ریدایرکت نمیشه من باز هم یاد اوری میکنم که روی لوکل همه جیز با درگاه ویرچوال پرباد درسته اما روی سرور ایراد میگره که فکر میکنم ایراد کانفیگی باشه اکسپشن نیست 
![1](https://user-images.githubusercontent.com/7371261/70708081-ecde3080-1cee-11ea-8b45-5e83677f935e.png)

**Comment by PooriaShariatzadeh** [comment]
من بر اساس لینک زیر و حتی چند منبع دیگه هم امتحان کردم اما بازم نشد 
https://code-maze.com/enabling-cors-in-asp-net-core

**Comment by Sina-Soltani** [comment]
خطایی که شما نشون دادید در رابطه با کلاینت ساید هست
آیا شما قصد دارید با صورت آجاکس با درگاه پرداخت پارسیان ارتباط برقرار کنید؟
اگر بله، پس مشکل همین هست و چنین کاری اشتباه هست

**Comment by PooriaShariatzadeh** [comment]
کلاینت ساید من 
AngularJS 
هست و با 
http request
 با 
api server side
  ارتباط برقرار میکنم 
بعد از گذروندن تمامی مراحلی که در داکیومنت شما هست ریسلت رو به سمت کلاینت میفرستم 
متوجه نمیشم چرا روی لوکال درست کار میکنه اما سمت سرور ایراد داره 

کد سمت کلاینت
`angular.module('kishApp').factory('API', ['$http', 'blockUI', 'Session', 'Upload', '$localStorage', '$rootScope',
    function ($http, blockUI, Session, Upload, $localStorage, $rootScope) {
        return {
            Payment: function (Options) {
                blockUI.start();
                return $http({
                    method: "POST",
                    url: `${AppConfig.BaseApi}${Options.Controller}/${Options.Method}`,
                    data: Options.Data,
                    dataType: 'text',
                    processData: false,
                    files: Options.Files,
                    async: false,
                    headers: {
                        'Access-Control-Allow-Origin': '*',
                        'Access-Control-Allow-Methods': 'GET,PUT,POST,DELETE,OPTIONS',
                        'Content-Type': 'application/json; charset=utf-8',
                        'Token': localStorage.getItem('Token'),
                        'DeviceKey': localStorage.getItem('DeviceKey'),
                        'Domain': location.host,
                    }
                }).then(function (Result) {
                    if (Result.status == 200) {
                        document.write(Result.data);
                    } else {
                        blockUI.stop();
                        return ReturnResult(Result, Options.JustData, Options.AlertType, Options.ToastrOption);
                    }
                }, function (Result) {
                    blockUI.stop(Options.BlockId);
                    if (Result.status == 401)
                        Session.destroy();
                    return ReturnResult(Result, Options.JustData, Options.AlertType, Options.ToastrOption);
                });
            },
        };
    }]);`


کد سمت سرور 
`    [EnableCors("AllowOrigin")]
        [HttpPost("AddCredit")]
        public async Task<IActionResult> AddCredit(AddCreditView addCredit)
        {
            try
            {
                try
                {
                    Response.Headers.TryAdd("Access-Control-Allow-Origin", "https://beta.2ristpanel.com");
                    Response.Headers.TryAdd("Access-Control-Allow-Methods", "GET,PUT,POST,DELETE,OPTIONS");
                }
                catch (Exception ex )
                {            
                }
               
                var result= _financialService.AddCredit(addCredit);

                if (result.IsSucceed)
                {
                    var a= result.GatewayTransporter.TransportToGateway();
                    return a;
                }
                else
                {
                    return BadRequest(new Result {Message= result.Message,Status=ResultStatus.Error });
                }

            }
            catch (Exception ex)
            {
                return BadRequest(new Result { Message = ex.Message, Status = ResultStatus.Error });
            }
        }`

**Comment by PooriaShariatzadeh** [comment]
خیلی ممنون از وقتی که میگذارید تا به حال کسی رو توی ایران ندیدم انتقدر نسبت به ساخته رایگان و کم نظیر خودش مسول باشه و پاسخگو
راهکار چیه ایا امکان داره از 
 result.GatewayTransporter.TransportToGateway();
یک لینک همراه با پارامتر های بانک استخراج بشه تا سمت کلاینت ریدایرکت انجام بشه
بازم ممنون از وقتی که میذارید

**Comment by Sina-Soltani** [comment]
> 
> 
> کلاینت ساید من
> AngularJS
> هست و با
> http request
> با
> api server side
> ارتباط برقرار میکنم

همونطور که گفتم روشی که دارید استفاده میکنید صحیح نیست و شما عملیات ریدایرکت کردن کاربر رو نباید به عهده سمت کلاینت بزارید و این وظیفه سمت سرور هست

شما باید به این ترتیب عمل کنید

سمت کلاینت درخواست پرداخت رو آماده و به صورت غیر آجاکسی ارسال میکنید به سمت سرور خودتون
دو روش برای این کار میتونید استفاده کنید
میتونید یک فرم پست کنید که شامل اطلاعات پرداخت مثل مبلغ و بانک مورد نظر هست
یا اینکه
کاربر رو توسط جاوا اسکریپت با استفاده از دستور
window.location.href = "http://www.mysite.com/payment/?price=1000&gateway=Parsian";
به وب سایت خودتون هدایت کنید

پس از اینکه کاربر به سمت سایت شما هدایت میشه، با استفاده از پکیج پَرباد میتونید درخواست پرداخت رو به بانک ارسال کنید و باقی کار کاملا مانند مثال ها هست

**Comment by Sina-Soltani** [comment]
> 
> 
> خیلی ممنون از وقتی که میگذارید تا به حال کسی رو توی ایران ندیدم انتقدر نسبت به ساخته رایگان و کم نظیر خودش مسول باشه و پاسخگو
> راهکار چیه ایا امکان داره از
> result.GatewayTransporter.TransportToGateway();
> یک لینک همراه با پارامتر های بانک استخراج بشه تا سمت کلاینت ریدایرکت انجام بشه
> بازم ممنون از وقتی که میذارید

خواهش میکنم

**Comment by PooriaShariatzadeh** [comment]
ممنون دقیقا بهم ایده دادید که چیکار باید بکنم و انجام شد خیلی ممنون
