### ISSUE TITLE
کارت شما از سمت بانک صادرکننده محدود است

### ISSUE THREAD

**Issue by rbsdotnet** [Sina-Soltani/Parbad#55]
### توضیح خطا
بعد از اینکه وارد بانک میشیم
اطلاعات کارت رو ثبت میکنیم این خطا صادر میشه
دلیلش چیه؟
مبلغ 30000 هزار ریال بوده

![01](https://user-images.githubusercontent.com/49598914/71541884-9f132a80-2974-11ea-811c-f267ce897f58.jpg)

### نوع برنامه وب
ASP.NET CORE

**Comment by Sina-Soltani** [comment]
با بانک سامان و یا شعبه صادر کننده کارت خود تماس بگیرید
