### ISSUE TITLE
خطا در Register کردن سرویس

### ISSUE THREAD

**Issue by idotnetdev** [Sina-Soltani/Parbad#56]
با سلام و عرض ادب
من با استفاده از آموزش های شما توی همین گیت هاب و ویکی پرباد رو به پروژه ام اضافه کردم ولی یه ایرادی داره و موقعی که اینترفیس IOnlinePayment رو به کنترلرم اضافه میکنم این خطا رو میده.
میشه لطفا راهنمایی کنید؟

` None of the constructors found with 'Autofac.Core.Activators.Reflection.DefaultConstructorFinder' on type 'Parbad.Internal.DefaultOnlinePayment' can be invoked with the available services and parameters:
Cannot resolve parameter 'Parbad.Storage.Abstractions.IStorageManager storageManager' of constructor 'Void .ctor(System.IServiceProvider, Parbad.Storage.Abstractions.IStorageManager, Parbad.PaymentTokenProviders.IPaymentTokenProvider, Parbad.Abstraction.IGatewayProvider, Microsoft.Extensions.Options.IOptions`1[Parbad.Options.MessagesOptions], Microsoft.Extensions.Logging.ILogger`1[Parbad.IOnlinePayment])'. `

البته از ورژن قدیمیش استفاده کرده بودم مشکلی نداشت ولی با این ورژن مشکل دارم.

**Comment by Sina-Soltani** [comment]
> البته از ورژن قدیمیش استفاده کرده بودم مشکلی نداشت ولی با این ورژن مشکل دارم.

درود

چه ورژنی؟

**Comment by idotnetdev** [comment]
بعد از تقریبا دو روز و نوشتن این سوال مشکل رو حل کردم.
ورژنش یادم نیست ولی در هر صورت ممنونم.
خیلی کتابخونه خوب و عالی هست. فقط یه سوالی ذهنم رو درگیر کرده.
اینکه موقع Application Start پروژه اطلاعات بانک ها رو میدیم بهش؛ بخوام به صورت تنظیماتی اطلاعات رو بهش بدم چیکار باید کنم؟

**Comment by Sina-Soltani** [comment]
> اینکه موقع Application Start پروژه اطلاعات بانک ها رو میدیم بهش؛ بخوام به صورت تنظیماتی اطلاعات رو بهش بدم چیکار باید کنم؟

منظورتون از (به صورت تنظیماتی اطلاعات رو بهش بدم) چه چیزی هست دقیقا؟ کجا؟

**Comment by idotnetdev** [comment]
یعنی یه قسمتی توی سایت هست که میشه چند تا درگاه رو تعریف کرد. فقط اطلاعات درگاه هارو ثبت میکنیم و دیگه توی Web.Config و ... نیست و بلافاصله میشه درگاه به سایت اضافه بشه بدون کد نویسی.
این کار رو قبلا خودم انجام دادم ولی تک تک درگاه ها رو پیاده کردم بعدا یه قسمتی رو به عنوان مدیریت درگاه های بانکی اضافه کردم و ازشون برای همین کاری که عرض کردم استفاده کردم.
الان میخوام همین کارو با استفاده از پرباد انجام بدم.

با توجه به اینکه ParbadBuilder رو موقع Start تنظیم می کنیم آیا بعدا امکانش هست که بشه تنظیمش کرد مثلا موقع ثبت تنظیمات مربوط به درگاه ها؟

**Comment by Sina-Soltani** [comment]
در واقع فکر میکنم منظور شما تنظیم درگاه ها به صورت داینامیک هست

این قسمت رو لطفا نگاه کنید
[Adding an account using a custom source (such as Database)](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-an-account-using-a-custom-source-such-as-database)

**Comment by idotnetdev** [comment]
اینها رو قبلا کامل مطالعه کردم. این مطلبی که زحمتش رو کشیدین و نوشتین باز هم همون اول برنامه اطلاعات درگاه ها رو ثبت میکنه و دیگه در حین اجرای برنامه نمیشه به لیست درگاه ها اضافه کرد. درسته؟

**Comment by Sina-Soltani** [comment]
خیر درست نیست
در هنگام شروع درخواست پرداخت، اطلاعات خوانده میشه

**Comment by idotnetdev** [comment]
یعنی من موقعی که اطلاعات یه درگاه رو ثبت میکنم میتونم باز هم ParbadBuilder رو صدا کنم و اطلاعات درگاه جدید رو بهش بدم بدون اینکه نیاز باشه تا اپلیکیشن ریستارت بشه؟

**Comment by Sina-Soltani** [comment]
لینکی که براتون گذاشتم یک نمونه مثال داره برای تنظیم درگاه بانک ملت که زمانیکه یک درخواست پرداخت برای بانک ملت ایجاد میشه، اون مخزن داده که شما ایجاد میکنید، توسط پرباد استفاده میشه و اطلاعات را از شما میگیره
بنابراین همونطور که گفتم اطلاعات پس از هر درخواست، از مخزن شما خونده میشه و این به این معنی هست که زمانیکه شما در دیتابیس وب سایت خودتون تغییری ایجاد میکنید، اون اطلاعات میتونه به پَرباد داده بشه

**Comment by idotnetdev** [comment]
خیلی عالی به این شکلش فکر نکرده بودم. فکر می کردم یه بار میخونه.
ممنون از راهنمایی خوب و دقیقتون.

**Comment by Sina-Soltani** [comment]
خواهش میکنم
