### ISSUE TITLE
دریافت کد وضعیت بازگشتی از بانک

### ISSUE THREAD

**Issue by mohammad68a** [Sina-Soltani/Parbad#57]
با سلام
چطور میتوان به کد وضعیت بازگشتی از سمت بانک نیز دسترسی پیدا کرد
من نیاز دارم تا کد وضعیت را پس از 
call back
در پایگاه داده ذخیره کنم

**Comment by Sina-Soltani** [comment]
درود

چنین امکانی در حال حاضر موجود نیست

**Comment by mohammad68a** [comment]
آیا کد وضعیت درون حافظه پرباد ذخیره میشود؟
پس بدون کد وضعیت دسترسی به متد
Translate
برای نمایش متن خطای مناسب در هر زمانی مثلا لیست تراکنش ها نداریم.

**Comment by Sina-Soltani** [comment]
> 
> 
> آیا کد وضعیت درون حافظه پرباد ذخیره میشود؟
خیر

> پس بدون کد وضعیت دسترسی به متد
> Translate
> برای نمایش متن خطای مناسب در هر زمانی مثلا لیست تراکنش ها نداریم.

پیام‌ها توسط پَرباد ترجمه میشن.از پراپرتی
Message
به همین منظور میتونید استفاده کنید
