### ISSUE TITLE
عدم انتقال به درگاه پرداخت پارسیان

### ISSUE THREAD

**Issue by sina-ssghm** [Sina-Soltani/Parbad#58]
### توضیح خطا
 سلام من برای راه اندازی درگاه پارسیان از بانک یک pincode و یک terminalId گرفتم
در زمان اضافه کردن درگاه با پرباد پارامتری با عنوان LoginAccount گرفته میشه و نه چیز دیگری
من هر 2 کلیدی که از بانک گرفتم رو تست کردم و در هر 2 حالت مشکل داشتم.
لطفا راهنمایی کنید

از ورژن جدید استفاده میکنم

### نوع برنامه وب
ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود
نتیجه درخواست
Request
به چه صورت بوده؟
آیا موفق بوده یا غیر موفق؟
آیا خطایی رخ میده و یا پیغامی از پرباد دریافت کردید؟

**Comment by sina-ssghm** [comment]
var result = await onlinePayment.RequestAsync(configureInvoice: invoice =>
               {
                   invoice.SetTrackingNumber(transactionId);
                   invoice.SetCallbackUrl(callback);
                   invoice.UseParsian();
                   invoice.SetAmount(amount);

               });
result.IsSucceed => false
Unexpected end tag. Line 1, position 3.

طریقه رجیستر کردن درگاه هم  بوسیله 
IGatewayAccountSource
هست

**Comment by Sina-Soltani** [comment]
لطفا داکیومنتی درگاه پرداخت که از بانک پلرسیان دریافت کردید رو اینجا قرار بدید.
(بدون ذکر کردن اطلاعات حساس بانکی)

این احتمال میتونه وجود داشته باشه که تغییراتی در سیستمشون داده باشن.

همچنین در
GatewayAccountSource
که پیاده سازی کردید یک بریک پوینت بزارید و یک درخواست پرداخت ارسال کنید ببینید که کد شما فراخوانی میشه یا خیر

**Comment by sina-ssghm** [comment]
پذيرنده گرامي   با سلام و   احترام        ضمن تشکر از حسن انتخاب شما در انتخاب درگاه پرداخت اينترنتي پارسيان به اطلاع   مي رساند درخواست شما با موفقيت در سامانه هاي اين شرکت پردازش و درگاه پرداخت   اينترنتي پارسيان آماده پياده سازي و فعالسازي در سايت شما مي باشد.    ا 

PIN CODE:*********
Terminal:*********

[مستندات](https://pgw.pec.ir/IPG/Docs/IPGSW1/IPGSW1Sale.zip)
[نمونه  کد .net](https://pgw.pec.ir/IPG/PecPGW.Samples.zip)

**Comment by Sina-Soltani** [comment]
پارامتر
LoginAccount
در درون داکیومنتی که ارسال کردید هم موجود هست
بنابراین تغییری به وجود نیومده
لطفا از جایی که درگاه رو دریاف کردید سوال کنید که
Pin code
و
Terminal
برای چی هستن چون در داکیومنتی که خودشون دادن، چنین چیزی وجود نداره و فقط
LoginAccount
وجود داره

نتیجه رو گزارش بدید تا بررسی کنیم

**Comment by sina-ssghm** [comment]
مهندس پرسیدم گفتن 
loginacount
همون 
pincode 
هست .وارد کردم ولی باز کار نکرد.سمپل خود تاپ اوکی بود منو انتقال داد ولی پرباد همون خطا رو میده هنوز.بریک پوینت هم گذاشتم مشکلی نداشت

**Comment by Sina-Soltani** [comment]
امروز بررسی میکنم بهتون خبر میدم

**Comment by Sina-Soltani** [comment]
فکر میکنم در اطلاعات حساب بانکی که به شما دادند، کاراکتر‌هایی وجود داشته باشه که باعث تولید خطا میشده

لطفا ورژن جدید رو امتحان کنید و نتیجه رو خبر بدید
[Parbad.3.2.3-beta1](https://www.nuget.org/packages/Parbad/3.2.3-beta1)
```
Install-Package Parbad -Version 3.2.3-beta1
```

**Comment by sina-ssghm** [comment]
سلام ممنون از پیگیریتون . درست نشده
`XML loading exception. Unexpected end tag. Line 1, position 3.`

**Comment by Sina-Soltani** [comment]
درود

لطفا
LoginAccount
رو برای من ایمیل کنید تا بررسی کنم
soltani.sina1989@live.com

**Comment by Sina-Soltani** [comment]
LoginAccount
که ایمیل کردید رو تست کردم و کار میکنه هر چند که پیغام آدرس آی پی معتبر نمی باشد رو از بانک پارسیان دریافت میکنم ولی این نشون میده که برنامه درست کار میکنه و صرفا چون من از یک آدرس غیر معتبر دارم ارسال میکنم این پیغام رو میگیرم
در نتیجه برنامه به درستی بدون خطا کار میکنه

لطفا تنظیمات پَرباد رو اینجا قرار بدید تا اون رو هم بررسی کنیم
(بدون قرار دادن اطلاعات حساس)

**Comment by sina-ssghm** [comment]
` 
services.AddParbad()
                .ConfigureGateways(gateways =>
                {
                    
                    gateways.AddParsian()
                    
                    .WithAccounts(source =>
                    {
                        source.Add<ParsianAccountSource>(ServiceLifetime.Transient);
 
                    });
                    gateways.AddSaman()
                    
                    .WithAccounts(source =>
                    {
                        source.Add<SamanAccountSource>(ServiceLifetime.Transient);
 
                    });
                    
                })
                .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
                .ConfigureStorage(builder =>
                {
                    builder.UseEntityFrameworkCore(ef => ef.UseSqlServer(Configuration.GetConnectionString("ParbadConnection"), options => options.UseParbadMigrations()))
                    .ConfigureDatabaseInitializer(builder =>
                    {
                        // For creating
                        //builder.CreateDatabase();

                        // For creating and migrating
                        //builder.CreateAndMigrateDatabase();

                        // For deleting and recreating
                        //builder.DeleteAndCreateDatabase();

                        //// Define a custom database initializer
                        builder.AddInitializer(async context =>
                        {
                            await context.Database.MigrateAsync();
                        });
                    }); ;
                });

`
` public class ParsianAccountSource : IGatewayAccountSource<ParsianGatewayAccount>
    {
        private readonly IUnitOfWork unitOfWork;

        public ParsianAccountSource(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public async Task AddAccountsAsync(IGatewayAccountCollection<ParsianGatewayAccount> accounts)
        {
            var repo = unitOfWork.Repository<Gateway>();
            Expression<Func<Gateway, bool>> gatewayCondition = s => s.IsActive == true && s.GatewayType == Domain.Enum.GatewayType.Parsian;
            if (repo.All.Any(gatewayCondition))
            {
                var gateway = await repo.All.FirstOrDefaultAsync(gatewayCondition);
                accounts.Add(new ParsianGatewayAccount 
                {
                    Name = gateway.Title,
                    LoginAccount = "",
                   
                });
            }
        }
    }
`
` var result = await onlinePayment.RequestAsync(configureInvoice: invoice =>
               {
                   invoice.SetTrackingNumber(transactionId);
                   invoice.SetCallbackUrl(PaymentInput.CallBack(context, transactionId, tripId));
                   invoice.UseParsian();
                   invoice.SetAmount(amount);

               });
            if (result.IsSucceed)
            {
                return new OperationResult<object>
                {
                    Succeed = true,
                    Data = result.GatewayTransporter,
                };
            }
            return new OperationResult<object>
            {
                Succeed = false,
                Message = "با عرض پوزش درگاه پرداخت انتخاب شده در حال حاضر قادر به پاسخ گویی نیست"
            };`



دقیقا روی 
result.IsSucceed
false 
دریافت میکنم و منتقل نمیشه

**Comment by Sina-Soltani** [comment]
[PTest.zip](https://github.com/Sina-Soltani/Parbad/files/4097644/PTest.zip)

این سمپل رو دانلود کنید
لاگین اکانت رو در تنظیمات به صورت دستی وارد کنید
و سمپل رو روی هاست امتحان کنید

نتیجه رو لطفا گزارش بدید

**Comment by sina-ssghm** [comment]
مهندس باگ رو پیدا کردم .همه چیز اوکیه مشکلی نداره تنها چیزی که هست اینه که متد
.SetCallbackUrl("https://localhost:5002/Payment/Verify?id=105")
با این مقداری که من ست کردم کار نمیکنه فکر میکنم واسه علامت سوال باش.با سولوشن خودتون هم تست کردم خطا داد.
لطفا چک کنید

**Comment by Sina-Soltani** [comment]
مشکل همون کاراکترهایی هست که گفتم احتمالا باعث خطا میشن و حق با شماست مشکل در آدرس برگشتی هست که شما ارسال کردید
(البته نه برای علامت سوال)

امروز آپدیت جدید آماده میکنم برای این مشکل و اطلاع میدم

**Comment by Sina-Soltani** [comment]
لطفا ورژن جدید رو امتحان کنید و نتیجه رو خبر بدید
[Parbad.3.2.3-beta2](https://www.nuget.org/packages/Parbad/3.2.3-beta2)
```
Install-Package Parbad -Version 3.2.3-beta2
```

**Comment by sina-ssghm** [comment]
سلام 
ممنون از پیگیری دقیق و سریع شما 
مشکل حل شد.

**Comment by Sina-Soltani** [comment]
خواهش میکنم
زدن دکمه ستاره (بالای صفحه گیت هاب) برای پروژه، به معنای رضایت و تشکر هست

موفق باشید
