### ISSUE TITLE
Wrong Action name in MVC sample code

### ISSUE THREAD

**Issue by Hameds** [Sina-Soltani/Parbad#59]
Here in MVC sample code`PayRequest` should be `Pay`
https://github.com/Sina-Soltani/Parbad/blob/cda1b4ed833a03cf598709caf2d8eb938448bd30/samples/Parbad.Sample.Mvc/Views/Payment/Pay.cshtml#L5

**Comment by Sina-Soltani** [comment]
Thank you @Hameds . I will fix the samples.
