### ISSUE TITLE
لزوم وجود کد پاسخ مناسب بجای پیغام "The requested payment is already processed before."

### ISSUE THREAD

**Issue by mrmashal** [Sina-Soltani/Parbad#60]
### توضیح خطا
با سلام. هنگامی که متد
OnlinePayment.VerifyAsync
برای تراکنشی که قبلا تایید شده فراخوانی شود، تنها راه برای تشخیص این موضوع، پیغام متنی
"The requested payment is already processed before."
است. به نظرم بهتر است این موضوع با تعریف یک کد در مقدار برگشتی مشخص شود و در مثالها هم تاکید شود چون در حال حاضر مقدار برگشتی مانند یک تراکنش ناموفق است و اگر مثلا به هر دلیلی صفحه بانک دو بار برای سرور ما ارسال شود، اگر کد ما با دقت نوشته نشده باشد امکان رونویسی یک تراکنش موفق بصورت ناموفق وجود دارد

### نام و نسخه پکیج
Parbad.AspNetCore
1.0.1

### نوع برنامه وب
ASP.NET CORE

**Comment by Sina-Soltani** [comment]
درود

بررسی میکنم

**Comment by Sina-Soltani** [comment]
لطفا نسخه جدید را نصب کنید
```
Install-Package Parbad -Version 3.3.0
```
