### ISSUE TITLE
درگاه مجازی با IIS Express در اکثر موارد کار نمی‌کند

### ISSUE THREAD

**Issue by m-rambod** [Sina-Soltani/Parbad#61]
### توضیح خطا
سلام جناب سلطانی
اول اینکه واقعاً بابت تهیه کردن پکیج پرباد ازتون تشکر میکنم. واقعاً کار من رو که برای اولین بار سمت برنامه‌نویسی پرداخت آنلاین می‌رفتم، راحت کرد.
و اما مشکل من اینه که درگاه مجازی در حالتی که وبسایت رو با
IIS Express
باز میکنم در اکثر مواقع باز نمیشه و مرورگر در حالت لودینگ میمونه و هیچ پیغام خطایی رو هم نمیده
اما وقتی وبسایت رو پابلیش میکنم مشکلی نداره و درست کار میکنه

### نام و نسخه پکیج
[Parbad]
[3.2.3]

### نوع برنامه وب
ASP.NET MVC

**Comment by Sina-Soltani** [comment]
درود

> اول اینکه واقعاً بابت تهیه کردن پکیج پرباد ازتون تشکر میکنم. واقعاً کار من رو که برای اولین بار سمت برنامه‌نویسی پرداخت آنلاین می‌رفتم، راحت کرد.

خواهش میکنم

> و اما مشکل من اینه که درگاه مجازی در حالتی که وبسایت رو با
> IIS Express
> باز میکنم در اکثر مواقع باز نمیشه و مرورگر در حالت لودینگ میمونه و هیچ پیغام خطایی رو هم نمیده
> اما وقتی وبسایت رو پابلیش میکنم مشکلی نداره و درست کار میکنه

برنامه ها تست شده و چنین مشکلی وجود نمیتونه داشته باشه
لطفا کد‌های مربوط به تنظیمات و پرداخت پَرباد رو اینجا قرار بدید تا بررسی کنیم

**Comment by m-rambod** [comment]
> برنامه ها تست شده و چنین مشکلی وجود نمیتونه داشته باشه
> لطفا کد‌های مربوط به تنظیمات و پرداخت پَرباد رو اینجا قرار بدید تا بررسی کنیم
>>
کد مربوط به تنظیمات:
```
 public static IParbadBuilder Configure()
        {
            var connectionString = System.Configuration.ConfigurationManager.ConnectionStrings["Parbad"].ConnectionString;
            return ParbadBuilder.CreateDefaultBuilder()
                .ConfigureGateways(gateways =>
                {
                    gateways
                        .AddMellat()
                        .WithAccounts(accounts =>
                        {
                            accounts.AddInMemory(account =>
                            {
                                account.TerminalId = 123;
                                account.UserName = "MyId";
                                account.UserPassword = "MyPassword";
                            });
                        });

                    gateways
                        .AddParbadVirtual()
                        .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
                })
                .ConfigureHttpContext(builder => builder.UseOwinFromCurrentHttpContext())
                .ConfigureStorage(builder =>
                {
                    builder
                    .UseEntityFrameworkCore(ef => ef.UseSqlServer(connectionString, options => options.UseParbadMigrations()))
                    .ConfigureDatabaseInitializer(builder =>
                    {
                        builder.CreateAndMigrateDatabase();
                    });
                });
        }
```

کد مربوط به اکشن PayRequest
```
var result = await _onlinePayment.RequestAsync(invoice =>
                {
                    invoice
                        .UseAutoIncrementTrackingNumber()
                        .SetAmount(payViewModel.Amount)
                        .SetCallbackUrl(verifyUrl)
                        .SetGateway(payViewModel.Gateway.ToString());
                });

                if (result.IsSucceed)
                {
                    Handler.Reservation.SetPayTrackingNumber(reservation.Id, result.TrackingNumber);
                    return result.GatewayTransporter.TransportToGateway();
                }
```

**Comment by Sina-Soltani** [comment]
Owin
در برنامه شما فعال هست؟

**Comment by m-rambod** [comment]
> Owin
> در برنامه شما فعال هست؟
>>
من از
ASP.NET Identity
استفاده میکنم. همین موضوع فعال بودن اُوین رو ثابت میکنه؟
ضمن اینکه وقتی وبسایت روی 
IIS
دیپلوی میشه دیگه مشکلی نداره و همه چیز اوکیه
> 
> آیا درگاه مجازی رو فعال کردید؟
>>
بله فعال شده
```
 public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);
            InitializeIdentity();


            var containerBuilder = new ContainerBuilder();
            ConfigureServices(containerBuilder);
            var container = containerBuilder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
            app.UseAutofacMiddleware(container);
            app.UseAutofacMvc();

            var serviceProvider = container.Resolve<IServiceProvider>();
            app.UseParbadVirtualGateway(serviceProvider);
        }
```

**Comment by Sina-Soltani** [comment]
[WebApplication8.zip](https://github.com/Sina-Soltani/Parbad/files/4147825/WebApplication8.zip)

این سمپل را اجرا کنید ببینید آیا درگاه مجازی اجرا میشه یا خیر

**Comment by m-rambod** [comment]
> [WebApplication8.zip](https://github.com/Sina-Soltani/Parbad/files/4147825/WebApplication8.zip)
> 
> این سمپل را اجرا کنید ببینید آیا درگاه مجازی اجرا میشه یا خیر

بله اجرا میشه

**Comment by Sina-Soltani** [comment]
پس باید نگاه کنید ببینید مشکل برنامتون چه چیزی میتونه باشه.
شاید
Owin
به درستی برنامه ریزی نشده باشه

**Comment by Sina-Soltani** [comment]
آیا نتیجه ای بدست آوردین؟
این تیکت رو باید ببندیم؟

**Comment by m-rambod** [comment]
خیر متاسفانه نتیجه ای حاصل نشد
به هر حال از وقتی که گذاشتید بسیار سپاسگزارم

**Comment by Sina-Soltani** [comment]
خواهش میکنم.
در صورتی که تمایل داشتید میتونید این پکیج رو در قسمت بالای صفحه ستاره بزنید تا بقیه هم مطلع بشن و استفاده کنن
موفق باشید

**Comment by m-rambod** [comment]
با کمال میل
