### ISSUE TITLE
اضافه کردن درگاه ها بصورت داینامیک

### ISSUE THREAD

**Issue by castell0riz0n** [Sina-Soltani/Parbad#66]
Hi. there was another issue about adding gateways dynamically (#52 ) and you said it's not possible for now
do you have any solution to configure gateways dynamically for different companies and gateways in startup using database source ?

**Comment by Sina-Soltani** [comment]
Hi,
Yes it's possible. I will add it to the next release.
I can't tell you a specific release date but maybe within a week. Because there are also another improvements and features which must be added all together.

**Comment by castell0riz0n** [comment]
This is great. Thanks . 👌

**Comment by Sina-Soltani** [comment]
About the feature that you need, can something like this help you?

`Startup.cs`
```csharp
services.AddParbad()
.ConfigureGateways(gateways => 
{
   gateways.Add<YourDynamicGatewaySource>();
})
```

```csharp
public class YourDynamicGatewaySource
{
   private readonly IYourDatabase _database;

   public YourDynamicGatewaySource(IYourDatabase database)
   {
      _database = database;
   }

   public void Add(GatewayCollection collection)
   {
         var gateways = database.GetAllGateways();
         
         foreach(var gateway in gateways)
         {
            switch(gateway.Type)
            {
               case YourGatewayTypes.Parsian:
                  collection.AddParsian()........
                  break;
            }
         }
   }
}
```

**Comment by castell0riz0n** [comment]
yes, something like this will perfectly fine. (using Database or services to fetch gateways data)

**Comment by Mansoun** [comment]
Hi mr Soltani. I appreciate to you. but have a small queastion. 
in the persian website, you said for dynamic setting bank account , we should use IParbadOptionsProvider<MellatGatewayOptions> . 
after two days I found this issue page and i realized the problem wasn't me .. hopefully :D
so this dynamic mechanism system is very important to us and its a grate feature. 
we are waiting for new version . 
Thanks.

**Comment by Sina-Soltani** [comment]
> 
> 
> Hi mr Soltani. I appreciate to you. but have a small queastion.
> in the persian website, you said for dynamic setting bank account , we should use IParbadOptionsProvider .
> after two days I found this issue page and i realized the problem wasn't me .. hopefully :D
> so this dynamic mechanism system is very important to us and its a grate feature.
> we are waiting for new version .
> Thanks.

@Mansoun 
Hi,
I think you were looking wrong.  `IParbadOptionsProvider` is something different than Gateway Account.

There are 2 different things:

- Adding Gateway dynamically
- Adding Gateway Account dynamically

Which one are you looking for?
The second one (Gateway Account) does already exist and you can easily use it
Here can you see the tutorials: [Adding Gateway Accounts using a custom source](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#adding-an-account-using-a-custom-source-such-as-database)

The first one (Gateway) is under development. It's going to be release in some days later (I can't say an exact date because I'm very busy right now)

**Comment by Mansoun** [comment]
Hi.
Yes your right. I wanted that link. Thanks again and good luck ;)

**Comment by castell0riz0n** [comment]
Hi Sina, feature implemented or not ?

**Comment by Sina-Soltani** [comment]
Hi,
no still not. unfortunately I don't have enough time for that.
For now I close the ticket but I will do it later.

**Comment by castell0riz0n** [comment]
Thanks, good luck dude 👍

**Comment by sadeq-qafari** [comment]
Hi,

I need to set the gateway account just before creating invoice, without adding it to a list of accounts, because I may have thousands or hundreds of thousands of accounts and I think it's not a good idea to load them all in one place.

Is this feature implemented?

**Comment by Sina-Soltani** [comment]
Hi, still not yet.
Lots of things must be changed and this is not a small feature. I need time for that cause I'm busy and can handle only the small features first. But I'm working on it.
By the way, people can contribute and develop new features themselves and send pull requests.
