### ISSUE TITLE
درگاه مجازی

### ISSUE THREAD

**Issue by amirreza58** [Sina-Soltani/Parbad#71]
در بخش درگاه مجازی درصورت کنسل کردن پرداخت  در هنگام Verify

`
var verifyResult = await _onlinePayment.VerifyAsync(invoice);
`

همواره
`
verifyResult = verifyResult.IsSucceed
verifyResult.Status = PaymentVerifyResultStatus.Succeed
`
میشود در صورتیکه 
`
verifyResult.TransactionCode = ""
`
است

**Web application type:**
* ASP.NET CORE

**Comment by Sina-Soltani** [comment]
بررسی میشه

**Comment by Sina-Soltani** [comment]
لطفا نسخه جدید را نصب کنید
```
Install-Package Parbad -Version 3.3.3
```

**Comment by amirreza58** [comment]
سلام
مشکل رفع شده است
ممنون
