### ISSUE TITLE
مشکل در Verify

### ISSUE THREAD

**Issue by feryt20** [Sina-Soltani/Parbad#72]
**Bug description (wIthout specifiing the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**
برنامه هنگام بازگشت به متد وریفای در قسمت وریفای اسینک گیر میکنه و هیچ خطایی نمیده
نمیدونم آیا باید جای خاصی کد خاصی اضافه کنم؟
کدهای برنامه:

` public async Task<ActionResult> Pay()
        {
            var verifyUrl = Url.Action("Verify", "Home", null, Request.Url.Scheme);

            var result = await _onlinePayment.RequestAsync(invoice =>
            {
                invoice
                    .SetAmount(10000)
                    .SetCallbackUrl(verifyUrl)
                    .UseAutoIncrementTrackingNumber()
                    .SetGateway(Gateways.ParbadVirtual.ToString());
            });

            if (result.IsSucceed)
            {
                return result.GatewayTransporter.TransportToGateway();
            }
            else
            {
                // درخواست پرداخت موفقیت آمیز نبود
            }

            return View("Error" , result);
        }

        public async Task<ActionResult> Verify()
        {
            var invoice = await _onlinePayment.FetchAsync();

            // Check if the invoice is new or it's already processed before.
            if (invoice.Status == PaymentFetchResultStatus.AlreadyProcessed)
            {
                // You can also see if the invoice is already verified before.
                var isAlreadyVerified = invoice.IsAlreadyVerified;
                return Content("The payment is already processed before.");
            }

            // An example of checking the invoice in your website.
            if (!Is_There_Still_Product_In_Shop(invoice.TrackingNumber))
            {
                var cancelResult = await _onlinePayment.CancelAsync(invoice, cancellationReason: "Sorry, We have no more products to sell.");

                return View("CancelResult", cancelResult);
            }

            var verifyResult = await _onlinePayment.VerifyAsync(invoice);
         
            return View(verifyResult);
        }`

` public void ConfigureServices(ContainerBuilder containerBuilder)
        {
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            containerBuilder.RegisterControllers(typeof(HomeController).Assembly);

            var parbadBuilder = ParbadBuilder.CreateDefaultBuilder()
                                  .ConfigureGateways(gateways =>
                                  {
                                      gateways
                                           .AddMellat()
                                           .WithAccounts(source =>
                                           {
                                               source.AddInMemory(account =>
                                               {
                                                   account.TerminalId = 123;
                                                   account.UserName = "user";
                                                   account.UserPassword = "pass";
                                               });
                                           });
                                      gateways
                                         .AddParbadVirtual()
                                         .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
                                  })
                                    .ConfigureHttpContext(builder => builder.UseOwinFromCurrentHttpContext())
                                    .ConfigureStorage(builder => builder.UseMemoryCache());

            containerBuilder.Populate(parbadBuilder.Services); 
        }

        public void Configuration(IAppBuilder app)
        {
            var containerBuilder = new ContainerBuilder();
            ConfigureServices(containerBuilder);
            var container = containerBuilder.Build();
            DependencyResolver.SetResolver(new AutofacDependencyResolver(container));
            app.UseAutofacMiddleware(container);
            app.UseAutofacMvc();
            var serviceProvider = container.Resolve <IServiceProvider>();
            app.UseParbadVirtualGateway(serviceProvider);

            //ConfigureAuth(app);
        }`

**Package name and version**
**نام و نسخه پکیج**
* Package Name: parbad
* Version: 3.3.2

**Web application type:**
**نوع برنامه وب**
* ASP.NET MVC

**Comment by Sina-Soltani** [comment]
برنامه تست شد و مشکلی وجود نداره
لطفا اپلیکیشن خود را کنترل کنید.

همچنین برای اطمینان خاطر از عملکرد برنامه، میتوانید نمونه مثال را دانلود و امتحان کنید
[MVC Sample](https://github.com/Sina-Soltani/Parbad/tree/master/samples/Parbad.Sample.Mvc)
