### ISSUE TITLE
عدم انتقال به درگاه ملت

### ISSUE THREAD

**Issue by feryt20** [Sina-Soltani/Parbad#74]
**Bug description (wIthout specifiing the sensitive data)**
**توضیح خطا (بدون ذکر کردن اطلاعات خصوصی درگاه بانکی)**
با سلام و احترام
برنامه به درگاه بانک ملت هدایت نمیشه و همینجوری توی لود گیر میکنه
حتی نمونه سمپل هم همین مشکل رو داره
فعلا وب فرم رو تست کردم اینجوری بود
احتمالا بقیه هم همین مشکل و دارن
لطفا بررسی کنید

**Package name and version**
**نام و نسخه پکیج**
* Package Name: Parbad
* Version: 3.3.3

**Web application type:**
**نوع برنامه وب**
* ASP.NET MVC
* ASP.NET WebForms

**Comment by Sina-Soltani** [comment]
درود
بررسی میشه

**Comment by feryt20** [comment]
ممنون
داشتم دیباگ میکردم گویا مشکل از کلاس زیر هست
MellatGateway.cs
خط 48 به بعد اجرا نمیشه
`var responseMessage = await _httpClient
                .PostXmlAsync(MellatHelper.GetWebServiceUrl(account.IsTestTerminal), data, cancellationToken)
                .ConfigureAwaitFalse();`

**Comment by Sina-Soltani** [comment]
برنامه روی 
ASP.NET MVC
تست شد و مشکلی نداره

اما ظاهرا در
ASP.NET WebForms
موقع برگشت مشکلی با کانتکست وجود داره که باید بررسی کنم و اطلاع میدم.


> 
> 
> ممنون
> داشتم دیباگ میکردم گویا مشکل از کلاس زیر هست
> MellatGateway.cs
> خط 48 به بعد اجرا نمیشه
> `var responseMessage = await _httpClient .PostXmlAsync(MellatHelper.GetWebServiceUrl(account.IsTestTerminal), data, cancellationToken) .ConfigureAwaitFalse();`

درگاه ملت تست شد و مشکلی مشاهده نشد.
آیا خطایی دریافت میکنید؟

**Comment by feryt20** [comment]
مشکل اینجاس که برنامه هیچ خطایی نمیده
باید یه خطا بده ولی خطا نمیده
من یه فیلم گرفتم الان آپلود میکنم

**Comment by feryt20** [comment]
اول با درگاه پارسیان تست کردم ببینید خطا میده
بعد با ملت تست کردم 
http://s11.picofile.com/file/8394128768/2020.zip.html

**Comment by feryt20** [comment]
توی ام وی سی مشکلی نداره و ارور میده پذیرنده نامعتبر
ولی
توی وب فرم هیچ اروری نمیده و توی صفحه لودینگ میمونه

**Comment by Sina-Soltani** [comment]
> 
> 
> اول با درگاه پارسیان تست کردم ببینید خطا میده
> بعد با ملت تست کردم
> http://s11.picofile.com/file/8394128768/2020.zip.html

خطایی که دارید برای بانک پارسیان میبینید کاملا مشخص هست. لطفا متن خطا رو بخونید
نوشته که بانک پارسیان نه اضافه شده و نه تنظیم نشده

**Comment by feryt20** [comment]
> 
> 
> > اول با درگاه پارسیان تست کردم ببینید خطا میده
> > بعد با ملت تست کردم
> > http://s11.picofile.com/file/8394128768/2020.zip.html
> 
> خطایی که دارید برای بانک پارسیان میبینید کاملا مشخص هست. لطفا متن خطا رو بخونید
> نوشته که بانک پارسیان نه اضافه شده و نه تنظیم نشده

برای بانک ملت هم باید همین خطا رو بده یا بگه پذیرنده نامعتبر

الان همین مورد رو توی ام وی سی چک کنید ارور میده پذیرنده نامعتبر

ولی توی وب فرم هیچ اتفاقی نمیوفته و روی لودینگ گیر میکنه

**Comment by feryt20** [comment]
من الان فیلم میگیرم روی ام وی سی ببینید چه اتفاقی میوفته
توی ام وی سی اطلاعات میره سرور بانک ملت و نتیجه ای که برمیگرده توی صفحه وریفای میگه پذیرنده_نامعتبر
اما توی وب فرم اطلاعات نمیره و برگرده انگار
الان ویدیو آپلود میکنم
بازم ممنون

**Comment by Sina-Soltani** [comment]
> 
> 
> من الان فیلم میگیرم روی ام وی سی ببینید چه اتفاقی میوفته
> توی ام وی سی اطلاعات میره سرور بانک ملت و نتیجه ای که برمیگرده توی صفحه وریفای میگه پذیرنده_نامعتبر
> اما توی وب فرم اطلاعات نمیره و برگرده انگار
> الان ویدیو آپلود میکنم
> بازم ممنون

همونطور که در کامنت های بالا گفتم، ظاهرا مشکلی در
ASP.NET WebForms
وجود داره که در حال بررسی هستم
در نتیجه تست های درگاه‌ها رو فقط با
ASP.NET CORE
یا
ASP.NET MVC
انجام بدید

**Comment by feryt20** [comment]
چک کردم
هم اموی سی هم دات نت کور بدون مشکل اجرا میشن
فقط وب فرم مشکل داره
http://s10.picofile.com/file/8394130684/2021.zip.html

**Comment by Sina-Soltani** [comment]
مشکل بررسی شد
ایراد از پلتفرم
ASP.NET WebForms
هست که با پردازش‌های موازی و بلاک شده مشکل داره
روش حل مشکل رو به زودی اینجا میزارم

**Comment by feryt20** [comment]
سپاسگزارم

**Comment by Sina-Soltani** [comment]
طبق صحبت هایی که با تیم
ASP.NET
کردم، ایراد از پلتفرم
ASP.NET WebForms
هست. به هر حال این پلتفرم قدیمی و منقرض شده هست و اینگونه مسائل طبیعی هست

امروز نسخه جدیدی منتشر میکنم که این مشکل رو پوشش بده
بعد از انتشار خبر میدم

**Comment by feryt20** [comment]
خیلی ممنون

**Comment by Sina-Soltani** [comment]
لطفا نسخه جدید پَرباد رو نصب کنید
`Install-Package Parbad -Version 3.4.0`
`Install-Package Parbad.Owin -Version 1.0.4`

سپس صفحه های
.aspx
که درون اونها کد پَرباد نوشته شده رو باز کنید و در خط بالای آن جایی که عنوان و سایر مشخصات نوشته شده، مقدار زیر رو تنظیم کنید
`Async="true"`
[مثال](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.WebForm/PayRequest.aspx#L1)

سپس متدهایی که از پَرباد استفاده میکنن رو نیز به
async
تغییر بدید
[مثال](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.WebForm/PayRequest.aspx.cs#L18)

نمونه کامل پروژه
[ASP.NET WebForms Sample](https://github.com/Sina-Soltani/Parbad/tree/master/samples/Parbad.Sample.WebForm)

**Comment by feryt20** [comment]
ممنون
