### ISSUE TITLE
خطا در ارسال کاربر به درگاه زرین پال

### ISSUE THREAD

**Issue by Mansoun** [Sina-Soltani/Parbad#75]
توضیح خطا:
هیچ اروری نمیده و توی همون ویو میمونه!
بعد از اینکه 
Result.IsSucceed
میشود
به درگاه منتقل نمیشه.

Parbad 3.3.3.0
Parbad.Gateway.ZarinPal 1.0.4.0

 ASP.NET MVC 5.2

**Comment by Sina-Soltani** [comment]
لطفا کد‌های مربوط به تنظیمات و پرداخت رو قرار بدید تا بررسی کنیم
در صورت امکان از آبجکت
result
و محتویات آن اسکرین شات بگیرید اینجا قرار بدید

**Comment by Mansoun** [comment]
public class ZarrinPalSource : IGatewayAccountSource<ZarinPalGatewayAccount>
    {
        private readonly IBankManagement _bankmanagement;
        public ZarrinPalSource(IBankManagement bankmanagement)
        {
            _bankmanagement = bankmanagement;
        }
        public async Task AddAccountsAsync(IGatewayAccountCollection<ZarinPalGatewayAccount> accounts)
        {
            var settings = await _bankmanagement.findByEnumName(BanksENUM.ZarinPal);

            accounts.Add(new ZarinPalGatewayAccount
            {
                Name = settings.Name,
                MerchantId = settings.MerchantId,
                IsSandbox = true
            });
        }
    }
________________________________________________________________________
return ParbadBuilder.CreateDefaultBuilder()
                .ConfigureGateways(gateways =>
                {
 gateways.AddZarinPal()
                    .WithAccounts(source =>
                    {
                        source.Add<ZarrinPalSource>(ServiceLifetime.Transient);
                    });
 gateways
                         .AddParbadVirtual()
                         .WithOptions(options => options.GatewayPath = "/MyVirtualGateway");
                })
                .ConfigureHttpContext(builder => builder.UseOwinFromCurrentHttpContext())
                .ConfigureStorage(builder => builder.UseMemoryCache());
_______________________________________________________________________
 var verifyUrl = Url.Action("Verify", "Register",new {Area = "student"}, Request.Url.Scheme);

            if (vm.BankSelected == "ZarinPal")
            {
                var result = await _onlinePaymentParbod.RequestAsync(invoice =>
                {
                    invoice
                        .SetAmount(Orderprice.Price)
                        .SetCallbackUrl(verifyUrl)
                        .UseZarinPal("ثبت نام در دوره", currentUser.Email, currentUser.PhoneNumber);
                    invoice.SetTrackingNumber(Orderprice.OrderId);
                });
                if (result.IsSucceed)
                {
                    return result.GatewayTransporter.TransportToGateway();
                }
![zarinIssue](https://user-images.githubusercontent.com/35144971/79436837-a2dfc100-7fe6-11ea-8e3f-4bfbe7d372b5.png)

**Comment by Sina-Soltani** [comment]
درگاه زرین پال تست شد و مشکلی مشاهده نشد
هر چند که کدهای شما هم ظاهرا مشکلی ندارن ولی احتمال داره که مشکل از تنظیمات خود برنامه
MVC
شما باشه

آیا
OWIN
رو به روش صحیح تنظیم کردید؟
در صورت امکان، کدهای کلاس
Startup
مروبوط به تنظیمات
OWIN
رو قرار بدید تا بررسی
کنیم.
(اطلاعات حساس و خصوصی رو حذف کنید)

**Comment by Mansoun** [comment]
تا جایی که میدونم درست تنظیم شده. یه مشکلی روی کانتینر تزریق وابستگی داشتم که با راهنمایی های شما حل شد. در اسرع وقت تا فردا کدهای 
Startup
و تنظیمات 
Owin 
رو میفرستم. 
ممنون

**Comment by Mansoun** [comment]
بعد از بررسی های زیاد متوجه نشدم مشکل از چیه دقیقا
` public void Configuration(IAppBuilder app)
        {
            app.MapSignalR();
            ConfigureAuth(app);
            var parbad = ParbadConfig.Configure();
            var container = SmObjectFactory.Container;
            container.Populate(parbad.Services);

            ParbadBuilder.CreateDefaultBuilder()
               .ConfigureHttpContext(builder => builder.UseOwinFromCurrentHttpContext());
        }`
__________________________________________________________________________
` protected void Application_Start()
        {
            System.Web.Mvc.ModelBinders.Binders.Add(typeof(DateTime), new PersianDateModelBinder());
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
            setDbInitializer();
            //Set current Controller factory as StructureMapControllerFactory
            ControllerBuilder.Current.SetControllerFactory(new StructureMapControllerFactory());
            Microsoft.AspNet.SignalR.GlobalHost.DependencyResolver = SmObjectFactory.Container.GetInstance<Microsoft.AspNet.SignalR.IDependencyResolver>();


        }`

**Comment by Sina-Soltani** [comment]
فکر میکنم
OWIN
در پروژه شما شاید اشتباه پیاده سازی شده باشه

همچنین سوالی که پیش میاد اینه که چرا بعد از تنظیم پَرباد، دوباره اون رو بعد از این خط تنظیم میکنید؟
```c#
container.Populate(parbad.Services);
```

**Comment by Mansoun** [comment]
سلام.
منظور شما این تنظیمه؟
`ParbadBuilder.CreateDefaultBuilder()
               .ConfigureHttpContext(builder => builder.UseOwinFromCurrentHttpContext());`
این رو کامنت کردم باز تغییری نکرد.
با توجه به سمپل شما تنظیمات خاصی برای 
Owin
پیدا نکردم و طبق سمپل شما تنظیمات رو انجام دادم.
راهی برای دیباگ کردن 
TransportToGateway()
نیست؟

**Comment by Sina-Soltani** [comment]
برای مثال، یکی از مواردی که پیاده‌سازی اشتباهی هست اینه که زمانیکه یک پروژه
OWIN Base
هست، دیگه وجود فایل
Global.asax
معنی نداره

**Comment by Mansoun** [comment]
درسته.
نکته ای که هست کلا پروژه نمیتونه به لینک های خارجی ریدایرکت کنه.
چیزی که برمیگردونه اینه که توی اسکرین شات هم مشهوده

> Session = '((Microsoft.AspNetCore.Http.DefaultHttpContext)((Parbad.Owin.Http.OwinHttpContextAccessor)((Parbad.Internal.GatewayRedirect)((Parbad.Internal.PaymentRequestResult)result).GatewayTransporter)._httpContextAccessor).HttpContext).Session' threw an exception of...

![zarinIssue2](https://user-images.githubusercontent.com/35144971/79555810-6af37f00-80b5-11ea-9409-fa082747a104.png)

**Comment by Sina-Soltani** [comment]
آیا با درگاه مجازی تست کردید تا به حال؟

**Comment by Mansoun** [comment]
نه تست میکنم و مطلعتون میکنم

**Comment by Mansoun** [comment]
مهندس جان دیگه همون 
result.IsSucceed
هم نمیده و کلا 
onlinePayment.RequestAsync
هم خطا برمیگردونه.
علت خطا هم ضمیمه کردم.
توی کدهام قبلا توی کانفیگ خود تزریق کننده چنین عمل کرده بودم
         

> ioc.For<IOnlinePayment>()
>                 .HybridHttpOrThreadLocalScoped()
>                 .Use<DefaultOnlinePayment>(); 
فکر کنم کلا مشکل از همین بود. در اولین فرصت ارور مربوطه رو اصلاح میکنم و با درگاه مجازی تست میکنم مجدد

![zarinIssue3](https://user-images.githubusercontent.com/35144971/79568071-77ce9d80-80ca-11ea-9fce-5e15b397faf7.png)

**Comment by Sina-Soltani** [comment]
در هر صورت ایراد از ساختار پروژه شما هست
پیشنهادی که میتونم جهت رفع مشکل بهتون بکنم اینه که در صورت امکان، تزریق وابستگی پروژتون رو عوض کنید چون
StructureMap
یک پروژه منقرض شده و خارج از توسعه هست
(طبق اعلام رسمی سازنده)

بهتره چیز دیگه ای مثل
Autofac
استفاده کنید

همچنین در صورتیکه میخواید سینتکس کدی که همین الان دارید استفاده میکنید رو حفظ کنید میتونید از
Lamar
استفاده کنید که در واقع ادامه راه
StructureMap
هست

**Comment by Mansoun** [comment]
بله باید عوضش کنم
