### ISSUE TITLE
راهنمایی برای تزریق وابستگی

### ISSUE THREAD

**Issue by feryt20** [Sina-Soltani/Parbad#77]
سلام
میشه لطفا یک روش پیاده سازی دیگه برای ام وی سی بفرمایید بجز AutoFac
چون من از آیدنتیتی استفاده میکنم و بعد از استفاده از اتوفک سیستم احراز هویت کلا از کار میوفته
میام اروراشو برطرف میکنم باز میبینم یه جای دیگه به مشکل برمیخوره
خواستم از روش های دیگه برای تزریق وابستگی استفاده کنم ولی سر هرکدوم یه جور اذیت شدم
ممنون میشم یه روش سادتر تر معرفی کنید که این مشکلات رو نداشته باشه

**Comment by Sina-Soltani** [comment]
درود
متاسفانه چنین درخواستی رو نمیتونم انجام بدم چون این یک مشکل در پروژه خصوصی شما هست و باید جستجو کنید ببینید مشکلات اصلی از کجاست و اونها رو برطرف کنید

کتابخانه
Autofac
پس از مایکروسافت، دومین کتابخانه معروف تزریق وابستگی موجود در دنیا هست
پنجاه میلیون بار دانلود شده و بیش از ۳ هزار ستاره در گیت هاب داره

بنابراین پیشنهادی که میتونم بهتون بکنم اینه که در مورد مشکلتون تحقیق کنید تا حل بشه

**Comment by feryt20** [comment]
متاسفانه هنوز راه حلی پیدا نکردم
حتی سمپل خود اتوفک رو هم دانلود کردم همین مشکلو داشت
