### ISSUE TITLE
VerifyResultStatus یکسان در تمامی حالت ها

### ISSUE THREAD

**Issue by AmirHosseinHmd** [Sina-Soltani/Parbad#8]
<div dir="rtl">سلام آقای سلطانی، خسته نباشید. متشکر بابت این کتابخانه خیلی خوب.
ما در پروژمون (ASP.NET MVC) داریم از پرباد (و بانک پاسارگاد) استفاده می کنیم، منتها چند تا مشکل وجود داره:

1. یک اینکه در "اینام" VerifyResultStatus، در تمامی وضعیت ها، مقدار AlreadyVerified باز گردونده میشه، یعنی هم هنگام پرداخت موفق، هم هنگام کنسل کردن. اصلا این گزینه به چه معناست و چرا این مشکل وجود داره؟

2. چرا در اینام PaymentDataStatus، مقدار Cancelled وجود نداره، و اصلا تفاوت اون با VerifyResultStatus چی هست؟

3. طبق چیزی که من دیدم، Transaction ID ذخیره نمیشه. یعنی حتی در صفحه تأیید پرداخت نمایش داده میشه اما بعد از اون به متد Update در Storage ارسال نمیشه.

ضمنا من چون دیدم Issue قبلی دیروز باز شده و شما سریع پاسخ دادید تصمیم گرفتم این Issue رو باز کنم، وگرنه مجبور میشدم از API خود بانک پاسارگاد استفاده کنم.
ممنون میشم اگر پاسخ بدید.</div>

**Comment by Sina-Soltani** [comment]
(اگر در خواندن متن مشکل چپ چین راست چین، دارید لطفا داخل برنامه ای مثل ورد کپی کنید)


۱. مقدار Already Verified در اینام VerifyResultStatus به معنای این هست که اگر شما بنا به دلایلی بیش از یکبار، درخواست تأیید رو به بانک ارسال کنید، این مقدار به شما بازگشت داده خواهد شد.
علت آینه که درخواستی که قبلاً تأیید شده، اگر بار دیگه آنجام بشه، نباید Success رو برگردونه. چون فروشنده ممکن هست بیش از یکبار عملیات خرید رو برای مشتری انجام بده. برای مثال ممکنه کاربر صفحه رو رفرش کنه و این عملیات دو مرتبه تکرار بشه.

۲. در مورد ذخیره در دیتابیس، قرار هست نسخه جدیدی آماده بشه که بسیار کامل‌تر از نسخه فعلی هست.

۳. TransactionID فقط در صورتی ذخیره میشه که پرداخت موفقیت آمیز بوده باشه. در‌واقع به پرداختی که انجام نگرفته، هیچ TransactionID هم اختصاص داده نمیشه از جانب بانک.

**Comment by AmirHosseinHmd** [comment]
<div dir="rtl">
خب متوجه نشدم، الان من چطوری بعد از بازگشت به سایت متوجه بشم که کاربر پرداخت رو کنسل کرده یا پرداختش موفقیت آمیز بوده؟ ضمنا من جای دیگه غیر از در اکشن متدی که قراره بوده کاربر رو به بانک منتقل کنه، عملیات تأیید رو انجام ندادم. این دو اکشن متد من هست:
`        [AbarbazarMVCAuthorize(Roles = "ShopOwner")]
        [Route("Shop/Plan")]
        [Route("Shop/Plan/{shopPlanTermId:int}")]
        public ActionResult ShopPlan(int? shopPlanTermId, string couponCode)
        {
            if (shopPlanTermId.HasValue)
            {
                int shopId = (User as AbarbazarPrincipal).ShopId;
                ShopPlanService service = new ShopPlanService();
                if (service.IsPurchaseValid(shopId, shopPlanTermId.Value, couponCode))
                {
                    decimal finalPrice = service.GetShopPlanPurchaseFinalPrice(shopPlanTermId.Value, couponCode);
                    if (finalPrice > 0)
                    {
                        var invoice = new Invoice(service.GenerateUniqueOrderNumber(),
                            (long)finalPrice,
                            Request.Url.GetLeftPart(System.UriPartial.Authority) + $"/Panel/Shop/Plan/{shopPlanTermId}/Verify{(!string.IsNullOrEmpty(couponCode) ? "?couponCode=" + couponCode : string.Empty)}");
                        var reqResult = Parbad.Payment.Request(Parbad.Providers.Gateway.ParbadVirtualGateway, invoice);

                        if (reqResult.Status == RequestResultStatus.Success)
                            return reqResult.ToActionResult();
                        else
                            ViewBag.PurchaseErrorMessage = Presentation.Resources.Messages.ExceptionWasThrown;
                    }
                    else
                    {
                        bool purchaseResult = service.CompleteShopPlanPurchase(shopId, new CreateOrUpgradeShopPlan
                        {
                            ShopPlanTermId = shopPlanTermId.Value,
                            CouponCode = couponCode
                        });
                        if (purchaseResult)
                            return Redirect("/Panel/Shop/Plan");
                    }
                }
                ViewBag.PurchaseErrorMessage = Presentation.Resources.Messages.ShopPlanPurchaseIsNotValid;
            }
            return View(new ShopService().GetShopPlanInfo());
        }

        [AbarbazarMVCAuthorize(Roles = "ShopOwner")]
        [Route("Shop/Plan/{shopPlanTermId:int}/Verify")]
        public ActionResult ShopPlanPurchaseFinalize(int shopPlanTermId, string couponCode, string paymentID)
        {
            ShopPlanService service = new ShopPlanService();
            long orderNumber = 0;
            int shopId = (User as AbarbazarPrincipal).ShopId;

            var paymentResult = Parbad.Payment.Verify(HttpContext, invoice =>
            {
                orderNumber = invoice.OrderNumber;
                if (!service.IsPurchaseValid(shopId, shopPlanTermId, couponCode))
                    invoice.Cancel();
            });
            if (paymentResult.Status == VerifyResultStatus.Success/* || paymentResult.Status == VerifyResultStatus.AlreadyVerified*/)
            {
                bool purchaseResult = service.CompleteShopPlanPurchase(shopId, new CreateOrUpgradeShopPlan
                {
                    ShopPlanTermId = shopPlanTermId,
                    PaymentGuid = paymentID,
                    CouponCode = couponCode
                });
                if (!purchaseResult)
                {
                    Parbad.Payment.Refund(new RefundInvoice(orderNumber));
                    ViewBag.PurchaseErrorMessage = Presentation.Resources.Messages.ShopPlanPurchaseIsNotValid;
                }
            }
            return RedirectToAction("ShopPlan");
        }`
در مورد ذخیره در دیتابیس، می تونید حدودا بهم بگید نسخه ای که میفرمایید کی ریلیز میشه؟ و اینکه تا اون موقع باید چه کار کرد در خصوص اون وضعیت های پرداخت؟
</div>

**Comment by Sina-Soltani** [comment]
شما با درگاه تست ParbadVirtualGateway هم تست کردید؟

**Comment by AmirHosseinHmd** [comment]
<div dir="rtl">
بله، با هر دو درگاه (مجازی پرباد و درگاه بانک پاسارگاد) چک کردیم و همین مشکل وجود داره.
</div>

**Comment by AmirHosseinHmd** [comment]
<div dir="rtl">فکر می کنم باگ باشه، چون بعد از زدن دکمه Pay در درگاه مجازی پرباد و همینطور بانک پاسارگاد، پیغام موفقیت آمیز بودن پرداخت در هر دو درگاه نمایش داده میشه، اما در دیتابیس TransactionID ذخیره نمیشه.</div>

**Comment by AmirHosseinHmd** [comment]
[لطفا این عکس رو مشاهده کنید، شماره تراکنش نال هست](https://filebin.net/ug9bx36h93rv3vu8/Test.png?t=b7hdz0g2)

**Comment by AmirHosseinHmd** [comment]
[این صفحه قبل از عکس بالا هست](https://filebin.net/e2j726t9qzkhy8nz/Test2.PNG?t=sov4yiwm)

**Comment by Sina-Soltani** [comment]
من الان یکبار دیگه سیستم رو تست کردم و هیچ مشکلی وجود نداره.
آیا شما خودتون دارید در دیتابیس ذخیره میکنید و یا اینکه از SQLServer خود این کتابخونه دارید استفاده میکنید؟

**Comment by AmirHosseinHmd** [comment]
<div dir="rtl">
عزیز پس لطف کنید به سورس کد من یه نگاهی بندازید. اینطور که شما می فرمایید پس نباید اشکال از سمت شما باشه. اما خب من هم هیچ اشکالی در سورس کد خودم نمی بینم.
در مورد سوالتون درباره نحوه ذخیره سازی هم باید عرض کنم که به شکل دلخواه دارم ذخیره می کنم.
ضمنا عرض کنم که دارم از نسخه beta استفاده می کنم.
</div>

**Comment by Sina-Soltani** [comment]
اگر ممکنه کد مربوط به ذخیره سازی رو قرار بدید تا ببینم

**Comment by AmirHosseinHmd** [comment]
[خدمت شما](https://filebin.net/0ukz72vy4oschb0l/Storage.cs?t=1eqqpjcl)

**Comment by AmirHosseinHmd** [comment]
<div dir="rtl">ممنون میشم اگر به سورس کد اکشن متد ها هم نگاهی بندازید</div>

**Comment by AmirHosseinHmd** [comment]
عذر میخوام اینکه گفته بودید "همینجا در گیت هاب" قرار بدید رو ندیدم. یک لحظه...

**Comment by AmirHosseinHmd** [comment]
کد ذخیره سازی:
```
namespace Abarbazar.Models.DomainModels
{
    public class ParbadStorage : Storage
    {
        private readonly AbarbazarDatabaseContext dbContext;
        public ParbadStorage() => dbContext = new AbarbazarDatabaseContext();

        protected override void Insert(PaymentData paymentData)
        {
            dbContext.Payments.Add(new Payment
            {
                UserId = (HttpContext.Current.User as AbarbazarPrincipal).UserId,
                PaymentId = paymentData.Id,
                OrderNumber = paymentData.OrderNumber,
                Amount = paymentData.Amount,
                CreatedOn = paymentData.CreatedOn,
                ReferenceId = paymentData.ReferenceId,
                TransactionId = paymentData.TransactionId,
                AdditionalData = paymentData.AdditionalData,
                GatewayId = paymentData.Gateway == Parbad.Providers.Gateway.ParbadVirtualGateway ? PaymentGateway.ParbadVirtualId : PaymentGateway.PasargadId,
                StatusId = paymentData.Status == PaymentDataStatus.Verified ? PaymentStatus.VerifiedId : paymentData.Status == PaymentDataStatus.Failed ? PaymentStatus.FailedId : paymentData.Status == PaymentDataStatus.Refunded ? PaymentStatus.RefundedId : PaymentStatus.RequestedId,
            });
            dbContext.SaveChanges();
        }

        protected override Task InsertAsync(PaymentData paymentData)
        {
            dbContext.Payments.Add(new Payment
            {
                UserId = (HttpContext.Current.User as AbarbazarPrincipal).UserId,
                PaymentId = paymentData.Id,
                OrderNumber = paymentData.OrderNumber,
                Amount = paymentData.Amount,
                CreatedOn = paymentData.CreatedOn,
                ReferenceId = paymentData.ReferenceId,
                TransactionId = paymentData.TransactionId,
                AdditionalData = paymentData.AdditionalData,
                GatewayId = paymentData.Gateway == Parbad.Providers.Gateway.ParbadVirtualGateway ? PaymentGateway.ParbadVirtualId : PaymentGateway.PasargadId,
                StatusId = paymentData.Status == PaymentDataStatus.Verified ? PaymentStatus.VerifiedId : paymentData.Status == PaymentDataStatus.Failed ? PaymentStatus.FailedId : paymentData.Status == PaymentDataStatus.Refunded ? PaymentStatus.RefundedId : PaymentStatus.RequestedId,
            });
            return dbContext.SaveChangesAsync();
        }

        protected override PaymentData SelectById(Guid id)
        {
            return dbContext.Payments.Where(p => p.PaymentId == id).Select(p => new PaymentData
            {
                Id = p.PaymentId,
                OrderNumber = p.OrderNumber,
                Amount = (long)p.Amount,
                CreatedOn = p.CreatedOn,
                ReferenceId = p.ReferenceId,
                TransactionId = p.TransactionId,
                AdditionalData = p.AdditionalData,
                Gateway = p.GatewayId == PaymentGateway.ParbadVirtualId ? Parbad.Providers.Gateway.ParbadVirtualGateway : Parbad.Providers.Gateway.Pasargad,
                Status = p.StatusId == PaymentStatus.VerifiedId ? PaymentDataStatus.Verified : p.StatusId == PaymentStatus.FailedId ? PaymentDataStatus.Failed : p.StatusId == PaymentStatus.RefundedId ? PaymentDataStatus.Refunded : PaymentDataStatus.Requested,
            }).SingleOrDefault();
        }

        protected override Task<PaymentData> SelectByIdAsync(Guid id)
        {
            return dbContext.Payments.Where(p => p.PaymentId == id).Select(p => new PaymentData
            {
                Id = p.PaymentId,
                OrderNumber = p.OrderNumber,
                Amount = (long)p.Amount,
                CreatedOn = p.CreatedOn,
                ReferenceId = p.ReferenceId,
                TransactionId = p.TransactionId,
                AdditionalData = p.AdditionalData,
                Gateway = p.GatewayId == PaymentGateway.ParbadVirtualId ? Parbad.Providers.Gateway.ParbadVirtualGateway : Parbad.Providers.Gateway.Pasargad,
                Status = p.StatusId == PaymentStatus.VerifiedId ? PaymentDataStatus.Verified : p.StatusId == PaymentStatus.FailedId ? PaymentDataStatus.Failed : p.StatusId == PaymentStatus.RefundedId ? PaymentDataStatus.Refunded : PaymentDataStatus.Requested,
            }).SingleOrDefaultAsync();
        }

        protected override PaymentData SelectByOrderNumber(long orderNumber)
        {

            return dbContext.Payments.Where(p => p.OrderNumber == orderNumber).Select(p => new PaymentData
            {
                Id = p.PaymentId,
                OrderNumber = p.OrderNumber,
                Amount = (long)p.Amount,
                CreatedOn = p.CreatedOn,
                ReferenceId = p.ReferenceId,
                TransactionId = p.TransactionId,
                AdditionalData = p.AdditionalData,
                Gateway = p.GatewayId == PaymentGateway.ParbadVirtualId ? Parbad.Providers.Gateway.ParbadVirtualGateway : Parbad.Providers.Gateway.Pasargad,
                Status = p.StatusId == PaymentStatus.VerifiedId ? PaymentDataStatus.Verified : p.StatusId == PaymentStatus.FailedId ? PaymentDataStatus.Failed : p.StatusId == PaymentStatus.RefundedId ? PaymentDataStatus.Refunded : PaymentDataStatus.Requested,
            }).SingleOrDefault();
        }

        protected override Task<PaymentData> SelectByOrderNumberAsync(long orderNumber)
        {
            return dbContext.Payments.Where(p => p.OrderNumber == orderNumber).Select(p => new PaymentData
            {
                Id = p.PaymentId,
                OrderNumber = p.OrderNumber,
                Amount = (long)p.Amount,
                CreatedOn = p.CreatedOn,
                ReferenceId = p.ReferenceId,
                TransactionId = p.TransactionId,
                AdditionalData = p.AdditionalData,
                Gateway = p.GatewayId == PaymentGateway.ParbadVirtualId ? Parbad.Providers.Gateway.ParbadVirtualGateway : Parbad.Providers.Gateway.Pasargad,
                Status = p.StatusId == PaymentStatus.VerifiedId ? PaymentDataStatus.Verified : p.StatusId == PaymentStatus.FailedId ? PaymentDataStatus.Failed : p.StatusId == PaymentStatus.RefundedId ? PaymentDataStatus.Refunded : PaymentDataStatus.Requested,
            }).SingleOrDefaultAsync();
        }

        protected override void Update(PaymentData paymentData)
        {
            Payment payment = dbContext.Payments.SingleOrDefault(p => p.PaymentId == paymentData.Id);
            payment.OrderNumber = payment.OrderNumber;
            payment.Amount = payment.Amount;
            payment.ReferenceId = payment.ReferenceId;
            payment.TransactionId = payment.TransactionId;
            payment.AdditionalData = payment.AdditionalData;
            payment.StatusId = paymentData.Status == PaymentDataStatus.Verified ? PaymentStatus.VerifiedId : paymentData.Status == PaymentDataStatus.Failed ? PaymentStatus.FailedId : paymentData.Status == PaymentDataStatus.Refunded ? PaymentStatus.RefundedId : PaymentStatus.RequestedId;
            payment.AdditionalData = paymentData.AdditionalData;
            dbContext.SaveChanges();
        }

        protected override Task UpdateAsync(PaymentData paymentData)
        {
            Payment payment = dbContext.Payments.SingleOrDefault(p => p.PaymentId == paymentData.Id);
            payment.OrderNumber = payment.OrderNumber;
            payment.Amount = payment.Amount;
            payment.ReferenceId = payment.ReferenceId;
            payment.TransactionId = payment.TransactionId;
            payment.AdditionalData = payment.AdditionalData;
            payment.StatusId = paymentData.Status == PaymentDataStatus.Verified ? PaymentStatus.VerifiedId : paymentData.Status == PaymentDataStatus.Failed ? PaymentStatus.FailedId : paymentData.Status == PaymentDataStatus.Refunded ? PaymentStatus.RefundedId : PaymentStatus.RequestedId;
            payment.AdditionalData = paymentData.AdditionalData;
            return dbContext.SaveChangesAsync();
        }
    }
}
```

**Comment by AmirHosseinHmd** [comment]
این کد اکشن متد ها رو هم ممنون میشم اگر یه بررسی کوچیک بفرمایید:
`

        [AbarbazarMVCAuthorize(Roles = "ShopOwner")]
        [Route("Shop/Plan")]
        [Route("Shop/Plan/{shopPlanTermId:int}")]
        public ActionResult ShopPlan(int? shopPlanTermId, string couponCode)
        {
            if (shopPlanTermId.HasValue)
            {
                int shopId = (User as AbarbazarPrincipal).ShopId;
                ShopPlanService service = new ShopPlanService();
                if (service.IsPurchaseValid(shopId, shopPlanTermId.Value, couponCode))
                {
                    decimal finalPrice = service.GetShopPlanPurchaseFinalPrice(shopPlanTermId.Value, couponCode);
                    if (finalPrice > 0)
                    {
                        var invoice = new Invoice(service.GenerateUniqueOrderNumber(),
                            (long)finalPrice,
                            Request.Url.GetLeftPart(System.UriPartial.Authority) + $"/Panel/Shop/Plan/{shopPlanTermId}/Verify{(!string.IsNullOrEmpty(couponCode) ? "?couponCode=" + couponCode : string.Empty)}");
                        var reqResult = Parbad.Payment.Request(Parbad.Providers.Gateway.ParbadVirtualGateway, invoice);

                        if (reqResult.Status == RequestResultStatus.Success)
                            return reqResult.ToActionResult();
                        else
                            ViewBag.PurchaseErrorMessage = Presentation.Resources.Messages.ExceptionWasThrown;
                    }
                    else
                    {
                        bool purchaseResult = service.CompleteShopPlanPurchase(shopId, new CreateOrUpgradeShopPlan
                        {
                            ShopPlanTermId = shopPlanTermId.Value,
                            CouponCode = couponCode
                        });
                        if (purchaseResult)
                            return Redirect("/Panel/Shop/Plan");
                    }
                }
                ViewBag.PurchaseErrorMessage = Presentation.Resources.Messages.ShopPlanPurchaseIsNotValid;
            }
            return View(new ShopService().GetShopPlanInfo());
        }

        [AbarbazarMVCAuthorize(Roles = "ShopOwner")]
        [Route("Shop/Plan/{shopPlanTermId:int}/Verify")]
        public ActionResult ShopPlanPurchaseFinalize(int shopPlanTermId, string couponCode, string paymentID)
        {
            ShopPlanService service = new ShopPlanService();
            long orderNumber = 0;
            int shopId = (User as AbarbazarPrincipal).ShopId;

            var paymentResult = Parbad.Payment.Verify(HttpContext, invoice =>
            {
                orderNumber = invoice.OrderNumber;
                if (!service.IsPurchaseValid(shopId, shopPlanTermId, couponCode))
                    invoice.Cancel();
            });
            if (paymentResult.Status == VerifyResultStatus.Success/* || paymentResult.Status == VerifyResultStatus.AlreadyVerified*/)
            {
                bool purchaseResult = service.CompleteShopPlanPurchase(shopId, new CreateOrUpgradeShopPlan
                {
                    ShopPlanTermId = shopPlanTermId,
                    PaymentGuid = paymentID,
                    CouponCode = couponCode
                });
                if (!purchaseResult)
                {
                    Parbad.Payment.Refund(new RefundInvoice(orderNumber));
                    ViewBag.PurchaseErrorMessage = Presentation.Resources.Messages.ShopPlanPurchaseIsNotValid;
                }
            }
            return RedirectToAction("ShopPlan");
        }`

**Comment by AmirHosseinHmd** [comment]
<div dir="rtl">
نکته دیگه ای رو هم که الان متوجه شدم اینه که متدی که به دلگیت پارامتر دوم متد Payment.Verify() ارسال می کنم کال نمیشه.
</div>

**Comment by AmirHosseinHmd** [comment]
> > این مواردی که میگم رو لطفا دقیق انجام بدید و اطلاع بدید.
> > ابتدا سفارش رو انجام بدید و برید به درگاه تست ParbadVirtualGateway
> > قبل از اینکه کلید پرداخت رو بزنید، برید به پایگاه داده که اطلاعات رو ثبت کردید ببینید مقدار فیلد Status چی هست
> 
> در واقع منظورم به رکوردی که ثبت شده هست. با توجه به شماره سفارشی که تولید کردید

<div dir="rtl">در اون مرحله وضعیت Verified هست.</div>

**Comment by Sina-Soltani** [comment]
بله.
به همین خاطر میخواستم کد ذخیره سازیتون رو ببینم.
در ذخیره سازی شما دارید وضعیت رو اشتباه ذخیره میکنید.
در نتیجه زمانیکه کاربر از بانک برمیگرده و درخواست باید تایید بشه،  وضعیت اون درخواست از همون ابتدا اشتباه ذخیره شده توسط شما.
علت اینکه کد کنسل کردن پرداخت در دیلیگت پارامتر دوم هم هیچوقت کال نمیشه همین هست. چون اصلا هیچ پردازشی بابت اون پرداخت انجام نمیشه که بخواد کنسل بشه.

**Comment by AmirHosseinHmd** [comment]
بله الان متوجه شدم اشتباه از من بوده. عذر خواهی می کنم.
بازهم خیلی ازتون متشکرم که وقتتون در اختیار من قرار دادید. لطف کردید. واقعا پشتیبانیتون خیلی خوب بود. امیدوارم موفق باشید.

**Comment by Sina-Soltani** [comment]
`bool purchaseResult = service.CompleteShopPlanPurchase(shopId, new CreateOrUpgradeShopPlan
            {
                ShopPlanTermId = shopPlanTermId,
                PaymentGuid = paymentID,
                CouponCode = couponCode
            });
            if (!purchaseResult)
            {
                Parbad.Payment.Refund(new RefundInvoice(orderNumber));
                ViewBag.PurchaseErrorMessage = Presentation.Resources.Messages.ShopPlanPurchaseIsNotValid;
            }`

بهتره که هر گونه چک کردن سفارش با پایگاه داده و سیستم خودتون رو به جای اینکه بعد از تایید سفارش انجام بدید که بخواید Refund کنید،  در قسمت پارامتر دوم دیلیگت صدا کنید و بررسی کنید.
به اینصورت دیگه نیازی نیست که یک درخواست تأیید بشه و از حساب کاربر کم بشه، و بعدش بلافاصله Refund بشه. در واقع اگر شرایط رو درون پارامتر دوم چک کنید، اصلا نیازی به نوشتن دستور Refund هم نیست.

**Comment by Sina-Soltani** [comment]
موفق باشید
