### ISSUE TITLE
فارسی سازی پیام ها

### ISSUE THREAD

**Issue by amirreza58** [Sina-Soltani/Parbad#80]
سلام
در هنگام Verify پیام :

The requested payment is already processed before

آیا قابل تغییر است ؟
در سورس DefaultOnlinePayment.cs این پیام مستقیما درج شده است

**Comment by Sina-Soltani** [comment]
درود

[Messages Configuration](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#messages)

**Comment by amirreza58** [comment]
این پیام :

The requested payment is already processed before
شامل هیچکدام نشد لطفا راهنمایی بفرمایید

**Comment by Sina-Soltani** [comment]
درسته

یک سری از پیام‌ها هنوز قابل تنظیم نیستن.
در نسخه بعدی قرار خواهند گرفت

**Comment by amirreza58** [comment]
`return new PaymentVerifyResult
                {
                    TrackingNumber = payment.TrackingNumber,
                    Amount = payment.Amount,
                    GatewayName = payment.GatewayName,
                    GatewayAccountName = payment.GatewayAccountName,
                    TransactionCode = payment.TransactionCode,
                    Status = payment.IsPaid ? PaymentVerifyResultStatus.AlreadyVerified : PaymentVerifyResultStatus.Failed,
                    Message = "The requested payment is already processed before."
                };`
در سایر بخش های از 

`_messagesOptions.Value.XXXXXXXXXX`

استفاده شده است

**Comment by amirreza58** [comment]
ممنون
