### ISSUE TITLE
ایراد در متد _onlinePayment.RequestAsync

### ISSUE THREAD

**Issue by MohammadReza10** [Sina-Soltani/Parbad#81]
سلام
من طبق اموزش گیت هاب و فیلم یوتیوب پیش رفتم ولی ایراد میده
به صورت دستی دیتابیسم ایجاد کردم
----------------------------------------
An unhandled exception occurred while processing the request.
ArgumentException: Format of the initialization string does not conform to specification starting at index 0.

Microsoft.Data.Common.DbConnectionOptions.GetKeyValuePair(string connectionString, int currentPosition, StringBuilder buffer, bool useOdbcRules, out string keyname, out string keyvalue)
-------------------------------------------
var result = await _onlinePayment.RequestAsync(invoice =>

**Comment by Sina-Soltani** [comment]
درود

طبق خطایی که فرستادید، مشکل از رشته اتصالی به دیتابیس هست

ConnectionString
رو چک کنید
