### ISSUE TITLE
درگاه زرین پال

### ISSUE THREAD

**Issue by amirreza58** [Sina-Soltani/Parbad#82]
سلام
در درگاه زرین پال وقتی مبلغ 200,000 ریال (بیست هزار تومان) را ارسال میکنیم در درگاه موقع پرداخت 2,000,000 ریال نمایش میدهد

> var result = await _onlinePayment.RequestAsync(invoice =>
                    {
                        invoice
                            .UseAutoIncrementTrackingNumber()
                            .SetAmount(200000)
                            .SetCallbackUrl(verifyUrl)
                            .UseZarinPal("Test");
                    });

مثل اینکه تومان را تبدیل به ریال میکند آیا در زرین پال باید تومان ارسال کرد؟

**Comment by amirreza58** [comment]
در مستندات فنی زرین پال صفحه 5 نوشته است که مبلغ باید به تومان ارسال شود

**Comment by Sina-Soltani** [comment]
بله. مبلغ رو به تومان وارد کنید
شاید در نسخه‌های بعدی این کار به صورت اتوماتیک صورت بگیره
