### ISSUE TITLE
دیتابیس

### ISSUE THREAD

**Issue by MohammadReza10** [Sina-Soltani/Parbad#83]
دلیل اینکه تو جدول 
payment
یه رکورد درج میکنه ولی تو جدول
transaction
دوتا درج میکنه از همون fk
چیه ؟
مشکل از سیستم منه یا خودتون اینطوری برنامه نویسی کردین

**Comment by Sina-Soltani** [comment]
به ازای هر گونه درخواست پرداخت، تایید پرداخت، برگشت تراکنش و عدم موفقیت‌های به وجود اومده، یک رکورد
Transaction
ثبت میشه

بنابراین از زمانی که درخواست پرداخت شروع میشه تا زمانیکه تایید یا رد میشه، باید ۲ رکورد
Transaction
به ازای هر 
Payment
وجود داشته باشه

**Comment by MohammadReza10** [comment]
نتیجتا 
Transaction
زود پر میشه
نسخه قبلی که 
guid
بود بهتر نبود ؟

**Comment by Sina-Soltani** [comment]
منظور شما از زود پر میشه چی هست دقیقا؟
متوجه نشدم

**Comment by MohammadReza10** [comment]
منظورم 
bigint 
هستش 
guid
بود بهتر بود
