### ISSUE TITLE
برگشت وجه مقدار مشخص

### ISSUE THREAD

**Issue by keyone2693** [Sina-Soltani/Parbad#84]
ایا بانک ملت این متد رو ساپورت میکنه 

RefundSpecificAmountAsync
که یه بخش از پول پرداخت شده رو برگردونیم

؟

**Comment by Sina-Soltani** [comment]
خیر. در توضیحات متد نوشته شده

**Comment by keyone2693** [comment]
اخه تو مستندات خوده بانک ملت نوشته این امکان رو داره


بعد سوال دیگه بعد از اینکه وریفای موفق کردیم میتونیم پول رو برگشت بزنیم ؟

**Comment by Sina-Soltani** [comment]
> 
> 
> اخه تو مستندات خوده بانک ملت نوشته این امکان رو داره

لطفا لینک مستندات رو اینجا قرار بدید تا بررسی کنیم

> 
> 
> بعد سوال دیگه بعد از اینکه وریفای موفق کردیم میتونیم پول رو برگشت بزنیم ؟

بله
