### ISSUE TITLE
دریافت شماره کارت در درگاه PayIr

### ISSUE THREAD

**Issue by rezathecoder** [Sina-Soltani/Parbad#86]
سلام. در درگاه پرداخت
 Pay.ir 
وقتی میخوام شماره کارت رو از
 AdditionalData 
بگیرم همیشه مقدارش null هست.

کد ایجاد پرداخت:

`var result = await _onlinePayment.RequestAsync(invoice =>
                    {
                        invoice.UseAutoIncrementTrackingNumber();
                        invoice.SetAmount(amount);
                        invoice.SetCallbackUrl(Url.Action("Verify", "Payment", null, Url.ActionContext.HttpContext.Request.Scheme));
                    });

                if ( result.IsSucceed ) {
                    // It will redirect the client to the gateway.
                    return result.GatewayTransporter.TransportToGateway();
                } else {
                    TempData["ErrorMessage"] = "خطا در انجام تراکنش.";
                    return RedirectToAction(nameof(Index));
                }`
کد وریفای:

`var invoice = await _onlinePayment.FetchAsync();

            // Check if the invoice is new or it's already processed before.
            if ( invoice.Status == PaymentFetchResultStatus.AlreadyProcessed ) {
                TempData["ErrorMessage"] = "تراکنش قبلا پردازش شده است.";
                return RedirectToAction(nameof(Index));
            }

            var verifyResult = await _onlinePayment.VerifyAsync(invoice);

            if ( verifyResult.IsSucceed ) {

                var transaction = await _context.Transactions.Where(t => t.TrackingNumber == verifyResult.TrackingNumber).FirstOrDefaultAsync();

                if ( transaction == null )
                    return RedirectToAction(nameof(Index));

                transaction.TransactionCode = verifyResult.TransactionCode;
                transaction.IsCompleted = true;
                transaction.CardNumber = verifyResult.GetPayIrAdditionalData().CardNumber;
                transaction.Mobile = verifyResult.GetPayIrAdditionalData().Mobile;
                await _context.SaveAsync();

                TempData["SuccessMessage"] = "پرداخت با موفقیت انجام شد.";
            } else {
                TempData["ErrorMessage"] = "خطایی در انجام تراکنش رخ داده است.";
            }

            return RedirectToAction(nameof(Index));`

پرداخت به درستی انجام میشه اما شماره کارت مقدارش خالی هست همیشه. داخل دیتابیس پرباد رو هم چک کردم همیشه فیلد
 AdditionalData 
مقدارش برابر {} هست.

لطفا بررسی و راهنمایی بفرمایید.

پکیج های استفاده شده:
Parbad.AspNetCore V1.0.6
Parbad.Gateway.PayIr V1.1.2
Parbad.Storage.EntityFrameworkCore V1.0.6

نوع برنامه وب:
AspNetCore 3.1.5

**Comment by Sina-Soltani** [comment]
درود.
بررسی میشه.

**Comment by Sina-Soltani** [comment]
کدی که گذاشتید به نظر میرسه کامل نیست. آیا در قسمت
Request
درگاه مورد نظر رو ذکر کردید؟

اگر بله، لطفا کد اضافه کردن تنظیمات درگاه رو اینجا قرار بدید
ConfigureGateways

(اطلاعات حساس بانکی رو حذف کنید)

**Comment by rezathecoder** [comment]
بله درگاه ذکر شده و به درستی هم پرداخت صورت میگیره.
کد اضافه کردن تنظیمات در startup.cs

`services.AddParbad()

                .ConfigureGateways(gateways =>
                {
                    gateways.AddPayIr()
                    .WithAccounts(accounts =>
                    {
                        accounts.AddInMemory(account =>
                        {
                            account.Api = "myapi";
                            account.IsTestAccount = false;
                        });
                    });
                })
                .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
            .ConfigureStorage(builder =>
            {
                builder
                   .UseEntityFrameworkCore(ef => ef.UseSqlServer(Configuration.GetConnectionString("ParbadDataContext"), options => options.UseParbadMigrations()))
                   .ConfigureDatabaseInitializer(builder =>
                   {
                       // For creating and migrating
                       builder.CreateAndMigrateDatabase();
                   });
            });`

کد Request:

`var result = await _onlinePayment.RequestAsync(invoice =>
                    {
                        invoice.UseAutoIncrementTrackingNumber();
                        invoice.SetGateway("PayIr");
                        invoice.SetAmount(amount);
                        invoice.SetCallbackUrl(Url.Action(nameof(Callback), "Balance", null, Url.ActionContext.HttpContext.Request.Scheme));
                    });`

*در پست اول به اشتباه کد ست کردن درگاه رو حذف کردم که عذرخواهی میکنم. ولی در اپلیکیشن به درستی ست شده است.

**Comment by Sina-Soltani** [comment]
متاسفانه قابلیت تست واقعی امکان پذیر نیست و همچنین حالت تست این درگاه، فقط دو دکمه پرداخت موفق و پرداخت ناموفق رو داره که در واقع جایی برای وارد کردن اطلاعاتی مانند شماره موبایل موجود نیست

![Untitled](https://user-images.githubusercontent.com/10329804/84569179-caec6600-ad84-11ea-8b73-6f53cc6cf8cf.png)

همچنین پیاده‌سازی این درگاه در پَرباد، کاملا مطابق با مستندات ارائه شده توسط خود درگاه هست
[https://docs.pay.ir/gateway/](https://docs.pay.ir/gateway/)

بنابراین این مشکل از سمت اون درگاه هست
چیزی که من فکر میکنم این هست که اونها شاید اصلا شماره کارتی که باهاش پرداحت انجام شده رو برنمیگردونن به شما و در واقع اون شماره کارت و موبایلی که توی مستندات خودشون نوشتن، احتمالا خود ما در هنگام آماده سازی و ارسال درخواست به اونها میدیم و اونها پس از پرداخت دوباره به ما پس میدن که خب در این صورت کار بسیار عجیبی هست

با توجه به اینکه شما از اونها درگاه دارید، میتونید در بخش پشتیبانی این سوال رو مطرح کنید:

- آیا شماره کارتی که شما پس از عملیات تایید ارسال میکنید، شماره کارتی هست که کاربر با اون پرداخت رو انجام داده و یا اینکه این همون شماره ای هست که خودمون در هنگام ارسال درخواست پرداخت به شما ارسال میکنیم؟

**Comment by rezathecoder** [comment]
سپاسگزارم از بررسی شما. من از شرکت مربوطه سوال میکنم و نتیجه رو اعلام میکنم.
فقط یک نکته که به نظر خودم میرسه این هست که طبق مستندات مقداری که برای شماره کارت برمیگردونن کلیدش برابر
cardNumber
هست که با حرف کوچک شروع شده. در ست کردن مقادیر از کد
nameof(CardNumber)
استفاده شده با حرف بزرگ شروع میشود. آیا این مورد مشکل ساز نیست؟

https://docs.pay.ir/gateway/#success-examples-Verify-verify-1_0_0-0

**Comment by Sina-Soltani** [comment]
خیر.
این عملیات توسط
[Newtonsoft.Json](https://www.nuget.org/packages/Newtonsoft.Json/)
انجام میشه و حروف کوچی و بزرگ اهمیتی ندارن.

**Comment by rezathecoder** [comment]
درود خدمت شما
فکر کنم مشکل رو پیدا کردم لطفا بررسی کنید.
https://github.com/Sina-Soltani/Parbad/blob/c15b9a6507e5e3233feb0bcbcc01698f87bb0f81/src/Parbad.Gateway/PayIr/src/Internal/PayIrHelper.cs#L91

در این خط کد 
JsonSerializerSettings
به متد 
DeserializeObject
ارسال نشده تا برای نوع نامگذاری کلید ها که
camelCase
هست تبدیل صحیح رو انجام بده. درحالی که در 
https://github.com/Sina-Soltani/Parbad/blob/c15b9a6507e5e3233feb0bcbcc01698f87bb0f81/src/Parbad.Gateway/PayIr/src/PayIrGateway.cs#L81
برای پست کردن درخواست وریفای این درخواست ارسال شده.

مشکل بعدی 
https://github.com/Sina-Soltani/Parbad/blob/c15b9a6507e5e3233feb0bcbcc01698f87bb0f81/src/Parbad.Gateway/PayIr/src/Internal/PayIrHelper.cs#L102

مقدار شماره کارت به اشتباه برابر مقدار شماره فاکتور قرار گرفته. لطفا اصلاح بفرمایید

**Comment by Sina-Soltani** [comment]
> 
> 
> درود خدمت شما
> فکر کنم مشکل رو پیدا کردم لطفا بررسی کنید.
> 

درود
همونطور که یکبار گفته شد، مشکل این نیست
جهت اطلاعات بیشتر
[Newtonsoft.Json](https://www.newtonsoft.com/json)
رو مطالعه کنید
و همچنین
[نمونه مثال](https://dotnetfiddle.net/aj1HJh)
رو اجرا کنید تا ببینید


>
> camelCase
> هست تبدیل صحیح رو انجام بده. درحالی که در
>  برای پست کردن درخواست وریفای این مقدار ارسال شده.

علت اینکه در هنگام پست کردن، اطلاعات به کمل کیس تبدیل شده این هست که ما از درون سیستم درگاه پی آی آر خبری نداریم که آیا به حروف بزرگ یا کوچک حساس هستند یا خیر. بنابراین مطابق حالت دریافتی اونها اطلاعات رو تبدیل میکنیم.
اما در سمت خود ما میدونیم که اهمیتی نداره کوچک یا بزرگ بودن


>
> مشکل بعدی
> 
> 
> مقدار شماره کارت به اشتباه برابر مقدار شماره فاکتور قرار گرفته. لطفا اصلاح بفرمایید

ممنون بله این یک اشتباه هست و باید تصحیح بشه

> 
> با توجه به اینکه شما از اونها درگاه دارید، میتونید در بخش پشتیبانی این سوال رو مطرح کنید:
> 
>   آیا شماره کارتی که شما پس از عملیات تایید ارسال میکنید، شماره کارتی هست که کاربر با اون پرداخت رو انجام داده و یا اینکه این همون شماره ای هست که خودمون در هنگام ارسال درخواست پرداخت به شما ارسال میکنیم؟
> لطفا نتیجه رو گزارش بدید

آیا این مورد رو پیگیری کردید؟

**Comment by rezathecoder** [comment]
بله پیگیری کردم جواب دادن:

> بله شماره کارت برگشت داده شده به صورت mask شده از سمت psp ارسال میشه و همون شماره کارتی هست که باهاش پرداخت انجام شده.
دیتای برگشتی به وب سایت تون مشکلی نداره
توجه بفرمایید که اسم پارامتر و type پارامتر رو صحیح دریافت بفرمایید

**Comment by rezathecoder** [comment]
بله پیگیری کردم. پاسخ دادن:

> بله شماره کارت برگشت داده شده به صورت
 mask 
شده از سمت 
psp
 ارسال میشه و همون شماره کارتی هست که باهاش پرداخت انجام شده.
دیتای برگشتی به وب سایت تون مشکلی نداره
توجه بفرمایید که اسم پارامتر و
 type
 پارامتر رو صحیح دریافت بفرمایید

**Comment by Sina-Soltani** [comment]
باگ مربوط به پراپرتی
CardNumber
رفع شده
لطفا نسخه جدید رو نصب کنید و نتیجه رو گزارش بدید
`Install-Package Parbad.Gateway.PayIr -Version 1.1.3-beta1`

**Comment by rezathecoder** [comment]
بله مشکل حل شده. به درستی شماره کارت دریافت میشود
سپاسگزارم

**Comment by Sina-Soltani** [comment]
https://github.com/Sina-Soltani/Parbad/blob/c15b9a6507e5e3233feb0bcbcc01698f87bb0f81/src/Parbad.Gateway/PayIr/src/Internal/PayIrHelper.cs#L102

پس در واقع مشکل در پر کردن اشتباه یک پراپرتی بوده

**Comment by rezathecoder** [comment]
بله درسته. ممنون از شما
