### ISSUE TITLE
خطای cors در محیط پروداکشن

### ISSUE THREAD

**Issue by aboozarmofid** [Sina-Soltani/Parbad#88]
سلام
من در محیط پروداکشن  با خطای
cors (Cross-origin resource sharing )
تنها در اکشنی که در آن کار پرداخت انجام می شود، مواجه می شوم
در محیط 
development
این خطا ایجاد نمی شود
من از
ASP.NET CORE WEB API
استفاده می کنم.
ممنون

**Comment by Sina-Soltani** [comment]
درود

هر چند که بعید میدونم این مشکل به پَرباد مربوط باشه.
اما برای رفع مشکل باید اطلاعات بیشتری اینجا قرار بدید
خطا چه زمانی اتفاق میوفته؟
آیا خطا سمت سروره یا سمت کلاینت؟ چون این خطا معمولا سمت کلاینت به وجود میاد
آیا
StackTrace
موجود هست؟ 

کد پرداخت رو هم همچنین قرار بدید

**Comment by aboozarmofid** [comment]
من از انگولار برای کلاینت استفاده می کنم.
اطلاعات فاکتور را به سرور ارسال می کنم و لینک پرداخت را از پرباد دریافت می کنم و به کلاینت بر می گردانم
![code](https://user-images.githubusercontent.com/15994322/84668021-535f3800-af38-11ea-85a5-63f87883ac66.jpg)

و بعد از آن در انگولار با
window.location.href = response.redirectUrl 
کاربر به صفحه پرداخت منتقل میشود

همه این کار ها در محیط 
development 
بدون هیج مشکلی انجام می شود ولی روی سرور پروداکشن قبل از اینکه لینک پرداخت ایجاد شود خطای 
Cors
ایجاد می شود: 
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://......./api/payment/zarinpalpayment. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by Sina-Soltani** [comment]
همونطور که گفتم این مشکل ارتباطی با پَرباد نداره.

این خطا به خاطر پیاده سازی نکردن
CORS
در برنامه سمت سرورتون هست
طبق خطایی که شما فرستادید، زمانیکه توسط انگولار درخواست آجاکس به سمت سرورتون به اکشن
Payment/ZarinPalPayment
ارسال میشه، به دلیل عدم تنظیم
CORS
جلوی درخواست گرفته میشه. علت اینکه در محیط
Development
داره بدون مشکل کار میکنه اینه که این محیط
Local Host
هست و نیازی به اجازه نداره

برای اطلاعات بیشتر میتونید در گوگل جستجو کنید و یا مطلب زیر رو مطالعه کنید
[Enable Cross-Origin Requests (CORS) in ASP.NET Core](https://docs.microsoft.com/en-us/aspnet/core/security/cors?view=aspnetcore-3.1)
