### ISSUE TITLE
Disable logging JSON files

### ISSUE THREAD

**Issue by sadeq-qafari** [Sina-Soltani/Parbad#90]
Hi,

How can we disable logging JSON files that will be created every time we make a payment. These files are created both in testing and production environment.

Here is a sample content of these files:

`{
  "EventType": "DefaultAuditContext",
  "Environment": {
    "UserName": "myUsername",
    "MachineName": "myMachineName",
    "DomainName": "myMachineName",
    "CallingMethodName": "Audit.EntityFramework.DbContextHelper+<CreateAuditScopeAsync>d__31.MoveNext()",
    "AssemblyName": "Audit.EntityFramework.Core, Version=15.0.0.0, Culture=neutral, PublicKeyToken=571d6b80b242c87e",
    "Culture": "en-US"
  },
  "StartDate": "2020-06-19T15:56:52.4927131",
  "EndDate": "2020-06-19T15:56:52.6271577",
  "Duration": 134,
  "EntityFrameworkEvent": {
    "Database": "MyDb",
    "Entries": [
      {
        "Schema": "Payment",
        "Table": "Payment",
        "Action": "Insert",
        "PrimaryKey": {
          "Id": 92
        },
        "ColumnValues": {
          "Id": 92,
          "ActionBy": 10,
          "Amount": 5200000.0,
          "Code": "Reservation",
          "GatewayAccountName": null,
          "GatewayDetailId": 1,
          "GatewayName": "ParbadVirtual",
          "IsActive": false,
          "IsCompleted": false,
          "IsDeleted": false,
          "IsPaid": false,
          "RequestId": 10283,
          "TenantId": 2,
          "Token": "d3d1588748f5496d963af008788702e0",
          "TrackingNumber": 637281952117552482,
          "TransactionCode": null
        },
        "Valid": true
      }
    ],
    "Result": 1,
    "Success": true
  }
}`

**Comment by Sina-Soltani** [comment]
Parbad doesn't log any JSON files!
The users must decide what kind of logging they want to use. It can be Console, JSON, XML, Debug and so on.
Parbad uses the default Microsoft Logging to log the information. So it depends on you to decide what kind of OUTPUT you want to use.
Did I understand your question correctly?

**Comment by sadeq-qafari** [comment]
Thank you for your response.
So is there a way to disable the whole Parbad logging?

**Comment by Sina-Soltani** [comment]
Currently no there isn't. But it can be added in the next release.

**Comment by Sina-Soltani** [comment]
You can now install the latest version and disable the logger.
`Install-Package Parbad -Version 3.5.1`
[Enabling/Disabling the Logging](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#enablingdisabling-the-logging)
