### ISSUE TITLE
بانک پارسیان

### ISSUE THREAD

**Issue by paramony** [Sina-Soltani/Parbad#94]
سلام آقای سلطانی . لطفا  در مورد اطلاعاتی که باید برای بانک پارسیان در بخش استارت آپ پروژه وارد کنم به من کمک کنید چون در کتابخانه شما فقط یک پراپرتی وجود دارد به نام لاگین اما اطلاعات بان پارسیان متفاوت هست

**Comment by Sina-Soltani** [comment]
درود

چه مقادیری به شما از طرف بانک داده شده؟
(فقط نام رو ذکر کنید. اطلاعات حساس رو اینجا قرار ندید)

**Comment by paramony** [comment]
اطلاعاتی مثل پین کد و ترمینال و اطلاعات پنل گزارش گیری که شامل آدرس و نام کاربری و پسورد هست .

**Comment by Sina-Soltani** [comment]
لطفا داکیومنتی که بانک بهتون داده رو اینجا قرار بدید

**Comment by paramony** [comment]
بله

**Comment by paramony** [comment]
مستندات بانک 

https://pgw.pec.ir/IPG/Docs/IPGSW1/IPGSW1Sale.zip

**Comment by paramony** [comment]
ممنونم آقای سلطانی که کمک می کنید

**Comment by paramony** [comment]
آقای سلطانی این اطلاعاتی هست که بانک به من داده

**Comment by Sina-Soltani** [comment]
مستندات همون مستندات قبلی هستند
مشکلی که بانک پارسیان داره اینه که داکیومنتی که به مشتری میدن با سیستمی که طراحی کردن همخوانی نداره

پین در واقع همون
LoginAccount
هست
امتحان کنید و نتیجه رو گزارش بدید اینجا

> 
> 
> ممنونم آقای سلطانی که کمک می کنید

خواهش میکنم

**Comment by paramony** [comment]
آقای سلطانی من با کمک شما به درگاه متصل شدم و پول هم پرداخت میشه اما در برگشت میزنه اطلاعات نادرست است و بعد از چند دقیقه پول هم بازگشت پیدا می کنه 
message :  Invalid data is received from the gateway

**Comment by paramony** [comment]
این نمونه کد من در متد Verify  است
var result = await _onlinePayment.VerifyAsync(invoice =>
            {
                if (!IsEveryThingOk(Convert.ToInt32(invoice.TrackingNumber)))
                {
                    invoice.CancelPayment();
                }
            });

**Comment by Sina-Soltani** [comment]
بعید میدونم چنین خطایی وجود داشته باشه.

آیا آخرین نسخه از
Parbad
رو دارید استفاده می‌کنید؟

لطفا کد مربوط به تنظیمات رو در اینجا به صورت کامل قرار بدید
 (مقادیر حساس رو پاک کنید)

**Comment by paramony** [comment]
services.AddParbad()
          .ConfigureGateways(gateways =>
          {
              gateways
                 .AddParsian().WithAccounts(source =>
                 {

                     source.AddInMemory(account =>
                     {
                         account.LoginAccount = "Pin Code";
                     });
                 });

          })
          .ConfigureHttpContext(builder => builder.UseDefaultAspNetCore())
          .ConfigureStorage(builder => builder.UseMemoryCache());

**Comment by paramony** [comment]
نه آخرین نسخه نیست

**Comment by Sina-Soltani** [comment]
چه نسخه ای؟
لطفا آخرین نسخه رو امتحان کنید
`Install-Package Parbad -Version 3.5.1`

**Comment by paramony** [comment]
آقای سلطانی من باید متد Verify  رو از نوع Post در نظر بگیرم ؟

**Comment by paramony** [comment]
نسخه من 1.0.1 هست

**Comment by Sina-Soltani** [comment]
> 
> 
> آقای سلطانی من باید متد Verify رو از نوع Post در نظر بگیرم ؟
خیر هیچ نوعی برای اکشن متد وریفای نباید تعیین بشه


> 
> 
> نسخه من 1.0.1 هست

نسخه ۱.۰.۱ برای سال ۲۰۱۶ بوده

**Comment by paramony** [comment]
آقای سلطانی با آپدیت کردن پکیج مشکل من حل شد . ممنونم از شما به خاطر راهنمایی تون

**Comment by Sina-Soltani** [comment]
خواهش میکنم
موفق باشید
