### ISSUE TITLE
درگاه پرداخت الکترونیک سپهر

### ISSUE THREAD

**Issue by GhalamborM** [Sina-Soltani/Parbad#95]
سلام
درگاه پرداخت الکترونیک سپهر هم پشتیبانی میشه؟

**Comment by Sina-Soltani** [comment]
درود
آیا مستندات درگاه موجود هست؟

**Comment by GhalamborM** [comment]
[مدارک-درگاه-پرداخت-اینترنتی-پرداخت-الکترونیک-سپهر.pdf](https://github.com/Sina-Soltani/Parbad/files/4885938/-.-.-.-.-.-.pdf)

**Comment by GhalamborM** [comment]
[SepehrPay+Gateway+Manual+2.1.1.10-+Token.pdf](https://github.com/Sina-Soltani/Parbad/files/4885940/SepehrPay%2BGateway%2BManual%2B2.1.1.10-%2BToken.pdf)

**Comment by Sina-Soltani** [comment]
بله امکان افزودن موجود هست
در نسخه بعدی افزوده خواهد شد
تاریخ خاصی برای انتشار نسخه معین نمیشه، اما احتمال داره تا آخر هفته افزوده بشه

**Comment by Sina-Soltani** [comment]
درگاه پرداخت سپهر افزوده شد.
لطفا نصب کنید و نتیجه رو اعلام کنید

```
Install-Package Parbad.Gateway.Sepehr -Version 1.0.0
```

[Parbad.Gateway.Sepehr](https://www.nuget.org/packages/Parbad.Gateway.Sepehr/)

**Comment by GhalamborM** [comment]
تشکر
بدون مشکل انجام شد
