### ISSUE TITLE
اشکال اتصال به اوراکل

### ISSUE THREAD

**Issue by parsintalk** [Sina-Soltani/Parbad#96]
سلام، ضمن تشکر از ماژول فوق العادتون.
من در حال حاضر از اوراکل استفاده می کنم و با توجه به اینکه اوراکل به حروف بزرگ و کوچیک حساسه.
امکانش هست schema های کل پروژتون رو با حروف بزرگ در نظر بگیرید ؟
مثلا وقتی یه کاربر به نام PARBAD تو اوراکل ساخته میشه.
دیگه نمی شه schema های Parbad va parbad رو ساپورت کنه.
کافیه تو پروژتون تمام رشته های "parbad"  با"PARBAD" جا به جا بشه.
با سپاس فراوان

**Comment by Sina-Soltani** [comment]
درود
بررسی میشه

**Comment by Sina-Soltani** [comment]
لطفا نسخه جدید رو نصب کنید

[Parbad.Storage.EntityFrameworkCore](https://www.nuget.org/packages/Parbad.Storage.EntityFrameworkCore/)

[تنظیمات پایگاه داده و جداول](https://github.com/Sina-Soltani/Parbad/wiki/Configuration#using-entityframework-core)

**Comment by parsintalk** [comment]
عالی بود ممنونم.
